import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      // Products
      { source: "/trafficpatternsxd", destination: "/products/traffic-patterns-xd", permanent: true },
      { source: "/trafficpatterns", destination: "/products/traffic-patterns", permanent: true },
      { source: "/streetprint", destination: "/products/streetprint", permanent: true },
      { source: "/streetbond", destination: "/products/streetbond", permanent: true },
      { source: "/streetbondsr", destination: "/products/streetbond-sr", permanent: true },
      { source: "/mmax-2", destination: "/products/mmax", permanent: true },
      { source: "/decomark", destination: "/products/decomark", permanent: true },
      { source: "/duratherm-2", destination: "/products/duratherm", permanent: true },
      { source: "/durashield", destination: "/products/durashield", permanent: true },
      { source: "/premark", destination: "/products/premark", permanent: true },
      { source: "/airmark", destination: "/products/airmark", permanent: true },
      // Applications
      { source: "/crosswalks", destination: "/applications/crosswalks", permanent: true },
      { source: "/bike-bus-lanes", destination: "/applications/bus-bike-lanes", permanent: true },
      { source: "/parking-lots", destination: "/applications/parking-lots", permanent: true },
      { source: "/commercial-parking-lot-solutions", destination: "/applications/parking-lots", permanent: true },
      { source: "/commercial-parking-lot-surfaces", destination: "/applications/parking-lots", permanent: true },
      { source: "/parks-paths", destination: "/applications/parks-paths", permanent: true },
      { source: "/public-art", destination: "/applications/public-art", permanent: true },
      { source: "/community-branding", destination: "/applications/community-branding", permanent: true },
      { source: "/regulatory-markings", destination: "/applications/regulatory-markings", permanent: true },
      { source: "/air-ports", destination: "/applications/airports", permanent: true },
      { source: "/residential-driveways", destination: "/applications/driveways", permanent: true },
      { source: "/private-driveways", destination: "/applications/driveways", permanent: true },
      { source: "/townhomes", destination: "/applications/driveways", permanent: true },
      { source: "/leed-urban-heat-island", destination: "/applications/community-branding", permanent: true },
      { source: "/decorative-streetscape-solutions", destination: "/applications/crosswalks", permanent: true },
      // Blog post redirects
      { source: "/keeping-pedestrians-safe-and-operation-budgets-low", destination: "/blog/keeping-pedestrians-safe", permanent: true },
      { source: "/pedestrian-safety-solutions", destination: "/blog/pedestrian-safety-solutions", permanent: true },
      { source: "/vancouver-decorative-crosswalk-design", destination: "/blog/vancouver-decorative-crosswalk-design", permanent: true },
      { source: "/enhancing-multimodal-connectivity-in-york-region-toronto", destination: "/blog/multimodal-connectivity-york-region", permanent: true },
      { source: "/case-study-branded-crosswalks-and-pedestrian-safety-in-vancouver-richmond", destination: "/blog/branded-crosswalks-vancouver-richmond", permanent: true },
      { source: "/decorative-asphalt-for-high-traffic-areas", destination: "/blog/decorative-asphalt-high-traffic", permanent: true },
      { source: "/veterans-crosswalk-kitchener-trafficpatterns", destination: "/blog/veterans-crosswalk-kitchener", permanent: true },
      { source: "/trafficpatternsdx-mmax-durable-transit-lanes-crossings", destination: "/blog/durable-transit-lanes-crossings", permanent: true },
      { source: "/trafficpatterns-crosswalks-white-rock-langley", destination: "/blog/white-rock-langley-trafficpatterns", permanent: true },
      { source: "/decorative-hardscape-solutions-grey-is-the-new-black", destination: "/blog/decorative-hardscape-grey-is-new-black", permanent: true },
      { source: "/decorative-paving-solutions", destination: "/blog/decorative-paving-solutions", permanent: true },
      { source: "/trafficpatternsxd-urban-design-solutions", destination: "/blog/trafficpatternsxd-urban-design", permanent: true },
      { source: "/hubss-com-rainbow-crosswalk", destination: "/blog/simcoe-rainbow-crosswalk", permanent: true },
      { source: "/streetbondsr-solar-reflective-coatings", destination: "/blog/streetbondsr-solar-reflective-coatings", permanent: true },
      { source: "/new-traffic-pattern-crosswalk-upgrade-for-tsain-ko-centre-2", destination: "/blog/pictograph-crosswalk-sechelt", permanent: true },
      { source: "/strengthening-cycling-and-transit-integration-with-long-lasting-surface-solutions", destination: "/blog/cycling-transit-integration-surface-solutions", permanent: true },
      { source: "/enhancing-safety-and-durability-for-high-traffic-transit-stations", destination: "/blog/safety-durability-transit-stations", permanent: true },
      { source: "/extending-transit-lane-lifespan", destination: "/blog/extending-transit-lane-lifespan", permanent: true },
      { source: "/transportation-infrastructure-guide", destination: "/blog/transportation-infrastructure-guide", permanent: true },
      { source: "/playgrounds-recreation-case-studies", destination: "/blog/playgrounds-recreation", permanent: true },
      { source: "/educational-facilities-case-study", destination: "/blog/educational-facilities", permanent: true },
      { source: "/community-spaces-case-study", destination: "/blog/community-spaces", permanent: true },
      { source: "/community-branding-case-study", destination: "/blog/community-branding-case-study", permanent: true },
      { source: "/commercial-applications-case-study", destination: "/blog/commercial-applications", permanent: true },
      { source: "/municipalities-case-studies", destination: "/blog/municipalities-case-study", permanent: true },
      { source: "/stamped-asphalt-vs-stamped-concrete", destination: "/blog/stamped-asphalt-vs-concrete", permanent: true },
      // White papers
      { source: "/white-paper-transportation-and-urban-design", destination: "/blog/white-paper-transportation-urban-design", permanent: true },
      { source: "/white-paper-surface-solutions-for-resilient-transit-infrastructure", destination: "/blog/white-paper-resilient-transit-infrastructure", permanent: true },
      // Blog posts & project profiles (2020–2022)
      { source: "/surface-system-solutions-for-school-playgrounds", destination: "/blog/surface-solutions-school-playgrounds", permanent: true },
      { source: "/decorative-asphalt-for-communities", destination: "/blog/decorative-asphalt-communities", permanent: true },
      { source: "/asphalt-coatings-for-parks-and-plazas", destination: "/blog/asphalt-coatings-parks-plazas", permanent: true },
      { source: "/streetbondsr-for-cooler-asphalt-surfaces", destination: "/blog/streetbondsr-cooler-asphalt", permanent: true },
      { source: "/enhancing-transit-hubs-in-the-gta-and-metro-vancouver", destination: "/blog/enhancing-transit-hubs-gta-vancouver", permanent: true },
      { source: "/new-traffic-pattern-crosswalk-upgrade-for-tsain-ko-centre", destination: "/blog/tsain-ko-crosswalk-sechelt", permanent: true },
      { source: "/decorative-asphalt-crosswalks", destination: "/blog/decorative-asphalt-crosswalks", permanent: true },
      { source: "/roadway-accents-natures-walk", destination: "/blog/roadway-accents-natures-walk", permanent: true },
      { source: "/every-child-matters-decorative-asphalt-crosswalk", destination: "/blog/every-child-matters-crosswalk", permanent: true },
      { source: "/stamped-asphalt-parking-lot", destination: "/blog/stamped-asphalt-parking-lot", permanent: true },
      { source: "/terry-fox-decorative-asphalt-plaza-coquitlam", destination: "/blog/terry-fox-plaza-coquitlam", permanent: true },
      { source: "/decorative-crosswalk-and-meridian", destination: "/blog/decorative-crosswalk-meridian", permanent: true },
      { source: "/the-laneway-project", destination: "/blog/laneway-project", permanent: true },
      { source: "/parc-riviera-mews-streetbond-asphalt-walkway", destination: "/blog/parc-riviera-streetbond-walkway", permanent: true },
      { source: "/decorative-asphalt-for-rutland-centennial-park-kelowna", destination: "/blog/rutland-centennial-park-kelowna", permanent: true },
      { source: "/societe-de-transport-du-saguenay", destination: "/blog/societe-transport-saguenay", permanent: true },
      { source: "/bikeway-intersection", destination: "/blog/bikeway-intersection", permanent: true },
      { source: "/decorative-asphalt-renewal", destination: "/blog/decorative-asphalt-renewal", permanent: true },
      { source: "/asphalt-coatings-for-playgrounds", destination: "/blog/asphalt-coatings-playgrounds", permanent: true },
      { source: "/west-vancouver-rainbow-crosswalk", destination: "/blog/west-vancouver-rainbow-crosswalk", permanent: true },
      { source: "/ackerys-alley-decorative-asphalt-orpheum-theatre-laneway", destination: "/blog/ackerys-alley-orpheum-laneway", permanent: true },
      { source: "/decorative-paving-stamped-asphalt-after-2-years-wear", destination: "/blog/stamped-asphalt-2-years-wear", permanent: true },
      { source: "/ralphs-farm-market-decorative-asphalt-parking-lot", destination: "/blog/ralphs-farm-market-parking-lot", permanent: true },
      { source: "/reunion-murrayville-schoolhouse-decorative-asphalt-sidewalk", destination: "/blog/murrayville-schoolhouse-sidewalk", permanent: true },
      { source: "/decorative-crosswalk_richmond-brighouse", destination: "/blog/richmond-brighouse-crosswalk", permanent: true },
      { source: "/decorative-asphalt-path", destination: "/blog/bowen-island-asphalt-path", permanent: true },
      { source: "/ubc-musqueam-crosswalk", destination: "/blog/ubc-musqueam-crosswalk", permanent: true },
      { source: "/white-rock-pier-decoraive-crosswalk", destination: "/blog/white-rock-pier-crosswalk", permanent: true },
      { source: "/squamish-nation-rainbow-crosswalk", destination: "/blog/squamish-nation-rainbow-crosswalk", permanent: true },
      { source: "/melfort-saskatchewan-waterpark-splash-pad", destination: "/blog/melfort-waterpark-splash-pad", permanent: true },
      { source: "/victoria-harbor-decorative-asphalt-walkway", destination: "/blog/victoria-harbour-walkway", permanent: true },
      { source: "/sports-court-asphalt-paving", destination: "/blog/sports-court-asphalt-paving", permanent: true },
      { source: "/rainbow-crosswalk-sechelt", destination: "/blog/rainbow-crosswalk-sechelt", permanent: true },
      { source: "/white-rock-stamped-asphalt-pathway", destination: "/blog/white-rock-stamped-pathway", permanent: true },
      { source: "/checkerboard-decorative-asphalt-crosswalk", destination: "/blog/checkerboard-crosswalk-coquitlam", permanent: true },
      { source: "/first-nations-decorative-crosswalk-design-granville-street", destination: "/blog/first-nations-crosswalk-granville", permanent: true },
      { source: "/lickman-interchange-decorative-asphalt-roundabout", destination: "/blog/lickman-interchange-roundabout", permanent: true },
      { source: "/stamped-asphalt-streetscapes-viva-next", destination: "/blog/stamped-asphalt-viva-next", permanent: true },
      { source: "/decorative-paving-for-townhomes-canada", destination: "/blog/decorative-paving-townhomes", permanent: true },
      { source: "/decorative-paving-public-art", destination: "/blog/decorative-paving-public-art-joyce", permanent: true },
      { source: "/decorative-crosswalk-commercial-drive", destination: "/blog/decorative-crosswalk-commercial-drive", permanent: true },
      { source: "/pedestrian-channelization-public-spaces", destination: "/blog/pedestrian-channelization-public-spaces", permanent: true },
      { source: "/decorative-paving-labyrinth-bc-childrens-hospital", destination: "/blog/bc-childrens-hospital-labyrinth", permanent: true },
      { source: "/best-crosswalks-canada", destination: "/blog/best-crosswalks-canada", permanent: true },
      { source: "/durable-pavement-coatings-ideal-for-waterparks", destination: "/blog/durable-coatings-waterparks", permanent: true },
      { source: "/complete-streets-new-westminster", destination: "/blog/complete-streets-new-westminster", permanent: true },
      { source: "/community-branding-horizontal-wayfinding-for-vancouvers-spirit-trail", destination: "/blog/spirit-trail-wayfinding-vancouver", permanent: true },
      { source: "/performance-crosswalks-for-asphalt-and-concrete", destination: "/blog/performance-crosswalks-asphalt-concrete", permanent: true },
      { source: "/imprinted-asphalt-crosswalks-for-york-transit-corridor", destination: "/blog/imprinted-asphalt-york-transit", permanent: true },
      { source: "/residential-decorative-paving", destination: "/blog/residential-decorative-paving", permanent: true },
      { source: "/laneway-revitalization", destination: "/blog/laneway-revitalization-vancouver", permanent: true },
      { source: "/residential-decorative-driveways", destination: "/blog/residential-decorative-driveways", permanent: true },
      { source: "/decorative-paving-for-playgrounds", destination: "/blog/decorative-paving-playgrounds", permanent: true },
      { source: "/parking-lot-wayfinding", destination: "/blog/parking-lot-wayfinding", permanent: true },
      { source: "/durable-coatings-for-asphalt", destination: "/blog/durable-coatings-asphalt", permanent: true },
      { source: "/stamped-asphalt-decorative-crosswalks", destination: "/blog/stamped-asphalt-decorative-crosswalks", permanent: true },
      { source: "/enhanced-parking-lot-surfaces", destination: "/blog/enhanced-parking-lot-surfaces", permanent: true },
      // Footer/nav link variants
      { source: "/traffic-patterns", destination: "/products/traffic-patterns", permanent: true },
      // Other pages
      { source: "/case-studies", destination: "/blog", permanent: true },
      { source: "/featured-projects", destination: "/projects", permanent: true },
      { source: "/documentation", destination: "/resources", permanent: true },
      { source: "/about-us", destination: "/about", permanent: true },
      { source: "/contact-us", destination: "/contact", permanent: true },
    ];
  },
  turbopack: {
    root: path.resolve(__dirname),
    resolveAlias: {
      tailwindcss: path.resolve(__dirname, "node_modules/tailwindcss"),
    },
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "plus.unsplash.com" },
    ],
  },
};

export default nextConfig;
