// HUBSS Product Source-of-Truth — per-product fact data.
// Sourced from manufacturer PDFs in /public/docs/ and manufacturer websites.
// Every claim should be traceable to the "sources" array; everything unverified
// is in "verifyFlags". This file is consumed by generate-docs.js.

module.exports = [

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "TrafficPatternsXD",
    filename: "01-TrafficPatternsXD.docx",
    eyebrow: "Flagship — Decorative Pavement Marking System",
    manufacturer: "Ennis-Flint® by PPG (PPG Traffic Solutions, Greensboro NC). HUBSS is the Canadian distributor and certified-applicator network.",
    whatItIs: [
      "An imprinted, aggregate-reinforced preformed thermoplastic pavement marking system. Two-foot-square sheets are laid on prepared asphalt, heated, and stamped with a wire-rope template — producing a brick-style decorative crosswalk or traffic-calming surface that is permanently bonded to the asphalt below.",
      "The 'XD' stands for 'Extremely Durable.' TrafficPatternsXD is the heavy-duty variant of the TrafficPatterns family, engineered for the most demanding pedestrian and vehicular conditions — bus lanes, BRT corridors, high-volume intersections.",
    ],
    keyFeatures: [
      "150 mil (3.8 mm) minimum thickness — heaviest in the preformed thermoplastic line.",
      "Aggregate-reinforced through the full cross-section; new anti-skid elements are exposed as the surface wears.",
      "Sheets stamped into the asphalt with a wire-rope template after heating — produces a brick-style imprinted finish.",
      "Heat-fused to asphalt — permanent chemical bond, not a coating that can peel.",
      "Applies at ambient and road temperatures down to 45°F (7°C); no pavement preheating to a specific temperature required.",
      "Available in 25+ standard colours plus a premium palette (PMS values published in the Colour Guide).",
    ],
    specs: [
      ["Material", "Preformed thermoplastic — ester-modified rosin, aggregates, pigments, binders, anti-skid elements"],
      ["Minimum thickness", "150 mil (3.8 mm)"],
      ["Sheet size", "2 ft × 2 ft (0.61 m × 0.61 m), ±3 mm tolerance"],
      ["Anti-skid (intermixed)", "Minimum 30% intermix; minimum 6 Mohs hardness"],
      ["Skid resistance", "Minimum 60 BPN per ASTM E303"],
      ["Static friction", "Minimum 0.6 (wet & dry) per ASTM C1028 / ASTM D2047"],
      ["Minimum install temperature", "45°F (7°C) ambient and road"],
      ["Substrate", "Asphalt only — explicitly NOT for Portland cement concrete"],
      ["Retroreflectivity", "Non-reflective. Companion white transverse stripe (90 / 125 mil) carries glass beads if required."],
      ["Storage", "24 months indoors"],
      ["Sealer", "Two-part epoxy required prior to application — no VOC solvents; gel time ≥ 20 min at 27°C"],
      ["Carton", "Max 25 in × 25 in; max 70 lb (32 kg)"],
    ],
    colours: "25+ standard colours including Black, White, Field Grey, Grey, Salmon, Sonoma Sand, Cinnamon, Sienna, Cocoa, Heritage Red, Colonial Brick, Burnt Orange, Terracotta, Khaki, Tan, Sand, Santa Fe Clay, Chestnut, Dark Brick Red, Brick Red, Light Grey, Olive Green, Green, Pink, Purple, Lilac. Premium colours: Light Blue, Sky Blue, Blue, Teal, SYG, Kelly Green, Lemon Yellow, Light Green, Orange, Yellow, Red. Pantone references are published in the Colour Guide. Custom patterns and colours available on request, within manufacturing limits.",
    applications: [
      "High-volume decorative crosswalks",
      "BRT corridors and bus priority lanes",
      "Major intersections subject to heavy turning movements and concentrated wheel loads",
      "Traffic-calming installations on collector and arterial streets",
      "Civic plazas with vehicular access through the area",
      "Through-areas in parking lots",
    ],
    documents: [
      { title: "Product Specification",                       type: "Specification",       filename: "TrafficPatternsXD-Specification.pdf" },
      { title: "Product Specification (branded HUBSS cover)", type: "Specification",       filename: "TrafficPatternsXD-Specification-Branded.pdf" },
      { title: "Product Specification (French)",              type: "Specification (FR)",  filename: "TrafficPatternsXD-Specification-FR.pdf" },
      { title: "Two-Component Sealer Specification",          type: "Specification",       filename: "TrafficPatternsXD-Two-Component-Sealer.pdf" },
      { title: "Cross-Section Detail",                        type: "Drawing",             filename: "TrafficPatternsXD-CrossSection-Detail.pdf" },
      { title: "Colour Guide",                                type: "Colour Guide",        filename: "TrafficPatternsXD-Colour-Guide.pdf" },
      { title: "Technical Data Sheet (TS002)",                type: "TDS",                 filename: "TS002_TrafficPatternsXD_220204.pdf" },
      { title: "Design Manual",                               type: "Design Manual",       filename: "TrafficPatternsXD-Design-Manual.pdf" },
    ],
    sources: [
      "TrafficPatternsXD Specification (.pdf)",
      "TrafficPatternsXD TS002 Technical Data Sheet (.pdf)",
      "TrafficPatternsXD Cross-Section Detail (.pdf)",
      "TrafficPatternsXD Colour Guide (.pdf)",
      "TrafficPatternsXD Two-Component Sealer Specification (.pdf)",
      "PPG Traffic Solutions launch announcement, January 2021 (PCI Magazine / PPG investor relations)",
    ],
    verifyFlags: [
      "Open-to-traffic time after installation: the spec says \"allowed to cool thoroughly\" but does not state a specific number of minutes or hours. The current site claim of \"open to traffic within hours\" is plausible but unsourced — confirm the practical re-opening time for a typical installation.",
      "Coverage rate: TPXD is sold per panel/sheet rather than per area. Confirm what HUBSS quotes to municipalities — sq ft per panel? installed sq ft per crew-day?",
      "AODA compliance: the technical data sheet cites ADA compliance specifically (American). AODA is not referenced anywhere in the PPG / Ennis-Flint documentation. Confirm whether HUBSS has independent AODA test data or should reword as \"designed to meet accessibility standards including ADA; suitable for AODA-compliant designs subject to site-specific review.\"",
      "Service life: PDFs do not state a specific year-figure for TPXD service life. Website language like \"engineered for multi-year service\" is defensible; specific claims like \"20-year durability\" or \"7-year service life\" are not in any source document — supply project-based evidence if those claims are to appear on the site.",
    ],
    discrepancies: [
      "Current website specs claim \"Glass beads embedded through full cross-section\" — this is INCORRECT for TPXD. The technical data sheet describes anti-skid/anti-slip elements (minimum 30% intermix, minimum 6 Mohs hardness), NOT glass beads. Glass beads only apply to the companion white transverse stripe and to PreMark's beaded variants. Recommended correction: \"Anti-skid elements distributed through full cross-section — new elements exposed as the surface wears.\"",
      "Current website claims TPXD installs on \"asphalt or concrete.\" PDF specification §5.4 is explicit: \"The System shall not be applied to Portland Cement Concrete.\" Asphalt only.",
      "Current website document list shows THREE entries all labeled \"Specification\" (Branded, plain English, and French). Proposed clean titles: \"Product Specification\" / \"Product Specification (branded HUBSS cover)\" / \"Product Specification (French)\" — each visually distinct and meaningful to the reader.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "TrafficPatterns",
    filename: "02-TrafficPatterns.docx",
    eyebrow: "Flagship — Decorative Pavement Marking System",
    manufacturer: "Ennis-Flint® by PPG (PPG Traffic Solutions, Greensboro NC). HUBSS is the Canadian distributor and certified-applicator network.",
    whatItIs: [
      "An interconnected preformed thermoplastic pavement marking system that simulates pavers or stones. Pre-cut interlocking sheets are surface-applied with infrared heat — no stamping templates or grids required.",
      "The standard-duty product in the TrafficPatterns family. Suitable for decorative crosswalks, parks, schools, and public spaces where TPXD's heavier 150 mil cross-section is not required. Works on BOTH asphalt and concrete — a key differentiator from TPXD.",
    ],
    keyFeatures: [
      "125 mil (3.2 mm) minimum thickness — preformed at the factory.",
      "Interconnected sheet design simulates pavers; no stamping template required (unlike TPXD or StreetPrint).",
      "Applies to both asphalt AND Portland cement concrete, including 'green' concrete that has set but not appreciably hardened.",
      "Heat-applied with an infrared heater — heating indicators on the surface signal molten state.",
      "Anti-skid elements harder than TPXD — minimum 8 Mohs (vs. 6 Mohs for TPXD).",
      "'Open to traffic within minutes of application' (manufacturer marketing language).",
    ],
    specs: [
      ["Material", "Preformed thermoplastic — ester-modified rosin, aggregates, pigments, binders, anti-skid elements"],
      ["Minimum thickness", "125 mil (3.18 mm)"],
      ["Sheet size", "Interconnected: 24 in × 24 in (0.61 × 0.61 m). Solid Sheets variant: 24 in × 36 in (0.61 × 0.91 m)"],
      ["Anti-skid (intermixed)", "Minimum 30% intermix; minimum 8 Mohs hardness"],
      ["Skid resistance", "Minimum 60 BPN per ASTM E303"],
      ["Static friction", "Minimum 0.6 (wet & dry) per ASTM C1028 / ASTM D2047"],
      ["Minimum install temperature", "45°F (7.2°C) ambient and road"],
      ["Substrate", "Asphalt AND Portland cement concrete (including green concrete)"],
      ["Installation", "Infrared heat — no stamping template, no grid"],
      ["Carton", "Max 25 in (Solid: 40 in) × 25 in; max 50 lb (23 kg)"],
    ],
    colours: "Same standard + premium palette as TrafficPatternsXD (see TPXD entry). Standard patterns: Running Bond, Herringbone, Plain Weave, Basket Weave, Ashlar, Stacked Tile (large + small), Diagonal Tile (large + small), Honeycomb, Courtyard, Quarter Round, Terrazzo. Standard borders TP36 through TP42.",
    applications: [
      "Decorative crosswalks (standard duty)",
      "Parks and pathways",
      "Schools and playgrounds (regulatory + decorative)",
      "Public spaces and civic plazas",
      "Parking lot through-areas and design elements",
      "Pedestrian-safety treatments where TPXD's heavier 150 mil is not required",
    ],
    documents: [
      { title: "Product Specification — Solid Sheets 125 mil",            type: "Specification", filename: "TrafficPatterns-Solid-Sheets-125-Specification.pdf" },
      { title: "Product Specification — 125 mil with Self-Adhesive Back", type: "Specification", filename: "TrafficPatterns-125-with-SA-Specification.pdf" },
      { title: "Two-Component Sealer Specification",                      type: "Specification", filename: "TrafficPatterns-Specification-Two-Component-Sealer.pdf" },
      { title: "Custom Design Guidelines",                                type: "Design Guide",  filename: "TrafficPatterns-Custom-Design-Guidelines.pdf" },
      { title: "Colour Guidelines",                                       type: "Colour Guide",  filename: "TrafficPatterns-Colour-Guidelines.pdf" },
      { title: "Technical Data Sheet (TS001)",                            type: "TDS",           filename: "TS001_TrafficPatterns_220204.pdf" },
      { title: "Design Manual",                                           type: "Design Manual", filename: "TrafficPatterns-Design-Manual.pdf" },
    ],
    sources: [
      "TrafficPatterns Solid Sheets 125 Specification (.pdf)",
      "TrafficPatterns 125 with Self-Adhesive Specification (.pdf)",
      "TrafficPatterns TS001 Technical Data Sheet (.pdf)",
      "TrafficPatterns Colour Guidelines (.pdf)",
    ],
    verifyFlags: [
      "\"Glass beads embedded through full cross-section\" appears on the current site — same correction as for TPXD. TrafficPatterns carries anti-skid elements, not glass beads, through the cross-section. Glass beads are a PreMark feature, not a TrafficPatterns one.",
      "\"Open to traffic in hours\" — TS001 says \"within minutes.\" Confirm with HUBSS whether \"minutes\" applies to small areas (a single crosswalk) vs. \"hours\" for large-area installations.",
      "Pedestrian-safety / freeze-thaw resilience: claims are reasonable but not quantified in the PDFs. If specific year-figures are used on the site (\"holds retroreflectivity for years\"), they should be qualified — TrafficPatterns is a non-reflective product; the retroreflectivity claim more accurately belongs to PreMark or the companion white transverse stripe.",
    ],
    discrepancies: [
      "Current website: \"Retroreflective glass beads are embedded through the full cross-section, holding nighttime visibility as the surface wears.\" — INCORRECT for TrafficPatterns. The product contains anti-skid elements at minimum 8 Mohs hardness; it is described by the manufacturer as a decorative product, not a retroreflective one. Retroreflectivity is provided by accompanying white transverse stripes (separate product line) or by PreMark beaded variants.",
      "Current website says \"holds retroreflectivity for years where conventional traffic paint typically requires repainting in a year or less.\" — overstatement. Reword as decorative durability vs. paint durability.",
      "Current document library has \"Two-Component Sealer Spec\" and three other specs without strong differentiating labels. Proposed clean titles above remove ambiguity.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "StreetBond",
    filename: "03-StreetBond.docx",
    eyebrow: "Flagship — Coloured Pavement Coating System",
    manufacturer: "GAF / StreetBond (1 Campus Drive, Parsippany-Troy Hills, NJ 07054). NOT an Ennis-Flint / PPG product. HUBSS is the Canadian distributor. NOTE: legacy PDFs reference Quest Construction Products, the previous brand owner.",
    whatItIs: [
      "A high-performance waterborne epoxy-modified acrylic pavement coating that turns ordinary asphalt or concrete into coloured, durable, slip-resistant surfaces — bike lanes, bus priority lanes, decorative crosswalks, plazas, parks, and branded private installations.",
      "StreetBond is a system, not a single product. The line includes water-based variants (SB120, SB150, SB150 AL), MMA-based variants for cold-climate work (Pro 220, Pro 250), and concrete primers (QS solvent-based, WB waterborne).",
    ],
    keyFeatures: [
      "Waterborne epoxy-modified acrylic — flexes with the pavement, resists peeling, balances hardness against wear and slip.",
      "73+ standard colours plus custom colour matching. 'Invisible Shade' technology pushes Solar Reflectance above 0.334 even on darker colours.",
      "ADA-compliant.",
      "VOC < 50 g/L (calculated) for the water-based variants — well below SCAQMD Rule 1113 limits for industrial maintenance coatings.",
      "1-year limited manufacturer warranty (additional coverage available for eligible projects).",
      "Documented field performance: 10+ years on Beale Street (Memphis); 12+ years in Padua (Italy).",
    ],
    specs: [
      ["Product family", "SB120 + SB150 + SB150 AL (water-based, epoxy-modified acrylic); Pro 220 + Pro 250 (MMA / PMMA); Concrete Primer QS + WB"],
      ["Chemistry (water-based)", "Two-component waterborne epoxy-modified acrylic (Part A + Part B + colourant)"],
      ["Density", "SB120: 14.0 lb/gal (1.67 g/mL); SB150: 13.7 lb/gal (1.65 g/mL); SB150 AL: 11.1 lb/gal"],
      ["Volume solids", "SB120: 54–61%; SB150: 53.5–60.6%; SB150 AL: 45.2 ± 2%"],
      ["VOC", "< 50 g/L (calculated) for water-based variants"],
      ["Drying — touch dry", "1–4 hours at 77°F (25°C), 40% RH (ASTM D5895)"],
      ["Cure — to traffic", "6–24 hours (climate dependent)"],
      ["Application temperature", "50°F (10°C) and rising, up to 113°F (45°C). Surface temp must be 50°F and rising. No precipitation within 24 hours."],
      ["Coverage (single layer, sprayed)", "≈ 600 ft² per 5-gal unit at 6.3 mil dry thickness (≈ 146 ft²/gal)"],
      ["Coverage (3 layers, pedestrian)", "≈ 200 ft² per unit (≈ 49 ft²/gal)"],
      ["Coverage (4 layers, vehicular)", "≈ 150 ft² per unit (≈ 36 ft²/gal)"],
      ["Friction — SB150 (ASTM E303)", "Dry 55–90 BPN / Wet 35–70 BPN"],
      ["Taber abrasion — SB150 (H-10 wheel)", "0.16–1.0 g per 1,000 cycles (dry)"],
      ["Adhesion (ASTM D4541)", "300–1,400 psi"],
      ["Freeze point", "32°F (0°C) — do not let pail freeze"],
      ["Pro 220 / 250 application temp", "32°F to 95°F (0–35°C); rain-proof in ~30 min at 68°F (20°C)"],
    ],
    colours: "73+ standard colours plus full custom colour matching. Standard tile palette includes Traffic Red, Bike Lane Green, Sunflower, Pacific Blue, Civic Orange, Night White. SR-qualifying colours are flagged in the StreetBond Colour Guide. 'Invisible Shade' technology pushes Solar Reflectance above 0.334 on darker tones.",
    applications: [
      "Bike lanes and cycle priority zones",
      "Bus priority lanes and BRT station zones",
      "Decorative coloured crosswalks",
      "Civic plazas and pedestrian-priority surfaces",
      "Parks and pathway surfacing",
      "Branded private driveways and entryways",
      "Sport courts and playground surfacing",
      "Parking lots and parking-stall delineation",
    ],
    documents: [
      { title: "StreetBond Brochure",                                          type: "Brochure",     filename: "StreetBond-Brochure.pdf" },
      { title: "StreetBond Colour Guide (73+ colours)",                        type: "Colour Guide", filename: "StreetBond-Colour-Guide.pdf" },
      { title: "Substrate Preparation Guide",                                  type: "Substrate",    filename: "StreetBond_Substrate_Guide.pdf" },
      { title: "Colorant Technical Data Sheet",                                type: "TDS",          filename: "StreetBond-Colorant.pdf" },
      { title: "SB120 — Technical Data Sheet",                                 type: "TDS",          filename: "StreetBond-SB120-Data-Sheet-12.22-Rev.pdf" },
      { title: "SB120 — Product Specification (asphalt)",                      type: "Specification",filename: "StreetBond_SB120_Specifications.pdf" },
      { title: "SB120 — Product Specification (over concrete)",                type: "Specification",filename: "StreetBond-SB120-Over-Concrete-Specification.pdf" },
      { title: "SB150 — Technical Data Sheet",                                 type: "TDS",          filename: "StreetBond-SB150-Data-Sheet-12.22-Rev.pdf" },
      { title: "SB150 AL — Technical Data Sheet (airless sprayer compatible)", type: "TDS",          filename: "StreetBond-SB150AL-Data-Sheet-12.22-Rev.pdf" },
      { title: "SB150 — Product Specification (asphalt)",                      type: "Specification",filename: "StreetBond_SB150_Specifications.pdf" },
      { title: "SB150 — Product Specification (over concrete)",                type: "Specification",filename: "StreetBond-SB150-Over-Concrete-Specification.pdf" },
      { title: "Pro 220 (MMA) — Technical Data Sheet",                         type: "TDS",          filename: "StreetBond-Pro-220-TDS.pdf" },
      { title: "Pro 220 + 250 — Installation Guide",                           type: "Installation", filename: "StreetBond-Pro-220-and-250-Intallation.pdf" },
      { title: "Pro 220 + 250 — Brochure",                                     type: "Brochure",     filename: "StreetBond-Pro-220-Pro-250-Brochure-1.pdf" },
      { title: "Pro 250 (PMMA) — Technical Data Sheet",                        type: "TDS",          filename: "Data-Sheet-StreetBond-Pro-250.pdf" },
      { title: "Concrete Primer QS — Technical Data Sheet (solvent-based)",    type: "TDS",          filename: "StreetBond-QS-Concrete-TDS.pdf" },
      { title: "Concrete Primer WB — Technical Data Sheet (waterborne)",       type: "TDS",          filename: "StreetBond-Concrete-Primer-WB-TDS.pdf" },
    ],
    sources: [
      "StreetBond Brochure, Colour Guide, Substrate Guide (.pdf)",
      "StreetBond SB120 / SB150 / SB150 AL Technical Data Sheets (.pdf)",
      "StreetBond Pro 220 and Pro 250 Technical Data Sheets (.pdf)",
      "StreetBond Concrete Primer QS + WB Technical Data Sheets (.pdf)",
    ],
    verifyFlags: [
      "Manufacturer attribution: confirm whether HUBSS website should attribute StreetBond to GAF, to 'StreetBond by GAF,' or simply present it as a product family without manufacturer attribution. Current site says nothing about GAF.",
      "\"Pantone matching\" claim: the StreetBond brochure mentions custom colours and 73+ standard colours; it does not explicitly state \"full Pantone matching.\" Pantone PMS codes ARE published on TrafficPatterns/TPXD colour guides, but not on StreetBond. Confirm with HUBSS whether the Pantone-match claim is supportable for StreetBond specifically.",
      "Site \"30–50 sq ft per gallon\" — defensible at the 3–4 layer level but only meaningful with a layer-count qualifier. Recommend wording: \"Coverage 36–49 ft²/gal at 3–4 layer build (pedestrian / vehicular).\"",
      "Site \"2–4 hours dry time\" — accurate as TOUCH-DRY, but cure-to-traffic is 6–24 hours. Recommend separating: touch-dry 1–4 hr, cure-to-traffic 6–24 hr.",
      "Manufacturer line attribution: legacy PDFs still carry 'Quest Construction Products' branding while newer TDSs read 'StreetBond by GAF.' Confirm with the supplier which branding should appear on the HUBSS website.",
    ],
    discrepancies: [
      "Current site is silent on manufacturer attribution. StreetBond is a GAF/StreetBond product, not an Ennis-Flint/PPG product. This matters because GAF and PPG are different companies — and Doug is likely to be asked about it by spec writers.",
      "Current site lists 'Pantone matching' as a spec. Pantone reference values are published for TrafficPatterns colours, not for StreetBond — the StreetBond colour guide uses StreetBond's own colour codes. Update the spec to '73+ standard colours plus custom colour-matching capability' until Pantone is verified.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "StreetBondSR",
    filename: "04-StreetBondSR.docx",
    eyebrow: "Flagship — Solar-Reflective Pavement Coating",
    manufacturer: "GAF / StreetBond (Parsippany NJ). Same parent product family as StreetBond. HUBSS is the Canadian distributor.",
    whatItIs: [
      "Solar-reflective version of StreetBond150 — the standard waterborne epoxy-modified acrylic coating is paired with high-SRI pigment colourants to reduce surface temperature and mitigate urban heat island effects.",
      "Engineered specifically for projects targeting LEED v4 Sustainable Sites Credit 7.1 (Heat Island Effect — Non-Roof), climate action plan implementation, or municipal heat-mitigation programs.",
    ],
    keyFeatures: [
      "Solar Reflectance Index (SRI) ≥ 29 qualifies for LEED credit — multiple StreetBondSR colours documented above this threshold.",
      "'Invisible Shade' colourant technology pushes Solar Reflectance > 0.334 — meeting LEED thresholds without restricting designs to white or light grey only.",
      "Same flexible adhesion + slip-resistance characteristics as StreetBond150 — the SR effect is achieved through colourant chemistry, not by changing the base coating.",
      "Documented compliance with LEED v4 SSc7.1 (Heat Island Effect) and Green Neighborhood Development GIB Credit 9.",
      "Manufactured in ISO 9001 and ISO 14001 facilities.",
    ],
    specs: [
      ["Base coating", "StreetBond150 (waterborne epoxy-modified acrylic)"],
      ["Volume solids", "58.2% (ASTM D2697)"],
      ["Weight solids", "74.9% (ASTM D2369)"],
      ["Density", "13.8 lbs/gal (1.58 kg/L) per ASTM D1475"],
      ["Shore hardness", "38.3 (ASTM D2240)"],
      ["VOC", "Approx. 19 g/L measured (ASTM D3960-05) — well below SCAQMD Rule 1113 thresholds"],
      ["Friction — wet", "77 BPN (ASTM E303)"],
      ["Friction — dry", "81 BPN (ASTM E303)"],
      ["Solar Reflectance Index", "Limestone Grey SRI = 65; Slate SRI = 33; multiple other SR-qualifying colours"],
      ["Solar Reflectance (SR, distinct from SRI)", "≥ 0.334 with Invisible Shade colourants"],
      ["LEED credit", "SSc7.1 Heat Island Effect (Non-Roof) — 1 credit at SRI ≥ 29 on ≥ 50% of hardscape"],
      ["Flexibility (mandrel bend)", "Passes 6.35 mm @ 21°C; passes 101.6 mm @ -18°C"],
      ["Drying — re-coat", "35 min at 23°C, 37% RH (ASTM D5895)"],
    ],
    colours: "Same overall StreetBond palette (73+ colours), with SR-qualifying colours flagged in the StreetBondSR Colour Guide. Documented SR values include Marigold 0.35, Avocado 0.35, Pumpkin Spice 0.33, Chestnut Brown 0.34, Limestone Grey SRI 65, Slate SRI 33.",
    applications: [
      "Parking lots targeting LEED Heat Island Reduction credit",
      "Civic plazas and pedestrian-priority areas in climate-action zones",
      "School and campus hardscape (children's surface temperature exposure)",
      "Urban parks and pathways in heat-vulnerable communities",
      "Commercial sites with sustainability reporting requirements",
    ],
    documents: [
      { title: "StreetBondSR Brochure",                       type: "Brochure",     filename: "StreetBondSR-Brochure.pdf" },
      { title: "Colour Guide — SR-qualifying tones",          type: "Colour Guide", filename: "Colour-Guide-1.pdf" },
      { title: "Friction Certificate of Analysis (ASTM E303)",type: "Certificate",  filename: "StreetBond-SR-Certificate-of-Analysis-Friction.pdf" },
      { title: "Flat Surface Product Specification",          type: "Specification",filename: "StreetBond-SR-Flat-Surface-Specification.pdf" },
    ],
    sources: [
      "StreetBondSR Brochure and Flat Surface Specification (.pdf)",
      "StreetBondSR Friction Certificate of Analysis — GeoEngineers (.pdf)",
      "StreetBondSR Colour Guide (.pdf)",
    ],
    verifyFlags: [
      "Current site spec reads \"Initial Solar Reflectance ≥ 0.33\" — defensible, but the technical foundation is actually SRI ≥ 29 (the LEED-credit metric). SR and SRI are related but different scales. Recommend stating BOTH: \"SRI ≥ 29 (LEED qualifying) / Solar Reflectance > 0.334 with Invisible Shade colourants.\"",
      "LEED credit name — \"SS Credit: Heat Island Reduction\" is current LEED v4 language; LEED v4.1 may use updated nomenclature. Confirm the current credit label HUBSS wants on the site.",
      "Coverage / dry time / cure are inherited from StreetBond150 — confirm they should be listed on the SR page directly or referenced back to the StreetBond page.",
    ],
    discrepancies: [
      "Current site lists Solar Reflectance ≥ 0.33 as a flat number. The SR test value documented in the materials is ≥ 0.334. More importantly, the LEED requirement is SRI ≥ 29 (a different, more rigorous metric). The site should reflect the LEED metric directly.",
      "Document library on the current site does not show the Friction Certificate of Analysis prominently — for LEED submissions and municipal procurement, this is one of the most useful documents to feature, since it documents both slip resistance AND VOC compliance in one place.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "StreetPrint",
    filename: "05-StreetPrint.docx",
    eyebrow: "Flagship — Stamped Asphalt System",
    manufacturer: "Integrated Paving Concepts (IPC) — originator of the StreetHeat® reciprocating asphalt re-heating technology. The colour coat is StreetBond150 (GAF). HUBSS is the Canadian certified-applicator network.",
    whatItIs: [
      "A genuine stamped-asphalt system. The asphalt itself is reheated in place with StreetHeat® infrared equipment, imprinted with a wire-rope template using a vibratory plate compactor, then coated with StreetBond150 for colour and protection.",
      "The finished surface IS the asphalt — there is no separate paver, no thermoplastic inlay, no joints. This makes the surface flush with the surrounding road and structurally compatible with municipal winter maintenance.",
    ],
    keyFeatures: [
      "Surface is the asphalt itself — imprinted, not a separate material laid on top.",
      "Flush with surrounding pavement — no raised edges, no shear risk under snowplow blades.",
      "More than 50 million square feet installed since 1992 (manufacturer claim).",
      "100+ template SKUs across 15 pattern families: Offset Brick, Diagonal Herringbone, Standard Herringbone, Ashlar Slate, British Cobble, Stone, Eurofan, Scallop, Tile sets, Borders, Accents, Radial Extensions, Numbers/Letters, Signage/Playground, International.",
      "Colour comes from StreetBond150 — full 73+ colour StreetBond palette available.",
      "Left uncoated, the imprinted asphalt can be opened to traffic immediately.",
      "Must be installed by a certified StreetPrint applicator. HUBSS maintains the Canadian applicator certification.",
    ],
    specs: [
      ["System", "Imprinted asphalt + StreetBond150 colour coat"],
      ["Imprint depth", "Minimum 3/8 inch — areas less than 3/8\" must be reheated and re-stamped"],
      ["Asphalt heating depth", "Minimum 1/2 inch (12.5 mm) without burning the surface"],
      ["Surface temperature limit during heating", "Must not exceed 325°F (162°C) by infrared measurement"],
      ["Recommended HMA thickness", "1.5–2 inches compacted. 1\" asphalt risky (grout-line cracking)"],
      ["Open to traffic — uncoated", "Immediately"],
      ["Open to traffic — coated", "Per StreetBond150 cure schedule: 6–24 hours"],
      ["Pattern library", "15 families, 100+ individual template SKUs"],
      ["Template sizes", "SR-120, SR-60, SR-20 (proprietary); paver-compatible options"],
      ["Substrate", "Asphalt only — not for patios, pool decks, or concrete surfaces"],
      ["Warranty on imprint itself", "None — variables outside manufacturer control (traffic, asphalt mix, install quality). Coating carries StreetBond warranty."],
    ],
    colours: "Full StreetBond150 colour palette — 73+ standard colours plus custom. SR-qualifying tones available for LEED projects (use the StreetBondSR specification when SR is required).",
    applications: [
      "Decorative crosswalks on asphalt",
      "Residential and commercial driveways",
      "Parks, pathways, and trails",
      "Plazas and pedestrian-priority streetscapes",
      "Town home developments and community-branding installations",
      "Heritage district streetscape recreations (brick, cobble, slate, fan patterns)",
      "Traffic-calming installations and gateway treatments",
      "Public art installations using custom templates",
    ],
    documents: [
      { title: "StreetPrint FAQ",                            type: "FAQ",           filename: "StreetPrint-FAQ.pdf" },
      { title: "Asphalt Texturing Specification",            type: "Specification", filename: "StreetPrint-Asphalt-Texturing-Specification.pdf" },
      { title: "Colour Guide",                               type: "Colour Guide",  filename: "StreetPrint-Colour-Guide.pdf" },
      { title: "Template Catalog (100+ pattern SKUs)",       type: "Template Catalog", filename: "StreetPrint-Template-Catalog.pdf" },
    ],
    sources: [
      "StreetPrint Asphalt Texturing Specification (.pdf)",
      "StreetPrint FAQ (.pdf)",
      "StreetPrint Template Catalog (.pdf)",
      "StreetPrint Colour Guide (.pdf)",
    ],
    verifyFlags: [
      "Current site claims \"12+ standard patterns.\" The Template Catalog shows 100+ SKUs across 15 families. Recommend updating to \"100+ patterns across 15 families.\"",
      "\"Snowplow-safe\" — the flush-surface design absolutely is plow-tolerant in practice, but no PDF reviewed uses the exact phrase \"snowplow-safe.\" Confirm with HUBSS that this is the right shorthand to use on the website.",
      "\"More than 50 million square feet installed since 1992\" — manufacturer marketing claim. Confirm whether HUBSS wants to use this number or a Canada-specific figure.",
      "The original product is sometimes referred to as just \"StreetPrint\" and sometimes as \"StreetPrint Genuine Stamped Asphalt.\" Confirm preferred product name for site copy.",
    ],
    discrepancies: [
      "Current site says \"12+ standard patterns plus fully custom designs.\" Significantly understated — the Template Catalog includes 100+ SKUs in 15 pattern families. Easy fix and a stronger marketing claim.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "DecoMark",
    filename: "06-DecoMark.docx",
    eyebrow: "Specialty — Custom Surface Signage & Branding",
    manufacturer: "Ennis-Flint® by PPG (PPG Traffic Solutions, Greensboro NC). Distributed by Flint Trading, Inc. HUBSS is the Canadian sales/support distributor.",
    whatItIs: [
      "A custom preformed thermoplastic system for horizontal surface graphics — logos, wayfinding, civic art, school spirit markings, brand identification, community-pride installations. Factory-fabricated to artwork specifications, then heat-fused to asphalt or concrete.",
      "DecoMark is non-reflective and is positioned by the manufacturer as branding/identification + directional surface signage — distinct from the regulatory pavement-marking line. The category eyebrow should reflect this (currently \"Specialty & Regulatory\" — proposed: \"Specialty / Branding & Surface Signage\").",
    ],
    keyFeatures: [
      "Made-to-order from vector artwork (CAD or vector files accepted).",
      "Factory-fabricated multi-colour segments — 24 in × 36 in, factory-assembled.",
      "Heat-fused to asphalt and concrete (including green concrete that has set but not appreciably hardened).",
      "Surface signage that lasts 6 to 8 times longer than painted alternatives (longer in pedestrian-only areas).",
      "ADA-compliant pedestrian and wheelchair-friendly surface.",
      "Manufactured in an ISO 9001:2015 certified facility.",
    ],
    specs: [
      ["Material", "Preformed thermoplastic — ester-modified rosin, aggregates, pigments, binders, anti-skid elements"],
      ["Minimum thickness", "125 mil (3.18 mm)"],
      ["Standard sheet size", "24 in × 36 in (0.6 m × 0.91 m), factory-assembled multi-colour segments"],
      ["Anti-skid (intermixed)", "Minimum 30% intermix; minimum 9 Mohs hardness (highest in the line)"],
      ["Skid resistance", "Minimum 60 BPN per ASTM E303"],
      ["Static friction", "Minimum 0.6 (wet & dry) per ASTM C1028 / ASTM D2047"],
      ["Minimum install temperature", "45°F (7°C) ambient and road — no pavement preheating required"],
      ["Substrate", "Asphalt and Portland cement concrete (including green concrete)"],
      ["Installation tools", "Propane torch, infrared heater, or blue-flame radiant heater — no compactor required"],
      ["Sealer", "Two-component sealer required prior to application (supplied in 300/600 mL cartridges)"],
      ["Storage", "12 months indoors at 35°F–90°F"],
      ["Carton", "Max 40 in × 25 in; max 70 lb (32 kg)"],
    ],
    colours: "35+ standard colours: Black, Grey, Light Grey, Khaki, Sand, Tan, Cinnamon, Salmon, Pink, Santa Fe Clay, Heritage Red, Terracotta, Sienna, Brick Red, Dark Brick Red, Cocoa, Colonial Brick, Red, Sonoma Sand, Chestnut, Orange, Burnt Orange, Yellow, Lemon Yellow, SYG, Olive Green, Field Gray, Lilac, Purple, Blue, Light Blue, Sky Blue, Teal, Green, Light Green, Kelly Green, White. Custom colour-matching available within manufacturing limits.",
    applications: [
      "Custom logos and brand identification (civic, school, corporate)",
      "Wayfinding and directional surface signage",
      "School spirit and community pride markings",
      "Indigenous public art partnerships and civic mural installations",
      "Neighbourhood placemaking",
      "Shopping mall and commercial property branding",
      "Parks, trails, and trailhead identification",
      "Accessibility wayfinding (combined with appropriate regulatory markings)",
    ],
    documents: [
      { title: "Product Specification",                  type: "Specification", filename: "DecoMark-Specification.pdf" },
      { title: "Application Instructions",               type: "Application Guide", filename: "DecoMark-Application-Instructions.pdf" },
      { title: "Custom Design Guidelines",               type: "Design Guide",  filename: "DecoMark-Custom-Design-Guidelines.pdf" },
      { title: "Colour Guide",                           type: "Colour Guide",  filename: "DecoMark-Colour-Guide.pdf" },
      { title: "Technical Data Sheet (TS004)",           type: "TDS",           filename: "TS004_DecoMark_220204.pdf" },
    ],
    sources: [
      "DecoMark Specification, Application Instructions, TS004 TDS, Colour Guide (.pdf)",
      "Ennis-Flint by PPG product literature",
    ],
    verifyFlags: [
      "Current site eyebrow is \"Specialty & Regulatory.\" DecoMark is positioned by the manufacturer as a branding / identification / surface-signage product — not specifically regulatory. Recommend revised eyebrow: \"Specialty / Custom Surface Signage\" or \"Specialty / Branding & Wayfinding.\"",
      "\"Print-grade colour accuracy\" — defensible language, but the technical limit is the 35+ standard palette plus custom-match capability. Confirm that HUBSS does not promise digital-print fidelity (which is a different thermoplastic technology entirely).",
      "Minimum order: site says \"project-based.\" Confirm with HUBSS whether there is a minimum dollar value, minimum sq ft, or no minimum at all.",
    ],
    discrepancies: [
      "Category eyebrow \"Specialty & Regulatory\" misrepresents the product. DecoMark is decorative + branding; regulatory pavement markings are PreMark territory.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "MMAX",
    filename: "07-MMAX.docx",
    eyebrow: "Specialty — MMA Resin Coloured Lane Treatment",
    manufacturer: "Ennis-Flint® by PPG (PPG Traffic Solutions). HUBSS is the Canadian distributor. Older APAC documentation refers to Ennis Traffic Safety Solutions Pty Ltd, Australia — same parent.",
    whatItIs: [
      "A two-component methyl methacrylate (MMA) resin coating with corundum aggregate. Squeegee-, roller-, or spray-applied. Used as a coloured lane treatment for transit lanes, BRT corridors, and cycle priority zones — anywhere a fast-curing, high-grip, fade-resistant coloured surface is needed.",
      "Not a preformed thermoplastic. MMAX is liquid-applied and cures via a BPO (benzoyl peroxide) catalyst added at installation.",
    ],
    keyFeatures: [
      "Cures to traffic-ready in 30 to 60 minutes — typically 45 minutes — enabling complete overnight installation in active corridors.",
      "Corundum aggregate (9 Mohs hardness — hardest in the anti-skid lineup) embedded throughout the cured film.",
      "Extended Season variant applies down to 35°F (2°C) substrate temperature and up to 150°F (66°C).",
      "VOC < 100 g/L (calculated) for the Extended Season formulation.",
      "EF Green colour meets FHWA chromaticity coordinates for bike-lane green; Transit Lane Red meets coordinates for bus-lane red.",
      "ISO 9001:2015 certified manufacturing.",
    ],
    specs: [
      ["Material", "Two-component MMA resin + corundum aggregate. BPO catalyst added at install."],
      ["Aggregate hardness", "Corundum, 9 Mohs"],
      ["Density", "18.5 ± 0.5 lbs/gallon (ASTM D1475)"],
      ["Viscosity", "85–105 Krebs"],
      ["Shore hardness", "50–60 Shore D (ASTM D2240)"],
      ["Elongation", "> 30% (ASTM D638 Type I)"],
      ["Total solids", "> 99%"],
      ["Water absorption", "< 0.25% (ASTM D570)"],
      ["VOC", "< 100 g/L (Extended Season)"],
      ["Build thickness", "90 mil typical per kit coverage spec"],
      ["Application temperature", "35°F to 150°F (2°C to 66°C) substrate temp (Extended Season variant)"],
      ["Pot life after BPO addition", "< 15 minutes"],
      ["No-pickup time", "< 30 minutes at 77°F (25°C) per ASTM D711"],
      ["Cure to traffic", "30–60 minutes (temperature + catalyst dependent)"],
      ["Skid resistance", "> 60 BPN per ASTM E303 (Extended Season with corundum)"],
      ["Coverage", "45–50 sq ft per kit at 90-mil build (one kit = 2.79 gal mixed)"],
      ["Shelf life", "1 year unopened, stored 40°F–80°F"],
    ],
    colours: "8 standard kit colours: EF Green (PMS 361C), Transit Lane Red (PMS 7622C), Truffle (PMS 7530C), Terracotta (PMS 7595C), Brick Red (PMS 7624C), Hollywood Green (PMS 7484C), Red (PMS 200C), White. Older PDS lists EF Black, EF Yellow, EF Blue, and EF Bus Lane Red as additional options. Custom colours available on request.",
    applications: [
      "Coloured bike lanes (EF Green)",
      "Coloured bus lanes / BRT corridors (Transit Lane Red)",
      "Transit priority surfaces and bus-stop pads",
      "Coloured crosswalks where rapid cure is required",
      "Symbols and legends on coloured background lanes",
      "Cool-weather and shoulder-season work where MMAX Extended Season's wider temperature window is needed",
    ],
    documents: [
      { title: "MMAX Product Data Sheet",                              type: "TDS",          filename: "MMAX-Product-Data.pdf" },
      { title: "MMAX Next-Gen Brochure",                               type: "Brochure",     filename: "MMAX-Next-Gen-Brochure_06_09_23-1.pdf" },
      { title: "Extended Season MMAX — Product Data Sheet",            type: "TDS",          filename: "Extended-Season-MMAX-product-data-sheet.pdf" },
      { title: "Extended Season MMAX Corundum — Product Data Sheet",   type: "TDS",          filename: "Extended-Season-MMAX-Corundum-PDS-070723.pdf" },
      { title: "Corundum Area Markings — Application Instructions",    type: "Installation", filename: "Application_Instructions_MMAX_Corundum_Area_Markings.pdf" },
    ],
    sources: [
      "MMAX Product Data Sheet and Extended Season variants (.pdf)",
      "MMAX Application Instructions for Corundum Area Markings (.pdf)",
      "MMAX Next-Gen Brochure (.pdf)",
    ],
    verifyFlags: [
      "Current site spec \"+3°C and rising minimum temperature\" — conservative compared to Extended Season MMAX's documented 35°F (≈ 2°C) floor. Both are correct, but Extended Season is the actual selling point. Recommend revising to \"Extended Season variant applies down to 2°C substrate temperature, up to 66°C.\"",
      "Current site says \"1.5–3 mm thickness applied.\" The PDS states 90 mil typical build (≈ 2.3 mm). 1.5 mm is below the documented build; 3 mm is above. Recommend tightening to \"approximately 2.3 mm (90 mil) typical build, applied in two coats.\"",
      "Current site says \"acrylic-MMA chemistry\" for UV stability. MMAX is described in the PDS as pure MMA — no acrylic component. Recommend revising to \"MMA-based, UV-stable pigments.\"",
    ],
    discrepancies: [
      "Site spec lists temperature as \"+3°C and rising\" — Extended Season's actual lower limit is 35°F (2°C). The site is more conservative than the manufacturer's documented capability.",
      "Site spec lists \"1.5–3mm applied\" thickness. Manufacturer's typical build is 90 mil ≈ 2.3 mm. Range on the site is wider than the manufacturer's recipe.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "DuraTherm",
    filename: "08-DuraTherm.docx",
    eyebrow: "Specialty — Inlaid Preformed Thermoplastic",
    manufacturer: "Ennis-Flint® by PPG (PPG Traffic Solutions). HUBSS is the Canadian distributor and certified-applicator network.",
    whatItIs: [
      "An inlaid preformed thermoplastic pavement marking system. A specialized infrared heater softens the asphalt, a template imprints depressions into the heated surface, and precut DuraTherm sheets are placed into the depressions, then thermally bonded.",
      "The thermoplastic sits SLIGHTLY BELOW the surface level of the surrounding asphalt — 'snowplow friendly.' This sub-flush profile is what makes DuraTherm uniquely tolerant of snowplow blades and aggressive winter maintenance.",
    ],
    keyFeatures: [
      "Sub-flush installation — thermoplastic sits slightly below the surrounding asphalt level for plow tolerance.",
      "Imprinted, not milled — the depression is formed by template + heat + vibratory plate compactor (700–900 lb), not by cold-milling a groove.",
      "90 mil minimum thickness — described in manufacturer marketing as \"90-mil grout lines.\"",
      "Heat-fused to asphalt by Ennis-Flint StreetHeat® / Magnum / Flint2000EX equipment.",
      "Anti-skid: minimum 6 Mohs intermix, minimum 8 Mohs surface-applied.",
      "Manufactured without glass beads — DuraTherm is non-reflective.",
      "ISO 9001 certified manufacturing; ADA-compliant pedestrian + wheelchair-friendly surface.",
      "Must be installed by an Ennis-Flint TrafficScapes Certified Applicator. HUBSS is the Canadian certifying body.",
    ],
    specs: [
      ["Material", "Preformed thermoplastic — ester-modified rosin, aggregates, pigments, binders, anti-skid elements"],
      ["Minimum thickness", "90 mil (2.3 mm)"],
      ["Sheet sizes", "Primary pattern sheets 24 in × 24 in (0.6 × 0.6 m). Borders 8 in or 12 in wide × 24 in long"],
      ["Template sizes", "150-mil thickness; standard crosswalk widths 6 ft to 20 ft in 2-ft increments"],
      ["Anti-skid (intermixed)", "Min 30% intermix, min 6 Mohs hardness"],
      ["Anti-skid (surface)", "Min 8 Mohs hardness"],
      ["Skid resistance", "Minimum 60 BPN per ASTM E303"],
      ["Static friction", "Minimum 0.6 (wet & dry) per ASTM C1028 / ASTM D2047"],
      ["Minimum install temperature", "40°F (5°C) ambient and road — DO NOT apply below 5°C"],
      ["Substrate", "ASPHALT ONLY — the specification explicitly excludes Portland cement concrete"],
      ["Installation", "Template + 700–900 lb vibratory plate compactor + Ennis-Flint infrared heating equipment"],
      ["Storage", "12 months indoors"],
      ["Carton", "Max 25 in × 25 in; max 50 lb (23 kg)"],
    ],
    colours: "Standard: White, Sand, Tan, Cinnamon, Salmon, Burnt Orange, Sienna, Khaki, Sonoma Sand, Chestnut, Santa Fe Clay, Heritage Red, Colonial Brick, Brick Red, Red, Yellow, School Green, Sky Blue. Premium: Light Grey, Light Green, Green, Olive, SYG, Lemon Yellow, Orange, Red, Kelly Green, Teal, Light Blue, Blue, Purple, Pink. Patterns: Running Bond, Running Bond R90, Herringbone, Herringbone R90, Plain Weave, Basket Weave, Diagonal Tile (large + small), Stacked Tile (large + small), Honeycomb, Courtyard, Ashlar, Wheels w/ Brick Frame, Wheels w/ Tile Frame, Scalloped, Wheels.",
    applications: [
      "Public roadway crosswalks (typically inlaid between standard white crosswalk lines)",
      "Streetscape elements and traffic-calming patterns",
      "Heritage districts and community-branding inlays",
      "Residential and commercial pedestrian/vehicular areas",
      "Pedestrian plazas with vehicular access through the area",
      "Anywhere snowplow tolerance is the deciding factor between decorative pavement options",
    ],
    documents: [
      { title: "Product Specification (branded HUBSS cover)", type: "Specification", filename: "DuraTherm-Specification-Branded.pdf" },
      { title: "Colour Guide",                                type: "Colour Guide",  filename: "Duratherm-Colour-Guide.pdf" },
      { title: "Technical Data Sheet (TS003)",                type: "TDS",           filename: "TS003_DuraTherm_220204.pdf" },
      { title: "Custom Design Guidelines",                    type: "Design Guide",  filename: "Duratherm-Custom-Design-Guidelines.pdf" },
      { title: "Design Manual",                               type: "Design Manual", filename: "DuraTherm-Design-Manual.pdf" },
    ],
    sources: [
      "DuraTherm Specification (.pdf)",
      "DuraTherm TS003 Technical Data Sheet (.pdf)",
      "DuraTherm Colour Guide and Design Manual (.pdf)",
    ],
    verifyFlags: [
      "Site says \"flush with the surrounding road — no raised edges, no profile for plow blades.\" Manufacturer language is \"slightly below the surface level\" (sub-flush) — that's what makes it plow-tolerant. Site language is directionally right but slightly imprecise. Confirm whether to keep \"flush\" (consumer-friendly) or shift to \"sub-flush\" (technically accurate).",
      "Site says \"embedded into a milled groove in the asphalt.\" The depression is created by template imprinting into heated asphalt, NOT by cold milling. Recommend revising to \"imprinted into heated asphalt by template and vibratory plate compactor.\"",
      "Asphalt only — confirm the current site never implies DuraTherm can be installed on concrete. The TS003 sheet is explicit that the system is not approved for Portland cement concrete.",
    ],
    discrepancies: [
      "Site copy says DuraTherm sits in a \"milled groove.\" Manufacturer install method is template-imprinted into heated asphalt — fundamentally different from cold milling.",
      "Site copy says \"flush surface, zero plow profile.\" Manufacturer describes the installed thermoplastic as sub-flush (\"slightly below the surface level\"). The intent is right; precise wording should match the spec.",
      "Currently no clear callout on the site that DuraTherm is asphalt-only. The manufacturer's specification is explicit: not approved for Portland cement concrete. This should be visible on the product page.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "DuraShield",
    filename: "09-DuraShield.docx",
    eyebrow: "Specialty — Asphalt Maintenance Coating",
    manufacturer: "GAF / StreetBond (Parsippany NJ). DuraShield is a StreetBond family product, NOT an Ennis-Flint / PPG product. HUBSS is the Canadian distributor.",
    whatItIs: [
      "A two-component waterborne epoxy-modified acrylic pavement maintenance coating, spray + back-roll applied to asphalt. Used for parking lots, residential driveways, and pedestrian areas where colour, slip resistance, and chemical protection are required — but the heavy decorative finish of StreetBond150 isn't needed.",
      "Available in two documented colour variants: Asphalt (black) and Solar Gray. Solar Gray provides solar reflectance for heat-mitigation projects.",
    ],
    keyFeatures: [
      "Same flexible epoxy-modified acrylic chemistry as StreetBond — moves with the pavement, will not peel.",
      "Solar Gray variant: Solar Reflectance = 0.33, contributes to heat-island mitigation.",
      "VOC < 50 g/L — well below SCAQMD Rule 1113 thresholds for industrial maintenance coatings.",
      "Excellent chemical resistance — manufacturer cites resistance to UV damage; per-chemical fuel/oil/deicing-specific resistance data is not enumerated in the TDS.",
      "Available with anti-slip aggregate broadcast for pedestrian areas (a field practice, not enumerated in the two TDS files reviewed).",
      "24-month shelf life unopened (40°F–90°F).",
    ],
    specs: [
      ["Type", "Two-component waterborne epoxy-modified acrylic"],
      ["Density", "14.3 lbs/gal (1.7 kg/L) per ASTM D1475"],
      ["Volume solids", "57% (±2) per ASTM D2697"],
      ["Weight solids", "75% (±2) per ASTM D2369"],
      ["Shore hardness", "80.8 (ASTM D2240)"],
      ["Mandrel bend", "1-1/2 in @ 23°C per ASTM D522-93 A"],
      ["Water absorption", "< 6% (ASTM D570)"],
      ["VOC", "< 50 g/L (calculated)"],
      ["Solar Reflectance (Solar Gray variant)", "SR = 0.33 initial"],
      ["Coverage", "65 sq ft/gallon (1.6 m²/L), 25 mil wet / 14 mil dry, in 2 layers"],
      ["Taber abrasion — dry (H-10 wheel)", "0.7 g per 1,000 cycles per ASTM D4060"],
      ["Taber abrasion — wet (H-10 wheel)", "3 g per 1,000 cycles"],
      ["Friction — dry", "> 65 BPN per ASTM E303"],
      ["Friction — wet", "> 35 BPN per ASTM E303"],
      ["Drying — touch dry", "35 min at 73°F (23°C), 37% RH (ASTM D5895)"],
      ["Minimum install temperature", "50°F (10°C) and rising; not to drop below 50°F within 24 hours"],
      ["Packaging", "Part A 5-gal (3.75 gal net) + Part B 1-pint (10 oz net); OR Part A 55-gal drum + Part B 2-gal"],
      ["Substrate", "Asphalt (per the two TDS sheets reviewed)"],
    ],
    colours: "Two documented colours per the TDS sheets: Asphalt (black) and Solar Gray. Per TDS, colour \"cannot be altered using supplemental pigments.\" Other colours may exist in the broader DuraShield line — verify with the manufacturer if expanded palette claims are needed on the site.",
    applications: [
      "Parking lots — asphalt restoration and protection",
      "Residential driveways — paving and asphalt maintenance",
      "Pathways, raised medians, pedestrian plazas",
      "Pedestrian areas (anti-slip aggregate broadcast option)",
      "Asphalt surfaces exposed to chemicals (fuel, oil, deicers) — per manufacturer claim",
      "Heat-mitigation surfaces (Solar Gray variant for parking lots and large hardscape)",
    ],
    documents: [
      { title: "Part A+B Asphalt (black) — Technical Data Sheet",     type: "TDS", filename: "DuraShield-Pavement-Coating-Part-A-B-Color-Asphalt-TDS.pdf" },
      { title: "Part A+B Solar Gray — Technical Data Sheet",          type: "TDS", filename: "DuraShield-Pavement-Coating-Part-A-B-Color-Solar-Gray-TDS.pdf" },
    ],
    sources: [
      "DuraShield Asphalt (black) Part A+B Technical Data Sheet (.pdf)",
      "DuraShield Solar Gray Part A+B Technical Data Sheet (.pdf)",
    ],
    verifyFlags: [
      "Current site says SR = 0.34. The TDS documents SR = 0.33. Recommend correcting to 0.33.",
      "Current site says \"low VOC, meets SCAQMD regulations.\" The TDS lists VOC < 50 g/L — defensible as meeting SCAQMD Rule 1113 limits, but the TDS itself does not explicitly cite SCAQMD certification. Recommend revising to \"Low VOC (< 50 g/L) — meets typical industrial maintenance coating limits.\"",
      "Current site says \"fuel/oil/deicing resistant.\" The TDS lists \"Excellent chemical resistance\" generically and \"Highly resistant to UV damage,\" but specific fuel/oil/deicing-resistance test results are not enumerated. Confirm with manufacturer or soften to \"chemically resistant per manufacturer.\"",
      "Current site says \"anti-slip available with aggregate texture.\" This is a standard field practice but is not documented in the two TDS sheets reviewed. Confirm whether DuraShield has a defined anti-slip add-mix or whether this is broadcast aggregate (field decision).",
      "Manufacturer attribution: confirm whether the HUBSS website should attribute DuraShield to GAF / StreetBond, or present it as a HUB Surface Systems product without manufacturer attribution. The TDS is a GAF/StreetBond document.",
    ],
    discrepancies: [
      "Site spec says Solar Reflectance = 0.34. The Solar Gray TDS clearly states SR = 0.33 initial. Easy correction.",
      "Site claim of SCAQMD compliance is not directly supported by the TDS, which only lists VOC < 50 g/L. The two facts are consistent but not equivalent.",
      "Site claim of fuel / oil / deicing resistance is more specific than the TDS supports. The TDS uses the generic phrase \"excellent chemical resistance.\" Per-chemical test data would need to come from the manufacturer.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "AirMark",
    filename: "10-AirMark.docx",
    eyebrow: "Specialty — Airport Pavement Marking System",
    manufacturer: "Ennis-Flint® by PPG (PPG Traffic Solutions, Greensboro NC). HUBSS is the Canadian distributor. IMPORTANT: the AirMark folder bundles three RELATED but DISTINCT products — see Document Library below.",
    whatItIs: [
      "AirMark is the preformed thermoplastic pavement marking system specifically engineered for airfield use — taxiways, ramps, aprons, gates, and vehicular airside roads. The 'airside' descriptor is what distinguishes AirMark from airport landside markings (driveways, parking lots, terminal access roads), which use PreMark for Airports.",
      "AirMark is NON-RUNWAY. Runway and primary taxiway markings use a separate liquid waterborne acrylic — WB Airfield / Traffic Paint for Airfields — applied via airless spray. Three distinct products live in the AirMark folder; each has its own page on this section of the document.",
    ],
    keyFeatures: [
      "Preformed thermoplastic with retroreflective glass beads embedded throughout the cross-section.",
      "Designed to meet FAA airfield marking requirements; brochure references FAA Advisory Circular guidelines and ICAO standards.",
      "Heat-applied, withstands jet blast, snow clearing, rubber removal treatments, and the daily operational demands of an active airfield.",
      "5 standard colours (NOT just white and yellow): Red, White, Yellow, Black, Pink.",
      "Applied by certified crews — installation efficiency reduces runway / taxiway closure time vs. hand-painted multi-colour markings.",
      "Manufactured in an ISO 9001:2015 certified facility.",
    ],
    specs: [
      ["Application", "Taxiways, ramps, aprons, gates, vehicular airside roads — NON-RUNWAY"],
      ["Material", "Preformed thermoplastic with retroreflective glass beads embedded throughout cross-section"],
      ["Colours", "5 standard: Red, White, Yellow, Black, Pink"],
      ["Compliance reference", "FAA Advisory Circular (AC 150/5340-1 series) and ICAO standards"],
      ["Manufacturing", "ISO 9001:2015 certified"],
      ["Installation", "Heat application by certified crews"],
      ["Thickness", "[Not stated in AirMark brochure reviewed — VERIFY against TDS or PPG technical sheet]"],
      ["Cure / open-to-traffic", "[Not stated in AirMark brochure reviewed — VERIFY]"],
      ["Coverage rate", "[Not stated in AirMark brochure reviewed — VERIFY]"],
      ["Retroreflectivity (mcd/m²/lux)", "[Not stated in AirMark brochure reviewed — VERIFY]"],
    ],
    colours: "5 standard colours: Red, White, Yellow, Black, Pink. Custom colours [VERIFY] — not stated in the brochure reviewed.",
    applications: [
      "Taxiway centrelines, hold-short markings, designators",
      "Apron and ramp markings",
      "Helipad markings",
      "Gate and stand markings",
      "Vehicular airside roadway markings (service-road striping, intersection markings)",
      "Ground-vehicle parking and traffic-flow markings",
    ],
    documents: [
      { title: "AirMark Brochure (English)",                          type: "Brochure",    filename: "AirMark/AirMark_Brocure.pdf" },
      { title: "AirMark Brochure (French)",                           type: "Brochure (FR)", filename: "AirMark/AirMark-Brocure-FR.pdf" },
      { title: "PreMark for Airports (landside thermoplastic)",       type: "Brochure",    filename: "PreMark - Groundside/PreMark-for-Airports.pdf" },
      { title: "WB Airfield Paint (waterborne, runway-capable)",      type: "TDS",         filename: "Airfield Paint/WB-Airfield-Product-Data.pdf" },
      { title: "Traffic Paint for Airfields (English)",               type: "Brochure",    filename: "Airfield Paint/TrafficPaint-for-Airfields.pdf" },
      { title: "Traffic Paint for Airfields (French)",                type: "Brochure (FR)", filename: "Airfield Paint/TrafficPaint-for-Airfields-FR.pdf" },
    ],
    sources: [
      "AirMark Brochure — English (.pdf)",
      "PreMark for Airports — landside thermoplastic brochure (.pdf)",
      "WB Airfield Product Data Sheet — waterborne paint TDS (.pdf)",
      "Traffic Paint for Airfields brochure (.pdf)",
    ],
    verifyFlags: [
      "Current site says \"white and yellow.\" AirMark brochure documents FIVE standard colours: Red, White, Yellow, Black, Pink. Update the website palette.",
      "Thickness, cure time, coverage rate, retroreflectivity values: NONE of these were stated in the AirMark brochure reviewed. The TDS for AirMark specifically (separate from the airfield paint TDS) was not present in the docs folder. Source these directly from PPG before publishing on the website.",
      "Three distinct products are sometimes conflated in the AirMark folder. Recommend reorganizing the document library by product (AirMark / PreMark for Airports / WB Airfield Paint), since the website's Resources page reads from this folder.",
      "Runway vs. non-runway: Doug's note confirmed AirMark is NON-RUNWAY only. Runway markings are the territory of WB Airfield / Traffic Paint for Airfields. Make sure the website page does not imply AirMark is used on runways.",
      "FAA Advisory Circular: the brochure prints \"AC 150/5349-1,\" which appears to be a typo. The standard current AC is AC 150/5340-1 (most recent revision is L). Confirm correct AC reference before quoting it on the site.",
    ],
    discrepancies: [
      "Current site lists only \"white and yellow\" colours. AirMark brochure lists 5 standard colours.",
      "Current site copy doesn't distinguish AirMark from PreMark for Airports or WB Airfield Paint. These are three different products in the same folder. Each should have a clear identity if any of them are to appear on the website.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "PreMark",
    filename: "11-PreMark.docx",
    eyebrow: "Specialty — Regulatory Pavement Markings",
    manufacturer: "Ennis-Flint® by PPG (PPG Traffic Solutions). PreMark® and ViziGrip® are registered trademarks; PreMarkXF™ is a trademark. HUBSS is the Canadian distributor.",
    whatItIs: [
      "Pre-cut preformed thermoplastic regulatory pavement markings — arrows, stop bars, yield triangles, school-zone legends, bike-lane pictograms, accessible parking symbols, crosswalk lines, rumble strips. Heat-applied with a propane torch, with no surface preheating required. Lasts 6 to 8 times longer than paint.",
      "PreMark is offered in four manufacturing finishes (BD, VG, NB, SK) that determine surface texture and retroreflectivity. PreMarkXF is the cold-weather variant with no minimum road or ambient temperature requirement.",
    ],
    keyFeatures: [
      "Heat-applied via industrial propane torch — drive-on immediately after installation.",
      "Made with up to 60% recycled material (sustainability claim from manufacturer brochure).",
      "Impervious to oil and gasoline.",
      "Manufacturing finishes: BD (Beaded — full retroreflectivity), VG (ViziGrip — beads + anti-skid for crosswalks/bike/accessibility), NB (Non-Beaded — for reversible arrows), SK (Skid-Only — for coloured preferential lanes).",
      "PreMarkXF cold-weather variant: \"No minimum road or ambient temperature requirements for application.\"",
      "24-month shelf life (PreMark); 2 years (PreMarkXF).",
      "Manufactured in an ISO 9001:2015 certified facility.",
      "ADA-compliant pedestrian and wheelchair-friendly surface.",
    ],
    specs: [
      ["Material", "Preformed thermoplastic — high-quality resin, binder, aggregate; up to 60% recycled material"],
      ["Manufacturing finishes", "BD (Beaded), VG (ViziGrip), NB (Non-Beaded), SK (Skid-Only)"],
      ["Standard thickness", "[Not explicitly stated in TS005 or PreMarkXF Brochure reviewed — site claims 125 mil / 90 mil ViziGrip — VERIFY against a PPG PreMark spec sheet]"],
      ["Installation", "Industrial propane heat torch — no surface preheating required"],
      ["Application temperature (PreMark)", "[Not stated in TS005 — VERIFY]"],
      ["Application temperature (PreMarkXF)", "No minimum road or ambient temperature requirements"],
      ["Retroreflectivity (BD / VG variants)", "Factory-applied surface beads + intermix glass beads, exposed as surface wears"],
      ["Skid resistance", "VG and SK variants carry anti-skid elements; BD relies on bead surface profile"],
      ["Sealer", "Recommended on concrete and for large multi-coloured / colorized-lane installations"],
      ["Substrate", "Asphalt and concrete (sealer recommended for concrete)"],
      ["Shelf life", "24 months (PreMark) / 2 years (PreMarkXF)"],
    ],
    colours: "10 standard regulatory colours: Black, Blue, Purple, Red, Grey, Green, Orange, White, Bike Lane Green, Yellow.",
    applications: [
      "Turn arrows, stop bars, yield triangles",
      "School zone legends and school-area markings",
      "Bike pictograms and lane symbols",
      "Accessible parking symbols (ISA — International Symbol of Accessibility)",
      "Crosswalk ladder lines and continental crosswalk patterns",
      "Rumble strips and traffic-calming legends",
      "Coloured preferential lane symbols (SK variant)",
      "Reversible arrows (NB variant)",
    ],
    documents: [
      { title: "Technical Data Sheet (TS005)",                      type: "TDS",      filename: "TS005_PreMark_220204.pdf" },
      { title: "PreMarkXF Brochure (cold-weather variant)",         type: "Brochure", filename: "PreMarkXF-Brochure.pdf" },
    ],
    sources: [
      "PreMark TS005 Technical Data Sheet (.pdf)",
      "PreMarkXF Brochure (.pdf)",
    ],
    verifyFlags: [
      "Standard thickness — current site claims 125 mil standard and 90 mil ViziGrip. NEITHER value is explicitly stated in the TS005 sheet or PreMarkXF brochure reviewed. The 125 mil / 90 mil split is plausible (it matches the TrafficPatternsXD transverse line stripe thicknesses) but should be confirmed against a PreMark-specific spec sheet from PPG before being published.",
      "Application temperature for standard PreMark — TS005 does not state a minimum. PreMarkXF is the cold-weather variant. Confirm whether standard PreMark has a documented minimum (e.g., 45°F like other Ennis-Flint thermoplastics) or whether PreMarkXF should be the default product called out for Canadian conditions.",
      "Site lists \"intersection-grade glass bead surface.\" Only the BD and VG manufacturing finishes carry surface beads — NB and SK do not. Recommend clarifying that retroreflectivity depends on finish selection.",
      "\"Lower total cost of ownership than traditional marking methods\" — defensible based on the 6–8× life claim, but no specific TCO calculation is in the docs. If the website wants to quote a number (\"X% lower TCO\"), source it.",
    ],
    discrepancies: [
      "Site spec lists \"125 mil standard / 90 mil ViziGrip option\" as a thickness fact. The PDFs reviewed do not state these numbers. ViziGrip (VG) is a manufacturing finish (surface beads + anti-skid), not a thickness option per se. Verify the actual thickness numbers from a current PPG PreMark spec sheet before re-using these figures.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "ChipFill",
    filename: "12-ChipFill.docx",
    eyebrow: "Concrete & Asphalt Repair",
    manufacturer: "Geveko Markings (Denmark / Sweden). Distributed in Canada by HUB Surface Systems. NOTE: ChipFill is a Geveko Markings product, NOT a HUB-manufactured product. Current website branding suggests it is HUB-owned — this should be reviewed.",
    whatItIs: [
      "A hot-applied surface defect repair material designed for permanent restoration of road damage — potholes, cracks, joints, surface defects, cobblestone joints. Pre-formed in chip form, laid into the prepared defect, and activated with a propane heat torch.",
      "All-year-round application capability. Sets rapidly so traffic can re-open within minutes of installation. Used in combination with AggreFill for larger potholes (up to ~1 m²).",
    ],
    keyFeatures: [
      "Hot-applied — propane heat torch activation, no specialized equipment or hot-mix plant required.",
      "Year-round, all-conditions deployment — works through Canadian winters when hot-mix asphalt plants are closed.",
      "Conforms to defect contour and bonds chemically to surrounding asphalt or concrete.",
      "Seals the repaired area against water ingress — addresses the freeze-thaw mechanism that turns minor defects into structural failures.",
      "Sets in minutes — lane can re-open to traffic same shift.",
      "Pre-formed chip format makes it possible to repair small defects without aggregate batching or asphalt-plant logistics.",
    ],
    specs: [
      ["Type", "Hot-applied preformed surface defect repair material"],
      ["Application method", "Lay into defect, activate with propane heat torch"],
      ["Substrate", "Asphalt and concrete"],
      ["Weather window", "All year, all conditions"],
      ["Cure / re-open to traffic", "Minutes after install"],
      ["Defect size — standalone", "Smaller defects: cracks, joints, surface defects, small potholes"],
      ["Defect size — with AggreFill", "Up to ~1 m² in diameter"],
      ["Material composition", "[Not stated in Geveko web summary — VERIFY]"],
      ["Temperature range for install", "[Not stated in Geveko web summary — VERIFY]"],
      ["Packaging / bag size", "[VERIFY — search results show 26 lb bag at ATS Traffic Canada]"],
    ],
    colours: "Standard: Black (asphalt match). Confirm with Geveko Markings whether other colours are available for cobblestone or decorative repair contexts.",
    applications: [
      "Routine patrol patching (smaller potholes, cracks)",
      "Emergency response programs",
      "Utility-cut restoration (small-scale)",
      "Edge-joint repair",
      "Cobblestone joint filling",
      "Sidewalk, pathway, and pedestrian-infrastructure spot repair",
      "Parking lots, residential driveways, and townhouse pavements",
    ],
    documents: [
      // ChipFill currently has NO PDFs in /public/docs/. Documents listed here would need to be sourced from Geveko Markings.
    ],
    sources: [
      "Geveko Markings ChipFill product page (https://www.geveko-markings.com/products/complementary-and-trading-goods/chipfill/)",
      "Geveko Markings Road & Surface Repair solution page (https://www.geveko-markings.com/solutions/road-surface-repair)",
      "ATS Traffic Canada product listing — ChipFill 26 lb Black (https://store.atstraffic.ca/chipfill-26-lbs-black-81240012)",
      "Global Highways: \"Geveko's ChipFill makes its mark\" (https://www.globalhighways.com/wh3/products/gevekos-chipfill-makes-its-mark)",
    ],
    verifyFlags: [
      "CRITICAL: Manufacturer attribution. ChipFill is a Geveko Markings product, not a HUB-manufactured product. The product is also distributed by ATS Traffic in Canada. Current website implies HUB ownership. Confirm whether HUBSS holds an exclusive Canadian distribution arrangement, a regional one, or simply resells. Either way, manufacturer attribution should be visible on the page.",
      "There are NO PDFs in /public/docs/chipfill/ — meaning the site currently has no document downloads for this product at all. Recommend sourcing a Geveko Markings TDS, application instructions, and (if available) a YouTube install video to complete the document library.",
      "Material composition, temperature range, exact cure time in seconds, bag size, coverage rate, shelf life: none of these are stated on the Geveko product page summary. They will need to be sourced from a Geveko TDS or from HUBSS's direct supplier contact.",
      "\"Permanent\" claim: Geveko marketing says \"permanent restoration.\" Confirm with the manufacturer how this compares to municipal definitions of permanent (typically ≥ 2 years).",
    ],
    discrepancies: [
      "Current website implies ChipFill is a HUB-owned product. It is in fact manufactured by Geveko Markings (Denmark/Sweden) and is also sold in Canada through other distributors (e.g., ATS Traffic). This is a meaningful attribution issue and should be reviewed before publishing.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "AggreFill",
    filename: "13-AggreFill.docx",
    eyebrow: "Concrete & Asphalt Repair",
    manufacturer: "Geveko Markings (Denmark / Sweden). Distributed in Canada by HUB Surface Systems. AggreFill is a Geveko Markings product, paired with their ChipFill repair system.",
    whatItIs: [
      "A pre-coated aggregate filler used in combination with ChipFill to permanently repair larger potholes — up to approximately 1 m² in diameter. AggreFill provides the structural mass to fill the void; ChipFill bonds the aggregate matrix and seals the repaired surface.",
      "The AggreFill + ChipFill system is positioned by the manufacturer as a permanent repair, not a seasonal temporary patch. Year-round deployment, traffic-ready within minutes.",
    ],
    keyFeatures: [
      "Two-product system: AggreFill fills the void, ChipFill bonds and seals.",
      "Larger pothole capacity — up to ~1 m² diameter and deeper than ChipFill alone can address.",
      "Cold-applied aggregate plus heat-torch ChipFill matrix — no hot-mix plant required.",
      "Year-round, all-conditions deployment.",
      "Sets in minutes — lane can re-open to traffic same shift.",
      "Pre-coated aggregate produces a chemical bond to the surrounding pavement when heat-activated alongside ChipFill.",
    ],
    specs: [
      ["Type", "Pre-coated aggregate filler — paired with Geveko ChipFill"],
      ["Application method", "Cold-applied aggregate, then heat-torch ChipFill matrix above and around"],
      ["Substrate", "Asphalt and concrete"],
      ["Repair size", "Up to approximately 1 m² in diameter"],
      ["Cure / re-open to traffic", "Minutes after install (matches ChipFill)"],
      ["Weather window", "All year, all conditions"],
      ["Material composition", "[Not stated in Geveko web summary — VERIFY]"],
      ["Aggregate gradation", "[VERIFY]"],
      ["Coverage rate", "[VERIFY]"],
      ["Bag size", "[VERIFY]"],
    ],
    colours: "Aggregate-coloured. Not a decorative product.",
    applications: [
      "Larger road potholes (up to ~1 m²)",
      "Parking lot craters",
      "Industrial-site pothole damage",
      "Utility cut restoration (medium-scale)",
      "Driveway and townhouse pavement deep repair",
      "Any pothole too deep or wide for stand-alone ChipFill",
    ],
    documents: [
      // AggreFill currently has NO PDFs in /public/docs/. Documents listed here would need to be sourced from Geveko Markings.
    ],
    sources: [
      "Geveko Markings — \"How to apply AggreFill™ for ChipFill™\" (YouTube)",
      "Geveko Markings — Road & Surface Repair solution page",
      "Geveko Markings — Hot-applied high-performance materials product category",
    ],
    verifyFlags: [
      "Manufacturer attribution — AggreFill is Geveko Markings, paired with their ChipFill product. Same attribution question as ChipFill: confirm HUBSS distribution arrangement and whether manufacturer should be visible on the website.",
      "There are NO PDFs in /public/docs/aggrefill/ — the site has no document downloads for AggreFill. Recommend sourcing the Geveko AggreFill TDS and application instructions.",
      "Material composition (aggregate type, pre-coating chemistry), exact coverage rate, bag size, and full application temperature window are all not enumerated in the public Geveko web pages. Source these from a Geveko TDS or direct supplier contact.",
      "\"Permanent\" claim: same caveat as ChipFill — confirm the manufacturer's definition of permanent (typically ≥ 2 years).",
    ],
    discrepancies: [
      "Same attribution issue as ChipFill — AggreFill is a Geveko Markings product, not HUB-manufactured.",
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  {
    name: "Fast Patch DPR",
    filename: "14-FastPatchDPR.docx",
    eyebrow: "Concrete & Asphalt Repair",
    manufacturer: "FastPatch® is a registered trademark of The Willamette Valley Company LLC (USA), marketed through FastPatch Systems (fastpatchsystems.com) and PavePatch.com. Distributed in Canada by HUB Surface Systems. NOTE: Fast Patch DPR is a Willamette Valley Company product, NOT a HUB-manufactured product.",
    whatItIs: [
      "FastPatch DPR (Distressed Pavement Repair) is a polymer-blend pourable repair material for asphalt and concrete — engineered for high-strength, fast-return-to-service repair of potholes, spalls, joints, wheel paths, and utility cuts. Mixed with a cordless drill, poured into the defect, and back in service in less than 45 minutes.",
      "Made from a unique polymer blend with up to 80% recycled and renewable materials (manufacturer claim). Odourless — suitable for indoor environments where ventilation rules out hot-mix or solvent-based materials.",
    ],
    keyFeatures: [
      "Back in service in less than 45 minutes (1 hr at 75°F, 2–3 hr at 50–65°F).",
      "FastPatch Kicker accelerator available for cooler-weather work — shortens cure time further.",
      "100% solids, 80% recycled/renewable polymer matrix.",
      "Completely odourless — suitable for warehouse floors, loading docks, and underground parking where ventilation constraints exclude petroleum-based materials.",
      "Excellent freeze-thaw resistance and impact absorption.",
      "Snowplow-friendly.",
      "Available in asphalt-repair formulation and concrete-repair formulation.",
      "Pre-measured kits: 5-gallon (11 L), 3-gallon (5 L), 1-gallon (2.5 L).",
    ],
    specs: [
      ["Type", "Polymer-blend distressed pavement repair material"],
      ["Composition", "Polymer matrix with up to 80% recycled and renewable materials; 100% solids"],
      ["Application method", "Mix with cordless drill, pour, finish"],
      ["Cure time at 75°F (24°C)", "1 hour"],
      ["Cure time at 50–65°F (10–18°C)", "2–3 hours"],
      ["Return to service", "< 45 minutes (with appropriate temperature/accelerator)"],
      ["Cold-weather option", "FastPatch Kicker accelerator"],
      ["Substrate", "Asphalt and concrete (separate formulations available)"],
      ["Kit sizes", "5 gal (11 L) / 3 gal (5 L) / 1 gal (2.5 L) pre-measured kits"],
      ["Odour", "Odourless — suitable for indoor application"],
      ["Freeze-thaw resistance", "Excellent (manufacturer claim)"],
      ["Snowplow compatibility", "Snow-plow friendly"],
      ["VOC", "[Not stated on FastPatch product page — VERIFY]"],
      ["Manufacturer", "The Willamette Valley Company LLC (USA)"],
    ],
    colours: "Black (asphalt formulation) and concrete-grey (concrete formulation). Not a decorative product.",
    applications: [
      "Roadways and bridges — spalls, crack repair, joint repair, broken corners, surface leveling, potholes",
      "Airports — spalls, wheel-path areas, approaches and departures",
      "Parking lots — potholes, walkways, broken areas",
      "Warehouses — floor spalls, loading-dock areas",
      "Sidewalks and curbs — trip-hazard remediation, walkway repair",
      "Indoor environments where ventilation constraints exclude solvent or asphalt-emulsion products",
    ],
    documents: [
      // FastPatch DPR currently has NO PDFs in /public/docs/. Documents would need to be sourced from FastPatch Systems / Willamette Valley Co.
    ],
    sources: [
      "FastPatch Systems — FastPatch DPR product page (https://fastpatchsystems.com/fastpatch-dpr/)",
      "PavePatch.com — FASTPATCH product overview (https://www.pavepatch.com/fastpatch-product-overview-i-18.html)",
      "Amazon product page — FASTPATCH DPR Pourable Asphalt Repair 5-Gal Kit",
    ],
    verifyFlags: [
      "CRITICAL: Manufacturer attribution. Fast Patch DPR is The Willamette Valley Company LLC, marketed through FastPatch Systems. The current HUBSS website does not attribute this. Confirm whether HUBSS holds a Canadian distribution arrangement and how the website should display manufacturer attribution.",
      "There are NO PDFs in /public/docs/fast-patch/ — the site has no document downloads. Recommend sourcing the FastPatch DPR TDS, MSDS/SDS, application instructions, and Kicker product literature from FastPatch Systems.",
      "VOC value, exact freeze-thaw cycle count, ASTM test data, and specific compliance certifications are not enumerated on the manufacturer's public product page. Source from the TDS / SDS.",
      "\"Up to 80% recycled and renewable materials\" — manufacturer claim. Confirm before quoting the specific 80% figure on the HUBSS site (the figure varies kit-to-kit per manufacturer marketing).",
      "FastPatch DPR is sold under the FastPatch® brand. Confirm whether HUBSS website should use \"Fast Patch DPR\" (current site) or \"FASTPATCH® DPR\" (manufacturer style) — trademark display matters.",
    ],
    discrepancies: [
      "Current site presents Fast Patch DPR as a HUB-distributed product without manufacturer attribution. The product is a registered trademark of Willamette Valley Company / FastPatch Systems and is distributed by several US/Canadian retailers — exclusive Canadian distribution arrangement (if any) should be confirmed and visible.",
      "Current site claims \"completely odourless, making it suitable for indoor environments including warehouse floors, loading docks, and underground parkades.\" Manufacturer confirms odourless + indoor suitability — claim is supported.",
    ],
  },
];
