/*
 * PHOTO DROP INSTRUCTIONS
 * =======================
 * Drop photos into public/images/applications/[slug]/
 *
 * Folder mapping from client photo library:
 * Crosswalks/           → crosswalks/
 * Commercial Spaces/    → commercial-spaces/
 * Splash Pads/          → splash-pads/
 * Playgrounds/          → playgrounds/
 * Parking Lots/         → parking-lots/
 * Parks & Paths/        → parks-paths/
 * Bike Lanes/           → bike-lanes/
 * Bus Lanes/            → bus-lanes/
 * Community Branding/   → community-branding/
 * Regulatory Markings/  → regulatory-markings/
 * Traffic Calming/      → traffic-calming/
 * Airports/             → airports/
 * Private Driveways/    → private-driveways/
 * Townhomes/            → townhomes/
 * LEED - Urban Heat Island/ → leed-urban-heat-island/
 *
 * Hero image:  hero.jpg (landscape, min 1920px wide)
 * Gallery:     01.jpg, 02.jpg, 03.jpg etc.
 * All images:  JPG, under 2MB each
 */

export interface Application {
  name: string;
  slug: string;
  shortDesc: string;
  imageUrl: string;
  gallery?: string[];
  description?: string[];
  relatedProducts?: string[];
  benefits?: string[];
  relatedPost?: { slug: string; title: string; excerpt: string };
  col?: string;
}

export const applications: Application[] = [
  {
    name: "Crosswalks",
    slug: "crosswalks",
    shortDesc: "High-visibility pedestrian crossings built with thermoplastic, stamped asphalt, and custom civic identity.",
    imageUrl: "/images/applications/crosswalks/crosswalks-01.jpg",
    gallery: [
      "/images/applications/crosswalks/crosswalks-01.jpg",
      "/images/applications/crosswalks/crosswalks-02.jpg",
      "/images/applications/crosswalks/crosswalks-03.jpg",
      "/images/applications/crosswalks/crosswalks-04.jpg",
      "/images/applications/crosswalks/crosswalks-05.jpg",
      "/images/applications/crosswalks/crosswalks-06.jpg",
      "/images/applications/crosswalks/crosswalks-07.jpg",
      "/images/applications/crosswalks/crosswalks-08.jpg",
      "/images/applications/crosswalks/crosswalks-09.jpg",
      "/images/applications/crosswalks/crosswalks-10.jpg",
      "/images/applications/crosswalks/crosswalks-100.jpg",
      "/images/applications/crosswalks/crosswalks-101.jpg",
      "/images/applications/crosswalks/crosswalks-102.jpg",
      "/images/applications/crosswalks/crosswalks-103.jpg",
      "/images/applications/crosswalks/crosswalks-104.jpg",
      "/images/applications/crosswalks/crosswalks-105.jpg",
      "/images/applications/crosswalks/crosswalks-106.jpg",
      "/images/applications/crosswalks/crosswalks-107.jpg",
      "/images/applications/crosswalks/crosswalks-108.jpg",
      "/images/applications/crosswalks/crosswalks-109.jpg",
      "/images/applications/crosswalks/crosswalks-11.jpg",
      "/images/applications/crosswalks/crosswalks-110.jpg",
      "/images/applications/crosswalks/crosswalks-111.png",
      "/images/applications/crosswalks/crosswalks-112.png",
      "/images/applications/crosswalks/crosswalks-113.png",
      "/images/applications/crosswalks/crosswalks-114.png",
      "/images/applications/crosswalks/crosswalks-115.png",
      "/images/applications/crosswalks/crosswalks-116.jpg",
      "/images/applications/crosswalks/crosswalks-117.jpg",
      "/images/applications/crosswalks/crosswalks-118.jpg",
      "/images/applications/crosswalks/crosswalks-119.jpg",
      "/images/applications/crosswalks/crosswalks-12.jpg",
      "/images/applications/crosswalks/crosswalks-120.jpg",
      "/images/applications/crosswalks/crosswalks-121.jpg",
      "/images/applications/crosswalks/crosswalks-122.jpg",
      "/images/applications/crosswalks/crosswalks-13.jpg",
      "/images/applications/crosswalks/crosswalks-14.jpg",
      "/images/applications/crosswalks/crosswalks-15.jpg",
      "/images/applications/crosswalks/crosswalks-16.jpg",
      "/images/applications/crosswalks/crosswalks-17.jpg",
      "/images/applications/crosswalks/crosswalks-18.jpg",
      "/images/applications/crosswalks/crosswalks-19.jpg",
      "/images/applications/crosswalks/crosswalks-20.jpg",
      "/images/applications/crosswalks/crosswalks-21.jpg",
      "/images/applications/crosswalks/crosswalks-22.jpg",
      "/images/applications/crosswalks/crosswalks-23.jpg",
      "/images/applications/crosswalks/crosswalks-24.jpg",
      "/images/applications/crosswalks/crosswalks-25.jpg",
      "/images/applications/crosswalks/crosswalks-26.jpg",
      "/images/applications/crosswalks/crosswalks-27.jpg",
      "/images/applications/crosswalks/crosswalks-28.jpg",
      "/images/applications/crosswalks/crosswalks-29.jpg",
      "/images/applications/crosswalks/crosswalks-30.jpg",
      "/images/applications/crosswalks/crosswalks-31.jpg",
      "/images/applications/crosswalks/crosswalks-32.jpg",
      "/images/applications/crosswalks/crosswalks-33.jpg",
      "/images/applications/crosswalks/crosswalks-34.jpg",
      "/images/applications/crosswalks/crosswalks-35.jpg",
      "/images/applications/crosswalks/crosswalks-36.jpg",
      "/images/applications/crosswalks/crosswalks-37.jpg",
      "/images/applications/crosswalks/crosswalks-38.jpg",
      "/images/applications/crosswalks/crosswalks-39.jpg",
      "/images/applications/crosswalks/crosswalks-40.png",
      "/images/applications/crosswalks/crosswalks-41.png",
      "/images/applications/crosswalks/crosswalks-42.jpg",
      "/images/applications/crosswalks/crosswalks-43.jpg",
      "/images/applications/crosswalks/crosswalks-44.jpg",
      "/images/applications/crosswalks/crosswalks-45.jpg",
      "/images/applications/crosswalks/crosswalks-46.jpg",
      "/images/applications/crosswalks/crosswalks-47.jpg",
      "/images/applications/crosswalks/crosswalks-48.jpg",
      "/images/applications/crosswalks/crosswalks-49.jpg",
      "/images/applications/crosswalks/crosswalks-50.jpg",
      "/images/applications/crosswalks/crosswalks-51.jpg",
      "/images/applications/crosswalks/crosswalks-52.jpg",
      "/images/applications/crosswalks/crosswalks-53.jpg",
      "/images/applications/crosswalks/crosswalks-54.jpg",
      "/images/applications/crosswalks/crosswalks-55.jpg",
      "/images/applications/crosswalks/crosswalks-56.jpg",
      "/images/applications/crosswalks/crosswalks-57.jpg",
      "/images/applications/crosswalks/crosswalks-58.jpg",
      "/images/applications/crosswalks/crosswalks-59.jpg",
      "/images/applications/crosswalks/crosswalks-60.jpg",
      "/images/applications/crosswalks/crosswalks-61.jpg",
      "/images/applications/crosswalks/crosswalks-62.jpg",
      "/images/applications/crosswalks/crosswalks-63.jpg",
      "/images/applications/crosswalks/crosswalks-64.jpg",
      "/images/applications/crosswalks/crosswalks-65.jpg",
      "/images/applications/crosswalks/crosswalks-66.jpg",
      "/images/applications/crosswalks/crosswalks-67.jpg",
      "/images/applications/crosswalks/crosswalks-68.jpg",
      "/images/applications/crosswalks/crosswalks-69.jpg",
      "/images/applications/crosswalks/crosswalks-70.jpg",
      "/images/applications/crosswalks/crosswalks-71.jpg",
      "/images/applications/crosswalks/crosswalks-72.jpg",
      "/images/applications/crosswalks/crosswalks-73.jpg",
      "/images/applications/crosswalks/crosswalks-74.jpg",
      "/images/applications/crosswalks/crosswalks-75.jpg",
      "/images/applications/crosswalks/crosswalks-76.jpg",
      "/images/applications/crosswalks/crosswalks-77.jpg",
      "/images/applications/crosswalks/crosswalks-78.jpg",
      "/images/applications/crosswalks/crosswalks-79.jpg",
      "/images/applications/crosswalks/crosswalks-80.jpg",
      "/images/applications/crosswalks/crosswalks-81.jpg",
      "/images/applications/crosswalks/crosswalks-82.jpg",
      "/images/applications/crosswalks/crosswalks-83.jpg",
      "/images/applications/crosswalks/crosswalks-84.jpg",
      "/images/applications/crosswalks/crosswalks-85.jpg",
      "/images/applications/crosswalks/crosswalks-86.jpg",
      "/images/applications/crosswalks/crosswalks-87.jpg",
      "/images/applications/crosswalks/crosswalks-88.jpg",
      "/images/applications/crosswalks/crosswalks-89.jpg",
      "/images/applications/crosswalks/crosswalks-90.jpg",
      "/images/applications/crosswalks/crosswalks-91.jpg",
      "/images/applications/crosswalks/crosswalks-92.jpg",
      "/images/applications/crosswalks/crosswalks-93.jpg",
      "/images/applications/crosswalks/crosswalks-94.jpg",
      "/images/applications/crosswalks/crosswalks-95.jpg",
      "/images/applications/crosswalks/crosswalks-96.jpg",
      "/images/applications/crosswalks/crosswalks-97.jpg",
      "/images/applications/crosswalks/crosswalks-98.jpg",
      "/images/applications/crosswalks/crosswalks-99.jpg",
    ],

    description: [
      "Crosswalks are the most visible expression of pedestrian safety in any Canadian municipality. HUB Surface Systems provides the full spectrum of crosswalk marking solutions — from standard preformed thermoplastic for high-traffic intersections to decorative stamped asphalt treatments that define neighbourhood character and slow traffic through visual cues.",
      "Our thermoplastic systems (TrafficPatterns and TrafficPatternsXD) deliver retroreflective performance that exceeds TAC and MUTCD requirements, with durability that outlasts traditional paint by 5–10x. For municipalities with Vision Zero commitments, high-contrast ladder crosswalks and coloured intersection treatments measurably improve pedestrian detection at critical points — particularly during low-light and wet conditions.",
      "Decorative crosswalk programs have transformed corridors in Vancouver, York Region, Toronto, and across the country — turning utilitarian infrastructure into community identity markers that celebrate local culture while reinforcing pedestrian priority.",
    ],
    relatedProducts: ["traffic-patterns", "traffic-patterns-xd", "decomark", "premark", "duratherm"],
    benefits: [
      "5–10x longer service life than painted markings",
      "ASTM Type III and IV retroreflectivity standards",
      "Vision Zero compatible — high-contrast ladder designs",
      "Custom decorative patterns for community identity",
      "20-year colour retention on StreetPrint treatments",
      "AODA compliant colour contrast and tactile integration",
    ],
    col: "sm:col-span-2 sm:row-span-2",
  },
  {
    name: "Commercial Spaces",
    slug: "commercial-spaces",
    shortDesc: "Decorative pavement for retail entries, plazas, and commercial properties.",
    imageUrl: "/images/applications/commercial-spaces/commercial-spaces-01.jpg",
    gallery: [
      "/images/applications/commercial-spaces/commercial-spaces-01.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-02.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-03.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-04.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-05.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-06.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-07.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-08.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-09.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-10.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-100.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-101.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-102.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-103.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-104.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-105.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-106.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-107.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-108.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-109.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-11.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-110.png",
      "/images/applications/commercial-spaces/commercial-spaces-111.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-112.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-113.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-114.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-115.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-12.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-13.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-14.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-15.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-16.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-17.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-18.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-19.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-20.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-21.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-22.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-23.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-24.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-25.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-26.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-27.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-28.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-29.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-30.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-31.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-32.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-33.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-34.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-35.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-36.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-37.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-38.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-39.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-40.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-41.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-42.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-43.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-44.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-45.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-46.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-47.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-48.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-49.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-50.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-51.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-52.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-53.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-54.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-55.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-56.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-57.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-58.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-59.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-60.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-61.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-62.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-63.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-64.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-65.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-66.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-67.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-68.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-69.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-70.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-71.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-72.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-73.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-74.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-75.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-76.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-77.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-78.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-79.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-80.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-81.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-82.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-83.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-84.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-85.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-86.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-87.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-88.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-89.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-90.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-91.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-92.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-93.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-94.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-95.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-96.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-97.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-98.jpg",
      "/images/applications/commercial-spaces/commercial-spaces-99.jpg",
    ],

    description: [
      "Commercial properties compete on first impressions. Stamped asphalt, coloured coatings, and precision thermoplastic markings communicate quality, care, and brand alignment from the moment a customer arrives. HUB's StreetPrint and StreetBond systems give developers and property managers a premium aesthetic at a fraction of the cost of concrete or stone pavers — with none of the joint maintenance.",
      "TrafficPatternsXD durable preformed markings delineate driveways, fire lanes, accessible routes, and pedestrian crossings within commercial developments with crisp, long-lasting precision.",
    ],
    relatedProducts: ["streetprint", "streetbond", "traffic-patterns-xd"],
    benefits: [
      "Premium aesthetic at fraction of paver installed cost",
      "20-year colour retention on StreetBond treatments",
      "Complete fire lane, accessible route, and safety markings",
      "Minimal installation disruption — phased execution available",
    ],
    col: "",
  },
  {
    name: "Splash Pads",
    slug: "splash-pads",
    shortDesc: "Safe, colourful surface systems for water play areas and aquatic facility surrounds.",
    imageUrl: "/images/applications/splash-pads/splash-pads-01.jpg",
    gallery: [
      "/images/applications/splash-pads/splash-pads-01.jpg",
      "/images/applications/splash-pads/splash-pads-02.jpg",
      "/images/applications/splash-pads/splash-pads-03.jpg",
      "/images/applications/splash-pads/splash-pads-04.jpg",
      "/images/applications/splash-pads/splash-pads-05.jpg",
      "/images/applications/splash-pads/splash-pads-06.jpg",
      "/images/applications/splash-pads/splash-pads-07.jpg",
      "/images/applications/splash-pads/splash-pads-08.jpg",
      "/images/applications/splash-pads/splash-pads-09.jpg",
      "/images/applications/splash-pads/splash-pads-10.jpg",
      "/images/applications/splash-pads/splash-pads-11.png",
      "/images/applications/splash-pads/splash-pads-12.jpg",
      "/images/applications/splash-pads/splash-pads-13.jpg",
      "/images/applications/splash-pads/splash-pads-14.jpg",
      "/images/applications/splash-pads/splash-pads-15.jpg",
      "/images/applications/splash-pads/splash-pads-16.jpg",
      "/images/applications/splash-pads/splash-pads-17.jpg",
      "/images/applications/splash-pads/splash-pads-18.jpg",
      "/images/applications/splash-pads/splash-pads-19.jpg",
    ],

    description: [
      "Splash pads and spray parks require surface systems with specialized performance properties: slip resistance to prevent falls on wet surfaces, chemical resistance to withstand constant water and disinfectant exposure, UV stability to maintain colour intensity through summer seasons, and the durability to sustain heavy barefoot traffic from children and families.",
      "StreetBond's slip-resistant formulation meets all of these requirements while delivering the vivid, playful colours that define great splash pad environments.",
    ],
    relatedProducts: ["streetbond", "mmax"],
    benefits: [
      "Slip-resistant formulation — wet surface safety certified",
      "Chemical resistant — withstands water treatment chemicals",
      "20-year UV-stable colour — vibrant through every season",
      "Custom colour to match themed design concepts",
    ],
    col: "",
  },
  {
    name: "Playgrounds",
    slug: "playgrounds",
    shortDesc: "Bright, durable surface markings and decorative treatments for school and park playgrounds.",
    imageUrl: "/images/applications/playgrounds/playgrounds-01.jpg",
    gallery: [
      "/images/applications/playgrounds/playgrounds-01.jpg",
      "/images/applications/playgrounds/playgrounds-02.jpg",
      "/images/applications/playgrounds/playgrounds-03.jpg",
      "/images/applications/playgrounds/playgrounds-04.jpg",
      "/images/applications/playgrounds/playgrounds-05.jpg",
      "/images/applications/playgrounds/playgrounds-06.jpg",
      "/images/applications/playgrounds/playgrounds-07.jpg",
      "/images/applications/playgrounds/playgrounds-08.jpg",
      "/images/applications/playgrounds/playgrounds-09.jpg",
      "/images/applications/playgrounds/playgrounds-10.jpg",
      "/images/applications/playgrounds/playgrounds-11.jpg",
      "/images/applications/playgrounds/playgrounds-12.jpg",
      "/images/applications/playgrounds/playgrounds-13.jpg",
      "/images/applications/playgrounds/playgrounds-14.jpg",
      "/images/applications/playgrounds/playgrounds-15.jpg",
      "/images/applications/playgrounds/playgrounds-16.jpg",
      "/images/applications/playgrounds/playgrounds-17.jpg",
      "/images/applications/playgrounds/playgrounds-18.jpg",
      "/images/applications/playgrounds/playgrounds-19.jpg",
      "/images/applications/playgrounds/playgrounds-20.jpg",
      "/images/applications/playgrounds/playgrounds-21.jpg",
      "/images/applications/playgrounds/playgrounds-22.jpg",
      "/images/applications/playgrounds/playgrounds-23.jpg",
      "/images/applications/playgrounds/playgrounds-24.jpg",
      "/images/applications/playgrounds/playgrounds-25.jpg",
      "/images/applications/playgrounds/playgrounds-26.jpg",
      "/images/applications/playgrounds/playgrounds-27.jpg",
      "/images/applications/playgrounds/playgrounds-28.jpg",
      "/images/applications/playgrounds/playgrounds-29.jpg",
      "/images/applications/playgrounds/playgrounds-30.jpg",
      "/images/applications/playgrounds/playgrounds-31.jpg",
      "/images/applications/playgrounds/playgrounds-32.jpg",
      "/images/applications/playgrounds/playgrounds-33.jpg",
      "/images/applications/playgrounds/playgrounds-34.jpg",
      "/images/applications/playgrounds/playgrounds-35.jpg",
      "/images/applications/playgrounds/playgrounds-36.jpg",
      "/images/applications/playgrounds/playgrounds-37.jpg",
      "/images/applications/playgrounds/playgrounds-38.jpg",
      "/images/applications/playgrounds/playgrounds-39.jpg",
      "/images/applications/playgrounds/playgrounds-40.jpg",
      "/images/applications/playgrounds/playgrounds-41.jpg",
      "/images/applications/playgrounds/playgrounds-42.jpg",
      "/images/applications/playgrounds/playgrounds-43.jpg",
      "/images/applications/playgrounds/playgrounds-44.jpg",
      "/images/applications/playgrounds/playgrounds-45.jpg",
      "/images/applications/playgrounds/playgrounds-46.jpg",
      "/images/applications/playgrounds/playgrounds-47.jpg",
      "/images/applications/playgrounds/playgrounds-48.jpg",
      "/images/applications/playgrounds/playgrounds-49.jpg",
      "/images/applications/playgrounds/playgrounds-50.jpg",
      "/images/applications/playgrounds/playgrounds-51.jpg",
      "/images/applications/playgrounds/playgrounds-52.jpg",
      "/images/applications/playgrounds/playgrounds-53.jpg",
    ],

    description: [
      "School and park playgrounds demand surface systems that can handle constant foot traffic, weather exposure, and years of active play while maintaining the bright, engaging colours that make outdoor spaces inviting for children.",
      "DecoMark preformed thermoplastic enables custom playground markings — hopscotch courts, four-square grids, compass roses, and educational graphics — with factory-manufactured precision that ensures consistent results and long service life.",
    ],
    relatedProducts: ["streetbond", "decomark", "premark"],
    benefits: [
      "Slip-resistant formulation for safety",
      "20-year UV-stable colour retention",
      "Custom graphics — hopscotch, four-square, educational",
      "AODA compliant accessible surface markings",
    ],
    col: "",
  },
  {
    name: "Parking Lots",
    slug: "parking-lots",
    shortDesc: "Durable line markings, wayfinding graphics, and decorative coatings for parking facilities.",
    imageUrl: "/images/applications/parking-lots/parking-lots-01.jpg",
    gallery: [
      "/images/applications/parking-lots/parking-lots-01.jpg",
      "/images/applications/parking-lots/parking-lots-02.jpg",
      "/images/applications/parking-lots/parking-lots-03.jpg",
      "/images/applications/parking-lots/parking-lots-04.jpg",
      "/images/applications/parking-lots/parking-lots-05.jpg",
      "/images/applications/parking-lots/parking-lots-06.jpg",
      "/images/applications/parking-lots/parking-lots-07.jpg",
      "/images/applications/parking-lots/parking-lots-08.jpg",
      "/images/applications/parking-lots/parking-lots-09.jpg",
      "/images/applications/parking-lots/parking-lots-10.jpg",
      "/images/applications/parking-lots/parking-lots-11.jpg",
      "/images/applications/parking-lots/parking-lots-12.jpg",
      "/images/applications/parking-lots/parking-lots-13.jpg",
      "/images/applications/parking-lots/parking-lots-14.jpg",
      "/images/applications/parking-lots/parking-lots-15.jpg",
      "/images/applications/parking-lots/parking-lots-16.jpg",
      "/images/applications/parking-lots/parking-lots-17.jpg",
      "/images/applications/parking-lots/parking-lots-18.jpg",
      "/images/applications/parking-lots/parking-lots-19.jpg",
      "/images/applications/parking-lots/parking-lots-20.jpg",
      "/images/applications/parking-lots/parking-lots-21.jpg",
      "/images/applications/parking-lots/parking-lots-22.jpg",
      "/images/applications/parking-lots/parking-lots-23.jpg",
      "/images/applications/parking-lots/parking-lots-24.jpg",
      "/images/applications/parking-lots/parking-lots-25.jpg",
      "/images/applications/parking-lots/parking-lots-26.jpg",
      "/images/applications/parking-lots/parking-lots-27.jpg",
      "/images/applications/parking-lots/parking-lots-28.jpg",
      "/images/applications/parking-lots/parking-lots-29.jpg",
      "/images/applications/parking-lots/parking-lots-30.jpg",
      "/images/applications/parking-lots/parking-lots-31.jpg",
      "/images/applications/parking-lots/parking-lots-32.jpg",
      "/images/applications/parking-lots/parking-lots-33.jpg",
      "/images/applications/parking-lots/parking-lots-34.jpg",
      "/images/applications/parking-lots/parking-lots-35.jpg",
      "/images/applications/parking-lots/parking-lots-36.jpg",
      "/images/applications/parking-lots/parking-lots-37.jpg",
      "/images/applications/parking-lots/parking-lots-38.jpg",
      "/images/applications/parking-lots/parking-lots-39.jpg",
      "/images/applications/parking-lots/parking-lots-40.jpg",
      "/images/applications/parking-lots/parking-lots-41.jpg",
      "/images/applications/parking-lots/parking-lots-42.jpg",
      "/images/applications/parking-lots/parking-lots-43.jpg",
      "/images/applications/parking-lots/parking-lots-44.jpg",
      "/images/applications/parking-lots/parking-lots-45.jpg",
      "/images/applications/parking-lots/parking-lots-46.jpg",
      "/images/applications/parking-lots/parking-lots-47.jpg",
      "/images/applications/parking-lots/parking-lots-48.jpg",
      "/images/applications/parking-lots/parking-lots-49.jpg",
      "/images/applications/parking-lots/parking-lots-50.jpg",
      "/images/applications/parking-lots/parking-lots-51.jpg",
      "/images/applications/parking-lots/parking-lots-52.jpg",
      "/images/applications/parking-lots/parking-lots-53.jpg",
      "/images/applications/parking-lots/parking-lots-54.jpg",
      "/images/applications/parking-lots/parking-lots-55.jpg",
      "/images/applications/parking-lots/parking-lots-56.jpg",
      "/images/applications/parking-lots/parking-lots-57.jpg",
      "/images/applications/parking-lots/parking-lots-58.jpg",
      "/images/applications/parking-lots/parking-lots-59.jpg",
    ],

    description: [
      "Commercial and municipal parking facilities experience intense, repetitive loading that degrades both the asphalt substrate and surface markings quickly. DuraShield asphalt rejuvenation coating is the foundation of HUB's parking lot program — restoring oxidized pavement, sealing hairline cracks, and providing a uniform professional finish.",
      "PreMark preformed thermoplastic stall markings, directional arrows, and regulatory symbols deliver crisp, long-lasting delineation that resists the wear that painted markings cannot sustain.",
    ],
    relatedProducts: ["durashield", "premark", "streetbond"],
    benefits: [
      "DuraShield extends pavement life 3–5 years between resurfacing",
      "PreMark stall markings last 5–10x longer than paint",
      "AODA accessible stall symbols — code compliant",
      "Minimal disruption — fast installation and same-day reopen",
    ],
    col: "",
  },
  {
    name: "Parks & Paths",
    slug: "parks-paths",
    shortDesc: "Surface treatments for pathways, greenways, and park infrastructure.",
    imageUrl: "/images/applications/parks-paths/parks-paths-01.jpg",
    gallery: [
      "/images/applications/parks-paths/parks-paths-01.jpg",
      "/images/applications/parks-paths/parks-paths-02.jpg",
      "/images/applications/parks-paths/parks-paths-03.jpg",
      "/images/applications/parks-paths/parks-paths-04.jpg",
      "/images/applications/parks-paths/parks-paths-05.jpg",
      "/images/applications/parks-paths/parks-paths-06.jpg",
      "/images/applications/parks-paths/parks-paths-07.jpg",
      "/images/applications/parks-paths/parks-paths-08.jpg",
      "/images/applications/parks-paths/parks-paths-09.jpg",
      "/images/applications/parks-paths/parks-paths-10.jpg",
      "/images/applications/parks-paths/parks-paths-100.png",
      "/images/applications/parks-paths/parks-paths-101.png",
      "/images/applications/parks-paths/parks-paths-102.png",
      "/images/applications/parks-paths/parks-paths-103.png",
      "/images/applications/parks-paths/parks-paths-104.png",
      "/images/applications/parks-paths/parks-paths-105.png",
      "/images/applications/parks-paths/parks-paths-106.jpg",
      "/images/applications/parks-paths/parks-paths-107.jpg",
      "/images/applications/parks-paths/parks-paths-108.jpg",
      "/images/applications/parks-paths/parks-paths-109.jpg",
      "/images/applications/parks-paths/parks-paths-11.jpg",
      "/images/applications/parks-paths/parks-paths-110.jpg",
      "/images/applications/parks-paths/parks-paths-111.jpg",
      "/images/applications/parks-paths/parks-paths-112.jpg",
      "/images/applications/parks-paths/parks-paths-113.jpg",
      "/images/applications/parks-paths/parks-paths-114.jpg",
      "/images/applications/parks-paths/parks-paths-115.jpg",
      "/images/applications/parks-paths/parks-paths-116.jpg",
      "/images/applications/parks-paths/parks-paths-117.jpg",
      "/images/applications/parks-paths/parks-paths-118.jpg",
      "/images/applications/parks-paths/parks-paths-119.jpg",
      "/images/applications/parks-paths/parks-paths-12.jpg",
      "/images/applications/parks-paths/parks-paths-120.jpg",
      "/images/applications/parks-paths/parks-paths-121.jpg",
      "/images/applications/parks-paths/parks-paths-122.jpg",
      "/images/applications/parks-paths/parks-paths-123.jpg",
      "/images/applications/parks-paths/parks-paths-124.jpg",
      "/images/applications/parks-paths/parks-paths-125.jpg",
      "/images/applications/parks-paths/parks-paths-126.jpg",
      "/images/applications/parks-paths/parks-paths-127.jpg",
      "/images/applications/parks-paths/parks-paths-128.jpg",
      "/images/applications/parks-paths/parks-paths-129.jpg",
      "/images/applications/parks-paths/parks-paths-13.jpg",
      "/images/applications/parks-paths/parks-paths-130.jpg",
      "/images/applications/parks-paths/parks-paths-131.jpg",
      "/images/applications/parks-paths/parks-paths-132.jpg",
      "/images/applications/parks-paths/parks-paths-133.jpg",
      "/images/applications/parks-paths/parks-paths-134.jpg",
      "/images/applications/parks-paths/parks-paths-135.jpg",
      "/images/applications/parks-paths/parks-paths-136.jpg",
      "/images/applications/parks-paths/parks-paths-137.jpg",
      "/images/applications/parks-paths/parks-paths-138.jpg",
      "/images/applications/parks-paths/parks-paths-139.jpg",
      "/images/applications/parks-paths/parks-paths-14.jpg",
      "/images/applications/parks-paths/parks-paths-140.jpg",
      "/images/applications/parks-paths/parks-paths-141.jpg",
      "/images/applications/parks-paths/parks-paths-142.jpg",
      "/images/applications/parks-paths/parks-paths-143.jpg",
      "/images/applications/parks-paths/parks-paths-144.jpg",
      "/images/applications/parks-paths/parks-paths-15.jpg",
      "/images/applications/parks-paths/parks-paths-16.jpg",
      "/images/applications/parks-paths/parks-paths-17.jpg",
      "/images/applications/parks-paths/parks-paths-18.jpg",
      "/images/applications/parks-paths/parks-paths-19.jpg",
      "/images/applications/parks-paths/parks-paths-20.jpg",
      "/images/applications/parks-paths/parks-paths-21.jpg",
      "/images/applications/parks-paths/parks-paths-22.jpg",
      "/images/applications/parks-paths/parks-paths-23.jpg",
      "/images/applications/parks-paths/parks-paths-24.jpg",
      "/images/applications/parks-paths/parks-paths-25.jpg",
      "/images/applications/parks-paths/parks-paths-26.jpg",
      "/images/applications/parks-paths/parks-paths-27.jpg",
      "/images/applications/parks-paths/parks-paths-28.jpg",
      "/images/applications/parks-paths/parks-paths-29.jpg",
      "/images/applications/parks-paths/parks-paths-30.jpg",
      "/images/applications/parks-paths/parks-paths-31.jpg",
      "/images/applications/parks-paths/parks-paths-32.jpg",
      "/images/applications/parks-paths/parks-paths-33.jpg",
      "/images/applications/parks-paths/parks-paths-34.jpg",
      "/images/applications/parks-paths/parks-paths-35.jpg",
      "/images/applications/parks-paths/parks-paths-36.jpg",
      "/images/applications/parks-paths/parks-paths-37.jpg",
      "/images/applications/parks-paths/parks-paths-38.jpg",
      "/images/applications/parks-paths/parks-paths-39.jpg",
      "/images/applications/parks-paths/parks-paths-40.jpg",
      "/images/applications/parks-paths/parks-paths-41.jpg",
      "/images/applications/parks-paths/parks-paths-42.jpg",
      "/images/applications/parks-paths/parks-paths-43.jpg",
      "/images/applications/parks-paths/parks-paths-44.jpg",
      "/images/applications/parks-paths/parks-paths-45.jpg",
      "/images/applications/parks-paths/parks-paths-46.jpg",
      "/images/applications/parks-paths/parks-paths-47.jpg",
      "/images/applications/parks-paths/parks-paths-48.jpg",
      "/images/applications/parks-paths/parks-paths-49.jpg",
      "/images/applications/parks-paths/parks-paths-50.jpg",
      "/images/applications/parks-paths/parks-paths-51.jpg",
      "/images/applications/parks-paths/parks-paths-52.jpg",
      "/images/applications/parks-paths/parks-paths-53.jpg",
      "/images/applications/parks-paths/parks-paths-54.jpg",
      "/images/applications/parks-paths/parks-paths-55.jpg",
      "/images/applications/parks-paths/parks-paths-56.jpg",
      "/images/applications/parks-paths/parks-paths-57.jpg",
      "/images/applications/parks-paths/parks-paths-58.jpg",
      "/images/applications/parks-paths/parks-paths-59.jpg",
      "/images/applications/parks-paths/parks-paths-60.jpg",
      "/images/applications/parks-paths/parks-paths-61.jpg",
      "/images/applications/parks-paths/parks-paths-62.jpg",
      "/images/applications/parks-paths/parks-paths-63.jpg",
      "/images/applications/parks-paths/parks-paths-64.jpg",
      "/images/applications/parks-paths/parks-paths-65.jpg",
      "/images/applications/parks-paths/parks-paths-66.jpg",
      "/images/applications/parks-paths/parks-paths-67.jpg",
      "/images/applications/parks-paths/parks-paths-68.jpg",
      "/images/applications/parks-paths/parks-paths-69.jpg",
      "/images/applications/parks-paths/parks-paths-70.jpg",
      "/images/applications/parks-paths/parks-paths-71.jpg",
      "/images/applications/parks-paths/parks-paths-72.jpg",
      "/images/applications/parks-paths/parks-paths-73.jpg",
      "/images/applications/parks-paths/parks-paths-74.jpg",
      "/images/applications/parks-paths/parks-paths-75.jpg",
      "/images/applications/parks-paths/parks-paths-76.jpg",
      "/images/applications/parks-paths/parks-paths-77.jpg",
      "/images/applications/parks-paths/parks-paths-78.jpg",
      "/images/applications/parks-paths/parks-paths-79.jpg",
      "/images/applications/parks-paths/parks-paths-80.jpg",
      "/images/applications/parks-paths/parks-paths-81.jpg",
      "/images/applications/parks-paths/parks-paths-82.jpg",
      "/images/applications/parks-paths/parks-paths-83.jpg",
      "/images/applications/parks-paths/parks-paths-84.jpg",
      "/images/applications/parks-paths/parks-paths-85.jpg",
      "/images/applications/parks-paths/parks-paths-86.jpg",
      "/images/applications/parks-paths/parks-paths-87.jpg",
      "/images/applications/parks-paths/parks-paths-88.jpg",
      "/images/applications/parks-paths/parks-paths-89.jpg",
      "/images/applications/parks-paths/parks-paths-90.jpg",
      "/images/applications/parks-paths/parks-paths-91.jpg",
      "/images/applications/parks-paths/parks-paths-92.jpg",
      "/images/applications/parks-paths/parks-paths-93.jpg",
      "/images/applications/parks-paths/parks-paths-94.jpg",
      "/images/applications/parks-paths/parks-paths-95.jpg",
      "/images/applications/parks-paths/parks-paths-96.png",
      "/images/applications/parks-paths/parks-paths-97.png",
      "/images/applications/parks-paths/parks-paths-98.png",
      "/images/applications/parks-paths/parks-paths-99.png",
    ],

    description: [
      "Parks and recreational trails are environments where surface aesthetics matter as much as durability. StreetBond colour coatings bring vibrancy to asphalt paths, plazas, and recreational courts while significantly extending surface life.",
      "DuraShield protective coatings act as a rejuvenating sealant for aging park infrastructure — penetrating the asphalt matrix to restore flexibility and slow oxidation.",
    ],
    relatedProducts: ["streetbond", "streetprint", "durashield"],
    benefits: [
      "StreetBond colour extends path life while improving aesthetics",
      "20-year UV-stable colour retention on treated surfaces",
      "DuraShield pavement rejuvenation defers resurfacing 3–5 years",
      "Custom wayfinding and trail marking graphics",
    ],
    col: "sm:col-span-2",
  },
  {
    name: "Bike Lanes",
    slug: "bike-lanes",
    shortDesc: "Protected bike lane surfaces and markings that improve cyclist safety and visibility.",
    imageUrl: "/images/applications/bike-lanes/bike-lanes-01.jpg",
    gallery: [
      "/images/applications/bike-lanes/bike-lanes-01.jpg",
      "/images/applications/bike-lanes/bike-lanes-02.jpg",
      "/images/applications/bike-lanes/bike-lanes-03.jpg",
      "/images/applications/bike-lanes/bike-lanes-04.jpg",
      "/images/applications/bike-lanes/bike-lanes-05.jpg",
      "/images/applications/bike-lanes/bike-lanes-06.jpg",
      "/images/applications/bike-lanes/bike-lanes-07.jpg",
      "/images/applications/bike-lanes/bike-lanes-08.jpg",
      "/images/applications/bike-lanes/bike-lanes-09.jpg",
      "/images/applications/bike-lanes/bike-lanes-10.jpg",
      "/images/applications/bike-lanes/bike-lanes-11.jpg",
      "/images/applications/bike-lanes/bike-lanes-12.jpg",
      "/images/applications/bike-lanes/bike-lanes-13.jpg",
      "/images/applications/bike-lanes/bike-lanes-14.jpg",
      "/images/applications/bike-lanes/bike-lanes-15.jpg",
      "/images/applications/bike-lanes/bike-lanes-16.jpg",
      "/images/applications/bike-lanes/bike-lanes-17.jpg",
      "/images/applications/bike-lanes/bike-lanes-18.jpg",
      "/images/applications/bike-lanes/bike-lanes-19.jpg",
      "/images/applications/bike-lanes/bike-lanes-20.jpg",
      "/images/applications/bike-lanes/bike-lanes-21.jpg",
      "/images/applications/bike-lanes/bike-lanes-22.jpg",
      "/images/applications/bike-lanes/bike-lanes-23.jpg",
      "/images/applications/bike-lanes/bike-lanes-24.jpg",
      "/images/applications/bike-lanes/bike-lanes-25.jpg",
      "/images/applications/bike-lanes/bike-lanes-26.jpg",
      "/images/applications/bike-lanes/bike-lanes-27.jpg",
      "/images/applications/bike-lanes/bike-lanes-28.jpg",
      "/images/applications/bike-lanes/bike-lanes-29.jpg",
      "/images/applications/bike-lanes/bike-lanes-30.jpg",
      "/images/applications/bike-lanes/bike-lanes-31.jpg",
      "/images/applications/bike-lanes/bike-lanes-32.png",
      "/images/applications/bike-lanes/bike-lanes-33.jpg",
      "/images/applications/bike-lanes/bike-lanes-34.jpg",
      "/images/applications/bike-lanes/bike-lanes-35.jpg",
      "/images/applications/bike-lanes/bike-lanes-36.jpg",
      "/images/applications/bike-lanes/bike-lanes-37.jpg",
      "/images/applications/bike-lanes/bike-lanes-38.jpg",
    ],

    description: [
      "Bike lane coatings are essential infrastructure for Complete Streets design. StreetBond provides the vivid green colour and UV stability that keeps cycling infrastructure visible and compelling for decades.",
      "MMAX methyl methacrylate resin delivers fast cure times for high-traffic cycling corridors — traffic-open in 60 minutes with exceptional bond strength and colour durability.",
    ],
    relatedProducts: ["mmax", "streetbond", "traffic-patterns", "premark"],
    benefits: [
      "StreetBond 20-year UV-stable colour retention",
      "MMAX traffic-open in 60 minutes — minimal disruption",
      "High-visibility green for conflict zone safety",
      "TAC and MUTCD compliant corridor markings",
    ],
    col: "",
  },
  {
    name: "Bus Lanes",
    slug: "bus-lanes",
    shortDesc: "High-durability coloured surface systems for bus rapid transit and dedicated bus lanes.",
    imageUrl: "/images/applications/bus-lanes/bus-lanes-01.jpg",
    gallery: [
      "/images/applications/bus-lanes/bus-lanes-01.jpg",
      "/images/applications/bus-lanes/bus-lanes-02.jpg",
      "/images/applications/bus-lanes/bus-lanes-03.jpg",
      "/images/applications/bus-lanes/bus-lanes-04.jpg",
      "/images/applications/bus-lanes/bus-lanes-05.jpg",
      "/images/applications/bus-lanes/bus-lanes-06.jpg",
      "/images/applications/bus-lanes/bus-lanes-07.jpg",
      "/images/applications/bus-lanes/bus-lanes-08.jpg",
      "/images/applications/bus-lanes/bus-lanes-09.jpg",
      "/images/applications/bus-lanes/bus-lanes-10.jpg",
      "/images/applications/bus-lanes/bus-lanes-11.jpg",
      "/images/applications/bus-lanes/bus-lanes-12.jpg",
      "/images/applications/bus-lanes/bus-lanes-13.jpg",
      "/images/applications/bus-lanes/bus-lanes-14.jpg",
      "/images/applications/bus-lanes/bus-lanes-15.jpg",
      "/images/applications/bus-lanes/bus-lanes-16.jpg",
      "/images/applications/bus-lanes/bus-lanes-17.jpg",
      "/images/applications/bus-lanes/bus-lanes-18.jpg",
      "/images/applications/bus-lanes/bus-lanes-19.jpg",
      "/images/applications/bus-lanes/bus-lanes-20.jpg",
      "/images/applications/bus-lanes/bus-lanes-21.jpg",
      "/images/applications/bus-lanes/bus-lanes-22.jpg",
      "/images/applications/bus-lanes/bus-lanes-23.jpg",
      "/images/applications/bus-lanes/bus-lanes-24.jpg",
      "/images/applications/bus-lanes/bus-lanes-25.jpg",
      "/images/applications/bus-lanes/bus-lanes-26.jpg",
      "/images/applications/bus-lanes/bus-lanes-27.jpg",
      "/images/applications/bus-lanes/bus-lanes-28.jpg",
      "/images/applications/bus-lanes/bus-lanes-29.jpg",
      "/images/applications/bus-lanes/bus-lanes-30.jpg",
      "/images/applications/bus-lanes/bus-lanes-31.jpg",
      "/images/applications/bus-lanes/bus-lanes-32.jpg",
      "/images/applications/bus-lanes/bus-lanes-33.jpg",
      "/images/applications/bus-lanes/bus-lanes-34.jpg",
      "/images/applications/bus-lanes/bus-lanes-35.jpg",
      "/images/applications/bus-lanes/bus-lanes-36.jpg",
      "/images/applications/bus-lanes/bus-lanes-37.png",
      "/images/applications/bus-lanes/bus-lanes-38.png",
      "/images/applications/bus-lanes/bus-lanes-39.png",
      "/images/applications/bus-lanes/bus-lanes-40.png",
    ],

    description: [
      "Bus lanes are high-stress transit corridors requiring surface systems that can endure daily bus wheel loads without delamination or colour fade. HUB's MMAX methyl methacrylate resin is the standard of care for BRT corridors.",
      "Red bus lane coatings provide unambiguous visual priority for transit vehicles while deterring unauthorized traffic.",
    ],
    relatedProducts: ["mmax", "traffic-patterns-xd", "streetbond"],
    benefits: [
      "MMAX traffic-open in 60 minutes — minimal disruption",
      "Exceptional bond strength — withstands bus wheel loads",
      "Fast-cure MMA application near freezing temperatures",
      "High-visibility red for transit priority",
    ],
    col: "",
  },
  {
    name: "Community Branding",
    slug: "community-branding",
    shortDesc: "Custom civic identity and placemaking graphics on roads, plazas, and public spaces.",
    imageUrl: "/images/applications/community-branding/community-branding-01.jpg",
    gallery: [
      "/images/applications/community-branding/community-branding-01.jpg",
      "/images/applications/community-branding/community-branding-02.jpg",
      "/images/applications/community-branding/community-branding-03.jpg",
      "/images/applications/community-branding/community-branding-04.jpg",
      "/images/applications/community-branding/community-branding-05.jpg",
      "/images/applications/community-branding/community-branding-06.jpg",
      "/images/applications/community-branding/community-branding-07.jpg",
      "/images/applications/community-branding/community-branding-08.jpg",
      "/images/applications/community-branding/community-branding-09.jpg",
      "/images/applications/community-branding/community-branding-10.jpg",
      "/images/applications/community-branding/community-branding-11.jpg",
      "/images/applications/community-branding/community-branding-12.jpg",
      "/images/applications/community-branding/community-branding-13.jpg",
      "/images/applications/community-branding/community-branding-14.jpg",
    ],

    description: [
      "A municipality's visual identity extends to its streets. Gateway intersections, BIA corridors, neighbourhood boundary markers, and civic plazas are all opportunities to reinforce place character and civic pride.",
      "StreetPrint stamped asphalt patterns create a tactile and visual distinction that signals entry into a special place — whether a heritage commercial district, a new transit village, or a waterfront promenade.",
    ],
    relatedProducts: ["decomark", "streetbond", "traffic-patterns", "streetprint"],
    benefits: [
      "Custom patterns coordinated with municipal brand standards",
      "Gateway and BIA corridor identity treatments",
      "DuraTherm snowplow-safe inlaid thermoplastic",
      "20-year colour retention — long-term civic investment",
    ],
    col: "",
  },
  {
    name: "Regulatory Markings",
    slug: "regulatory-markings",
    shortDesc: "MUTCD-compliant stop bars, arrows, legends, and regulatory road markings.",
    imageUrl: "/images/applications/regulatory-markings/regulatory-markings-1.jpg",
    gallery: [
      "/images/applications/regulatory-markings/regulatory-markings-1.jpg",
      "/images/applications/regulatory-markings/regulatory-markings-2.jpg",
      "/images/applications/regulatory-markings/regulatory-markings-3.jpg",
      "/images/applications/regulatory-markings/regulatory-markings-4.jpg",
      "/images/applications/regulatory-markings/regulatory-markings-5.jpg",
      "/images/applications/regulatory-markings/regulatory-markings-6.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-7.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-8.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-9.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-10.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-11.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-12.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-13.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-14.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-15.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-16.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-17.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-18.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-19.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-20.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-21.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-22.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-23.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-24.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-25.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-26.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-27.jpeg",
      "/images/applications/regulatory-markings/regulatory-markings-28.jpeg",
      "/images/applications/regulatory-markings/premark-arrows-intersection-01.jpg",
      "/images/applications/regulatory-markings/premark-turn-arrows-01.jpg",
    ],

    description: [
      "Regulatory road markings are safety-critical infrastructure that must meet TAC and MUTCD dimensional and reflectivity standards precisely. HUB's PreMark and TrafficPatterns preformed thermoplastic systems deliver factory-manufactured precision that ensures compliance while dramatically outlasting traditional painted markings.",
      "Stop bars, turn arrows, lane legends, and directional symbols are produced to exact specifications with integrated glass beads for ASTM Type III and IV retroreflectivity.",
    ],
    relatedProducts: ["premark", "traffic-patterns", "duratherm"],
    benefits: [
      "TAC and MUTCD dimensional compliance",
      "ASTM Type III and IV retroreflectivity",
      "5–10x longer service life than paint",
      "Factory precision — no spray drift or overspray",
    ],
    col: "",
  },
  {
    name: "Traffic Calming",
    slug: "traffic-calming",
    shortDesc: "Surface treatments that reduce vehicle speeds through visual contrast, pattern complexity, and the psychology of place — without physical infrastructure.",
    imageUrl: "/images/applications/traffic-calming/traffic-calming-01.jpg",
    gallery: [
      "/images/applications/traffic-calming/traffic-calming-01.jpg",
      "/images/applications/traffic-calming/traffic-calming-02.jpg",
      "/images/applications/traffic-calming/traffic-calming-03.jpg",
      "/images/applications/traffic-calming/traffic-calming-04.jpg",
      "/images/applications/traffic-calming/traffic-calming-05.jpg",
      "/images/applications/traffic-calming/traffic-calming-06.jpg",
      "/images/applications/traffic-calming/traffic-calming-07.jpg",
      "/images/applications/traffic-calming/traffic-calming-08.jpg",
      "/images/applications/traffic-calming/traffic-calming-09.jpg",
      "/images/applications/traffic-calming/traffic-calming-10.jpg",
      "/images/applications/traffic-calming/traffic-calming-11.jpg",
      "/images/applications/traffic-calming/traffic-calming-12.jpg",
      "/images/applications/traffic-calming/traffic-calming-13.jpg",
      "/images/applications/traffic-calming/traffic-calming-14.jpg",
      "/images/applications/traffic-calming/traffic-calming-15.jpg",
      "/images/applications/traffic-calming/traffic-calming-16.jpg",
      "/images/applications/traffic-calming/traffic-calming-17.jpg",
      "/images/applications/traffic-calming/traffic-calming-18.jpg",
      "/images/applications/traffic-calming/traffic-calming-19.jpg",
      "/images/applications/traffic-calming/traffic-calming-20.jpg",
      "/images/applications/traffic-calming/traffic-calming-21.jpg",
      "/images/applications/traffic-calming/traffic-calming-22.jpg",
      "/images/applications/traffic-calming/traffic-calming-23.jpg",
      "/images/applications/traffic-calming/traffic-calming-24.jpg",
      "/images/applications/traffic-calming/traffic-calming-25.jpg",
      "/images/applications/traffic-calming/traffic-calming-26.jpg",
      "/images/applications/traffic-calming/traffic-calming-27.jpg",
      "/images/applications/traffic-calming/traffic-calming-28.jpg",
      "/images/applications/traffic-calming/traffic-calming-29.jpg",
      "/images/applications/traffic-calming/traffic-calming-30.jpg",
      "/images/applications/traffic-calming/traffic-calming-31.jpg",
      "/images/applications/traffic-calming/traffic-calming-32.jpg",
      "/images/applications/traffic-calming/traffic-calming-33.jpg",
      "/images/applications/traffic-calming/traffic-calming-34.jpg",
      "/images/applications/traffic-calming/traffic-calming-35.jpg",
      "/images/applications/traffic-calming/traffic-calming-36.jpg",
      "/images/applications/traffic-calming/traffic-calming-37.jpg",
      "/images/applications/traffic-calming/traffic-calming-38.jpg",
      "/images/applications/traffic-calming/traffic-calming-39.jpg",
      "/images/applications/traffic-calming/traffic-calming-40.jpg",
      "/images/applications/traffic-calming/traffic-calming-41.jpg",
      "/images/applications/traffic-calming/traffic-calming-42.jpg",
      "/images/applications/traffic-calming/traffic-calming-43.png",
      "/images/applications/traffic-calming/traffic-calming-44.jpg",
      "/images/applications/traffic-calming/traffic-calming-45.jpg",
      "/images/applications/traffic-calming/traffic-calming-46.jpg",
      "/images/applications/traffic-calming/traffic-calming-47.jpg",
      "/images/applications/traffic-calming/traffic-calming-48.jpg",
      "/images/applications/traffic-calming/traffic-calming-49.jpg",
      "/images/applications/traffic-calming/traffic-calming-50.jpg",
      "/images/applications/traffic-calming/traffic-calming-51.jpg",
      "/images/applications/traffic-calming/traffic-calming-52.jpg",
      "/images/applications/traffic-calming/traffic-calming-53.jpg",
      "/images/applications/traffic-calming/traffic-calming-54.jpg",
      "/images/applications/traffic-calming/traffic-calming-55.jpg",
      "/images/applications/traffic-calming/traffic-calming-56.jpg",
    ],

    description: [
      "Traffic calming through surface design is one of the most cost-effective tools available to municipalities pursuing Vision Zero and Complete Streets. Unlike speed cushions or raised tables, surface treatments achieve speed reduction through visual psychology — no civil works, no drainage modifications, no snowplow conflicts.",
      "StreetPrint stamped asphalt intersections replicate the visual character of a brick or cobblestone plaza, communicating shared-space priority to drivers before they reach the crossing. TrafficPatternsXD pattern overlays extend this effect along full corridors with the added benefit of proven retroreflective performance.",
      "All HUB traffic calming systems maintain full AODA compliance and snowplow compatibility — non-negotiable requirements for Canadian municipal approval. Lane closure is minimal; traffic is typically restored within hours of installation.",
    ],
    relatedProducts: ["traffic-patterns-xd", "traffic-patterns", "streetprint", "streetbond"],
    benefits: [
      "Visual speed cues that reduce vehicle speeds without humps",
      "Flush-surface installation — snowplow and maintenance safe",
      "AODA compliant — zero elevation change",
      "School zone and gateway treatment specialists",
      "Supports active transportation and Vision Zero goals",
      "Traffic-open within hours of installation",
    ],
    col: "",
  },
  {
    name: "Airports",
    slug: "airports",
    shortDesc: "FAA and Transport Canada compliant airfield surface markings and runway coatings.",
    imageUrl: "/images/applications/airports/airports-01.jpg",
    gallery: [
      "/images/applications/airports/airports-01.jpg",
      "/images/applications/airports/airports-02.jpg",
      "/images/applications/airports/airports-03.jpg",
      "/images/applications/airports/airports-04.jpg",
      "/images/applications/airports/airports-05.jpg",
      "/images/applications/airports/airports-06.jpg",
      "/images/applications/airports/airports-07.jpg",
      "/images/applications/airports/airports-08.jpg",
      "/images/applications/airports/airports-09.jpg",
      "/images/applications/airports/airports-10.jpg",
      "/images/applications/airports/airports-11.jpg",
      "/images/applications/airports/airports-12.jpg",
      "/images/applications/airports/airports-13.jpg",
      "/images/applications/airports/airports-14.jpg",
      "/images/applications/airports/airports-15.jpg",
      "/images/applications/airports/airports-16.jpg",
      "/images/applications/airports/airports-17.jpg",
      "/images/applications/airports/airports-18.jpg",
      "/images/applications/airports/airports-19.jpg",
      "/images/applications/airports/airports-20.png",
      "/images/applications/airports/airports-21.jpg",
      "/images/applications/airports/airports-22.jpg",
      "/images/applications/airports/airports-23.jpg",
      "/images/applications/airports/airports-24.jpg",
      "/images/applications/airports/airports-25.jpg",
      "/images/applications/airports/airports-26.jpg",
      "/images/applications/airports/airports-27.jpg",
      "/images/applications/airports/airports-28.jpg",
    ],

    description: [
      "Airfield markings are safety-critical infrastructure with zero tolerance for ambiguity. Runway thresholds, holding position markings, taxiway centrelines, and apron designations must meet FAA Advisory Circular and Transport Canada standards precisely, every time.",
      "AirMark preformed thermoplastic is engineered specifically for this environment: permanent bond to asphalt and concrete, exceptional Type IV retroreflectivity for low-visibility operations.",
    ],
    relatedProducts: ["airmark", "premark", "mmax"],
    benefits: [
      "FAA AC 150/5370-10 and TC Canada compliant",
      "ASTM D4956 Type IV retroreflectivity",
      "Permanent bond — resists jet blast and fuel exposure",
      "Same-day application on fresh asphalt paving",
    ],
    col: "",
  },
  {
    name: "Public Art",
    slug: "public-art",
    shortDesc: "Large-scale pavement murals, cultural installations, and civic identity graphics on public surfaces.",
    imageUrl: "/images/applications/public-art/public-art-1.jpg",
    gallery: [
      "/images/applications/public-art/public-art-1.jpg",
      "/images/applications/public-art/public-art-2.jpg",
      "/images/applications/public-art/public-art-3.jpg",
      "/images/applications/public-art/public-art-4.jpg",
      "/images/applications/public-art/public-art-5.jpg",
      "/images/applications/public-art/public-art-6.jpg",
      "/images/applications/public-art/public-art-7.jpg",
      "/images/applications/public-art/public-art-8.jpg",
      "/images/applications/public-art/public-art-9.jpg",
      "/images/applications/public-art/public-art-10.jpeg",
      "/images/applications/public-art/public-art-11.jpg",
      "/images/applications/public-art/public-art-12.jpg",
      "/images/applications/public-art/public-art-13.jpg",
      "/images/applications/public-art/public-art-14.jpg",
      "/images/applications/public-art/public-art-15.jpg",
      "/images/applications/public-art/public-art-16.png",
      "/images/applications/public-art/public-art-17.jpg",
      "/images/applications/public-art/public-art-18.jpg",
      "/images/applications/public-art/public-art-19.jpg",
      "/images/applications/public-art/public-art-20.jpg",
      "/images/applications/public-art/public-art-21.jpg",
      "/images/applications/public-art/public-art-22.jpg",
    ],

    description: [
      "The street is a canvas. StreetBond's full-colour coating system makes large-scale pavement murals, Indigenous art installations, and civic identity graphics a reality on any asphalt or concrete surface.",
      "From tennis club logos to compass roses to pride crosswalks and Indigenous cultural markers, HUB's systems deliver the colour fidelity and UV stability to keep these installations vibrant for decades.",
    ],
    relatedProducts: ["streetbond", "decomark", "streetprint"],
    benefits: [
      "Full custom colour — any Pantone, any design",
      "20-year UV-stable colour retention",
      "Applicable on asphalt and concrete",
      "Used for Indigenous art, pride crosswalks, civic identity",
    ],
    col: "",
  },
  {
    name: "Residential Driveways",
    slug: "residential-driveways",
    shortDesc: "Stamped asphalt patterns that look like stone, brick, or custom designs — engineered to last 20+ years without the maintenance of real pavers.",
    imageUrl: "/images/applications/residential-driveways/residential-driveways-01.jpg",
    gallery: [
      "/images/applications/residential-driveways/residential-driveways-01.jpg",
      "/images/applications/residential-driveways/residential-driveways-02.jpg",
      "/images/applications/residential-driveways/residential-driveways-03.jpg",
      "/images/applications/residential-driveways/residential-driveways-04.jpg",
      "/images/applications/residential-driveways/residential-driveways-05.jpg",
      "/images/applications/residential-driveways/residential-driveways-06.jpg",
      "/images/applications/residential-driveways/residential-driveways-07.jpg",
      "/images/applications/residential-driveways/residential-driveways-08.jpg",
      "/images/applications/residential-driveways/residential-driveways-09.jpg",
      "/images/applications/residential-driveways/residential-driveways-10.jpg",
      "/images/applications/residential-driveways/residential-driveways-11.jpg",
      "/images/applications/residential-driveways/residential-driveways-12.jpg",
      "/images/applications/residential-driveways/residential-driveways-13.jpg",
      "/images/applications/residential-driveways/residential-driveways-14.jpg",
      "/images/applications/residential-driveways/residential-driveways-15.jpg",
      "/images/applications/residential-driveways/residential-driveways-16.jpg",
      "/images/applications/residential-driveways/residential-driveways-17.jpg",
      "/images/applications/residential-driveways/residential-driveways-18.jpg",
      "/images/applications/residential-driveways/residential-driveways-19.jpg",
      "/images/applications/residential-driveways/residential-driveways-20.jpg",
      "/images/applications/residential-driveways/residential-driveways-21.jpg",
      "/images/applications/residential-driveways/residential-driveways-22.jpg",
      "/images/applications/residential-driveways/residential-driveways-23.jpg",
      "/images/applications/residential-driveways/residential-driveways-24.jpg",
      "/images/applications/residential-driveways/residential-driveways-25.jpg",
      "/images/applications/residential-driveways/residential-driveways-26.jpg",
      "/images/applications/residential-driveways/residential-driveways-27.jpg",
      "/images/applications/residential-driveways/residential-driveways-28.jpg",
      "/images/applications/residential-driveways/residential-driveways-29.jpg",
      "/images/applications/residential-driveways/residential-driveways-30.jpg",
      "/images/applications/residential-driveways/residential-driveways-31.jpg",
      "/images/applications/residential-driveways/residential-driveways-32.jpg",
      "/images/applications/residential-driveways/residential-driveways-33.jpg",
      "/images/applications/residential-driveways/residential-driveways-34.jpg",
      "/images/applications/residential-driveways/residential-driveways-35.jpg",
      "/images/applications/residential-driveways/residential-driveways-36.jpg",
      "/images/applications/residential-driveways/residential-driveways-37.jpg",
      "/images/applications/residential-driveways/residential-driveways-38.jpg",
      "/images/applications/residential-driveways/residential-driveways-39.jpg",
      "/images/applications/residential-driveways/residential-driveways-40.jpg",
      "/images/applications/residential-driveways/residential-driveways-41.jpg",
      "/images/applications/residential-driveways/residential-driveways-42.jpg",
      "/images/applications/residential-driveways/residential-driveways-43.jpg",
      "/images/applications/residential-driveways/residential-driveways-44.jpg",
    ],
    description: [
      "Your driveway is the first thing people see. StreetPrint's in-place stamping process transforms existing or new asphalt into stone, brick, cobblestone, herringbone, or custom patterns — without tearing out the slab, without years of weeding joint gaps, and without the sticker shock of real unit pavers. The same system used on city plazas and heritage streetscapes comes to your property.",
      "The process is straightforward: fresh asphalt is laid and immediately stamped with heated steel templates while still workable, locking in texture and dimension before the surface cures. StreetBond colour coating is then applied over the stamped surface, delivering UV-stable pigment that maintains colour fidelity through 20+ Canadian winters. DuraShield protective topcoat seals the finished surface against water infiltration, freeze-thaw damage, and oil staining — extending the service life to 20+ years with only periodic resealing.",
      "Compared to interlocking stone, stamped asphalt installs in one to two days with no base excavation, no joint sand settling, and no individual pavers shifting or sinking over time. There are no weeds. No edge restraint failures. No pressure washing every spring. Just a surface that holds its character and its colour — and adds genuine curb appeal without the interlocking stone lifecycle headaches.",
    ],
    relatedProducts: ["streetprint", "streetbond", "durashield"],
    benefits: [
      "Municipal-grade materials — same systems on city streets",
      "20+ year lifespan with periodic DuraShield resealing",
      "12+ stamp patterns — brick, herringbone, cobble, slate, custom",
      "Installed in 1–2 days — no excavation, no weeks of disruption",
      "No joint maintenance — zero weeds, no sand topping, no shifting",
      "AODA-compliant slip resistance on all finished surfaces",
    ],
    relatedPost: {
      slug: "residential-driveways-stamped-asphalt",
      title: "Why Stamped Asphalt Driveways Outperform Interlocking Stone",
      excerpt: "Interlocking stone looks great on day one. Five years in, the weeds are growing through the joints. Here's the honest comparison.",
    },
    col: "",
  },
  {
    name: "Townhomes",
    slug: "townhomes",
    shortDesc: "Decorative shared driveways, pathways, and common areas for townhome developments.",
    imageUrl: "/images/applications/townhomes/townhomes-01.jpg",
    gallery: [
      "/images/applications/townhomes/townhomes-01.jpg",
      "/images/applications/townhomes/townhomes-02.jpg",
      "/images/applications/townhomes/townhomes-03.jpg",
      "/images/applications/townhomes/townhomes-04.png",
      "/images/applications/townhomes/townhomes-05.png",
      "/images/applications/townhomes/townhomes-06.png",
      "/images/applications/townhomes/townhomes-07.jpg",
      "/images/applications/townhomes/townhomes-08.jpg",
      "/images/applications/townhomes/townhomes-09.jpg",
      "/images/applications/townhomes/townhomes-10.jpg",
      "/images/applications/townhomes/townhomes-11.jpg",
      "/images/applications/townhomes/townhomes-12.jpg",
      "/images/applications/townhomes/townhomes-13.jpg",
      "/images/applications/townhomes/townhomes-14.jpg",
      "/images/applications/townhomes/townhomes-15.jpg",
      "/images/applications/townhomes/townhomes-16.jpg",
      "/images/applications/townhomes/townhomes-17.jpg",
      "/images/applications/townhomes/townhomes-18.png",
    ],

    description: [
      "Townhome developments demand surface treatments that balance aesthetic appeal with lifecycle durability across shared driveways, pathways, and common areas. StreetPrint stamped asphalt delivers the look of premium unit pavers — brick, cobblestone, or slate patterns — without the maintenance complexity.",
      "StreetBond colour coatings provide vivid, UV-stable finishes for wayfinding, zone delineation, and decorative accents throughout the development.",
    ],
    relatedProducts: ["streetprint", "streetbond", "traffic-patterns-xd", "durashield"],
    benefits: [
      "Premium paver aesthetic without joint maintenance",
      "20-year colour retention on StreetPrint treatments",
      "Shared driveway and common area specialists",
      "Enhances property value and curb appeal",
    ],
    col: "",
  },
  {
    name: "Pedestrian Safety",
    slug: "pedestrian-safety",
    shortDesc: "High-visibility surfaces and markings engineered to protect pedestrians at intersections, school zones, and mid-block crossings.",
    imageUrl: "/images/applications/crosswalks/crosswalk-1.jpg",
    description: [
      "Pedestrian fatalities at intersections remain one of the most preventable infrastructure failures in Canadian cities. HUB Surface Systems provides the full spectrum of surface-based pedestrian safety interventions — from high-contrast ladder crosswalks and school zone markings to accessible pedestrian pathways that meet AODA and provincial accessibility standards.",
      "Vision Zero municipalities specify TrafficPatternsXD for their highest-priority corridors. The 150mil aggregate-reinforced formula delivers BPN 65+ skid resistance and retroreflectivity that exceeds TAC requirements for 7+ years — performing in wet conditions, at night, and under snowplow operations without edge loss.",
      "Coloured StreetBond intersection treatments create a visual contract between motorists and pedestrians. Studies from York Region and the City of Vancouver document measurable reductions in operating speeds at decorated intersections versus standard crosswalk markings.",
    ],
    relatedProducts: ["traffic-patterns-xd", "traffic-patterns", "streetbond", "decomark", "premark"],
    benefits: [
      "BPN 65+ skid resistance — wet surface performance",
      "TAC-compliant retroreflectivity for 7+ years",
      "AODA compliant accessible pedestrian markings",
      "Snowplow-safe — no edge loss under mechanical operations",
      "Measurable speed reductions at coloured intersection treatments",
      "Vision Zero and Complete Streets specification support",
    ],
    col: "",
  },
  {
    name: "LEED - Urban Heat Island",
    slug: "leed-urban-heat-island",
    shortDesc: "Light-reflective surface systems that reduce urban heat island effect for LEED certification.",
    imageUrl: "/images/applications/leed-urban-heat-island/leed-urban-heat-island-01.jpg",
    gallery: [
      "/images/applications/leed-urban-heat-island/leed-urban-heat-island-01.jpg",
      "/images/applications/leed-urban-heat-island/leed-urban-heat-island-02.jpg",
    ],
    description: [
      "Urban heat islands form where dark asphalt and concrete absorb and re-radiate solar energy — raising ambient temperatures by 3–5°C above surrounding areas. StreetBond SR (Solar Reflective) is HUB's answer: a surface coating engineered to reflect solar radiation rather than absorb it, reducing pavement surface temperatures by up to 20°C.",
      "StreetBond SR contributes directly to LEED v4 Site Credit: Heat Island Reduction — providing the Solar Reflectance Index (SRI) documentation required for project certification.",
    ],
    relatedProducts: ["streetbond", "durashield"],
    benefits: [
      "StreetBond SR reduces pavement surface temp by up to 20°C",
      "Contributes to LEED v4 Heat Island Reduction credit",
      "SRI documentation provided for LEED submissions",
      "Applicable to new and existing asphalt surfaces",
    ],
    col: "sm:col-span-2",
  },,
  {
    name: "Sport Courts",
    slug: "sport-courts",
    shortDesc: "Coloured acrylic court markings and surface systems for basketball, tennis, pickleball, and multi-use sport courts.",
    imageUrl: "/images/applications/sport-courts/sport-courts-01.jpg",
    gallery: [
      "/images/applications/sport-courts/sport-courts-01.jpg",
      "/images/applications/sport-courts/sport-courts-02.jpg",
      "/images/applications/sport-courts/sport-courts-03.jpg",
      "/images/applications/sport-courts/sport-courts-04.jpg",
      "/images/applications/sport-courts/sport-courts-05.jpg",
      "/images/applications/sport-courts/sport-courts-06.jpg",
      "/images/applications/sport-courts/sport-courts-07.jpg",
      "/images/applications/sport-courts/sport-courts-08.jpg",
      "/images/applications/sport-courts/sport-courts-09.jpg",
      "/images/applications/sport-courts/sport-courts-10.jpg",
      "/images/applications/sport-courts/sport-courts-11.jpg",
      "/images/applications/sport-courts/sport-courts-12.jpg",
      "/images/applications/sport-courts/sport-courts-13.jpg",
      "/images/applications/sport-courts/sport-courts-14.jpg",
      "/images/applications/sport-courts/sport-courts-15.jpg",
      "/images/applications/sport-courts/sport-courts-16.jpg",
      "/images/applications/sport-courts/sport-courts-17.jpg",
      "/images/applications/sport-courts/sport-courts-18.jpg",
      "/images/applications/sport-courts/sport-courts-19.png",
      "/images/applications/sport-courts/sport-courts-20.jpg",
      "/images/applications/sport-courts/sport-courts-21.jpg",
    ],
    description: [
      "Sport courts demand surfaces that define space, guide play, and hold up under constant foot traffic and UV exposure — StreetBond's acrylic court coating system delivers all three. Fully customizable in colour and line configuration, it's the preferred system for municipal parks departments, residential strata, and commercial recreation facilities.",
      "From basketball and tennis to pickleball and multi-use recreational courts, HUB Sport Court systems provide professional-grade court markings with 20-year colour retention and slip-resistant texture.",
    ],
    relatedProducts: ["streetbond", "premark", "decomark"],
    benefits: [
      "20-year colour retention warranty",
      "Custom court layouts and multi-use configurations",
      "Slip-resistant surface texture built in",
      "Applied to existing asphalt or concrete",
    ],
  },
  {
    name: "Public Spaces",
    slug: "public-spaces",
    shortDesc: "Decorative pavement systems for plazas, promenades, waterfronts, and civic gathering spaces.",
    imageUrl: "/images/applications/public-spaces/public-spaces-01.jpg",
    gallery: [
      "/images/applications/public-spaces/public-spaces-01.jpg",
      "/images/applications/public-spaces/public-spaces-02.jpg",
      "/images/applications/public-spaces/public-spaces-03.jpg",
      "/images/applications/public-spaces/public-spaces-04.jpg",
      "/images/applications/public-spaces/public-spaces-05.jpg",
      "/images/applications/public-spaces/public-spaces-06.jpg",
      "/images/applications/public-spaces/public-spaces-07.jpg",
      "/images/applications/public-spaces/public-spaces-08.jpg",
      "/images/applications/public-spaces/public-spaces-09.png",
      "/images/applications/public-spaces/public-spaces-10.png",
      "/images/applications/public-spaces/public-spaces-11.png",
      "/images/applications/public-spaces/public-spaces-12.png",
      "/images/applications/public-spaces/public-spaces-13.png",
      "/images/applications/public-spaces/public-spaces-14.png",
      "/images/applications/public-spaces/public-spaces-15.png",
      "/images/applications/public-spaces/public-spaces-16.png",
      "/images/applications/public-spaces/public-spaces-17.png",
      "/images/applications/public-spaces/public-spaces-18.png",
      "/images/applications/public-spaces/public-spaces-19.png",
      "/images/applications/public-spaces/public-spaces-20.png",
      "/images/applications/public-spaces/public-spaces-21.png",
      "/images/applications/public-spaces/public-spaces-22.png",
      "/images/applications/public-spaces/public-spaces-23.png",
      "/images/applications/public-spaces/public-spaces-24.png",
      "/images/applications/public-spaces/public-spaces-25.png",
      "/images/applications/public-spaces/public-spaces-26.png",
      "/images/applications/public-spaces/public-spaces-27.png",
      "/images/applications/public-spaces/public-spaces-28.png",
      "/images/applications/public-spaces/public-spaces-29.png",
      "/images/applications/public-spaces/public-spaces-30.png",
      "/images/applications/public-spaces/public-spaces-31.png",
      "/images/applications/public-spaces/public-spaces-32.png",
      "/images/applications/public-spaces/public-spaces-33.png",
      "/images/applications/public-spaces/public-spaces-34.png",
      "/images/applications/public-spaces/public-spaces-35.png",
      "/images/applications/public-spaces/public-spaces-36.png",
      "/images/applications/public-spaces/public-spaces-37.png",
      "/images/applications/public-spaces/public-spaces-38.png",
      "/images/applications/public-spaces/public-spaces-39.jpg",
      "/images/applications/public-spaces/public-spaces-40.jpg",
      "/images/applications/public-spaces/public-spaces-41.jpg",
      "/images/applications/public-spaces/public-spaces-42.jpg",
      "/images/applications/public-spaces/public-spaces-43.jpg",
      "/images/applications/public-spaces/public-spaces-44.jpg",
      "/images/applications/public-spaces/public-spaces-45.jpg",
      "/images/applications/public-spaces/public-spaces-46.jpg",
      "/images/applications/public-spaces/public-spaces-47.jpg",
      "/images/applications/public-spaces/public-spaces-48.jpg",
      "/images/applications/public-spaces/public-spaces-49.jpg",
      "/images/applications/public-spaces/public-spaces-50.jpg",
      "/images/applications/public-spaces/public-spaces-51.jpg",
      "/images/applications/public-spaces/public-spaces-52.jpg",
      "/images/applications/public-spaces/public-spaces-53.jpg",
      "/images/applications/public-spaces/public-spaces-54.jpg",
      "/images/applications/public-spaces/public-spaces-55.jpg",
      "/images/applications/public-spaces/public-spaces-56.png",
      "/images/applications/public-spaces/public-spaces-57.jpg",
      "/images/applications/public-spaces/public-spaces-58.jpg",
      "/images/applications/public-spaces/public-spaces-59.jpg",
      "/images/applications/public-spaces/public-spaces-60.jpg",
      "/images/applications/public-spaces/public-spaces-61.jpg",
      "/images/applications/public-spaces/public-spaces-62.jpg",
      "/images/applications/public-spaces/public-spaces-63.jpg",
      "/images/applications/public-spaces/public-spaces-64.jpg",
      "/images/applications/public-spaces/public-spaces-65.jpg",
      "/images/applications/public-spaces/public-spaces-66.jpg",
      "/images/applications/public-spaces/public-spaces-67.jpg",
    ],
    description: [
      "Public plazas and civic promenades are high-profile spaces where surface design communicates civic values — and where quality must last decades. StreetPrint stamped asphalt and StreetBond colour treatments bring architectural character to concrete and asphalt plazas, integrating seamlessly with adjacent hardscape.",
      "From waterfront boardwalk connections to downtown pedestrian zones and civic square entries, HUB Public Space systems deliver durable, low-maintenance surfaces that strengthen community identity.",
    ],
    relatedProducts: ["streetprint", "streetbond", "decomark"],
    benefits: [
      "Architectural finish on asphalt or concrete substrates",
      "20-year colour and pattern retention",
      "Custom colours and patterns for civic identity",
      "Snowplow-safe flush-mount finish",
    ],
  },
];