export interface ImageConfig {
  featured: string | null;
  fallback: string;
  alt: string;
}

export function resolveImage(config: ImageConfig): { src: string; alt: string } {
  return { src: config.featured ?? config.fallback, alt: config.alt };
}

export const heroImages = {
  homepage: { featured: '/images/hero/hero-1.jpg', fallback: '/images/hero/hero-2.jpg', alt: 'Decorative stamped asphalt crosswalk installed by HUB Surface Systems for a Canadian municipality' } as ImageConfig,
  about: { featured: '/images/hero/hero-3.jpg', fallback: '/images/hero/hero-bg.jpg', alt: 'HUB Surface Systems team — 30 years of decorative and functional pavement solutions across Canada' } as ImageConfig,
};

export const productImages: Record<string, ImageConfig> = {
  'traffic-patterns':    { featured: '/images/products/traffic-patterns/traffic-patterns-08.jpg',       fallback: '/images/products/traffic-patterns/traffic-patterns-01.jpg',       alt: 'TrafficPatterns preformed thermoplastic crosswalk at UBC — Musqueam Nation Indigenous art installation on University of British Columbia campus' },
  'traffic-patterns-xd': { featured: '/images/products/traffic-patterns-xd/traffic-patterns-xd-03.jpg', fallback: '/images/products/traffic-patterns-xd/traffic-patterns-xd-01.jpg', alt: 'TrafficPatternsXD aggregate-reinforced preformed thermoplastic crosswalk — premium durability decorative pavement marking for high-traffic Canadian intersections' },
  'streetprint':         { featured: '/images/products/streetprint/streetprint-40.jpg',                 fallback: '/images/products/streetprint/streetprint-01.jpg',                 alt: 'StreetPrint stamped asphalt decorative driveway — estate herringbone pattern with circular medallion, installed by HUB Surface Systems' },
  'streetbond':          { featured: '/images/products/streetbond/streetbond-112.jpg',                  fallback: '/images/products/streetbond/streetbond-20.jpg',                   alt: 'StreetBond coloured acrylic pavement coating — vibrant bike lane and pedestrian crossing surface treatment on Canadian urban road' },
  'mmax':                { featured: '/images/products/mmax/mmax-05.jpg',                               fallback: '/images/products/mmax/mmax-01.jpg',                               alt: 'MMAX red bus lane — transit bus on MMA methyl methacrylate rapid-cure coloured bus lane pavement on Canadian transit corridor' },
  'decomark':            { featured: '/images/products/decomark/decomark-01.jpg',                       fallback: '/images/products/decomark/decomark-01.jpg',                       alt: 'DecoMark custom preformed thermoplastic surface graphics — placemaking civic art installation on Canadian public plaza pavement' },
  'duratherm':           { featured: '/images/products/duratherm/duratherm-01.jpg',                     fallback: '/images/products/duratherm/duratherm-01.jpg',                     alt: 'DuraTherm inlaid flush-mount thermoplastic crosswalk — snowplow-safe decorative pavement marking embedded in asphalt surface' },
  'premark':             { featured: '/images/products/premark/premark-01.jpg',                         fallback: '/images/products/premark/premark-01.jpg',                         alt: 'PreMark preformed thermoplastic road marking symbols — turn arrows, stop bars, and regulatory pavement markings for Canadian municipalities' },
  'airmark':             { featured: '/images/products/airmark/airmark-01.jpg',                         fallback: '/images/products/airmark/airmark-01.jpg',                         alt: 'AirMark preformed thermoplastic airfield markings — runway threshold, taxiway guidance, and apron surface markings' },
  'durashield':          { featured: '/images/products/durashield/durashield-01.jpg',                   fallback: '/images/products/durashield/durashield-01.jpg',                   alt: 'DuraShield penetrating asphalt rejuvenator and protective seal coat — pavement life extension treatment for Canadian municipal road surfaces' },
  'streetbondsr':        { featured: '/images/products/streetbondsr/streetbondsr-02.jpg',               fallback: '/images/products/streetbondsr/streetbondsr-01.png',               alt: 'StreetBondSR solar reflective acrylic pavement coating — parking area installation showing cool surface treatment for urban heat island mitigation' },
};

export const applicationImages: Record<string, ImageConfig> = {
  'crosswalks':            { featured: '/images/applications/crosswalks/crosswalks-03.jpg',                       fallback: '/images/applications/crosswalks/crosswalks-01.jpg',                       alt: 'High-visibility decorative crosswalk with TrafficPatternsXD preformed thermoplastic — pedestrian safety surface for Vision Zero Canadian streetscape' },
  'bike-lanes':            { featured: '/images/applications/bike-lanes/bike-lanes-14.jpg',                       fallback: '/images/applications/bike-lanes/bike-lanes-06.jpg',                       alt: 'Vivid green protected bike lane — StreetBond coloured cycling infrastructure for Complete Streets Canadian municipality' },
  'bus-lanes':             { featured: '/images/applications/bus-lanes/bus-lanes-20.jpg',                         fallback: '/images/applications/bus-lanes/bus-lanes-15.jpg',                         alt: 'Red MMAX bus rapid transit lane with transit bus — high-durability BRT surface marking for Canadian transit corridor' },
  'commercial-spaces':     { featured: '/images/applications/commercial-spaces/commercial-spaces-01.jpg',         fallback: '/images/applications/commercial-spaces/commercial-spaces-01.jpg',         alt: 'Commercial plaza decorative pavement — StreetPrint stamped asphalt retail entry and pedestrian streetscape surface' },
  'community-branding':    { featured: '/images/applications/community-branding/community-branding-08.jpg',       fallback: '/images/applications/community-branding/community-branding-05.jpg',       alt: 'UBC community identity crosswalk — custom civic graphics and DecoMark placemaking thermoplastic art on Canadian public street' },
  'parking-lots':          { featured: '/images/applications/parking-lots/parking-lots-01.jpg',                   fallback: '/images/applications/parking-lots/parking-lots-01.jpg',                   alt: 'Parking lot decorative surface system — PreMark thermoplastic stall markings and DuraShield asphalt protective coating' },
  'parks-paths':           { featured: '/images/applications/parks-paths/parks-paths-01.jpg',                     fallback: '/images/applications/parks-paths/parks-paths-01.jpg',                     alt: 'Park pathway coloured surface treatment — StreetBond slip-resistant recreational trail marking for Canadian municipal greenway' },
  'playgrounds':           { featured: '/images/applications/playgrounds/playgrounds-01.jpg',                     fallback: '/images/applications/playgrounds/playgrounds-01.jpg',                     alt: 'School playground surface markings — DecoMark custom preformed thermoplastic graphics and activity zones for children' },
  'private-driveways':     { featured: '/images/applications/residential-driveways/residential-driveways-01.jpg', fallback: '/images/applications/residential-driveways/residential-driveways-01.jpg', alt: 'Private driveway stamped asphalt — StreetPrint decorative brick pattern residential surface for Canadian home' },
  'residential-driveways': { featured: '/images/applications/residential-driveways/residential-driveways-03.jpg', fallback: '/images/applications/residential-driveways/residential-driveways-03.jpg', alt: 'Residential stamped asphalt driveway — aerial view of StreetPrint circular cobblestone pattern installed at Canadian home with attached garage' },
  'regulatory-markings':   { featured: '/images/applications/crosswalks/crosswalks-01.jpg',                       fallback: '/images/applications/crosswalks/crosswalks-01.jpg',                       alt: 'Regulatory road markings — PreMark preformed thermoplastic directional arrows, stop bars, and yield markings for Canadian municipalities' },
  'splash-pads':           { featured: '/images/applications/splash-pads/splash-pads-01.jpg',                     fallback: '/images/applications/splash-pads/splash-pads-01.jpg',                     alt: 'Splash pad coloured surface system — StreetBond slip-resistant acrylic coating for water play area and recreational splash zone' },
  'sport-courts':          { featured: '/images/applications/sport-courts/sport-courts-01.jpg',                   fallback: '/images/applications/sport-courts/sport-courts-01.jpg',                   alt: 'Sport court coloured surface system — StreetBond acrylic court markings for basketball, tennis, and multi-sport facility' },
  'townhomes':             { featured: '/images/applications/townhomes/townhomes-01.jpg',                         fallback: '/images/applications/townhomes/townhomes-01.jpg',                         alt: 'Townhome and strata development decorative driveway — StreetPrint stamped asphalt entry court and StreetBond coloured parking surface' },
  'traffic-calming':       { featured: '/images/applications/traffic-calming/traffic-calming-01.jpg',             fallback: '/images/applications/traffic-calming/traffic-calming-01.jpg',             alt: 'Traffic calming coloured pavement treatment — StreetBond and MMAX speed table surface markings for pedestrian safety zone' },
  'airports':              { featured: '/images/applications/airports/airports-01.jpg',                           fallback: '/images/applications/airports/airports-01.jpg',                           alt: 'Airport airfield markings — AirMark preformed thermoplastic runway and taxiway surface markings' },
  'leed-urban-heat-island':{ featured: '/images/applications/leed-urban-heat-island/leed-urban-heat-island-01.jpg', fallback: '/images/applications/leed-urban-heat-island/leed-urban-heat-island-01.jpg', alt: 'LEED urban heat island mitigation — StreetBond light-coloured solar-reflective pavement coating for cool surface compliance' },
  'public-art':            { featured: '/images/applications/community-branding/community-branding-11.jpg',       fallback: '/images/applications/public-spaces/public-spaces-12.png',               alt: 'Public art pavement installation — DecoMark and StreetBond custom civic mural and cultural identity street surface at Joyce-Collingwood Skytrain Station' },
  'pedestrian-safety':     { featured: '/images/applications/crosswalks/crosswalks-03.jpg',                       fallback: '/images/applications/crosswalks/crosswalks-01.jpg',                       alt: 'High-visibility pedestrian safety crosswalk — TrafficPatterns thermoplastic marking for Vision Zero school zone and intersection' },
};
