export interface ImageConfig {
  featured: string | null;
  fallback: string;
  alt: string;
}

export function resolveImage(config: ImageConfig): { src: string; alt: string } {
  return { src: config.featured ?? config.fallback, alt: config.alt };
}

export const heroImages = {
  homepage: { featured: '/images/hero/hero-1.jpg', fallback: '/images/hero/hero-2.jpg', alt: 'Decorative stamped asphalt crosswalk installed by HUB Surface Systems for a Canadian municipality' } as ImageConfig,
  about: { featured: '/images/hero/hero-3.jpg', fallback: '/images/hero/hero-bg.jpg', alt: 'HUB Surface Systems team — 30 years of decorative and functional pavement solutions across Canada' } as ImageConfig,
};

export const productImages: Record<string, ImageConfig> = {
  'traffic-patterns':    { featured: '/images/products/traffic-patterns/traffic-patterns-08.jpg',       fallback: '/images/products/traffic-patterns/traffic-patterns-01.jpg',       alt: 'TrafficPatterns preformed thermoplastic crosswalk at UBC — Musqueam Nation Indigenous art installation on University of British Columbia campus' },
  'traffic-patterns-xd': { featured: '/images/applications/crosswalks/crosswalks-114.png', fallback: '/images/products/traffic-patterns-xd/traffic-patterns-xd-10.jpg', alt: 'TrafficPatternsXD aggregate-reinforced preformed thermoplastic — red brick-pattern pier walkway on a waterfront promenade, installed by HUB Surface Systems' },
  'streetprint':         { featured: '/images/products/streetprint/streetprint-86.jpg',                 fallback: '/images/products/streetprint/streetprint-01.jpg',                 alt: 'StreetPrint stamped asphalt estate driveway — dark cobblestone-pattern entry between brick gate pillars under autumn trees' },
  'streetbond':          { featured: '/images/products/streetbond/streetbond-19.jpg',                  fallback: '/images/products/streetbond/streetbond-20.jpg',                   alt: 'StreetBond coloured pavement coating — red coated waterfront boardwalk with railing, coloured surface treatment by HUB Surface Systems' },
  'mmax':                { featured: '/images/products/mmax/mmax-04.jpg',                               fallback: '/images/products/mmax/mmax-01.jpg',                               alt: 'MMAX red bus-only lane — BUS ONLY legend on MMA methyl methacrylate coloured transit lane in London, Ontario' },
  'decomark':            { featured: '/images/applications/parks-paths/parks-paths-70.jpg',                       fallback: '/images/products/decomark/decomark-01.jpg',                       alt: 'DecoMark preformed thermoplastic public art — circular Indigenous medallion artwork fused into a concrete plaza at a building entrance' },
  'duratherm':           { featured: '/images/products/duratherm/duratherm-01.jpg',                     fallback: '/images/products/duratherm/duratherm-01.jpg',                     alt: 'DuraTherm inlaid flush-mount thermoplastic crosswalk — snowplow-safe decorative pavement marking embedded in asphalt surface' },
  'premark':             { featured: '/images/products/premark/premark-01.jpg',                         fallback: '/images/products/premark/premark-01.jpg',                         alt: 'PreMark preformed thermoplastic road marking symbols — turn arrows, stop bars, and regulatory pavement markings for Canadian municipalities' },
  'airmark':             { featured: '/images/products/airmark/airmark-01.jpg',                         fallback: '/images/products/airmark/airmark-01.jpg',                         alt: 'AirMark preformed thermoplastic airfield markings — runway threshold, taxiway guidance, and apron surface markings' },
  'durashield':          { featured: '/images/applications/parking-lots/parking-lots-04.jpg',                   fallback: '/images/products/durashield/durashield-01.jpg',                   alt: 'DuraShield protective pavement coating — freshly sealed dark grey commercial parking lot in front of a glass-fronted building' },
  'streetbondsr':        { featured: '/images/products/streetbond/streetbond-03.png',               fallback: '/images/products/streetbondsr/streetbondsr-01.png',               alt: 'StreetBondSR solar reflective pavement coating — light grey coated parking area, cool surface treatment for urban heat island reduction' },
};

export const applicationImages: Record<string, ImageConfig> = {
  'crosswalks':            { featured: '/images/applications/crosswalks/crosswalks-09.jpg',                       fallback: '/images/applications/crosswalks/crosswalks-01.jpg',                       alt: 'Decorative preformed thermoplastic crosswalk with white ladder bars at a transit intersection, bus passing behind — pedestrian safety surface by HUB Surface Systems' },
  'bike-lanes':            { featured: '/images/applications/bike-lanes/bike-lanes-14.jpg',                       fallback: '/images/applications/bike-lanes/bike-lanes-06.jpg',                       alt: 'Vivid green protected bike lane — StreetBond coloured cycling infrastructure for Complete Streets Canadian municipality' },
  'bus-lanes':             { featured: '/images/applications/bus-lanes/bus-lanes-20.jpg',                         fallback: '/images/applications/bus-lanes/bus-lanes-15.jpg',                         alt: 'Red MMAX bus rapid transit lane with transit bus — high-durability BRT surface marking for Canadian transit corridor' },
  'commercial-spaces':     { featured: '/images/applications/crosswalks/crosswalks-110.jpg',         fallback: '/images/applications/commercial-spaces/commercial-spaces-01.jpg',         alt: 'Commercial plaza red brick-pattern pedestrian crossing at a retail entrance in Oakville, Ontario — decorative pavement by HUB Surface Systems' },
  'community-branding':    { featured: '/images/blog/white-rock-langley-trafficpatterns/featured.jpg',       fallback: '/images/applications/community-branding/community-branding-05.jpg',       alt: 'Community branding crosswalk — custom blue and sand wave-pattern TrafficPatterns thermoplastic crossing in White Rock, BC' },
  'parking-lots':          { featured: '/images/applications/parking-lots/parking-lots-01.jpg',                   fallback: '/images/applications/parking-lots/parking-lots-01.jpg',                   alt: 'Parking lot decorative surface system — PreMark thermoplastic stall markings and DuraShield asphalt protective coating' },
  'parks-paths':           { featured: '/images/applications/parks-paths/parks-paths-01.jpg',                     fallback: '/images/applications/parks-paths/parks-paths-01.jpg',                     alt: 'Park pathway coloured surface treatment — StreetBond slip-resistant recreational trail marking for Canadian municipal greenway' },
  'playgrounds':           { featured: '/images/applications/playgrounds/playgrounds-01.jpg',                     fallback: '/images/applications/playgrounds/playgrounds-01.jpg',                     alt: 'School playground surface markings — DecoMark custom preformed thermoplastic graphics and activity zones for children' },
  'private-driveways':     { featured: '/images/applications/residential-driveways/residential-driveways-18.jpg', fallback: '/images/applications/residential-driveways/residential-driveways-01.jpg', alt: 'Private driveway in StreetPrint stamped asphalt — circular medallion entry between brick pillars at dusk, lit home behind' },
  'residential-driveways': { featured: '/images/applications/residential-driveways/residential-driveways-18.jpg', fallback: '/images/applications/residential-driveways/residential-driveways-03.jpg', alt: 'Residential stamped asphalt driveway — StreetPrint circular medallion entry between brick pillars at dusk, lit home behind' },
  'regulatory-markings':   { featured: '/images/applications/crosswalks/crosswalks-01.jpg',                       fallback: '/images/applications/crosswalks/crosswalks-01.jpg',                       alt: 'Regulatory road markings — PreMark preformed thermoplastic directional arrows, stop bars, and yield markings for Canadian municipalities' },
  'splash-pads':           { featured: '/images/applications/splash-pads/splash-pads-01.jpg',                     fallback: '/images/applications/splash-pads/splash-pads-01.jpg',                     alt: 'Splash pad coloured surface system — StreetBond slip-resistant acrylic coating for water play area and recreational splash zone' },
  'sport-courts':          { featured: '/images/products/streetbond/streetbond-67.png',                   fallback: '/images/applications/sport-courts/sport-courts-01.jpg',                   alt: 'Sport court in StreetBond coloured coating — pink and orange basketball court with circular graphics beside a park' },
  'townhomes':             { featured: '/images/applications/townhomes/townhomes-01.jpg',                         fallback: '/images/applications/townhomes/townhomes-01.jpg',                         alt: 'Townhome and strata development decorative driveway — StreetPrint stamped asphalt entry court and StreetBond coloured parking surface' },
  'traffic-calming':       { featured: '/images/applications/traffic-calming/traffic-calming-01.jpg',             fallback: '/images/applications/traffic-calming/traffic-calming-01.jpg',             alt: 'Traffic calming coloured pavement treatment — StreetBond and MMAX speed table surface markings for pedestrian safety zone' },
  'airports':              { featured: '/images/applications/airports/airports-01.jpg',                           fallback: '/images/applications/airports/airports-01.jpg',                           alt: 'Airport airfield markings — AirMark preformed thermoplastic runway and taxiway surface markings' },
  'leed-urban-heat-island':{ featured: '/images/applications/leed-urban-heat-island/leed-urban-heat-island-01.jpg', fallback: '/images/applications/leed-urban-heat-island/leed-urban-heat-island-01.jpg', alt: 'LEED urban heat island mitigation — StreetBond light-coloured solar-reflective pavement coating for cool surfaces' },
  'public-art':            { featured: '/images/applications/community-branding/community-branding-02.jpg',                fallback: '/images/applications/community-branding/community-branding-11.jpg',      alt: 'Public art crosswalk — black and white circular pattern thermoplastic pavement artwork on a city street' },
  'pedestrian-safety':     { featured: '/images/applications/crosswalks/crosswalks-03.jpg',                       fallback: '/images/applications/crosswalks/crosswalks-01.jpg',                       alt: 'High-visibility pedestrian safety crosswalk — TrafficPatterns thermoplastic marking for Vision Zero school zone and intersection' },
};
