/**
 * Pre-rendered PDF page previews.
 *
 * Android Chrome and in-app webviews (LinkedIn, Facebook, Instagram) do not
 * render PDFs inline, so an <iframe> preview showed a blank panel on exactly
 * the devices municipal specifiers most often use. These WebP page images
 * render everywhere.
 *
 * Generated by scripts/gen-pdf-previews.py and committed, because Vercel's
 * Node build image has no Python. Re-run that script whenever a PDF changes.
 */
import manifest from "@/lib/pdf-previews.json";

export interface PdfPreviewPage {
  src: string;
  w: number;
  h: number;
}

export interface PdfPreview {
  /** First few pages, in order. */
  pages: PdfPreviewPage[];
  /** Page count of the underlying PDF, so the UI can say "3 of 8". */
  total: number;
}

const PREVIEWS = manifest as Record<string, PdfPreview>;

/** Pre-rendered previews for a PDF href, or null when none were generated. */
export function previewFor(href: string | undefined | null): PdfPreview | null {
  if (!href) return null;
  const clean = href.split("?")[0].split("#")[0];
  return PREVIEWS[clean] ?? null;
}
