/**
 * Pre-rendered PDF page previews.
 *
 * Android Chrome and in-app webviews (LinkedIn, Facebook, Instagram) do not
 * render PDFs inline, so an <iframe> preview showed a blank panel on exactly
 * the devices municipal specifiers most often use. These WebP page images
 * render everywhere.
 *
 * Generated by scripts/gen-pdf-previews.py and committed, because Vercel's
 * Node build image has no Python. Re-run that script whenever a PDF changes.
 */
import manifest from "@/lib/pdf-previews.json";

export interface PdfPreviewPage {
  src: string;
  w: number;
  h: number;
}

export interface PdfPreview {
  /** First few pages, in order. */
  pages: PdfPreviewPage[];
  /** Page count of the underlying PDF, so the UI can say "3 of 8". */
  total: number;
}

const PREVIEWS = manifest as Record<string, PdfPreview>;

// Case-insensitive index. The manifest keys come from walking public/docs on
// disk ("/docs/StreetPrint/..."), while the app's data files spell some of the
// same folders lowercase ("/docs/streetprint/..."). On Windows both paths
// serve the same file, so the mismatch is invisible in local dev — on the
// case-sensitive Linux build it silently disqualified 14 of the 48 documents
// that HAVE generated previews, dropping them to the iframe fallback that
// blanks out on Android. Exact-case wins when both exist.
const BY_LOWER: Record<string, PdfPreview> = {};
for (const [k, v] of Object.entries(PREVIEWS)) BY_LOWER[k.toLowerCase()] = v;

/** Pre-rendered previews for a PDF href, or null when none were generated. */
export function previewFor(href: string | undefined | null): PdfPreview | null {
  if (!href) return null;
  const clean = href.split("?")[0].split("#")[0];
  return PREVIEWS[clean] ?? BY_LOWER[clean.toLowerCase()] ?? null;
}
