export interface Product {
  name: string;
  slug: string;
  shortDesc: string;
  description: string;
  imageUrl: string;
  gallery?: string[];
  specs: { label: string; value: string }[];
  relatedApplications: string[]; // application slugs
  colourCollections?: { name: string; hex: string }[];
}

export const products: Product[] = [
  {
    name: "TrafficPatterns",
    slug: "traffic-patterns",
    shortDesc: "Permanent pattern. Permanent impression.",
    imageUrl: "/images/products/traffic-patterns/traffic-patterns-01.jpg",
    gallery: [
      "/images/products/traffic-patterns/traffic-patterns-01.jpg",
      "/images/products/traffic-patterns/traffic-patterns-02.jpg",
      "/images/products/traffic-patterns/traffic-patterns-03.jpg",
      "/images/products/traffic-patterns/traffic-patterns-04.jpg",
      "/images/products/traffic-patterns/traffic-patterns-05.jpg",
      "/images/products/traffic-patterns/traffic-patterns-06.jpg",
      "/images/products/traffic-patterns/traffic-patterns-07.jpg",
      "/images/products/traffic-patterns/traffic-patterns-08.jpg",
      "/images/products/traffic-patterns/traffic-patterns-09.jpg",
      "/images/products/traffic-patterns/traffic-patterns-10.jpg",
      "/images/products/traffic-patterns/traffic-patterns-11.jpg",
      "/images/products/traffic-patterns/traffic-patterns-12.jpg",
      "/images/products/traffic-patterns/traffic-patterns-13.jpg",
      "/images/products/traffic-patterns/traffic-patterns-14.jpg",
      "/images/products/traffic-patterns/traffic-patterns-15.jpg",
      "/images/products/traffic-patterns/traffic-patterns-16.jpg",
      "/images/products/traffic-patterns/traffic-patterns-17.jpg",
      "/images/products/traffic-patterns/traffic-patterns-18.jpg",
      "/images/products/traffic-patterns/traffic-patterns-19.jpg",
      "/images/products/traffic-patterns/traffic-patterns-20.jpg",
      "/images/products/traffic-patterns/traffic-patterns-21.jpg",
      "/images/products/traffic-patterns/traffic-patterns-22.jpg",
      "/images/products/traffic-patterns/traffic-patterns-23.jpg",
      "/images/products/traffic-patterns/traffic-patterns-24.jpg",
      "/images/products/traffic-patterns/traffic-patterns-25.jpg",
      "/images/products/traffic-patterns/traffic-patterns-26.jpg",
      "/images/products/traffic-patterns/traffic-patterns-27.jpg",
      "/images/products/traffic-patterns/traffic-patterns-28.jpg",
      "/images/products/traffic-patterns/traffic-patterns-29.jpg",
      "/images/products/traffic-patterns/traffic-patterns-30.jpg",
      "/images/products/traffic-patterns/traffic-patterns-31.jpg",
      "/images/products/traffic-patterns/traffic-patterns-32.jpg",
      "/images/products/traffic-patterns/traffic-patterns-33.jpg",
      "/images/products/traffic-patterns/traffic-patterns-34.jpg",
      "/images/products/traffic-patterns/traffic-patterns-35.jpg",
      "/images/products/traffic-patterns/traffic-patterns-36.jpg",
      "/images/products/traffic-patterns/traffic-patterns-37.jpg",
      "/images/products/traffic-patterns/traffic-patterns-38.jpg",
      "/images/products/traffic-patterns/traffic-patterns-39.jpg",
      "/images/products/traffic-patterns/traffic-patterns-40.jpg",
      "/images/products/traffic-patterns/traffic-patterns-41.jpg",
      "/images/products/traffic-patterns/traffic-patterns-42.jpg",
      "/images/products/traffic-patterns/traffic-patterns-43.jpg",
      "/images/products/traffic-patterns/traffic-patterns-44.jpg",
      "/images/products/traffic-patterns/traffic-patterns-45.jpg",
      "/images/products/traffic-patterns/traffic-patterns-46.jpg",
      "/images/products/traffic-patterns/traffic-patterns-47.jpg",
      "/images/products/traffic-patterns/traffic-patterns-48.jpg",
      "/images/products/traffic-patterns/traffic-patterns-49.jpg",
      "/images/products/traffic-patterns/traffic-patterns-50.jpg",
      "/images/products/traffic-patterns/traffic-patterns-51.jpg",
      "/images/products/traffic-patterns/traffic-patterns-52.jpg",
      "/images/products/traffic-patterns/traffic-patterns-53.jpg",
      "/images/products/traffic-patterns/traffic-patterns-54.jpg",
      "/images/products/traffic-patterns/traffic-patterns-55.jpg",
      "/images/products/traffic-patterns/traffic-patterns-56.jpg",
      "/images/products/traffic-patterns/traffic-patterns-57.jpg",
      "/images/products/traffic-patterns/traffic-patterns-58.jpg",
      "/images/products/traffic-patterns/traffic-patterns-59.jpg",
      "/images/products/traffic-patterns/traffic-patterns-60.jpg",
      "/images/products/traffic-patterns/traffic-patterns-61.jpg",
      "/images/products/traffic-patterns/traffic-patterns-62.jpg",
      "/images/products/traffic-patterns/traffic-patterns-63.jpg",
      "/images/products/traffic-patterns/traffic-patterns-64.jpg",
      "/images/products/traffic-patterns/traffic-patterns-65.png",
      "/images/products/traffic-patterns/traffic-patterns-66.jpg",
      "/images/products/traffic-patterns/traffic-patterns-67.jpg",
      "/images/products/traffic-patterns/traffic-patterns-68.jpg",
      "/images/products/traffic-patterns/traffic-patterns-69.png",
      "/images/products/traffic-patterns/traffic-patterns-70.jpg",
      "/images/products/traffic-patterns/traffic-patterns-71.jpg",
      "/images/products/traffic-patterns/traffic-patterns-72.jpg",
      "/images/products/traffic-patterns/traffic-patterns-73.jpg",
      "/images/products/traffic-patterns/traffic-patterns-74.jpg",
      "/images/products/traffic-patterns/traffic-patterns-75.jpg",
      "/images/products/traffic-patterns/traffic-patterns-76.jpg",
      "/images/products/traffic-patterns/traffic-patterns-77.jpg",
      "/images/products/traffic-patterns/traffic-patterns-78.jpg",
      "/images/products/traffic-patterns/traffic-patterns-79.jpg",
      "/images/products/traffic-patterns/traffic-patterns-80.jpg",
      "/images/products/traffic-patterns/traffic-patterns-81.jpg",
      "/images/products/traffic-patterns/traffic-patterns-82.jpg",
      "/images/products/traffic-patterns/traffic-patterns-83.jpg",
      "/images/products/traffic-patterns/traffic-patterns-84.jpg",
      "/images/products/traffic-patterns/traffic-patterns-85.jpg",
      "/images/products/traffic-patterns/traffic-patterns-86.jpg",
    ],

    description: "Crisp, permanently fused markings that survive snowplows, de-icing chemicals, and decades of freeze-thaw cycles — that's what TrafficPatterns delivers. Factory-manufactured to 90mil thickness, each sheet arrives ready to apply: position, heat, bond. Trusted by York Region, the City of Toronto, Vancouver, and UBC, this benchmark preformed thermoplastic system delivers 5–7 years of consistent retroreflectivity where traffic paint lasts just 12–18 months.",
    specs: [
      { label: "Material",          value: "Preformed thermoplastic" },
      { label: "Thickness",         value: "90mil standard" },
      { label: "Retroreflectivity", value: "ASTM D4956 Type III glass beads" },
      { label: "Temperature Range", value: "-40°C to +60°C in service" },
      { label: "Installation",      value: "Heat application — open to traffic in hours" },
      { label: "Service Life",      value: "5–7 years" },
      { label: "Standards",         value: "TAC + MUTCD compliant" },
    ],
    relatedApplications: ["crosswalks", "bike-lanes", "bus-lanes", "parking-lots"],
  },
  {
    name: "StreetPrint",
    slug: "streetprint",
    shortDesc: "Where asphalt becomes architecture.",
    imageUrl: "/images/products/streetprint/streetprint-01.jpg",
    gallery: [
      "/images/products/streetprint/streetprint-01.jpg",
      "/images/products/streetprint/streetprint-02.jpg",
      "/images/products/streetprint/streetprint-03.jpg",
      "/images/products/streetprint/streetprint-04.jpg",
      "/images/products/streetprint/streetprint-05.jpg",
      "/images/products/streetprint/streetprint-06.jpg",
      "/images/products/streetprint/streetprint-07.jpg",
      "/images/products/streetprint/streetprint-08.jpg",
      "/images/products/streetprint/streetprint-09.jpg",
      "/images/products/streetprint/streetprint-10.jpg",
      "/images/products/streetprint/streetprint-11.jpg",
      "/images/products/streetprint/streetprint-12.jpg",
      "/images/products/streetprint/streetprint-13.jpg",
      "/images/products/streetprint/streetprint-14.jpg",
      "/images/products/streetprint/streetprint-15.jpg",
      "/images/products/streetprint/streetprint-16.jpg",
      "/images/products/streetprint/streetprint-17.jpg",
      "/images/products/streetprint/streetprint-18.jpg",
      "/images/products/streetprint/streetprint-19.jpg",
      "/images/products/streetprint/streetprint-20.jpg",
      "/images/products/streetprint/streetprint-21.jpg",
      "/images/products/streetprint/streetprint-22.jpg",
      "/images/products/streetprint/streetprint-23.jpg",
      "/images/products/streetprint/streetprint-24.jpg",
      "/images/products/streetprint/streetprint-25.jpg",
      "/images/products/streetprint/streetprint-26.jpg",
      "/images/products/streetprint/streetprint-27.jpg",
      "/images/products/streetprint/streetprint-28.jpg",
      "/images/products/streetprint/streetprint-29.jpg",
      "/images/products/streetprint/streetprint-30.jpg",
      "/images/products/streetprint/streetprint-31.jpg",
      "/images/products/streetprint/streetprint-32.jpg",
      "/images/products/streetprint/streetprint-33.jpg",
      "/images/products/streetprint/streetprint-34.jpg",
      "/images/products/streetprint/streetprint-35.jpg",
      "/images/products/streetprint/streetprint-36.jpg",
      "/images/products/streetprint/streetprint-37.jpg",
      "/images/products/streetprint/streetprint-38.jpg",
      "/images/products/streetprint/streetprint-39.jpg",
      "/images/products/streetprint/streetprint-40.jpg",
      "/images/products/streetprint/streetprint-41.jpg",
      "/images/products/streetprint/streetprint-42.jpg",
      "/images/products/streetprint/streetprint-43.jpg",
      "/images/products/streetprint/streetprint-44.jpg",
      "/images/products/streetprint/streetprint-45.jpg",
      "/images/products/streetprint/streetprint-46.jpg",
      "/images/products/streetprint/streetprint-47.jpg",
      "/images/products/streetprint/streetprint-48.jpg",
      "/images/products/streetprint/streetprint-49.jpg",
      "/images/products/streetprint/streetprint-50.jpg",
      "/images/products/streetprint/streetprint-51.jpg",
      "/images/products/streetprint/streetprint-52.jpg",
      "/images/products/streetprint/streetprint-53.jpg",
      "/images/products/streetprint/streetprint-54.jpg",
      "/images/products/streetprint/streetprint-55.jpg",
      "/images/products/streetprint/streetprint-56.jpg",
      "/images/products/streetprint/streetprint-57.png",
      "/images/products/streetprint/streetprint-58.jpg",
      "/images/products/streetprint/streetprint-59.jpg",
      "/images/products/streetprint/streetprint-60.jpg",
      "/images/products/streetprint/streetprint-61.jpg",
      "/images/products/streetprint/streetprint-62.jpg",
      "/images/products/streetprint/streetprint-63.png",
      "/images/products/streetprint/streetprint-64.jpg",
      "/images/products/streetprint/streetprint-65.jpg",
      "/images/products/streetprint/streetprint-66.jpg",
      "/images/products/streetprint/streetprint-67.jpg",
      "/images/products/streetprint/streetprint-68.jpg",
      "/images/products/streetprint/streetprint-69.jpg",
      "/images/products/streetprint/streetprint-70.jpg",
      "/images/products/streetprint/streetprint-71.jpg",
      "/images/products/streetprint/streetprint-72.jpg",
      "/images/products/streetprint/streetprint-73.jpg",
      "/images/products/streetprint/streetprint-74.jpg",
      "/images/products/streetprint/streetprint-75.jpg",
      "/images/products/streetprint/streetprint-76.jpg",
      "/images/products/streetprint/streetprint-77.jpg",
      "/images/products/streetprint/streetprint-78.jpg",
      "/images/products/streetprint/streetprint-79.jpg",
      "/images/products/streetprint/streetprint-80.jpg",
      "/images/products/streetprint/streetprint-81.jpg",
      "/images/products/streetprint/streetprint-82.jpg",
      "/images/products/streetprint/streetprint-83.jpg",
      "/images/products/streetprint/streetprint-84.jpg",
      "/images/products/streetprint/streetprint-85.jpg",
      "/images/products/streetprint/streetprint-86.jpg",
      "/images/products/streetprint/streetprint-87.jpg",
      "/images/products/streetprint/streetprint-88.jpg",
      "/images/products/streetprint/streetprint-89.jpg",
      "/images/products/streetprint/streetprint-90.jpg",
      "/images/products/streetprint/streetprint-91.jpg",
    ],

    description: "StreetPrint transforms existing asphalt into rich decorative hardscape — brick, cobblestone, slate, random stone — without ripping out the road. A proprietary in-place stamping process impresses a textured grid directly into freshly laid or reheated asphalt, then StreetBond UV-stable colour coating is applied over top. The finish looks like traditional pavers but performs like asphalt: flexible through freeze-thaw cycles, snowplow-safe, and backed by a 20-year colour retention warranty. Used by more than 500 Canadian municipalities, developers, and strata councils to define intersections, driveways, plazas, and pedestrian zones.",
    specs: [
      { label: "System",       value: "In-place asphalt stamping + StreetBond coating" },
      { label: "Patterns",     value: "12+ standard patterns · custom available" },
      { label: "Colour Coat",  value: "StreetBond UV-stable acrylic" },
      { label: "Durability",   value: "20-year colour retention warranty" },
      { label: "Base",         value: "New lay or existing asphalt" },
      { label: "Snowplow Safe",value: "Yes — flush surface, no raised edges" },
      { label: "Applications", value: "Intersections, plazas, driveways, crosswalks" },
    ],
    relatedApplications: ["crosswalks", "private-driveways", "community-branding", "parking-lots"],
  },
  {
    name: "TrafficPatternsXD",
    slug: "traffic-patterns-xd",
    shortDesc: "Built for the roads that never rest.",
    imageUrl: "/images/products/traffic-patterns-xd/traffic-patterns-xd-01.jpg",
    gallery: [
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-01.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-02.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-03.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-04.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-05.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-06.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-07.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-08.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-09.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-10.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-100.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-101.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-102.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-103.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-104.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-105.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-106.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-107.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-108.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-109.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-11.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-110.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-111.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-112.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-113.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-114.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-115.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-116.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-117.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-118.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-119.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-12.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-120.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-121.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-122.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-123.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-124.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-125.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-126.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-127.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-128.png",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-129.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-13.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-130.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-131.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-132.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-133.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-134.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-135.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-136.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-137.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-138.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-139.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-14.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-140.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-141.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-142.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-143.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-15.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-16.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-17.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-18.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-19.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-20.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-21.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-22.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-23.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-24.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-25.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-26.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-27.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-28.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-29.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-30.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-31.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-32.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-33.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-34.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-35.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-36.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-37.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-38.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-39.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-40.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-41.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-42.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-43.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-44.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-45.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-46.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-47.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-48.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-49.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-50.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-51.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-52.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-53.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-54.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-55.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-56.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-57.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-58.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-59.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-60.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-61.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-62.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-63.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-64.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-65.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-66.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-67.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-68.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-69.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-70.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-71.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-72.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-73.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-74.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-75.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-76.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-77.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-78.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-79.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-80.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-81.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-82.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-83.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-84.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-85.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-86.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-87.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-88.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-89.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-90.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-91.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-92.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-93.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-94.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-95.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-96.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-97.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-98.jpg",
      "/images/products/traffic-patterns-xd/traffic-patterns-xd-99.jpg",
    ],

    description: "TrafficPatternsXD was engineered for one purpose: to survive where everything else fails. At 150mil with a crushed aggregate-reinforced formula, XD handles the combined abuse of turning bus tires, snowplow blades, and freeze-thaw cycling at high-volume intersections and BRT corridors. Installed at London's East London Link BRT and on TTC bus priority corridors across Toronto, XD delivers consistent skid resistance (BPN 65+) and retroreflectivity for 7+ years. When standard thermoplastic wears prematurely at your most demanding locations, XD is the specified solution.",
    specs: [
      { label: "Material",         value: "Aggregate-reinforced preformed thermoplastic" },
      { label: "Thickness",        value: "150mil" },
      { label: "Aggregate",        value: "Crushed aggregate + glass bead surface" },
      { label: "Skid Resistance",  value: "BPN 65+ (exceeds MOT requirements)" },
      { label: "Retroreflectivity",value: "ASTM D4956 Type III" },
      { label: "Service Life",     value: "7+ years in high-volume use" },
      { label: "Standards",        value: "TAC + MUTCD compliant" },
    ],
    relatedApplications: ["crosswalks", "bike-lanes", "bus-lanes"],
  },
  {
    name: "StreetBond",
    slug: "streetbond",
    shortDesc: "Colour that bonds. Beauty that endures.",
    imageUrl: "/images/products/streetbond/streetbond-01.png",
    gallery: [
      "/images/products/streetbond/streetbond-01.png",
      "/images/products/streetbond/streetbond-02.png",
      "/images/products/streetbond/streetbond-03.png",
      "/images/products/streetbond/streetbond-04.png",
      "/images/products/streetbond/streetbond-05.png",
      "/images/products/streetbond/streetbond-06.png",
      "/images/products/streetbond/streetbond-07.png",
      "/images/products/streetbond/streetbond-08.png",
      "/images/products/streetbond/streetbond-09.jpg",
      "/images/products/streetbond/streetbond-10.jpg",
      "/images/products/streetbond/streetbond-100.jpg",
      "/images/products/streetbond/streetbond-101.jpg",
      "/images/products/streetbond/streetbond-102.jpg",
      "/images/products/streetbond/streetbond-103.jpg",
      "/images/products/streetbond/streetbond-104.jpg",
      "/images/products/streetbond/streetbond-105.jpg",
      "/images/products/streetbond/streetbond-106.jpg",
      "/images/products/streetbond/streetbond-107.jpg",
      "/images/products/streetbond/streetbond-108.jpg",
      "/images/products/streetbond/streetbond-109.jpg",
      "/images/products/streetbond/streetbond-11.jpg",
      "/images/products/streetbond/streetbond-110.jpg",
      "/images/products/streetbond/streetbond-111.jpg",
      "/images/products/streetbond/streetbond-112.jpg",
      "/images/products/streetbond/streetbond-12.jpg",
      "/images/products/streetbond/streetbond-13.jpg",
      "/images/products/streetbond/streetbond-14.jpg",
      "/images/products/streetbond/streetbond-15.jpg",
      "/images/products/streetbond/streetbond-16.jpg",
      "/images/products/streetbond/streetbond-17.jpg",
      "/images/products/streetbond/streetbond-18.jpg",
      "/images/products/streetbond/streetbond-19.jpg",
      "/images/products/streetbond/streetbond-20.jpg",
      "/images/products/streetbond/streetbond-21.jpg",
      "/images/products/streetbond/streetbond-22.jpg",
      "/images/products/streetbond/streetbond-23.jpg",
      "/images/products/streetbond/streetbond-24.jpg",
      "/images/products/streetbond/streetbond-25.jpg",
      "/images/products/streetbond/streetbond-26.jpg",
      "/images/products/streetbond/streetbond-27.jpg",
      "/images/products/streetbond/streetbond-28.jpg",
      "/images/products/streetbond/streetbond-29.jpg",
      "/images/products/streetbond/streetbond-30.jpg",
      "/images/products/streetbond/streetbond-31.jpg",
      "/images/products/streetbond/streetbond-32.jpg",
      "/images/products/streetbond/streetbond-33.jpg",
      "/images/products/streetbond/streetbond-34.jpg",
      "/images/products/streetbond/streetbond-35.jpg",
      "/images/products/streetbond/streetbond-36.jpg",
      "/images/products/streetbond/streetbond-37.jpg",
      "/images/products/streetbond/streetbond-38.jpg",
      "/images/products/streetbond/streetbond-39.jpg",
      "/images/products/streetbond/streetbond-40.jpg",
      "/images/products/streetbond/streetbond-41.jpg",
      "/images/products/streetbond/streetbond-42.jpg",
      "/images/products/streetbond/streetbond-43.jpg",
      "/images/products/streetbond/streetbond-44.jpg",
      "/images/products/streetbond/streetbond-45.jpg",
      "/images/products/streetbond/streetbond-46.jpg",
      "/images/products/streetbond/streetbond-47.jpg",
      "/images/products/streetbond/streetbond-48.jpg",
      "/images/products/streetbond/streetbond-49.png",
      "/images/products/streetbond/streetbond-50.jpg",
      "/images/products/streetbond/streetbond-51.jpg",
      "/images/products/streetbond/streetbond-52.jpg",
      "/images/products/streetbond/streetbond-53.jpg",
      "/images/products/streetbond/streetbond-54.jpg",
      "/images/products/streetbond/streetbond-55.jpg",
      "/images/products/streetbond/streetbond-56.jpg",
      "/images/products/streetbond/streetbond-57.png",
      "/images/products/streetbond/streetbond-58.jpg",
      "/images/products/streetbond/streetbond-59.png",
      "/images/products/streetbond/streetbond-60.png",
      "/images/products/streetbond/streetbond-61.png",
      "/images/products/streetbond/streetbond-62.png",
      "/images/products/streetbond/streetbond-63.png",
      "/images/products/streetbond/streetbond-64.png",
      "/images/products/streetbond/streetbond-65.png",
      "/images/products/streetbond/streetbond-66.png",
      "/images/products/streetbond/streetbond-67.png",
      "/images/products/streetbond/streetbond-68.png",
      "/images/products/streetbond/streetbond-69.png",
      "/images/products/streetbond/streetbond-70.png",
      "/images/products/streetbond/streetbond-71.png",
      "/images/products/streetbond/streetbond-72.png",
      "/images/products/streetbond/streetbond-73.png",
      "/images/products/streetbond/streetbond-74.png",
      "/images/products/streetbond/streetbond-75.png",
      "/images/products/streetbond/streetbond-76.png",
      "/images/products/streetbond/streetbond-77.png",
      "/images/products/streetbond/streetbond-78.png",
      "/images/products/streetbond/streetbond-79.png",
      "/images/products/streetbond/streetbond-80.jpg",
      "/images/products/streetbond/streetbond-81.jpg",
      "/images/products/streetbond/streetbond-82.jpg",
      "/images/products/streetbond/streetbond-83.jpg",
      "/images/products/streetbond/streetbond-84.jpg",
      "/images/products/streetbond/streetbond-85.jpg",
      "/images/products/streetbond/streetbond-86.jpg",
      "/images/products/streetbond/streetbond-87.jpg",
      "/images/products/streetbond/streetbond-88.jpg",
      "/images/products/streetbond/streetbond-89.jpg",
      "/images/products/streetbond/streetbond-90.jpg",
      "/images/products/streetbond/streetbond-91.jpg",
      "/images/products/streetbond/streetbond-92.jpg",
      "/images/products/streetbond/streetbond-93.jpg",
      "/images/products/streetbond/streetbond-94.jpg",
      "/images/products/streetbond/streetbond-95.jpg",
      "/images/products/streetbond/streetbond-96.jpg",
      "/images/products/streetbond/streetbond-97.jpg",
      "/images/products/streetbond/streetbond-98.jpg",
      "/images/products/streetbond/streetbond-99.jpg",
    ],
    description: "StreetBond is the industry-leading coloured pavement coating for asphalt and concrete — the product behind Vancouver's iconic decorative crosswalks, Bowen Island's community art path, and bike lane treatments across all 10 provinces. Its advanced acrylic formulation creates a permanent bond with the pavement surface, delivering vivid colour that resists fading, peeling, and cracking for 20 years. Available in an extensive standard palette and fully custom Pantone-matched, StreetBond is the go-to choice for municipal branding, Pride crosswalks, Indigenous art installations, and Complete Streets bike lane delineation. BC Ministry of Transportation recognized product.",
    specs: [
      { label: "Type",           value: "Acrylic coloured pavement coating" },
      { label: "Surfaces",       value: "Asphalt and concrete (acid-etched)" },
      { label: "Flexibility",    value: "Moves with pavement — will not peel or crack" },
      { label: "Durability",     value: "20-year colour retention warranty" },
      { label: "Coverage",       value: "30–50 sq ft per gallon (system-dependent)" },
      { label: "Dry Time",       value: "2–4 hours" },
      { label: "Colour Matching",value: "Full Pantone custom matching available" },
      { label: "Standards",      value: "MUTCD compliant · BCMOT recognized" },
    ],
    colourCollections: [
      { name: "Traffic Red",     hex: "#C0392B" },
      { name: "Bike Lane Green", hex: "#27AE60" },
      { name: "Sunflower",       hex: "#F1C40F" },
      { name: "Pacific Blue",    hex: "#2980B9" },
      { name: "Civic Orange",    hex: "#E67E22" },
      { name: "Night White",     hex: "#F2F2F2" },
    ],
    relatedApplications: ["bike-lanes", "bus-lanes", "private-driveways", "parks-paths", "parking-lots"],
  },
  {
    name: "MMAX",
    slug: "mmax",
    shortDesc: "Lanes that lead. Colour that commands.",
    imageUrl: "/images/products/mmax/mmax-01.jpg",
    gallery: [
      "/images/products/mmax/mmax-01.jpg",
      "/images/products/mmax/mmax-02.jpg",
      "/images/products/mmax/mmax-03.jpg",
      "/images/products/mmax/mmax-04.jpg",
      "/images/products/mmax/mmax-05.jpg",
      "/images/products/mmax/mmax-06.jpg",
      "/images/products/mmax/mmax-07.jpg",
      "/images/products/mmax/mmax-08.jpg",
      "/images/products/mmax/mmax-09.jpg",
      "/images/products/mmax/mmax-10.jpg",
      "/images/products/mmax/mmax-11.jpg",
      "/images/products/mmax/mmax-12.jpg",
      "/images/products/mmax/mmax-13.jpg",
      "/images/products/mmax/mmax-14.jpg",
      "/images/products/mmax/mmax-15.jpg",
      "/images/products/mmax/mmax-16.jpg",
      "/images/products/mmax/mmax-17.jpg",
      "/images/products/mmax/mmax-18.jpg",
      "/images/products/mmax/mmax-19.jpg",
      "/images/products/mmax/mmax-20.jpg",
      "/images/products/mmax/mmax-21.jpg",
      "/images/products/mmax/mmax-22.jpg",
      "/images/products/mmax/mmax-23.jpg",
      "/images/products/mmax/mmax-24.jpg",
      "/images/products/mmax/mmax-25.jpg",
      "/images/products/mmax/mmax-26.jpg",
      "/images/products/mmax/mmax-27.jpg",
      "/images/products/mmax/mmax-28.jpg",
      "/images/products/mmax/mmax-29.jpg",
      "/images/products/mmax/mmax-30.jpg",
      "/images/products/mmax/mmax-31.jpg",
      "/images/products/mmax/mmax-32.jpg",
      "/images/products/mmax/mmax-33.jpg",
    ],
    description: "Close the lane at midnight, reopen by morning rush — MMAX methyl methacrylate cures in 30–60 minutes, letting crews complete full corridor installations in a single overnight shift. This highest-performance coloured pavement system delivers mechanical bond strength exceeding 3 MPa, exceptional UV stability, and can be applied at temperatures as low as -10°C. Deployed on TTC bus priority corridors, London's East London Link BRT, and rapid transit projects across the country, MMAX is the specified solution where painted lanes are not an option.",
    specs: [
      { label: "Material",       value: "Methyl Methacrylate (MMA) resin" },
      { label: "Cure Time",      value: "30–60 minutes (traffic-ready)" },
      { label: "Bond Strength",  value: ">3 MPa" },
      { label: "Thickness",      value: "1.5–3mm applied" },
      { label: "Min. Temp",      value: "-10°C application" },
      { label: "UV Stability",   value: "High — colour-fast for 10+ years" },
      { label: "Service Life",   value: "10+ years in transit lane use" },
    ],
    relatedApplications: ["bike-lanes", "bus-lanes", "crosswalks"],
  },
  {
    name: "DecoMark",
    slug: "decomark",
    shortDesc: "From CAD file to civic landmark.",
    imageUrl: "/images/products/decomark/decomark-01.jpg",
    gallery: [
      "/images/products/decomark/decomark-01.jpg",
      "/images/products/decomark/decomark-02.jpg",
      "/images/products/decomark/decomark-03.jpg",
      "/images/products/decomark/decomark-04.jpg",
      "/images/products/decomark/decomark-05.jpg",
      "/images/products/decomark/decomark-06.jpg",
      "/images/products/decomark/decomark-07.jpg",
      "/images/products/decomark/decomark-08.jpg",
      "/images/products/decomark/decomark-09.jpg",
      "/images/products/decomark/decomark-10.jpg",
      "/images/products/decomark/decomark-11.jpg",
      "/images/products/decomark/decomark-12.jpg",
      "/images/products/decomark/decomark-13.jpg",
      "/images/products/decomark/decomark-14.jpg",
      "/images/products/decomark/decomark-15.jpg",
      "/images/products/decomark/decomark-16.jpg",
      "/images/products/decomark/decomark-17.jpg",
      "/images/products/decomark/decomark-18.jpg",
      "/images/products/decomark/decomark-19.jpg",
      "/images/products/decomark/decomark-20.jpg",
      "/images/products/decomark/decomark-21.jpg",
      "/images/products/decomark/decomark-22.jpg",
      "/images/products/decomark/decomark-23.jpg",
      "/images/products/decomark/decomark-24.jpg",
      "/images/products/decomark/decomark-25.jpg",
      "/images/products/decomark/decomark-26.jpg",
      "/images/products/decomark/decomark-27.jpg",
      "/images/products/decomark/decomark-28.jpg",
      "/images/products/decomark/decomark-29.jpg",
      "/images/products/decomark/decomark-30.jpg",
      "/images/products/decomark/decomark-31.jpg",
      "/images/products/decomark/decomark-32.jpg",
      "/images/products/decomark/decomark-33.jpg",
      "/images/products/decomark/decomark-34.jpg",
      "/images/products/decomark/decomark-35.jpg",
      "/images/products/decomark/decomark-36.jpg",
      "/images/products/decomark/decomark-37.jpg",
      "/images/products/decomark/decomark-38.jpg",
      "/images/products/decomark/decomark-39.jpg",
      "/images/products/decomark/decomark-40.jpg",
      "/images/products/decomark/decomark-41.jpg",
      "/images/products/decomark/decomark-42.jpg",
      "/images/products/decomark/decomark-43.jpg",
      "/images/products/decomark/decomark-44.jpg",
      "/images/products/decomark/decomark-45.jpg",
      "/images/products/decomark/decomark-46.jpg",
      "/images/products/decomark/decomark-47.jpg",
      "/images/products/decomark/decomark-48.jpg",
      "/images/products/decomark/decomark-49.jpg",
      "/images/products/decomark/decomark-50.jpg",
      "/images/products/decomark/decomark-51.jpg",
      "/images/products/decomark/decomark-52.jpg",
      "/images/products/decomark/decomark-53.jpg",
      "/images/products/decomark/decomark-54.jpg",
      "/images/products/decomark/decomark-55.jpg",
      "/images/products/decomark/decomark-56.jpg",
      "/images/products/decomark/decomark-57.jpg",
      "/images/products/decomark/decomark-58.jpg",
      "/images/products/decomark/decomark-59.jpg",
      "/images/products/decomark/decomark-60.jpg",
      "/images/products/decomark/decomark-61.jpg",
      "/images/products/decomark/decomark-62.jpg",
      "/images/products/decomark/decomark-63.jpg",
      "/images/products/decomark/decomark-64.jpg",
      "/images/products/decomark/decomark-65.jpg",
      "/images/products/decomark/decomark-66.jpg",
      "/images/products/decomark/decomark-67.jpg",
      "/images/products/decomark/decomark-68.jpg",
      "/images/products/decomark/decomark-69.jpg",
      "/images/products/decomark/decomark-70.jpg",
      "/images/products/decomark/decomark-71.jpg",
      "/images/products/decomark/decomark-72.jpg",
      "/images/products/decomark/decomark-73.jpg",
      "/images/products/decomark/decomark-74.jpg",
      "/images/products/decomark/decomark-75.jpg",
      "/images/products/decomark/decomark-76.jpg",
      "/images/products/decomark/decomark-77.jpg",
      "/images/products/decomark/decomark-78.jpg",
    ],

    description: "DecoMark is HUB's custom-graphic thermoplastic system, enabling municipalities, artists, and First Nations to bring complex designs — murals, Indigenous art, Pride crosswalks, neighbourhood identity patterns — directly to the street surface. Unlike spray-applied coatings, DecoMark uses precision-manufactured preformed thermoplastic components with full Pantone colour matching, delivering print-quality accuracy at street scale. Used for the BC Children's Hospital labyrinth, the UBC Musqueam cultural crosswalk, and Vancouver's Little Italy Commercial Drive installation. Installed to asphalt or acid-etched concrete by certified HUB applicators.",
    specs: [
      { label: "System",        value: "Precision preformed thermoplastic components" },
      { label: "Colour Range",  value: "Full custom Pantone matching" },
      { label: "Surfaces",      value: "Asphalt and concrete (including precast tiles)" },
      { label: "Design",        value: "Custom artwork — vector files accepted" },
      { label: "Installation",  value: "Certified HUB applicators" },
      { label: "Service Life",  value: "5-year colour warranty" },
      { label: "Min. Order",    value: "Project-based — no standard minimums" },
    ],
    relatedApplications: ["community-branding", "crosswalks", "playgrounds"],
  },
  {
    name: "DuraShield",
    slug: "durashield",
    shortDesc: "Protected surface. Extended life.",
    imageUrl: "/images/products/durashield/durashield-01.jpg",
    gallery: [
      "/images/products/durashield/durashield-01.jpg",
      "/images/products/durashield/durashield-02.jpg",
      "/images/products/durashield/durashield-03.jpg",
      "/images/products/durashield/durashield-04.jpg",
      "/images/products/durashield/durashield-05.jpg",
      "/images/products/durashield/durashield-06.jpg",
      "/images/products/durashield/durashield-07.jpg",
      "/images/products/durashield/durashield-08.jpg",
      "/images/products/durashield/durashield-09.jpg",
      "/images/products/durashield/durashield-10.jpg",
    ],

    description: "DuraShield is HUB's penetrating asphalt rejuvenator and protective seal coat — engineered to restore oxidized, faded, and brittle asphalt surfaces without full removal and replacement. Applied as a two-pass system, DuraShield penetrates the asphalt matrix to restore flexibility and resist further oxidation, then cures to a uniform, professional-grade surface finish. For municipalities and property managers looking to maximize pavement lifecycle and defer costly capital repaving, DuraShield delivers documented 3–5 year lifespan extension at a fraction of replacement cost. Ideal for parking lots, driveways, park paths, and low-volume roadways.",
    specs: [
      { label: "Type",               value: "Penetrating asphalt rejuvenator + seal coat" },
      { label: "Coverage",           value: "100–150 sq ft per gallon" },
      { label: "Penetration Depth",  value: "6–12mm" },
      { label: "Dry Time",           value: "4–8 hours" },
      { label: "Traffic Open",       value: "24 hours" },
      { label: "Lifespan Extension", value: "3–5 years documented" },
    ],
    relatedApplications: ["private-driveways", "parking-lots", "parks-paths"],
  },
  {
    name: "PreMark",
    slug: "premark",
    shortDesc: "Precision-formed. Snowplow-proof.",
    imageUrl: "/images/products/premark/premark-01.jpg",
    gallery: [
      "/images/products/premark/premark-01.jpg",
      "/images/products/premark/premark-02.jpg",
      "/images/products/premark/premark-03.jpg",
      "/images/products/premark/premark-04.jpg",
      "/images/products/premark/premark-05.jpg",
      "/images/products/premark/premark-06.jpg",
      "/images/products/premark/premark-07.jpg",
      "/images/products/premark/premark-08.jpg",
      "/images/products/premark/premark-09.jpg",
      "/images/products/premark/premark-10.jpg",
      "/images/products/premark/premark-11.jpg",
    ],

    description: "PreMark delivers the complete library of TAC and MUTCD-compliant preformed thermoplastic road marking symbols — arrows, turn legends, bike lane icons, accessibility symbols, speed legends, and hundreds of standard traffic control markings. Each symbol is manufactured to precise dimensions with Type III glass bead surface for ASTM D4956 retroreflectivity. Pre-cut and ready to apply, PreMark eliminates stencil setup, reduces crew time on-road, and delivers consistent, professional-quality results that outlast painted symbols by 5:1. Available in 90mil and 125mil thicknesses for standard and heavy-use installations.",
    specs: [
      { label: "Material",          value: "Preformed thermoplastic" },
      { label: "Thickness",         value: "90mil standard / 125mil heavy-use" },
      { label: "Retroreflectivity", value: "ASTM D4956 Type III glass beads" },
      { label: "Standards",         value: "TAC + MUTCD compliant" },
      { label: "Library",           value: "200+ standard symbols + custom" },
      { label: "Installation",      value: "Heat application — no stencil required" },
      { label: "Service Life",      value: "5-year warranty" },
    ],
    relatedApplications: ["crosswalks", "bike-lanes", "bus-lanes", "regulatory-markings"],
  },
  {
    name: "DuraTherm",
    slug: "duratherm",
    shortDesc: "Set into the road. There for life.",
    imageUrl: "/images/products/duratherm/duratherm-01.jpg",
    gallery: [
      "/images/products/duratherm/duratherm-01.jpg",
      "/images/products/duratherm/duratherm-02.jpg",
      "/images/products/duratherm/duratherm-03.jpg",
      "/images/products/duratherm/duratherm-04.jpg",
      "/images/products/duratherm/duratherm-05.jpg",
      "/images/products/duratherm/duratherm-06.jpg",
      "/images/products/duratherm/duratherm-07.jpg",
      "/images/products/duratherm/duratherm-08.jpg",
      "/images/products/duratherm/duratherm-09.jpg",
      "/images/products/duratherm/duratherm-10.jpg",
      "/images/products/duratherm/duratherm-11.jpg",
      "/images/products/duratherm/duratherm-12.jpg",
      "/images/products/duratherm/duratherm-13.jpg",
      "/images/products/duratherm/duratherm-14.jpg",
      "/images/products/duratherm/duratherm-15.jpg",
      "/images/products/duratherm/duratherm-16.jpg",
      "/images/products/duratherm/duratherm-17.jpg",
      "/images/products/duratherm/duratherm-18.jpg",
      "/images/products/duratherm/duratherm-19.jpg",
      "/images/products/duratherm/duratherm-20.jpg",
      "/images/products/duratherm/duratherm-21.jpg",
      "/images/products/duratherm/duratherm-22.jpg",
      "/images/products/duratherm/duratherm-23.jpg",
      "/images/products/duratherm/duratherm-24.jpg",
      "/images/products/duratherm/duratherm-25.jpg",
      "/images/products/duratherm/duratherm-26.jpg",
      "/images/products/duratherm/duratherm-27.jpg",
      "/images/products/duratherm/duratherm-28.jpg",
      "/images/products/duratherm/duratherm-29.jpg",
      "/images/products/duratherm/duratherm-30.jpg",
      "/images/products/duratherm/duratherm-31.jpg",
      "/images/products/duratherm/duratherm-32.jpg",
      "/images/products/duratherm/duratherm-33.jpg",
      "/images/products/duratherm/duratherm-34.jpg",
      "/images/products/duratherm/duratherm-35.jpg",
      "/images/products/duratherm/duratherm-36.jpg",
    ],

    description: "DuraTherm solves the single biggest failure mode of decorative pavement in Canada: snowplow shear. Using a specialized inlay process, DuraTherm is embedded flush with the asphalt surface — zero raised edges, zero profile for plow blades to catch. The result is a fully integrated, permanent installation that survives winter maintenance operations season after season. DuraTherm accepts custom designs and colour patterns, making it the preferred system for high-traffic decorative crosswalks, parking lot waymarking, and community branding applications where conventional thermoplastic overlays cannot survive the plow cycle.",
    specs: [
      { label: "Installation",   value: "Inlaid flush-mount — embedded in asphalt" },
      { label: "Profile",        value: "Zero edge — road surface level" },
      { label: "Snowplow Safe",  value: "Yes — no shear risk" },
      { label: "Bond",           value: "Full-depth asphalt integration" },
      { label: "Designs",        value: "Custom artwork accepted" },
      { label: "Service Life",   value: "7-year performance warranty" },
    ],
    relatedApplications: ["crosswalks", "parking-lots", "community-branding"],
  },
  {
    name: "AirMark",
    slug: "airmark",
    shortDesc: "FAA-grade clarity. Field-proven performance.",
    imageUrl: "/images/products/airmark/airmark-01.jpg",
    gallery: [
      "/images/products/airmark/airmark-01.jpg",
      "/images/products/airmark/airmark-02.jpg",
      "/images/products/airmark/airmark-03.jpg",
      "/images/products/airmark/airmark-04.jpg",
      "/images/products/airmark/airmark-05.jpg",
      "/images/products/airmark/airmark-06.jpg",
      "/images/products/airmark/airmark-07.jpg",
      "/images/products/airmark/airmark-08.jpg",
      "/images/products/airmark/airmark-09.jpg",
      "/images/products/airmark/airmark-10.jpg",
      "/images/products/airmark/airmark-11.jpg",
      "/images/products/airmark/airmark-12.jpg",
      "/images/products/airmark/airmark-13.jpg",
      "/images/products/airmark/airmark-14.jpg",
      "/images/products/airmark/airmark-15.jpg",
      "/images/products/airmark/airmark-16.jpg",
      "/images/products/airmark/airmark-17.jpg",
      "/images/products/airmark/airmark-18.jpg",
      "/images/products/airmark/airmark-19.jpg",
      "/images/products/airmark/airmark-20.jpg",
      "/images/products/airmark/airmark-21.jpg",
      "/images/products/airmark/airmark-22.jpg",
    ],

    description: "AirMark is HUB's precision thermoplastic marking system purpose-built for airfield environments — engineered to meet FAA Advisory Circular AC 150/5370-10 and Transport Canada standards on asphalt and concrete runways, taxiways, and aprons. Type IV glass bead loading delivers the high retroreflectivity required for low-visibility instrument conditions, while the thermoplastic bond holds firm under jet blast, aircraft loads, and deicing fluid exposure. Trusted by commercial airports, regional facilities, and private airstrips across Canada where precision placement and long-term durability are non-negotiable. Installed by certified HUB crews trained in airside safety protocols.",
    specs: [
      { label: "Compliance",        value: "FAA AC 150/5370-10 · TC Canada" },
      { label: "Retroreflectivity", value: "ASTM D4956 Type IV glass beads" },
      { label: "Material",          value: "Preformed thermoplastic" },
      { label: "Surfaces",          value: "Asphalt and concrete runways / taxiways" },
      { label: "Colours",           value: "White, yellow, orange, red (FAA standard)" },
      { label: "Installation",      value: "Heat application — certified airside crew" },
      { label: "Durability",        value: "Jet blast and deicing fluid resistant" },
    ],
    relatedApplications: ["airports"],
  },
];
