// lib/resource-documents.ts
// Flat document array for the Resources page filtering system.
// Generated from lib/documents.ts + lib/products.ts — keep in sync.

export interface ResourceDocument {
  id: string
  title: string
  type: string
  product: string
  productName: string
  subcategory?: string
  applications: string[]
  fileUrl: string
  fileSize: string
  updatedDate: string
  documentType?: string    // 'flyer' | 'catalogue' | 'spec-sheet' | etc. (slug form). Optional so existing entries don't need it.
  featured?: boolean       // Pre-selected for the Featured filter chip
  isNew?: boolean          // Pre-selected for the "New Documents" filter chip (catalogue + 2026 flyers)
  previewImageUrl?: string // Thumbnail for flyer cards (1200px WebP)
}

const productNameMap: Record<string, string> = {
  'streetprint':         'StreetPrint',
  'streetbond':          'StreetBond',
  'streetbond-sr':       'StreetBondSR',
  'traffic-patterns':    'TrafficPatterns',
  'traffic-patterns-xd': 'TrafficPatternsXD',
  'mmax':                'MMAX',
  'decomark':            'DecoMark',
  'durashield':          'DuraShield',
  'premark':             'PreMark',
  'duratherm':           'DuraTherm',
  'airmark':             'AirMark',
  'chipfill':            'ChipFill',
  'aggrefill':           'AggreFill',
  'fast-patch':          'Fast Patch DPR',
}

export function getProductName(slug: string): string {
  return productNameMap[slug] ?? slug
}

// Application slugs normalized to match filter-pill values
const productApplications: Record<string, string[]> = {
  'traffic-patterns':    ['crosswalks', 'bike-bus-lanes', 'parking-lots', 'regulatory-markings'],
  'traffic-patterns-xd': ['crosswalks', 'bike-bus-lanes', 'regulatory-markings'],
  'streetprint':         ['crosswalks', 'driveways', 'public-art', 'community-branding'],
  'streetbond':          ['bike-bus-lanes', 'driveways', 'parks-paths', 'parking-lots'],
  'streetbond-sr':       ['bike-bus-lanes', 'crosswalks', 'driveways', 'parks-paths'],
  'mmax':                ['bike-bus-lanes', 'crosswalks', 'regulatory-markings'],
  'decomark':            ['community-branding', 'public-art', 'crosswalks'],
  'durashield':          ['driveways', 'parking-lots', 'parks-paths'],
  'premark':             ['regulatory-markings', 'crosswalks', 'bike-bus-lanes'],
  'duratherm':           ['crosswalks', 'parking-lots', 'community-branding'],
  'airmark':             ['airports'],
  'chipfill':            ['driveways', 'parking-lots', 'parks-paths'],
  'aggrefill':           ['driveways', 'parking-lots', 'parks-paths'],
  'fast-patch':          ['driveways', 'parking-lots', 'parks-paths'],
}

export const resourceDocuments: ResourceDocument[] = [
  // ── StreetPrint ──────────────────────────────────────────────
  {
    id: 'sp-spec-001',
    title: 'StreetPrint Asphalt Texturing Specification',
    type: 'Spec Sheet',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/StreetPrint-Asphalt-Texturing-Specification.pdf',
    fileSize: '1.2 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sp-colour-001',
    title: 'StreetPrint Colour Guide',
    type: 'Colour Guide',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/streetprint-colour-guide.pdf',
    fileSize: '3.6 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sp-other-001',
    title: 'StreetPrint Template Catalog',
    type: 'Other',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/streetprint-template-catalog.pdf',
    fileSize: '5.1 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sp-other-002',
    title: 'StreetPrint FAQ',
    type: 'Other',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/streetprint-faq.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Jan 2024',
  },

  // ── StreetBond — Main ─────────────────────────────────────────
  {
    id: 'sb-brochure-001',
    title: 'StreetBond Brochure',
    type: 'Brochure',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond/StreetBond-Brochure.pdf',
    fileSize: '4.2 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-colour-001',
    title: 'StreetBond Colour Card — 2026 Edition',
    type: 'Colour Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond/StreetBond-Colour-Card-2026.pdf',
    fileSize: '0.3 MB',
    updatedDate: 'Aug 2026',
  },
  {
    id: 'sb-guide-001',
    title: 'StreetBond Substrate Guide',
    type: 'Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond/StreetBond_Substrate_Guide.pdf',
    fileSize: '1.4 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sb-data-008',
    title: 'StreetBond Colorant Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond/StreetBond-Colorant.pdf',
    fileSize: '0.6 MB',
    updatedDate: 'Feb 2026',
  },

  // ── StreetBond — SB120 ────────────────────────────────────────
  {
    id: 'sb-spec-001',
    title: 'StreetBond SB120 Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'SB120',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20120/StreetBond_SB120_Specifications.pdf',
    fileSize: '1.1 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sb-data-001',
    title: 'StreetBond SB120 Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'SB120',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20120/StreetBond-SB120-Data-Sheet-12.22-Rev.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-spec-004',
    title: 'StreetBond SB120 Over Concrete Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'SB120',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20120/StreetBond-SB120-Over-Concrete-Specification.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Mar 2023',
  },

  // ── StreetBond — SB150 ────────────────────────────────────────
  {
    id: 'sb-spec-002',
    title: 'StreetBond SB150 Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'SB150',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20150/StreetBond_SB150_Specifications.pdf',
    fileSize: '1.1 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sb-data-002',
    title: 'StreetBond SB150 Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'SB150',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20150/StreetBond-SB150-Data-Sheet-12.22-Rev.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-data-003',
    title: 'StreetBond SB150 AL Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'SB150',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20150/StreetBond-SB150AL-Data-Sheet-12.22-Rev.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-spec-003',
    title: 'StreetBond SB150 Over Concrete Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'SB150',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20150/StreetBond-SB150-Over-Concrete-Specification.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Jan 2024',
  },

  // ── StreetBond — Concrete Primer ──────────────────────────────
  {
    id: 'sb-data-004',
    title: 'StreetBond Concrete Primer WB Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Concrete Primer',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Concrete%20Primer/StreetBond-Concrete-Primer-WB-TDS.pdf',
    fileSize: '0.7 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-data-005',
    title: 'StreetBond Concrete Primer QS Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Concrete Primer',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Concrete%20Primer/StreetBond-QS-Concrete-TDS.pdf',
    fileSize: '0.7 MB',
    updatedDate: 'Feb 2024',
  },

  // ── StreetBond — Pro 220 [MMA] ────────────────────────────────
  {
    id: 'sb-install-001',
    title: 'StreetBond Pro 220 & 250 MMA Installation Guide',
    type: 'Installation Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Pro 220',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Pro%20220%20%5BMMA%5D/StreetBond-Pro-220-and-250-Intallation.pdf',
    fileSize: '2.1 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-brochure-002',
    title: 'StreetBond Pro 220 & 250 MMA Brochure',
    type: 'Brochure',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Pro 220',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Pro%20220%20%5BMMA%5D/StreetBond-Pro-220-Pro-250-Brochure-1.pdf',
    fileSize: '3.4 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-data-006',
    title: 'StreetBond Pro 220 MMA Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Pro 220',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Pro%20220%20%5BMMA%5D/StreetBond-Pro-220-TDS.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Mar 2024',
  },

  // ── StreetBond — Pro 250 [MMA] ────────────────────────────────
  {
    id: 'sb-install-002',
    title: 'StreetBond Pro 250 MMA Installation Guide',
    type: 'Installation Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Pro 250',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Pro%20250%20%5BMMA%5D/Installation_StreetBond-Pro-220-and-250.pdf',
    fileSize: '2.3 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-brochure-003',
    title: 'StreetBond Pro 220 & 250 MMA Brochure',
    type: 'Brochure',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Pro 250',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Pro%20250%20%5BMMA%5D/StreetBond-Pro-220-Pro-250-Brochure.pdf',
    fileSize: '3.5 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-data-007',
    title: 'StreetBond Pro 250 MMA Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    subcategory: 'Pro 250',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/StreetBond/StreetBond%20Pro%20250%20%5BMMA%5D/Data-Sheet-StreetBond-Pro-250.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Mar 2024',
  },

  // ── StreetBondSR (own product entry) ──────────────────────────
  {
    id: 'sbsr-brochure-001',
    title: 'StreetBondSR Brochure',
    type: 'Brochure',
    product: 'streetbond-sr',
    productName: 'StreetBondSR',
    applications: productApplications['streetbond-sr'],
    fileUrl: '/docs/StreetBondSR/StreetBondSR-Brochure.pdf',
    fileSize: '3.2 MB',
    updatedDate: 'Mar 2023',
  },
  {
    id: 'sbsr-spec-001',
    title: 'StreetBondSR Flat Surface Specification',
    type: 'Spec Sheet',
    product: 'streetbond-sr',
    productName: 'StreetBondSR',
    applications: productApplications['streetbond-sr'],
    fileUrl: '/docs/StreetBondSR/StreetBond-SR-Flat-Surface-Specification.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Mar 2023',
  },
  {
    id: 'sbsr-cert-001',
    title: 'StreetBondSR Certificate of Analysis — Friction',
    type: 'Certificate',
    product: 'streetbond-sr',
    productName: 'StreetBondSR',
    applications: productApplications['streetbond-sr'],
    fileUrl: '/docs/StreetBondSR/StreetBond-SR-Certificate-of-Analysis-Friction.pdf',
    fileSize: '0.4 MB',
    updatedDate: 'Mar 2023',
  },
  {
    id: 'sbsr-colour-001',
    title: 'StreetBondSR Colour Guide',
    type: 'Colour Guide',
    product: 'streetbond-sr',
    productName: 'StreetBondSR',
    applications: productApplications['streetbond-sr'],
    fileUrl: '/docs/StreetBondSR/StreetBondSR-Colour-Guide-2026.pdf',
    fileSize: '0.6 MB',
    updatedDate: 'Aug 2026',
  },

  // ── TrafficPatterns ──────────────────────────────────────────
  {
    id: 'tp-spec-ts001',
    title: 'TrafficPatterns Technical Specification (TS001)',
    type: 'Spec Sheet',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/TrafficPatterns/TS001_TrafficPatterns_220204.pdf',
    fileSize: '1.5 MB',
    updatedDate: 'Feb 2022',
  },
  {
    id: 'tp-design-001',
    title: 'TrafficPatterns Design Manual',
    type: 'Design Manual',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/TrafficPatterns/TrafficPatterns-Design-Manual.pdf',
    fileSize: '6.2 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tp-guide-001',
    title: 'TrafficPatterns Custom Design Guidelines',
    type: 'Guide',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/TrafficPatterns/TrafficPatterns-Custom-Design-Guidelines.pdf',
    fileSize: '1.6 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tp-spec-001',
    title: 'TrafficPatterns 125 with SA Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/TrafficPatterns/TrafficPatterns-125-with-SA-Specification.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tp-spec-002',
    title: 'TrafficPatterns Solid Sheets 125 Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/TrafficPatterns/TrafficPatterns-Solid-Sheets-125-Specification.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tp-spec-003',
    title: 'TrafficPatterns Two Component Sealer Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/TrafficPatterns/TrafficPatterns-Specification-Two-Component-Sealer.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tp-colour-001',
    title: 'TrafficPatterns Colour Guidelines',
    type: 'Colour Guide',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/TrafficPatterns/TrafficPatterns-Colour-Guidelines.pdf',
    fileSize: '3.2 MB',
    updatedDate: 'Mar 2024',
  },

  // ── TrafficPatternsXD ────────────────────────────────────────
  {
    id: 'tpxd-spec-ts002',
    title: 'TrafficPatternsXD Technical Specification (TS002)',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TS002_TrafficPatternsXD_220204.pdf',
    fileSize: '1.5 MB',
    updatedDate: 'Feb 2022',
  },
  {
    id: 'tpxd-design-001',
    title: 'TrafficPatternsXD Design Manual',
    type: 'Design Manual',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TrafficPatternsXD-Design-Manual.pdf',
    fileSize: '5.8 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tpxd-spec-001',
    title: 'TrafficPatternsXD Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TrafficPatternsXD-Specification.pdf',
    fileSize: '1.2 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tpxd-spec-branded',
    title: 'TrafficPatternsXD Specification — Branded',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TrafficPatternsXD-Specification-Branded.pdf',
    fileSize: '1.3 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tpxd-spec-002',
    title: 'TrafficPatternsXD Specification (FR)',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TrafficPatternsXD-Specification-FR.pdf',
    fileSize: '1.2 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tpxd-spec-003',
    title: 'TrafficPatternsXD Two Component Sealer Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TrafficPatternsXD-Two-Component-Sealer.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tpxd-colour-001',
    title: 'TrafficPatternsXD Colour Guide',
    type: 'Colour Guide',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TrafficPatternsXD-Colour-Guide.pdf',
    fileSize: '3.4 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'tpxd-other-001',
    title: 'TrafficPatternsXD Cross Section Detail',
    type: 'Other',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/TrafficPatternsXD/TrafficPatternsXD-CrossSection-Detail.pdf',
    fileSize: '0.6 MB',
    updatedDate: 'Jan 2024',
  },

  // ── MMAX ─────────────────────────────────────────────────────
  {
    id: 'mx-brochure-001',
    title: 'MMAX Next-Gen Brochure',
    type: 'Brochure',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/MMAX/MMAX-Next-Gen-Brochure_06_09_23-1.pdf',
    fileSize: '3.9 MB',
    updatedDate: 'Jun 2023',
  },
  {
    id: 'mx-install-001',
    title: 'MMAX Corundum Area Markings Application Instructions',
    type: 'Installation Guide',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/MMAX/Application_Instructions_MMAX_Corundum_Area_Markings.pdf',
    fileSize: '1.8 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'mx-data-001',
    title: 'MMAX Product Data Sheet',
    type: 'Data Sheet',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/MMAX/MMAX-Product-Data.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'mx-guide-001',
    title: 'MMAX Extended Season Corundum Product Data Sheet',
    type: 'Data Sheet',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/MMAX/Extended-Season-MMAX-Corundum-PDS-070723.pdf',
    fileSize: '1.3 MB',
    updatedDate: 'Jul 2023',
  },
  {
    id: 'mx-data-002',
    title: 'MMAX Extended Season Product Data Sheet',
    type: 'Data Sheet',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/MMAX/Extended-Season-MMAX-product-data-sheet.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Mar 2024',
  },

  // ── DecoMark ─────────────────────────────────────────────────
  {
    id: 'dm-spec-ts004',
    title: 'DecoMark Technical Specification (TS004)',
    type: 'Spec Sheet',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/TS004_DecoMark_220204.pdf',
    fileSize: '1.4 MB',
    updatedDate: 'Feb 2022',
  },
  {
    id: 'dm-install-001',
    title: 'DecoMark Application Instructions',
    type: 'Installation Guide',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-application-instructions.pdf',
    fileSize: '1.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dm-guide-001',
    title: 'DecoMark Custom Design Guidelines',
    type: 'Guide',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-custom-design-guidelines.pdf',
    fileSize: '1.5 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dm-spec-001',
    title: 'DecoMark Specification',
    type: 'Spec Sheet',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/DecoMark-Specification.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'dm-colour-001',
    title: 'DecoMark Colour Guide',
    type: 'Colour Guide',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-colour-guide.pdf',
    fileSize: '3.3 MB',
    updatedDate: 'Mar 2024',
  },

  // ── DuraShield ───────────────────────────────────────────────
  {
    id: 'ds-data-001',
    title: 'DuraShield Color Asphalt Technical Data Sheet',
    type: 'Data Sheet',
    product: 'durashield',
    productName: 'DuraShield',
    applications: productApplications['durashield'],
    fileUrl: '/docs/DuraShield/DuraShield-Pavement-Coating-Part-A-B-Color-Asphalt-TDS.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'ds-data-002',
    title: 'DuraShield Color Solar Gray Technical Data Sheet',
    type: 'Data Sheet',
    product: 'durashield',
    productName: 'DuraShield',
    applications: productApplications['durashield'],
    fileUrl: '/docs/DuraShield/DuraShield-Pavement-Coating-Part-A-B-Color-Solar-Gray-TDS.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Jan 2024',
  },

  // ── PreMark ──────────────────────────────────────────────────
  {
    id: 'pm-spec-ts005',
    title: 'PreMark Technical Specification (TS005)',
    type: 'Spec Sheet',
    product: 'premark',
    productName: 'PreMark',
    applications: productApplications['premark'],
    fileUrl: '/docs/PreMark/TS005_PreMark_220204.pdf',
    fileSize: '1.3 MB',
    updatedDate: 'Feb 2022',
  },
  {
    id: 'pm-brochure-002',
    title: 'PreMarkXF Brochure',
    type: 'Brochure',
    product: 'premark',
    productName: 'PreMark',
    applications: productApplications['premark'],
    fileUrl: '/docs/PreMark/PreMarkXF-Brochure.pdf',
    fileSize: '3.9 MB',
    updatedDate: 'Feb 2024',
  },

  // ── DuraTherm ────────────────────────────────────────────────
  {
    id: 'dt-spec-ts003',
    title: 'DuraTherm Technical Specification (TS003)',
    type: 'Spec Sheet',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/TS003_DuraTherm_220204.pdf',
    fileSize: '1.4 MB',
    updatedDate: 'Feb 2022',
  },
  {
    id: 'dt-design-001',
    title: 'DuraTherm Design Manual',
    type: 'Design Manual',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-design-manual.pdf',
    fileSize: '5.4 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dt-spec-001',
    title: 'DuraTherm Specification — Branded',
    type: 'Spec Sheet',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/DuraTherm-Specification-Branded.pdf',
    fileSize: '1.1 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'dt-guide-001',
    title: 'DuraTherm Custom Design Guidelines',
    type: 'Guide',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-custom-design-guidelines.pdf',
    fileSize: '1.5 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dt-colour-001',
    title: 'DuraTherm Colour Guide',
    type: 'Colour Guide',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-colour-guide.pdf',
    fileSize: '3.1 MB',
    updatedDate: 'Mar 2024',
  },

  // ── AirMark ──────────────────────────────────────────────────
  {
    id: 'am-brochure-001',
    title: 'AirMark Brochure (EN)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/AirMark/AirMark/AirMark_Brocure.pdf',
    fileSize: '4.3 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'am-brochure-002',
    title: 'AirMark Brochure (FR)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/AirMark/AirMark/AirMark-Brocure-FR.pdf',
    fileSize: '4.3 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'am-brochure-003',
    title: 'AirMark TrafficPaint for Airfields (EN)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/AirMark/Airfield%20Paint/TrafficPaint-for-Airfields.pdf',
    fileSize: '3.6 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'am-brochure-004',
    title: 'AirMark TrafficPaint for Airfields (FR)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/AirMark/Airfield%20Paint/TrafficPaint-for-Airfields-FR.pdf',
    fileSize: '3.6 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'am-data-001',
    title: 'AirMark WB Airfield Product Data Sheet',
    type: 'Data Sheet',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/AirMark/Airfield%20Paint/WB-Airfield-Product-Data.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'am-brochure-005',
    title: 'AirMark PreMark — Groundside Airports',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/AirMark/PreMark%20-%20Groundside/PreMark-for-Airports.pdf',
    fileSize: '3.8 MB',
    updatedDate: 'Feb 2024',
  },

  // ── 2026 Catalogue (flipbook viewer, not a downloadable PDF) ──
  {
    id: 'catalogue-2026',
    title: 'HUB Surface Systems Catalogue 2026',
    type: 'Catalogue',
    product: 'all',
    productName: 'Full Line',
    applications: [],
    fileUrl: '/catalogue',
    fileSize: '140 pages',
    updatedDate: 'June 2026',
    documentType: 'catalogue',
    featured: true,
    isNew: true,
    // Version-agnostic cover (written by build_flipbook.py) — never goes
    // stale on a flipbook version bump, unlike the old hardcoded /vNN/ path.
    previewImageUrl: '/catalogue/cover.webp',
  },

  // ── 2026 Product Flyers (14, one per product) ─────────────────
  {
    id: 'flyer-traffic-patterns-xd',
    title: 'TrafficPatternsXD — 2026 Product Flyer',
    type: 'Flyer',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-traffic-patterns-xd-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: true,
    previewImageUrl: '/resources/flyers/traffic-patterns-xd-preview.webp',
  },
  {
    id: 'flyer-traffic-patterns',
    title: 'TrafficPatterns — 2026 Product Flyer',
    type: 'Flyer',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-traffic-patterns-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/traffic-patterns-preview.webp',
  },
  {
    id: 'flyer-streetbond',
    title: 'StreetBond — 2026 Product Flyer',
    type: 'Flyer',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-streetbond-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: true,
    previewImageUrl: '/resources/flyers/streetbond-preview.webp',
  },
  {
    id: 'flyer-streetprint',
    title: 'StreetPrint — 2026 Product Flyer',
    type: 'Flyer',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-streetprint-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: true,
    previewImageUrl: '/resources/flyers/streetprint-preview.webp',
  },
  {
    id: 'flyer-decomark',
    title: 'DecoMark — 2026 Product Flyer',
    type: 'Flyer',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-decomark-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/decomark-preview.webp',
  },
  {
    id: 'flyer-mmax',
    title: 'MMAX — 2026 Product Flyer',
    type: 'Flyer',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-mmax-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/mmax-preview.webp',
  },
  {
    id: 'flyer-streetbond-sr',
    title: 'StreetBondSR — 2026 Product Flyer',
    type: 'Flyer',
    product: 'streetbond-sr',
    productName: 'StreetBondSR',
    applications: productApplications['streetbond-sr'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-streetbondsr-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: true,
    previewImageUrl: '/resources/flyers/streetbondsr-preview.webp',
  },
  {
    id: 'flyer-duratherm',
    title: 'DuraTherm — 2026 Product Flyer',
    type: 'Flyer',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-duratherm-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: true,
    previewImageUrl: '/resources/flyers/duratherm-preview.webp',
  },
  {
    id: 'flyer-durashield',
    title: 'DuraShield — 2026 Product Flyer',
    type: 'Flyer',
    product: 'durashield',
    productName: 'DuraShield',
    applications: productApplications['durashield'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-durashield-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/durashield-preview.webp',
  },
  {
    id: 'flyer-airmark',
    title: 'AirMark — 2026 Product Flyer',
    type: 'Flyer',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-airmark-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/airmark-preview.webp',
  },
  {
    id: 'flyer-premark',
    title: 'PreMark — 2026 Product Flyer',
    type: 'Flyer',
    product: 'premark',
    productName: 'PreMark',
    applications: productApplications['premark'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-premark-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/premark-preview.webp',
  },
  {
    id: 'flyer-chipfill',
    title: 'ChipFill — 2026 Product Flyer',
    type: 'Flyer',
    product: 'chipfill',
    productName: 'ChipFill',
    applications: productApplications['chipfill'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-chipfill-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/chipfill-preview.webp',
  },
  {
    id: 'flyer-aggrefill',
    title: 'AggreFill — 2026 Product Flyer',
    type: 'Flyer',
    product: 'aggrefill',
    productName: 'AggreFill',
    applications: productApplications['aggrefill'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-aggrefill-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/aggrefill-preview.webp',
  },
  {
    id: 'flyer-fast-patch',
    title: 'Fast Patch DPR — 2026 Product Flyer',
    type: 'Flyer',
    product: 'fast-patch',
    productName: 'Fast Patch DPR',
    applications: productApplications['fast-patch'],
    fileUrl: '/resources/flyers/HUBSS-Flyer-fast-patch-v01.pdf',
    fileSize: '~1.5 MB',
    updatedDate: 'May 2026',
    documentType: 'flyer',
    isNew: true,
    featured: false,
    previewImageUrl: '/resources/flyers/fast-patch-preview.webp',
  },
]


/**
 * Stale-record overrides for the Resources library.
 *
 * The Resources page prefers the Sanity-managed document list, seeded in
 * Feb 2024. When a document is superseded before the Studio record catches
 * up, correct it here — applied on top of whichever source wins, so code,
 * Sanity, and bookmarked URLs all agree.
 *
 * Delete an entry once its Sanity record has been updated in the Studio.
 */
const DOC_OVERRIDES: Record<string, Partial<ResourceDocument>> = {
  // Superseded Aug 2026 by the GAF 2026 colour card (HUB co-branded edition).
  'sb-colour-001': {
    title: 'StreetBond Colour Card — 2026 Edition',
    fileUrl: '/docs/StreetBond/StreetBond/StreetBond-Colour-Card-2026.pdf',
    fileSize: '0.2 MB',
    updatedDate: 'Aug 2026',
  },
  // The old SR guide's back page was GAF-only — Parsippany NJ address and a US
  // customer-service number, no Canadian contacts. Replaced Aug 2026 with an
  // edition carrying the HUB block. The 308 in next.config.ts already catches
  // the old URL; this stops /resources rendering a link that needs redirecting
  // in the first place, until the Sanity record is updated in Studio.
  'sbsr-colour-001': {
    fileUrl: '/docs/StreetBondSR/StreetBondSR-Colour-Guide-2026.pdf',
    fileSize: '0.6 MB',
    updatedDate: 'Aug 2026',
  },
}

export function applyDocOverrides<T extends { id: string }>(docs: T[]): T[] {
  return docs.map((d) => (DOC_OVERRIDES[d.id] ? { ...d, ...DOC_OVERRIDES[d.id] } : d))
}
