// lib/resource-documents.ts
// Flat document array for the Resources page filtering system.
// Generated from lib/documents.ts + lib/products.ts — keep in sync.

export interface ResourceDocument {
  id: string
  title: string
  type: string
  product: string
  productName: string
  applications: string[]
  fileUrl: string
  fileSize: string
  updatedDate: string
}

const productNameMap: Record<string, string> = {
  'streetprint':         'StreetPrint',
  'streetbond':          'StreetBond',
  'traffic-patterns':    'TrafficPatterns',
  'traffic-patterns-xd': 'TrafficPatternsXD',
  'mmax':                'MMAX',
  'decomark':            'DecoMark',
  'durashield':          'DuraShield',
  'premark':             'PreMark',
  'duratherm':           'DuraTherm',
  'airmark':             'AirMark',
}

export function getProductName(slug: string): string {
  return productNameMap[slug] ?? slug
}

// Application slugs normalized to match filter-pill values
// (products.ts uses "bus-bike-lanes" → filter pills use "bike-bus-lanes")
const productApplications: Record<string, string[]> = {
  'traffic-patterns':    ['crosswalks', 'bike-bus-lanes', 'parking-lots', 'regulatory-markings'],
  'traffic-patterns-xd': ['crosswalks', 'bike-bus-lanes', 'regulatory-markings'],
  'streetprint':         ['crosswalks', 'driveways', 'public-art', 'community-branding'],
  'streetbond':          ['bike-bus-lanes', 'driveways', 'parks-paths', 'parking-lots'],
  'mmax':                ['bike-bus-lanes', 'crosswalks', 'regulatory-markings'],
  'decomark':            ['community-branding', 'public-art', 'crosswalks'],
  'durashield':          ['driveways', 'parking-lots', 'parks-paths'],
  'premark':             ['regulatory-markings', 'crosswalks', 'bike-bus-lanes'],
  'duratherm':           ['crosswalks', 'parking-lots', 'community-branding'],
  'airmark':             ['airports'],
}

export const resourceDocuments: ResourceDocument[] = [
  // ── StreetPrint ──────────────────────────────────────────────
  {
    id: 'sp-spec-001',
    title: 'StreetPrint Specification Sheet',
    type: 'Spec Sheet',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/streetprint-spec.pdf',
    fileSize: '1.2 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sp-colour-001',
    title: 'StreetPrint Colour Guide',
    type: 'Colour Guide',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/streetprint-colour-guide.pdf',
    fileSize: '3.6 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sp-other-001',
    title: 'StreetPrint Template Catalog',
    type: 'Other',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/streetprint-template-catalog.pdf',
    fileSize: '5.1 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sp-other-002',
    title: 'StreetPrint FAQ',
    type: 'Other',
    product: 'streetprint',
    productName: 'StreetPrint',
    applications: productApplications['streetprint'],
    fileUrl: '/docs/streetprint/streetprint-faq.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Jan 2024',
  },

  // ── StreetBond ───────────────────────────────────────────────
  {
    id: 'sb-brochure-001',
    title: 'StreetBond Brochure',
    type: 'Brochure',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-brochure.pdf',
    fileSize: '4.2 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-colour-001',
    title: 'StreetBond Colour Guide',
    type: 'Colour Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-colour-guide.pdf',
    fileSize: '3.8 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-guide-001',
    title: 'StreetBond Substrate Guide',
    type: 'Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-substrate-guide.pdf',
    fileSize: '1.4 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sb-spec-001',
    title: 'StreetBond SB120 Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-sb120-spec.pdf',
    fileSize: '1.1 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sb-spec-002',
    title: 'StreetBond SB150 Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-sb150-spec.pdf',
    fileSize: '1.1 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sb-data-001',
    title: 'StreetBond SB120 Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-sb120-tds.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-data-002',
    title: 'StreetBond SB150 Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-sb150-tds.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-data-003',
    title: 'StreetBond SB150 AL Technical Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-sb150-al-tds.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-spec-003',
    title: 'StreetBond Concrete Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-concrete-spec.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'sb-data-004',
    title: 'StreetBond Concrete Primer WB Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-concrete-primer-wb-tds.pdf',
    fileSize: '0.7 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-data-005',
    title: 'StreetBond Concrete Primer QS Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-concrete-primer-qs-tds.pdf',
    fileSize: '0.7 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'sb-install-001',
    title: 'StreetBond Pro 220 MMA Installation Guide',
    type: 'Installation Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-pro220-install-guide.pdf',
    fileSize: '2.1 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-brochure-002',
    title: 'StreetBond Pro 220 MMA Brochure',
    type: 'Brochure',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-pro220-brochure.pdf',
    fileSize: '3.4 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-data-006',
    title: 'StreetBond Pro 220 MMA Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-pro220-tds.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-install-002',
    title: 'StreetBond Pro 250 MMA Installation Guide',
    type: 'Installation Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-pro250-install-guide.pdf',
    fileSize: '2.3 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-brochure-003',
    title: 'StreetBond Pro 250 MMA Brochure',
    type: 'Brochure',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-pro250-brochure.pdf',
    fileSize: '3.5 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'sb-data-007',
    title: 'StreetBond Pro 250 MMA Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-pro250-tds.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Mar 2024',
  },

  // ── StreetBond — additional docs from live site ─────────────
  {
    id: 'sb-data-008',
    title: 'StreetBond Colorant Data Sheet',
    type: 'Data Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-colorant.pdf',
    fileSize: '0.6 MB',
    updatedDate: 'Feb 2026',
  },
  {
    id: 'sb-spec-004',
    title: 'StreetBond SB120 Over Concrete Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbond-sb120-concrete-spec.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Mar 2023',
  },

  // ── StreetBondSR ───────────────────────────────────────────
  {
    id: 'sbsr-brochure-001',
    title: 'StreetBondSR Brochure',
    type: 'Brochure',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbondsr-brochure.pdf',
    fileSize: '3.2 MB',
    updatedDate: 'Mar 2023',
  },
  {
    id: 'sbsr-spec-001',
    title: 'StreetBondSR Flat Surface Specification',
    type: 'Spec Sheet',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbondsr-flat-surface-spec.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Mar 2023',
  },
  {
    id: 'sbsr-cert-001',
    title: 'StreetBondSR Certificate of Analysis — Friction',
    type: 'Certificate',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbondsr-certificate-friction.pdf',
    fileSize: '0.4 MB',
    updatedDate: 'Mar 2023',
  },
  {
    id: 'sbsr-colour-001',
    title: 'StreetBondSR Colour Guide',
    type: 'Colour Guide',
    product: 'streetbond',
    productName: 'StreetBond',
    applications: productApplications['streetbond'],
    fileUrl: '/docs/streetbond/streetbondsr-colour-guide.pdf',
    fileSize: '2.8 MB',
    updatedDate: 'Mar 2023',
  },

  // ── TrafficPatterns ──────────────────────────────────────────
  {
    id: 'tp-brochure-001',
    title: 'TrafficPatterns Brochure',
    type: 'Brochure',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/traffic-patterns/traffic-patterns-brochure.pdf',
    fileSize: '4.8 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tp-design-001',
    title: 'TrafficPatterns Design Manual',
    type: 'Design Manual',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/traffic-patterns/traffic-patterns-design-manual.pdf',
    fileSize: '6.2 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tp-guide-001',
    title: 'TrafficPatterns Custom Design Guidelines',
    type: 'Guide',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/traffic-patterns/traffic-patterns-custom-design-guidelines.pdf',
    fileSize: '1.6 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tp-spec-001',
    title: 'TrafficPatterns 125 with SA Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/traffic-patterns/traffic-patterns-125-sa-spec.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tp-spec-002',
    title: 'TrafficPatterns Solid Sheets 125 Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/traffic-patterns/traffic-patterns-solid-sheets-125-spec.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tp-spec-003',
    title: 'TrafficPatterns Two Component Sealer Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/traffic-patterns/traffic-patterns-two-component-sealer-spec.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tp-colour-001',
    title: 'TrafficPatterns Colour Guide',
    type: 'Colour Guide',
    product: 'traffic-patterns',
    productName: 'TrafficPatterns',
    applications: productApplications['traffic-patterns'],
    fileUrl: '/docs/traffic-patterns/traffic-patterns-colour-guide.pdf',
    fileSize: '3.2 MB',
    updatedDate: 'Mar 2024',
  },

  // ── TrafficPatternsXD ────────────────────────────────────────
  {
    id: 'tpxd-brochure-001',
    title: 'TrafficPatternsXD Brochure',
    type: 'Brochure',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/traffic-patterns-xd/traffic-patterns-xd-brochure.pdf',
    fileSize: '4.5 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tpxd-design-001',
    title: 'TrafficPatternsXD Design Manual',
    type: 'Design Manual',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/traffic-patterns-xd/traffic-patterns-xd-design-manual.pdf',
    fileSize: '5.8 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tpxd-spec-001',
    title: 'TrafficPatternsXD Specification (EN)',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/traffic-patterns-xd/traffic-patterns-xd-spec-en.pdf',
    fileSize: '1.2 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tpxd-spec-002',
    title: 'TrafficPatternsXD Specification (FR)',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/traffic-patterns-xd/traffic-patterns-xd-spec-fr.pdf',
    fileSize: '1.2 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'tpxd-spec-003',
    title: 'TrafficPatternsXD Two Component Sealer Specification',
    type: 'Spec Sheet',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/traffic-patterns-xd/traffic-patterns-xd-two-component-sealer-spec.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'tpxd-colour-001',
    title: 'TrafficPatternsXD Colour Guide',
    type: 'Colour Guide',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/traffic-patterns-xd/traffic-patterns-xd-colour-guide.pdf',
    fileSize: '3.4 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'tpxd-other-001',
    title: 'TrafficPatternsXD Cross Section Detail',
    type: 'Other',
    product: 'traffic-patterns-xd',
    productName: 'TrafficPatternsXD',
    applications: productApplications['traffic-patterns-xd'],
    fileUrl: '/docs/traffic-patterns-xd/traffic-patterns-xd-cross-section-detail.pdf',
    fileSize: '0.6 MB',
    updatedDate: 'Jan 2024',
  },

  // ── MMAX ─────────────────────────────────────────────────────
  {
    id: 'mx-brochure-001',
    title: 'MMAX Brochure',
    type: 'Brochure',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/mmax/mmax-brochure.pdf',
    fileSize: '3.9 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'mx-install-001',
    title: 'MMAX Application Instructions',
    type: 'Installation Guide',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/mmax/mmax-application-instructions.pdf',
    fileSize: '1.8 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'mx-data-001',
    title: 'MMAX Product Data Sheet',
    type: 'Data Sheet',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/mmax/mmax-product-data-sheet.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'mx-guide-001',
    title: 'MMAX Extended Season Corundum Guide',
    type: 'Guide',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/mmax/mmax-extended-season-corundum-guide.pdf',
    fileSize: '1.3 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'mx-data-002',
    title: 'MMAX Extended Season Product Data Sheet',
    type: 'Data Sheet',
    product: 'mmax',
    productName: 'MMAX',
    applications: productApplications['mmax'],
    fileUrl: '/docs/mmax/mmax-extended-season-pds.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Mar 2024',
  },

  // ── DecoMark ─────────────────────────────────────────────────
  {
    id: 'dm-brochure-001',
    title: 'DecoMark Brochure',
    type: 'Brochure',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-brochure.pdf',
    fileSize: '4.1 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'dm-install-001',
    title: 'DecoMark Application Instructions',
    type: 'Installation Guide',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-application-instructions.pdf',
    fileSize: '1.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dm-guide-001',
    title: 'DecoMark Custom Design Guidelines',
    type: 'Guide',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-custom-design-guidelines.pdf',
    fileSize: '1.5 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dm-spec-001',
    title: 'DecoMark Specification',
    type: 'Spec Sheet',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-spec.pdf',
    fileSize: '1.0 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'dm-colour-001',
    title: 'DecoMark Colour Guide',
    type: 'Colour Guide',
    product: 'decomark',
    productName: 'DecoMark',
    applications: productApplications['decomark'],
    fileUrl: '/docs/decomark/decomark-colour-guide.pdf',
    fileSize: '3.3 MB',
    updatedDate: 'Mar 2024',
  },

  // ── DuraShield ───────────────────────────────────────────────
  {
    id: 'ds-data-001',
    title: 'DuraShield Color Asphalt Technical Data Sheet',
    type: 'Data Sheet',
    product: 'durashield',
    productName: 'DuraShield',
    applications: productApplications['durashield'],
    fileUrl: '/docs/durashield/durashield-color-asphalt-tds.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'ds-data-002',
    title: 'DuraShield Color Solar Gray Technical Data Sheet',
    type: 'Data Sheet',
    product: 'durashield',
    productName: 'DuraShield',
    applications: productApplications['durashield'],
    fileUrl: '/docs/durashield/durashield-color-solar-gray-tds.pdf',
    fileSize: '0.8 MB',
    updatedDate: 'Jan 2024',
  },

  // ── PreMark ──────────────────────────────────────────────────
  {
    id: 'pm-brochure-001',
    title: 'PreMark Brochure',
    type: 'Brochure',
    product: 'premark',
    productName: 'PreMark',
    applications: productApplications['premark'],
    fileUrl: '/docs/premark/premark-brochure.pdf',
    fileSize: '3.7 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'pm-brochure-002',
    title: 'PreMarkXF Brochure',
    type: 'Brochure',
    product: 'premark',
    productName: 'PreMark',
    applications: productApplications['premark'],
    fileUrl: '/docs/premark/premark-xf-brochure.pdf',
    fileSize: '3.9 MB',
    updatedDate: 'Feb 2024',
  },

  // ── DuraTherm ────────────────────────────────────────────────
  {
    id: 'dt-brochure-001',
    title: 'DuraTherm Brochure',
    type: 'Brochure',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-brochure.pdf',
    fileSize: '4.0 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'dt-design-001',
    title: 'DuraTherm Design Manual',
    type: 'Design Manual',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-design-manual.pdf',
    fileSize: '5.4 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dt-guide-001',
    title: 'DuraTherm Custom Design Guidelines',
    type: 'Guide',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-custom-design-guidelines.pdf',
    fileSize: '1.5 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'dt-spec-001',
    title: 'DuraTherm Specification',
    type: 'Spec Sheet',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-spec.pdf',
    fileSize: '1.1 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'dt-colour-001',
    title: 'DuraTherm Colour Guide',
    type: 'Colour Guide',
    product: 'duratherm',
    productName: 'DuraTherm',
    applications: productApplications['duratherm'],
    fileUrl: '/docs/duratherm/duratherm-colour-guide.pdf',
    fileSize: '3.1 MB',
    updatedDate: 'Mar 2024',
  },

  // ── AirMark ──────────────────────────────────────────────────
  {
    id: 'am-brochure-001',
    title: 'AirMark Brochure (EN)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/airmark/airmark-brochure-en.pdf',
    fileSize: '4.3 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'am-brochure-002',
    title: 'AirMark Brochure (FR)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/airmark/airmark-brochure-fr.pdf',
    fileSize: '4.3 MB',
    updatedDate: 'Feb 2024',
  },
  {
    id: 'am-brochure-003',
    title: 'AirMark TrafficPaint Brochure (EN)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/airmark/airmark-trafficpaint-brochure-en.pdf',
    fileSize: '3.6 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'am-brochure-004',
    title: 'AirMark TrafficPaint Brochure (FR)',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/airmark/airmark-trafficpaint-brochure-fr.pdf',
    fileSize: '3.6 MB',
    updatedDate: 'Mar 2024',
  },
  {
    id: 'am-data-001',
    title: 'AirMark WB Airfield Product Data Sheet',
    type: 'Data Sheet',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/airmark/airmark-wb-airfield-pds.pdf',
    fileSize: '0.9 MB',
    updatedDate: 'Jan 2024',
  },
  {
    id: 'am-brochure-005',
    title: 'AirMark PreMark Groundside Airports Brochure',
    type: 'Brochure',
    product: 'airmark',
    productName: 'AirMark',
    applications: productApplications['airmark'],
    fileUrl: '/docs/airmark/airmark-premark-groundside-brochure.pdf',
    fileSize: '3.8 MB',
    updatedDate: 'Feb 2024',
  },
]
