"""
Embed all assigned catalog images into the Figma plugin's code.js as a base64
IMAGE_BANK constant. Each image is downsampled and re-encoded as JPEG for a
manageable file size while still delivering visually-rich Figma renders.

Two modes:
- DEFAULT (print): 1500px long edge, JPEG q82. Use for the final-export pass.
- --lite (review):  1200px long edge, JPEG q80. Use day-to-day so the plugin
  opens without OOM-ing Figma on a 30GB-RAM machine. Layout is identical;
  only image fidelity is reduced.

Plugin will use figma.createImage(bytes) + image-fill to embed real photos
instead of beige `[PHOTO]` placeholders.
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import re
import sys
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "output" / "catalog_data.json"
PLUGIN = ROOT / "figma-plugin" / "code.js"

PRESET_PRINT = {"max_edge": 1500, "quality": 82, "label": "print", "jpeg_opaque_pngs": False}
PRESET_LITE  = {"max_edge": 1200, "quality": 80, "label": "lite",  "jpeg_opaque_pngs": True}

# Module-level defaults — overwritten by main() based on CLI flags so that
# encode_image() can stay a single-argument function for backward compat.
MAX_EDGE = PRESET_PRINT["max_edge"]
JPEG_QUALITY = PRESET_PRINT["quality"]
JPEG_OPAQUE_PNGS = PRESET_PRINT["jpeg_opaque_pngs"]


def collect_image_paths(data: dict) -> list[str]:
    paths: list[str] = []

    def add(p):
        if p and isinstance(p, str):
            paths.append(p)

    add(data.get("cover_photo"))
    for v in (data.get("section_openers") or {}).values():
        add(v)
    for p in data.get("products") or []:
        add(p.get("hero"))
    for a in data.get("applications") or []:
        add(a.get("image"))
    for pr in data.get("projects") or []:
        add(pr.get("hero"))
        add(pr.get("detail"))
    for i in data.get("installers") or []:
        add(i.get("image"))

    # Brand logos — needed by plugin for cover, half-title, quiet-mark, back cover
    brand = ROOT.parent / "public" / "images" / "assets" / "logos" / "hubss-logos"
    add(str(brand / "hubss-logo-white-large.png"))
    add(str(brand / "hubss-logo-color.png"))

    # Asphalt photo for back cover
    asphalt = ROOT.parent / "public" / "images" / "applications" / "parking-lots" / "parking-lots-01.jpg"
    add(str(asphalt))

    # Moose mascot — Lunch & Learn page
    mascot = ROOT / "assets" / "moose-mascot.png"
    add(str(mascot))

    # Lunch & Learn QR (UTM-tagged) — generated by generate_plugin._generate_qr
    qr = ROOT / "assets" / "hubss-lunch-learn-qr.png"
    add(str(qr))

    # de-dup, keep order
    seen = set()
    out = []
    for p in paths:
        if p not in seen:
            seen.add(p)
            out.append(p)
    return out


def _png_has_real_transparency(im: "Image.Image") -> bool:
    """Return True only if the image has alpha pixels that aren't fully opaque.
    Catches photos that were saved as PNG but have no actual transparency —
    these can be safely re-encoded as JPEG to cut file size dramatically.
    """
    if im.mode == "P" and "transparency" in im.info:
        # Palette image — assume the transparency key is genuinely used
        return True
    if im.mode not in ("RGBA", "LA"):
        return False
    # Cheap test: look at extrema of alpha channel
    alpha = im.getchannel("A")
    lo, hi = alpha.getextrema()
    return lo < 255  # any non-opaque pixel anywhere


def encode_image(path: str) -> str | None:
    """Resize and encode an image as base64. Preserves PNG with transparency
    (for logos), uses JPEG for opaque photos.

    In --lite mode (JPEG_OPAQUE_PNGS=True) we additionally detect PNGs that
    are actually opaque (photos saved as PNG by mistake) and re-encode them
    as JPEG. This typically cuts 3–4 MB photo-PNGs down to ~200–400 KB each
    without any visible quality loss at the 1200px lite size.
    """
    if not Path(path).exists():
        return None
    try:
        with Image.open(path) as im:
            is_png = path.lower().endswith(".png")
            if JPEG_OPAQUE_PNGS:
                # Smart path: only keep PNG if there's actually transparency.
                keep_png = _png_has_real_transparency(im)
            else:
                # Legacy print-mode behavior: always keep PNG for *.png inputs.
                keep_png = is_png or im.mode in ("RGBA", "LA") or (
                    im.mode == "P" and "transparency" in im.info
                )

            if keep_png:
                im = im.convert("RGBA")
                im.thumbnail((MAX_EDGE, MAX_EDGE), Image.Resampling.LANCZOS)
                buf = io.BytesIO()
                im.save(buf, format="PNG", optimize=True)
            else:
                # Flatten any alpha against white before JPEG (in case the PNG
                # had alpha that turned out to be fully opaque — defensive).
                if im.mode in ("RGBA", "LA"):
                    bg = Image.new("RGB", im.size, (255, 255, 255))
                    bg.paste(im, mask=im.split()[-1])
                    im = bg
                else:
                    im = im.convert("RGB")
                im.thumbnail((MAX_EDGE, MAX_EDGE), Image.Resampling.LANCZOS)
                buf = io.BytesIO()
                im.save(buf, format="JPEG", quality=JPEG_QUALITY, optimize=True)
            return base64.b64encode(buf.getvalue()).decode("ascii")
    except Exception as e:
        print(f"  ! failed to encode {path}: {e}")
        return None


def main():
    global MAX_EDGE, JPEG_QUALITY, JPEG_OPAQUE_PNGS

    ap = argparse.ArgumentParser(
        description="Embed catalogue images into the Figma plugin's code.js"
    )
    ap.add_argument(
        "--lite",
        action="store_true",
        help="Use lighter image preset (1200px / q80) so the plugin opens "
             "comfortably without OOM-ing Figma. Layout unchanged.",
    )
    ap.add_argument(
        "--print",
        dest="print_mode",
        action="store_true",
        help="Force the full-fidelity print preset (1500px / q82). This is "
             "the default if neither flag is given.",
    )
    args = ap.parse_args()

    if args.lite and args.print_mode:
        ap.error("Pass only one of --lite or --print.")

    preset = PRESET_LITE if args.lite else PRESET_PRINT
    MAX_EDGE = preset["max_edge"]
    JPEG_QUALITY = preset["quality"]
    JPEG_OPAQUE_PNGS = preset["jpeg_opaque_pngs"]

    print(
        f"Preset: {preset['label']} — max_edge={MAX_EDGE}px, "
        f"quality={JPEG_QUALITY}, jpeg_opaque_pngs={JPEG_OPAQUE_PNGS}"
    )

    data = json.loads(DATA.read_text())
    paths = collect_image_paths(data)
    print(f"Found {len(paths)} unique image paths")

    bank: dict[str, str] = {}
    total_bytes = 0
    for i, p in enumerate(paths, 1):
        b64 = encode_image(p)
        if b64:
            key = Path(p).parent.name + "/" + Path(p).name  # parent/filename — unique across repeated filenames like featured.jpg
            bank[key] = b64
            total_bytes += len(b64)
            print(f"  [{i}/{len(paths)}] {Path(p).name:50s} {len(b64)//1024:6d} KB")
        else:
            print(f"  [{i}/{len(paths)}] {Path(p).name:50s} SKIPPED")

    print(f"\nTotal embedded base64: {total_bytes/1024/1024:.1f} MB")

    bank_js = json.dumps(bank, ensure_ascii=False)

    # Read current code.js
    code = PLUGIN.read_text(encoding="utf-8")

    # Replace existing IMAGE_BANK using simple string replace (regex fails on huge blobs)
    bank_decl = f"const IMAGE_BANK = {bank_js};"
    if "const IMAGE_BANK = {};" in code:
        # Fresh generate_plugin.py output — exact sentinel match
        code = code.replace("const IMAGE_BANK = {};", bank_decl, 1)
    elif "const IMAGE_BANK" in code:
        # Previous embed already ran — find the declaration boundary and swap it out
        start = code.find("const IMAGE_BANK = {")
        # The declaration ends at the first "};" that closes the top-level object
        # Walk forward to find the matching closing
        depth = 0
        i = start + len("const IMAGE_BANK = ")
        end = i
        while i < len(code):
            if code[i] == '{':
                depth += 1
            elif code[i] == '}':
                depth -= 1
                if depth == 0:
                    end = i + 1  # past the '}'
                    break
            i += 1
        # skip any trailing ";" and whitespace up to newline
        while end < len(code) and code[end] in '; \t':
            end += 1
        code = code[:start] + bank_decl + "\n" + code[end:]
    else:
        # IMAGE_BANK missing entirely — insert before EMBEDDED_DATA
        code = code.replace(
            "const EMBEDDED_DATA",
            bank_decl + "\nconst EMBEDDED_DATA",
            1,
        )

    PLUGIN.write_bytes(code.encode("utf-8"))
    print(f"Wrote IMAGE_BANK into {PLUGIN}")
    print(f"code.js size: {len(code)/1024/1024:.1f} MB")


if __name__ == "__main__":
    main()
