"""
generate_plugin.py — Write a clean, minimal code.js from catalog_data.json.

The embedded-image version of code.js reaches ~74 MB, which exceeds Figma's
plugin sandbox and prevents loading. This script generates a fresh ~100-200 KB
plugin that builds all 100 Figma frames with:
  - Correct frame names, background colours, navy bands, orange accents
  - All product/project text (name, tagline, body, callout, uses...)
  - Neutral light-grey [PHOTO] placeholder rectangles for every photo slot
  - Correct page order matching the PDF exactly

Usage:
    python -B -m src.export_json          # regenerate catalog_data.json
    python -B -m src.generate_plugin      # write fresh code.js
    Then in Figma: remove plugin, re-import manifest, click Build.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT   = Path(__file__).resolve().parent.parent
DATA   = ROOT / "output" / "catalog_data.json"
PLUGIN = ROOT / "figma-plugin" / "code.js"

# ---------------------------------------------------------------------------
# The Figma plugin JavaScript — embedded as a Python string.
# CATALOG_DATA_JSON is replaced with the actual JSON before writing.
# ---------------------------------------------------------------------------
JS = r"""
"use strict";
// HUBSS Catalogue Builder — generated by src/generate_plugin.py
// IMAGE_BANK is injected by src/embed_images.py after this file is written.
// Without embed_images, photo slots degrade gracefully to [PHOTO] placeholders.

const IMAGE_BANK = {};
const EMBEDDED_DATA = CATALOG_DATA_JSON;

// --- colour tokens ---
const O  = {r:0.976, g:0.451, b:0.086};  // HUBSS orange
const N  = {r:0.047, g:0.063, b:0.125};  // HUBSS navy rich
const W  = {r:1,     g:1,     b:1    };  // white
const D  = {r:0.12,  g:0.12,  b:0.12 };  // near-black body
const M  = {r:0.45,  g:0.45,  b:0.45 };  // mid grey
const F  = {r:0.65,  g:0.65,  b:0.65 };  // faint
const PH = {r:0.93,  g:0.93,  b:0.93 };  // v51: neutral light-grey photo placeholder (cream retired — Vernon: 'no cream background colors')

// --- low-level helpers ---
function fr(name, bg) {
  const f = figma.createFrame();
  f.name = name;
  f.resize(450, 450);
  f.clipsContent = true;
  f.fills = [{type:"SOLID", color: bg || W}];
  return f;
}

function rct(p, x, y, w, h, col, name) {
  const r = figma.createRectangle();
  r.resize(Math.max(1, Math.round(w)), Math.max(1, Math.round(h)));
  r.x = Math.round(x);
  r.y = Math.round(y);
  r.fills = [{type:"SOLID", color: col}];
  if (name) r.name = name;
  p.appendChild(r);
  return r;
}

function base64ToBytes(b64) {
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}

// ph() — photo rect: FILL mode crops to frame (correct for photos).
// Tries filename-only key first, full path as fallback.
function ph(p, x, y, w, h, label, imagePath) {
  const r = rct(p, x, y, w, h, PH, "[PHOTO] " + (label || ""));
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");   // parent/filename — unique key matching embed_images.py
    const fname = parts[parts.length - 1];    // filename-only fallback
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FILL", imageHash: img.hash}];
        r.name = label || "Photo";
      } catch(e) { /* keep placeholder */ }
    }
  }
  return r;
}

// phFit() — like ph() but FIT mode: shows entire image, may letterbox.
// Use when the subject (crosswalk decal, marking) must not be cropped at any edge.
function phFit(p, x, y, w, h, label, imagePath) {
  const r = rct(p, x, y, w, h, PH, "[PHOTO] " + (label || ""));
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");
    const fname = parts[parts.length - 1];
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FIT", imageHash: img.hash}];
        r.name = label || "Photo";
      } catch(e) {}
    }
  }
  return r;
}

// logo() — like ph() but uses FIT mode so the full wordmark is never cropped.
// Transparent fill when no image is present (looks clean over any background).
function logo(p, x, y, w, h, label, imagePath) {
  const r = figma.createRectangle();
  r.resize(Math.max(1, Math.round(w)), Math.max(1, Math.round(h)));
  r.x = Math.round(x);
  r.y = Math.round(y);
  r.fills = [];
  r.name = "[LOGO] " + (label || "");
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");
    const fname = parts[parts.length - 1];
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FIT", imageHash: img.hash}];
        r.name = label || "Logo";
      } catch(e) {}
    }
  }
  p.appendChild(r);
  return r;
}

function rul(p, x, y, w) {
  return rct(p, x, y, w, 2, O, "OrangeRule");
}

// tx() — all text creation goes through here.
// lh: explicit line height in px; if omitted, auto-computed for print-quality rhythm.
//   Body (sz < 11):  lh = sz × 1.55  (generous open leading, readable at small sizes)
//   Display (sz ≥ 11): lh = sz × 1.18  (tight but not cramped for headlines)
async function tx(p, text, x, y, sz, col, bold, maxW, align, lh) {
  if (!text || text === "") return null;
  const t = figma.createText();
  // v48 — Vernon: 'thin font on web' complaint. Inter Regular reads
  // visibly lighter than the print PDF's Helvetica Regular. Bumping
  // the non-bold default to Medium gives the on-screen Figma render
  // visual weight parity with what Doug sees in the printed catalogue.
  t.fontName = {family: "Inter", style: bold ? "Bold" : "Medium"};
  t.characters = String(text);
  t.fontSize = Math.round(sz);
  t.fills = [{type:"SOLID", color: col}];
  // Always set explicit line height — eliminates Figma's auto-leading inconsistencies
  // Display sizes (sz >= 11): tight 1.08× for print-quality heading rhythm
  const lineH = lh || (sz < 11 ? Math.round(sz * 1.55) : Math.round(sz * 1.08));
  t.lineHeight = {value: lineH, unit: "PIXELS"};
  if (maxW) {
    t.textAutoResize = "HEIGHT";
    t.resize(Math.max(10, Math.round(maxW)), 400);
  }
  if (align === "center") t.textAlignHorizontal = "CENTER";
  if (align === "right")  t.textAlignHorizontal = "RIGHT";
  t.x = Math.round(x);
  t.y = Math.round(y);
  p.appendChild(t);
  return t;
}

function navyBand(p, h) {
  rct(p, 0, 0, 450, Math.round(h), N, "NavyBand");
}

// --- page builders ---

async function pageCover(d) {
  const f = fr("Cover", N);
  // v44 pro look — Vernon: 'no cream banner, no cream nothing. Go pro.'
  // Full-bleed photo + restrained color logo top-LEFT + bottom masthead
  // sitting on a SOFT navy vignette (not a band). Editorial cover.
  ph(f, 0, 0, 450, 450, "Cover photo", d.cover_photo);
  // v45 — no vignette. Type sits directly on the photo.
  // White-text logo top-LEFT (Vernon: 'previous version was better').
  logo(f, 28, 28, 110, 22, "HUBSS logo white", d.brand && d.brand.logo_white);
  // Bottom masthead — confident display + small caps.
  await tx(f, "Catalogue 2026.", 28, 370, 30, W, true, 394);
  await tx(f, "DECORATIVE PAVEMENT SOLUTIONS", 28, 410, 8, W, false, 394, null, 11);
  return f;
}

async function pageHalfTitle(d) {
  const f = fr("Half Title");
  // Logo: refined to 180px — 40% of frame width, controlled and dignified.
  // Centred: x = (450 - 180) / 2 = 135. Optical centre sits above geometric midpoint.
  logo(f, 135, 172, 180, 40, "HUBSS logo colour", d.brand && d.brand.logo_color);
  // Rule: 24px centred tick (225 − 12 = 213), 12px below logo
  rct(f, 213, 222, 24, 1, O, "OrangeRule");
  await tx(f, "Catalogue 2026", 25, 236, 8, M, false, 400, "center", 12);
  await tx(f, "Established 1994", 25, 252, 6, F, false, 400, "center", 9);
  return f;
}

async function pageManifesto(d) {
  const f = fr("03 — Manifesto");
  const m = d.manifesto || {};
  // Label — 8px top margin, standard 28px left
  await tx(f, (m.eyebrow||"WHO WE ARE").toUpperCase(), 28, 40, 6, O, false, 394);
  // H1 display — 26px, tight 1.15× leading baked in by tx()
  let y = 76;
  const lines = m.h1_lines || ["The street", "is the canvas.", "We supply the paint."];
  for (let i = 0; i < lines.length; i++) {
    const col = (i === (m.h1_orange_line || 0)) ? O : D;
    await tx(f, lines[i], 28, y, 26, col, true, 394);
    y += 31;  // 26px font + 5px gap = tight stacked display
  }
  // Body copy — 16px gap from headline block
  await tx(f, m.body || "", 28, y + 16, 8, D, false, 362);
  rct(f, 28, 398, 394, 1, F, "rule");
  await tx(f, (m.signature || "").toUpperCase(), 28, 408, 5.5, F, false, 394);
  return f;
}

async function pageWhyStats(d) {
  const f = fr("04 — Why HUB Stats");
  const w = d.why_hub || {};
  await tx(f, (w.eyebrow||"WHY HUB").toUpperCase(), 28, 38, 6, O, false, 394);
  let y = 66;
  for (const line of (w.title_lines || [])) {
    await tx(f, line, 28, y, 22, D, true, 394);
    y += 27;  // 22px font, tight leading
  }
  // Stat cards — 2×2 grid, navy bg, orange number
  const stats = w.stats || [];
  const cw = 197, ch = 88, gy = 222;
  for (let i = 0; i < Math.min(stats.length, 4); i++) {
    const col = i % 2, row = Math.floor(i / 2);
    const gx = 28 + col * (cw + 6), gyy = gy + row * (ch + 6);
    rct(f, gx, gyy, cw, ch, N, "StatCard");
    // Number — 28px bold orange, inset 10px
    await tx(f, String(stats[i][0]||""), gx+10, gyy+10, 28, O, true, cw-20);
    // Stat label — 6px caps white
    await tx(f, String(stats[i][1]||"").toUpperCase(), gx+10, gyy+50, 6, W, false, cw-20, null, 9);
    // Sub-label — 6.5px mid grey
    await tx(f, String(stats[i][2]||""), gx+10, gyy+62, 6.5, M, false, cw-20, null, 10);
  }
  rul(f, 28, 430, 32);
  return f;
}

async function pageWhyProof(d) {
  const f = fr("05 — Why HUB Proof");
  const w = d.why_hub || {};
  await tx(f, "FOUR REASONS", 28, 38, 6, O, false, 394);
  await tx(f, "If it goes on the street,", 28, 64, 20, D, true, 394);
  await tx(f, "it stays on the street.", 28, 90, 20, O, true, 394);
  let y = 150;
  for (const [num, claim, detail] of (w.proof || [])) {
    await tx(f, String(num), 28, y, 6.5, O, false, 28, null, 10);
    await tx(f, claim, 58, y, 10, D, true, 350);
    await tx(f, detail, 58, y+14, 7.5, M, false, 350);
    rct(f, 28, y+46, 394, 1, F, "rule");
    y += 58;
  }
  rul(f, 28, 430, 32);
  return f;
}

async function pageTOC(sections, totalPages) {
  const f = fr("Contents");
  await tx(f, "CATALOGUE 2026", 28, 38, 6, O, false, 394, null, 9);
  await tx(f, "Contents.", 28, 52, 22, D, true, 394);
  rct(f, 28, 94, 394, 1, F, "rule");
  let y = 112;
  for (let i = 0; i < sections.length; i++) {
    const [label, num] = sections[i];
    const idx = String(i + 1).padStart(2, "0");
    // Row height = 40px, text lh = 13px → vertical centre offset = (40-13)/2 ≈ 13px from top rule
    // top rule at y-18, so centred text at y-18+13 = y-5; we use y-4 (nearest px)
    await tx(f, idx, 28, y - 4, 8, O, true, 28, null, 13);
    await tx(f, label, 62, y - 4, 9.5, D, false, 300, null, 13);
    await tx(f, String(num), 28, y - 4, 9, M, false, 394, "right", 13);
    rct(f, 28, y + 22, 394, 1, F, "rule");
    y += 40;
  }
  // Footer — dynamic page count, right-aligned
  await tx(f, String(totalPages || 100) + " pages", 28, y + 16, 6, F, false, 394, "right", 9);
  return f;
}

async function pageSectionOpen(num, title, imagePath) {
  const f = fr(`p__ / Section ${num} — ${title}`, N);
  // v50 parity (print page_section_open at final_catalog.py:513) —
  // Vernon: 'Section One could stand out more.' Orange dot pre-element,
  // rule UNDER the eyebrow, 64pt display, tracking -2.0.
  ph(f, 0, 0, 450, 450, "Section Opener / Photo / " + title, imagePath);
  // Orange dot — visual brand anchor
  const dot = figma.createEllipse();
  dot.resize(7, 7); dot.x = 22; dot.y = 320;
  dot.fills = [{type:"SOLID", color: O}];
  dot.name = "Section Opener / Dot";
  f.appendChild(dot);
  await tx(f, ("SECTION " + num).toUpperCase(), 34, 318, 8.5, W, false, 394, null, 13);
  rul(f, 28, 338, 44);   // rule UNDER eyebrow, not under the entire band
  f.children[f.children.length-1].name = "Section Opener / Brand Rule";
  await tx(f, title, 28, 358, 64, W, true, 394);
  // Name the last text node so layer panel reads cleanly
  const lastTx = f.children[f.children.length-1];
  if (lastTx && lastTx.type === "TEXT") lastTx.name = "Section Opener / Display Title";
  return f;
}

async function pageProductHero(prod) {
  const f = fr("Hero — " + prod.name, W);
  // v44 pro look — NO band. Editorial flow: photo top ~65% + white
  // space + small orange eyebrow + display italic serif tagline +
  // thin orange brand-pickup rule.
  ph(f, 0, 0, 450, 290, prod.name + " — hero photo", prod.hero);
  // Small orange dot + product name caps eyebrow.
  rct(f, 28, 324, 4, 4, O, "OrangeDot");
  await tx(f, (prod.name||"").toUpperCase(), 36, 322, 7.5, O, false, 394, null, 11);
  // Display italic serif tagline — editorial centerpiece. Serif (Inter
  // doesn't have a true italic in many platforms; fall back to Bold
  // italic if available, else Bold) — Figma will respect the request.
  const tag = figma.createText();
  tag.fontName = {family: "Inter", style: "Bold"};
  tag.characters = prod.tagline || "";
  tag.fontSize = 22;
  tag.fills = [{type:"SOLID", color: D}];
  tag.lineHeight = {value: 26, unit: "PIXELS"};
  tag.textAutoResize = "HEIGHT";
  tag.resize(394, 400);
  tag.x = 28; tag.y = 350;
  f.appendChild(tag);
  // v48 — Vernon: drop bottom decorative orange line.
  return f;
}

async function pageProductSpec(prod) {
  const f = fr("Spec — " + prod.name);
  // Band height 116px — enough room to push all header text into the 28px safe zone
  navyBand(f, 116);
  // Header text starts at y=28: the same safe-zone margin used everywhere else.
  // At 450px = 5", y=16 puts live text ~1mm from the trim edge — not print-safe.
  // y=28 = ~3mm from edge, safely inside the live area on any print spec.
  await tx(f, "BY HUB SURFACE SYSTEMS", 28, 28, 5.5, O, false, 394, null, 8);
  // Product name: 8px below eyebrow bottom (eyebrow bottom = 28+8 = 36, name at 44)
  await tx(f, prod.name || "", 28, 44, 24, W, true, 394);
  // Rule: 6px below name bottom (name bottom ≈ 44+28 = 72, rule at 78)
  rul(f, 28, 78, 24);
  // Category: 4px below rule
  await tx(f, (prod.category || "Decorative Pavement").toUpperCase(), 28, 84, 5.5, W, false, 394, null, 8);

  // Body zone — 28px breathing room below band (band ends at 116, content at 144)
  const title = prod.title || prod.name;
  await tx(f, title, 28, 144, 21, D, true, 394);
  await tx(f, prod.italic || "", 28, 184, 8.5, M, false, 394);
  const callout = ((prod.callout||"") + "  ·  " + (prod.callout_unit||"")).toUpperCase();
  rul(f, 28, 210, 24);
  await tx(f, callout, 28, 216, 6, O, false, 394, null, 9);
  await tx(f, prod.body || "", 28, 230, 8, D, false, 394);

  // Spec grid — anchored from bottom, leaving intentional white space above
  if (prod.spec_pairs && prod.spec_pairs.length) {
    rct(f, 28, 308, 394, 1, F, "rule");
    const colX = [28, 162, 296];
    for (let i = 0; i < Math.min(prod.spec_pairs.length, 6); i++) {
      const [lbl, val] = prod.spec_pairs[i];
      const col = i % 3, row = Math.floor(i / 3);
      const xx = colX[col], yy = 320 + row * 30;
      await tx(f, (lbl||"").toUpperCase(), xx, yy, 5.5, F, false, 124, null, 8);
      await tx(f, val||"", xx, yy+10, 8, D, true, 124, null, 12);
    }
  }
  // Uses — footer: rule then centred uses line, pinned near page bottom
  if (prod.uses && prod.uses.length) {
    rct(f, 28, 392, 394, 1, F, "rule");
    await tx(f, prod.uses.join("   ·   ").toUpperCase(), 28, 402, 6, M, false, 394, "center", 9);
  }
  // CTA: spec sheet URL — moved to y=414 (bottom=424, gap=26px ≥ 0.25" safe margin)
  await tx(f, "hubss.com/products", 28, 414, 6.5, O, false, 394, "right", 10);
  return f;
}

async function pageApplication(app, idx, total) {
  const f = fr(`App ${String(idx).padStart(2,"0")} — ${app.name}`);
  // v47 — matches v46 print: photo top ~65%, dark editorial type on
  // white space below. Orange-dot eyebrow + display + body + brand rule.
  ph(f, 0, 0, 450, 296, app.name + " — application photo", app.image);
  rct(f, 28, 324, 4, 4, O, "OrangeDot");
  await tx(f, (app.name||"").toUpperCase(), 36, 322, 7.5, O, false, 394, null, 11);
  await tx(f, app.tagline || "", 28, 350, 18, D, true, 394);
  await tx(f, app.body || "", 28, 388, 8.5, M, false, 394, null, 12);
  // v48 — Vernon: drop bottom decorative orange line. URL keeps it clean.
  await tx(f, "hubss.com", 28, 435, 5.5, O, false, 394, "right", 9);
  return f;
}

async function pageProjectHero(proj) {
  const f = fr("Hero — " + proj.name, W);
  // v47 — matches v46 print: photo top + dark editorial type on white
  // (was: NavyBand bottom + white type). No band.
  ph(f, 0, 0, 450, 296, proj.name + " — hero photo", proj.hero);
  rct(f, 28, 324, 4, 4, O, "OrangeDot");
  await tx(f, (proj.name||"").toUpperCase(), 36, 322, 7.5, O, false, 394, null, 11);
  await tx(f, proj.title || "", 28, 350, 20, D, true, 394);
  // v48 — Vernon: drop bottom decorative orange line.
  await tx(f, (proj.location||"").toUpperCase(), 28, 414, 6, M, false, 190, null, 9);
  await tx(f, (proj.product||"").toUpperCase(), 232, 414, 6, O, false, 190, null, 9);
  return f;
}

async function pageProjectStory(proj, idx) {
  const f = fr(`Story ${String(idx).padStart(2,"0")} — ${proj.name}`);
  // v47 — matches v46 print: dot eyebrow + dark display name + faint
  // location/product caps + mid-grey body.
  ph(f, 0, 0, 450, 296, proj.name + " — detail photo", proj.detail || proj.hero);
  const eyebrowLabel = proj.product ? proj.product.toUpperCase() : ("PROJECT " + String(idx).padStart(2,"0"));
  rct(f, 28, 324, 4, 4, O, "OrangeDot");
  await tx(f, eyebrowLabel, 36, 322, 7.0, O, false, 394, null, 11);
  await tx(f, proj.name || "", 28, 348, 17, D, true, 394, null, 20);
  await tx(f, ((proj.location||"") + "    " + (proj.product||"")).toUpperCase(), 28, 376, 5.5, F, false, 394, null, 8);
  await tx(f, proj.story || "", 28, 394, 8.0, M, false, 394, null, 11);
  return f;
}

async function pageInstaller(inst, idx, total) {
  const f = fr("Installer — " + inst.name);
  // Navy header band — credential zone. Keeps photo uncluttered.
  navyBand(f, 152);
  // Credential badge top-left, counter top-right — both sit in the navy zone
  await tx(f, "HUB CERTIFIED INSTALLER", 28, 28, 5.5, O, false, 260, null, 8);
  await tx(f, String(idx).padStart(2,"0") + " / " + String(total).padStart(2,"0"), 28, 28, 5.5, {r:0.38,g:0.38,b:0.38}, false, 394, "right", 8);
  // Name: 30px — large, white, in the navy zone
  await tx(f, inst.name, 28, 52, 30, W, true, 394);
  // Region: small caps, muted charcoal on navy
  await tx(f, (inst.region || "").toUpperCase(), 28, 102, 5.5, {r:0.45,g:0.45,b:0.45}, false, 394, null, 8);
  rul(f, 28, 128, 32);
  // Contained editorial photo — full width, runs from bottom of header to content zone
  ph(f, 0, 152, 450, 192, inst.name + " — photo", inst.image);
  // White content zone below photo
  await tx(f, inst.body || "", 28, 360, 8, D, false, 394);
  // Footer: moved up to y=400/410 — bottom=420, gap=30px (≥0.25" safe margin)
  rct(f, 28, 400, 394, 1, F, "rule");
  await tx(f, inst.phone || "", 28, 410, 10, D, true, 190);
  await tx(f, inst.url || "", 238, 411, 9, O, false, 182);
  return f;
}

// pageNetworkOpen — v47 — matches v46 print section openers. Full-bleed
// photo + white display type on photo. No scrim, no navy bottom.
async function pageNetworkOpen(d) {
  const f = fr("Section Four — Network", N);
  ph(f, 0, 0, 450, 450, "Network section opener", d.section_openers && d.section_openers.network);
  rul(f, 28, 313, 28);
  await tx(f, "SECTION FOUR", 28, 322, 7.5, W, false, 394, null, 11);
  await tx(f, "Network.", 28, 350, 44, W, true, 394);
  return f;
}

// pageDoublespread — two facing pages that read as one editorial spread.
// Left page: headline anchored bottom-left (big idea, reading direction cue).
// Right page: matching image, CTA URL bottom-right (where to go next).
// The left→right pairing creates intentional narrative: statement → action.
async function pageDoublespread(label, imagePath, caption, rightStyle, rightImagePath) {
  // v47 — matches v46 print: no scrim on left, no footer band on right.
  // Type sits directly on the photo (eyebrow + caption white on photo).
  const fL = fr("Spread L — " + (label||""), N);
  ph(fL, 0, 0, 450, 450, label + " — left", imagePath);
  rul(fL, 28, 352, 20);
  await tx(fL, (label||"").toUpperCase(), 28, 361, 6, W, false, 394, null, 9);
  if (caption) {
    await tx(fL, caption, 28, 382, 10.5, W, true, 390, null, 15);
  }

  // Right page — photo CTA by default; navy brand statement when rightStyle === "navy"
  const fR = fr("Spread R — " + (label||""), N);
  if (rightStyle === "navy") {
    // Closing editorial — navy, giant type, lands as a final statement.
    // INTENTIONAL navy: this is a typographic brand-statement spread,
    // not a photo overlay. Per Vernon's rule, navy is OK on type-only pages.
    rul(fR, 28, 80, 32);
    await tx(fR, "THIRTY YEARS IN THE MAKING.", 28, 96, 6, O, false, 394, null, 9);
    await tx(fR, "Built to", 28, 116, 52, W, true, 394);
    await tx(fR, "outlast.", 28, 180, 52, O, true, 394);
    rct(fR, 28, 248, 394, 1, {r:1,g:1,b:1}, "Divider");
    fR.children[fR.children.length-1].opacity = 0.15;
    await tx(fR, "30+ years   ·   1,000+ projects   ·   500+ municipalities", 28, 262, 7.5, M, false, 394, "center", 11);
    rct(fR, 28, 288, 394, 1, {r:1,g:1,b:1}, "Divider");
    fR.children[fR.children.length-1].opacity = 0.08;
    await tx(fR, "The surface beneath every city we've built.", 28, 308, 12, W, false, 360);
    await tx(fR, "Spec the surface. Watch it work. Walk over it for twenty years.", 28, 332, 8, M, false, 360);
    rct(fR, 28, 404, 394, 1, O, "OrangeRule");
    await tx(fR, "hubss.com", 28, 414, 7.5, O, true, 394, "right", 11);
  } else {
    // Photo right — full bleed, no footer band, URL on photo right-aligned
    ph(fR, 0, 0, 450, 450, label + " — right", rightImagePath || imagePath);
    await tx(fR, "hubss.com", 28, 426, 7.5, O, true, 394, "right", 11);
  }
  return [fL, fR];
}

// pageImageSpread — v47 full-bleed photo, no caption band. Type on photo.
async function pageImageSpread(label, imagePath, headline) {
  const f = fr("Spread — " + (label||""), N);
  ph(f, 0, 0, 450, 450, label, imagePath);
  rul(f, 30, 410, 30);
  if (headline) {
    await tx(f, headline.toUpperCase(), 68, 413, 6, W, false, 352);
  }
  return f;
}

async function pageTechnical() {
  const f = fr("Reference — Technical");
  await tx(f, "TECHNICAL REFERENCE", 30, 40, 7, O, false, 370);
  await tx(f, "At a Glance.", 30, 68, 24, D, true, 370);
  const prods = [
    ["TrafficPatternsXD", "Thermoplastic", "High-durability preformed marking"],
    ["TrafficPatterns",   "Thermoplastic", "Standard preformed marking"],
    ["StreetBond",        "MMA Coating",   "Decorative coloured pavement"],
    ["StreetPrint",       "Stamped Asphalt","Brick and stone patterns"],
    ["DecoMark",          "Epoxy",         "Coloured crosswalk systems"],
    ["MMAX",              "MMA Resin",     "Coloured lane treatment"],
    ["DuraTherm",         "Inlaid",        "Snowplow-safe flush inlay"],
    ["DuraShield",        "Penetrating",   "Asphalt rejuvenator"],
    ["PreMark",           "Pre-cut",       "Bike infrastructure markings"],
    ["AirMark",           "Airfield",      "FAA-compliant markings"],
  ];
  let y = 128;
  for (const [name, key, desc] of prods) {
    await tx(f, name, 30, y, 9, D, true, 148);
    await tx(f, key.toUpperCase(), 185, y, 6, O, false, 110);
    await tx(f, desc, 272, y, 8, M, false, 158);
    rct(f, 30, y+15, 390, 1, F, "rule");
    y += 22;
  }
  return f;
}

async function pageCities(d) {
  const f = fr("Reference — Cities");
  // "500+" as hero stat — visual anchor, gives the city list credibility and scale
  await tx(f, "500+", 30, 28, 60, O, true, 390);
  await tx(f, "Canadian municipalities", 30, 98, 9, D, false, 280, null, 13);
  await tx(f, "that specify HUB systems by name.", 30, 113, 9, M, false, 280, null, 13);
  await tx(f, "FROM HALIFAX TO VANCOUVER", 30, 133, 5.5, F, false, 390, null, 8);
  rct(f, 30, 150, 390, 1, F, "rule");
  await tx(f, "A partial list", 30, 158, 7, M, false, 390, "right", 10);
  // City list — 2 columns, 8px type, generous spacing
  const cities = d.cities || [];
  let y = 172;
  for (let i = 0; i < cities.length; i += 2) {
    if (y > 418) break;
    await tx(f, cities[i]||"", 30, y, 8, D, false, 185);
    if (cities[i+1]) await tx(f, cities[i+1], 235, y, 8, D, false, 175);
    y += 13;
  }
  return f;
}

async function pageLunchLearn(mascotPath) {
  // Moose-anchored Lunch & Learn page. Warm + editorial, not corporate.
  // Left column: headline + detail list. Right column: Moose mascot, large + clean.
  const f = fr("CTA — Lunch and Learn");

  // Moose — right column, FIT mode (transparent bg — no box, no crop)
  // Prominent, friendly, anchors the visual. Vernon can reposition in Figma.
  logo(f, 248, 10, 180, 260, "Moose — HUB mascot", mascotPath);

  // Left column — headline and what's included
  rul(f, 28, 16, 24);
  await tx(f, "ENGINEERS, PLANNERS + SPECIFIERS", 28, 26, 5, O, false, 210, null, 8);
  await tx(f, "Lunch Is On Us.", 28, 44, 24, D, true, 210);
  await tx(f, "Your Next Spec Is Free.", 28, 74, 15, O, true, 210);

  rct(f, 28, 104, 210, 1, F, "rule");

  const items = [
    "45 min · Tailored to your project",
    "Live Q&A with HUB technical team",
    "Spec sheets + sample materials",
    "CE credits: AIBC, RAIC, PEO",
    "Lunch included",
    "$25 voucher for virtual sessions",
    "Zero cost · No obligation",
  ];
  let dy = 114;
  for (const item of items) {
    await tx(f, "·  " + item, 28, dy, 7, D, false, 210);
    dy += 13;
  }

  rct(f, 28, dy + 4, 210, 1, F, "rule");
  await tx(f, "Not a sales pitch. An education.", 28, dy + 13, 7.5, M, false, 210);
  await tx(f, "Real case studies from 500+ Canadian municipalities.", 28, dy + 27, 7, M, false, 210);

  // Full-width URL zone below both columns
  rct(f, 28, 280, 394, 1, F, "rule");
  await tx(f, "hubss.com/lunch-learn", 28, 292, 13, O, true, 394);
  await tx(f, "City of Toronto  ·  York Region  ·  City of Vancouver  ·  UBC  ·  TransLink  ·  500+ municipalities", 28, 318, 6.5, M, false, 394, "center", 9);

  // Contacts
  rct(f, 28, 340, 394, 1, F, "rule");
  await tx(f, "BOOK DIRECTLY", 28, 350, 5, F, false, 394, null, 8);
  await tx(f, "Cleve Stordy   604.309.8212", 28, 362, 8, D, false, 188, null, 12);
  await tx(f, "Doug Bain   416.540.9287", 242, 362, 8, D, false, 178, null, 12);
  rct(f, 28, 390, 394, 1, F, "rule");
  await tx(f, "HUB SURFACE SYSTEMS   ·   hubss.com   ·   604.309.8212   ·   416.540.9287", 28, 400, 5.5, F, false, 394, "center", 8);
  return f;
}

async function pageContact(d) {
  // Contact page with navy header band for visual weight.
  const f = fr("Contact");
  // Navy header — gives visual interest without breaking the clean layout
  rct(f, 0, 0, 450, 82, N, "NavyBand");
  await tx(f, "TWO OFFICES. ONE NETWORK.", 30, 14, 5.5, O, false, 390, null, 8);
  rul(f, 30, 30, 24);
  await tx(f, "Speak with HUB.", 30, 44, 22, W, true, 390);
  // Content zone
  await tx(f, "Every project starts with a conversation.", 30, 96, 10, M, false, 390, null, 15);
  rct(f, 30, 128, 390, 1, F, "rule");
  // West
  await tx(f, "WESTERN CANADA", 30, 144, 5.5, O, false, 188, null, 8);
  await tx(f, "Cleve Stordy", 30, 158, 20, D, true, 188);
  await tx(f, "cleve.stordy@hubss.com", 30, 194, 8.5, D, false, 188);
  await tx(f, "604.309.8212", 30, 212, 8.5, M, false, 188);
  await tx(f, "Ladysmith, British Columbia", 30, 230, 7, M, false, 188);
  // East
  await tx(f, "EASTERN CANADA", 242, 144, 5.5, O, false, 178, null, 8);
  await tx(f, "Doug Bain", 242, 158, 20, D, true, 178);
  await tx(f, "doug.bain@hubss.com", 242, 194, 8.5, D, false, 178);
  await tx(f, "416.540.9287", 242, 212, 8.5, M, false, 178);
  await tx(f, "Milton, Ontario", 242, 230, 7, M, false, 178);
  rct(f, 30, 258, 390, 1, F, "rule");
  // URL — single bold destination
  await tx(f, "hubss.com", 30, 272, 16, O, true, 390);
  await tx(f, "Spec sheets · project gallery · installer network · lunch + learn booking", 30, 304, 8, M, false, 390, null, 12);
  rct(f, 30, 338, 390, 1, F, "rule");
  await tx(f, "© 2026 HUB Surface Systems   ·   Established 1994   ·   Coast to Coast", 30, 350, 5.5, F, false, 390, "center", 8);
  return f;
}

async function pageClosing() {
  // Confident sign-off. More breathing room, stronger hierarchy.
  const f = fr("Closing — The Street");
  // Eyebrow
  await tx(f, "THE STREET IS", 28, 52, 6.5, O, false, 394, null, 9);
  // Two-line display headline with more white space
  await tx(f, "The public realm.", 28, 76, 38, D, true, 394);
  await tx(f, "Ours to build right.", 28, 128, 38, O, true, 394);
  // Orange accent rule — visual pause before the statement
  rct(f, 28, 185, 48, 2, O, "OrangeRule");
  // Statement — tighter body copy with more breathing room above
  await tx(f, "Every surface we build is walked over, driven on, played at, and lived around. That is the standard we hold ourselves to. Specify it right. Watch it work. Walk over it for twenty years.", 28, 208, 9.5, D, false, 340);
  // Three-word sign-off as horizontal trio
  rct(f, 28, 356, 394, 1, F, "rule");
  await tx(f, "SPECIFIED.", 28, 370, 9, D, true, 120);
  await tx(f, "INSTALLED.", 162, 370, 9, D, true, 120);
  await tx(f, "BACKED.", 296, 370, 9, D, true, 100);
  rul(f, 28, 393, 32);
  await tx(f, "HUB SURFACE SYSTEMS", 28, 404, 5.5, F, false, 394, "center", 8);
  return f;
}

async function pageService() {
  const f = fr("Closing — Service Promise");
  await tx(f, "HOW WE WORK", 28, 50, 6.5, O, false, 394);
  await tx(f, "Specified.", 28, 76, 24, D, true, 394);
  await tx(f, "Installed.", 28, 110, 24, D, true, 394);
  await tx(f, "Backed.", 28, 144, 24, D, true, 394);
  await tx(f, "Every HUB project is spec-supported, installer-trained, and backed by our performance guarantee.", 28, 205, 8.5, D, false, 394);
  return f;
}

async function pageQuietMark(d) {
  const f = fr("Closing — HUB Mark");
  // Optical centre — logo sits in the upper third, generous air around it
  // 148×32px frame: same proportions as cover/back-cover for visual system cohesion
  logo(f, 151, 162, 148, 32, "HUBSS logo colour", d.brand && d.brand.logo_color);
  // Rule then type — spaced on a 16px baseline grid from logo bottom (y=194)
  rct(f, 213, 208, 24, 1, O, "OrangeRule");
  await tx(f, "HUB SURFACE SYSTEMS", 28, 220, 7, D, true, 394, "center", 11);
  await tx(f, "ESTABLISHED 1994   ·   COAST TO COAST", 28, 235, 5.5, F, false, 394, "center", 8);
  rct(f, 98, 260, 254, 1, F, "Divider");
  await tx(f, "Thank you.", 28, 280, 13, M, false, 394, "center", 18);
  return f;
}

async function pageBack(d) {
  const f = fr("Back Cover", N);
  ph(f, 0, 0, 450, 450, "Back cover — asphalt photo", d.brand && d.brand.asphalt_photo);
  // Single smooth navy wash — lets photo texture breathe while legibility is guaranteed
  rct(f, 0, 0, 450, 450, N, "NavyWash");
  f.children[f.children.length-1].opacity = 0.72;
  // Logo: FIT mode, 32px tall — centred, restrained
  // 148px wide gives correct aspect for ~5:1 horizontal wordmark
  logo(f, 151, 178, 148, 32, "HUBSS logo white — centred", d.brand && d.brand.logo_white);
  // Rule separates logo from tagline
  rct(f, 213, 222, 24, 1, O, "OrangeRule");
  await tx(f, "Canada's Leading Decorative Pavement Solutions", 28, 234, 7.5, W, false, 394, "center", 11);
  await tx(f, "hubss.com", 28, 254, 9, W, true, 394, "center", 13);
  // Light divider
  rct(f, 98, 280, 254, 1, {r:1,g:1,b:1}, "Divider");
  f.children[f.children.length-1].opacity = 0.20;
  await tx(f, "West / Prairies   604.309.8212", 28, 292, 6.5, W, false, 394, "center", 10);
  await tx(f, "Central / Maritimes   416.540.9287", 28, 306, 6.5, W, false, 394, "center", 10);
  await tx(f, "© 2026 HUB Surface Systems", 28, 330, 5.5, M, false, 394, "center", 8);
  return f;
}

async function pageBlank(idx) {
  // Intentional rest page — minimal, never truly empty.
  // Centred orange dash signals editorial breathing room, not an oversight.
  const f = fr("Rest " + idx);
  rct(f, 213, 224, 24, 2, O, "OrangeRule");
  return f;
}

// pageFieldNotes — a ruled notepad page for specifiers.
// Simple, intentional — the specifier gets a physical place to record their project details.
// Sits after the Contact page so it directly faces the contact information.
// addFolio — page number at bottom of content pages.
// y=415: bottom=423, gap=27px (0.3" from trim edge — within 0.25" safe margin).
// Skipped on: Cover, Back Cover, Half Title, Rest/blank, Section openers, Spread/DPS.
async function addFolio(frame, num) {
  await tx(frame, String(num), 28, 415, 5.5, M, false, 394, "center", 8);
}

async function pageFieldNotes() {
  const f = fr("Field Notes");
  // Header: small-caps label + orange rule — same visual grammar as the rest of the catalogue
  await tx(f, "FIELD NOTES", 28, 36, 6, O, false, 394, null, 9);
  rul(f, 28, 54, 20);
  await tx(f, "Your project. Your notes.", 28, 64, 7.5, M, false, 300, null, 11);
  // 14 ruled lines evenly distributed across the body — 96px to 398px
  const lineY0 = 96, lineY1 = 398, lineCount = 14;
  const lineGap = Math.round((lineY1 - lineY0) / (lineCount - 1));
  for (let i = 0; i < lineCount; i++) {
    rct(f, 28, lineY0 + i * lineGap, 394, 1, F, "NoteLine");
  }
  // Footer: moved up — bottom=~414, gap=36px (≥0.25" safe margin)
  rct(f, 28, 402, 394, 1, F, "rule");
  await tx(f, "HUB SURFACE SYSTEMS   ·   hubss.com   ·   604.309.8212   ·   416.540.9287", 28, 410, 5.5, F, false, 394, "center", 8);
  return f;
}

// pageHubNumbers — navy full-bleed stats spread.
// Giant orange numbers on navy — maximum typographic confidence.
async function pageHubNumbers() {
  const f = fr("By the Numbers", N);
  await tx(f, "BY THE NUMBERS", 28, 38, 6, O, false, 394, null, 9);
  rul(f, 28, 56, 24);
  // Three stacked stats — descending scale (56 → 44 → 44)
  const rows = [
    ["30+",    "years building Canadian streets"],
    ["1,000+", "projects completed coast to coast"],
    ["500+",   "municipalities that specify HUB by name"],
  ];
  let sy = 80;
  for (const [num, label] of rows) {
    await tx(f, num, 28, sy, 56, O, true, 394);          // lh = 56*1.18 = 66
    await tx(f, label, 28, sy + 72, 8.5, W, false, 360); // caption below number
    rct(f, 28, sy + 96, 394, 1, {r:1,g:1,b:1}, "Divider");
    f.children[f.children.length-1].opacity = 0.12;
    sy += 116;
  }
  return f;
}

// pageStatement — editorial quote page on white.
// A breath before the product sections begin. Clean typographic confidence.
async function pageStatement() {
  const f = fr("Editorial — Statement");
  await tx(f, "THE SURFACE UNDERFOOT", 28, 60, 6, O, false, 394, null, 9);
  await tx(f, "Every surface", 28, 86, 30, D, true, 394);
  await tx(f, "tells the city's", 28, 124, 30, D, true, 394);
  await tx(f, "story first.", 28, 162, 30, O, true, 394);
  rct(f, 28, 214, 32, 2, O, "OrangeRule");
  await tx(f, "From a community crosswalk in Sechelt to a transit corridor in Toronto, the mark on the street carries meaning beyond its function. Specify it right. Choose it to last twenty years.", 28, 230, 9.5, D, false, 330);
  rct(f, 28, 398, 394, 1, F, "rule");
  await tx(f, "hubss.com", 28, 410, 7, O, true, 394, "right", 11);
  return f;
}

// ---------------------------------------------------------------------
// v51 — VISUAL DESIGN SYSTEM
// Idempotent — checks if a style/component already exists by name before
// creating. Vernon's re-imports won't duplicate. Run once at the top
// of buildCatalogue so the styles + components exist before frames are
// built and can be referenced from the layers panel.
// ---------------------------------------------------------------------
function _hasPaintStyleByName(name) {
  const styles = figma.getLocalPaintStyles();
  for (let i = 0; i < styles.length; i++) if (styles[i].name === name) return styles[i];
  return null;
}
function _hasTextStyleByName(name) {
  const styles = figma.getLocalTextStyles();
  for (let i = 0; i < styles.length; i++) if (styles[i].name === name) return styles[i];
  return null;
}
function _hasComponentByName(name) {
  for (const page of figma.root.children) {
    for (const node of page.children) {
      if (node.type === "COMPONENT" && node.name === name) return node;
    }
  }
  return null;
}
function _ensurePaintStyle(name, color) {
  let s = _hasPaintStyleByName(name);
  if (s) return s;
  s = figma.createPaintStyle();
  s.name = name;
  s.paints = [{type:"SOLID", color: color}];
  return s;
}
function _ensureTextStyle(name, family, style, fontSize, lineHeight, tracking) {
  let s = _hasTextStyleByName(name);
  if (s) return s;
  s = figma.createTextStyle();
  s.name = name;
  s.fontName = {family: family, style: style};
  s.fontSize = fontSize;
  if (lineHeight) s.lineHeight = {value: lineHeight, unit: "PIXELS"};
  if (typeof tracking === "number") s.letterSpacing = {value: tracking, unit: "PERCENT"};
  return s;
}
async function createDesignSystem() {
  // Paint styles — brand palette
  _ensurePaintStyle("HUBSS / Orange",       O);
  _ensurePaintStyle("HUBSS / Navy",         N);
  _ensurePaintStyle("HUBSS / Ink",          D);
  _ensurePaintStyle("HUBSS / Paper",        W);
  _ensurePaintStyle("HUBSS / Mid Grey",     M);
  _ensurePaintStyle("HUBSS / Faint Grey",   F);

  // Text styles — print typography roles (v50)
  _ensureTextStyle("Display / Section",     "Inter", "Bold",     64, 66, -3.0);
  _ensureTextStyle("Display / Hero",        "Inter", "Bold",     44, 48, -2.0);
  _ensureTextStyle("Display / Product",     "Inter", "Bold",     26, 30, -2.0);
  _ensureTextStyle("Subhead / Tagline",     "Inter", "Medium",   16, 22, -1.0);
  _ensureTextStyle("Body / Regular",        "Inter", "Medium",   10, 15,  0.0);
  _ensureTextStyle("Body / Small",          "Inter", "Medium",    8, 12,  0.0);
  _ensureTextStyle("Eyebrow / Caps",        "Inter", "Bold",      7, 11,  16.0);
  _ensureTextStyle("TOC / Item",            "Inter", "Bold",     11, 17,  0.0);
  _ensureTextStyle("Page Number",           "Inter", "Medium",    8, 12,  0.0);

  // Components — reusable design-system elements parked on a hidden page
  // so they're discoverable in the Assets panel without cluttering canvas.
  let dsPage = figma.root.children.find(p => p.name === "Design System");
  if (!dsPage) {
    dsPage = figma.createPage();
    dsPage.name = "Design System";
  }
  if (!_hasComponentByName("Orange Dot")) {
    const c = figma.createComponent();
    c.name = "Orange Dot";
    c.resize(8, 8);
    const ell = figma.createEllipse();
    ell.resize(8, 8);
    ell.fills = [{type:"SOLID", color: O}];
    ell.name = "Dot";
    c.appendChild(ell);
    dsPage.appendChild(c);
  }
  if (!_hasComponentByName("Brand Rule / Orange Thin")) {
    const c = figma.createComponent();
    c.name = "Brand Rule / Orange Thin";
    c.resize(44, 2);
    const r = figma.createRectangle();
    r.resize(44, 2);
    r.fills = [{type:"SOLID", color: O}];
    r.name = "Rule";
    c.appendChild(r);
    dsPage.appendChild(c);
  }
  if (!_hasComponentByName("Page Number Footer")) {
    const c = figma.createComponent();
    c.name = "Page Number Footer";
    c.resize(40, 14);
    const tn = figma.createText();
    tn.fontName = {family:"Inter", style:"Medium"};
    tn.characters = "00";
    tn.fontSize = 8;
    tn.fills = [{type:"SOLID", color: M}];
    tn.x = 0; tn.y = 0;
    tn.name = "Page Number";
    c.appendChild(tn);
    dsPage.appendChild(c);
  }
}

// --- main build ---
async function buildCatalogue(d) {
  // v51 — load all weights used by the design system + frames
  await figma.loadFontAsync({family:"Inter", style:"Regular"});
  await figma.loadFontAsync({family:"Inter", style:"Medium"});
  await figma.loadFontAsync({family:"Inter", style:"SemiBold"});
  await figma.loadFontAsync({family:"Inter", style:"Bold"});
  // Bootstrap the design system once per Figma session (idempotent).
  try { await createDesignSystem(); } catch (e) { console.warn("Design system init failed:", e); }

  const frames = [];

  // Front matter — TOC on p3 so readers can navigate from the first spread
  frames.push(await pageCover(d));        // 0 = p1
  frames.push(await pageHalfTitle(d));    // 1 = p2
  frames.push(null);                      // 2 = p3  TOC — filled after numbering
  frames.push(await pageManifesto(d));    // 3 = p4  Brand promise (not in TOC — editorial)
  frames.push(await pageWhyStats(d));     // 4 = p5  Why HUB stats
  frames.push(await pageWhyProof(d));     // 5 = p6  Why HUB proof
  frames.push(await pageHubNumbers());    // 6 = p7  Bold stats moment — navy
  frames.push(await pageStatement());     // 7 = p8  Editorial statement — white

  // DPS-A — opening editorial. Full-bleed before Products section.
  // Vernon swaps images in Figma for final. Keys: dps_a_left / dps_a_right.
  {
    const dpsAL = d.section_openers && d.section_openers.dps_a_left;
    const dpsAR = d.section_openers && d.section_openers.dps_a_right;
    if (dpsAL) {
      const [aL, aR] = await pageDoublespread("The Work", dpsAL, "From every intersection, a statement.", undefined, dpsAR || dpsAL);
      frames.push(aL, aR);
    }
  }

  // Section 1 — Products
  const productsPage = frames.length + 1;
  frames.push(await pageSectionOpen("One", "Products.", d.section_openers && d.section_openers.products));
  for (const prod of (d.products || [])) {
    frames.push(await pageProductHero(prod));
    frames.push(await pageProductSpec(prod));
  }
  // Double-page spread at end of products — pure editorial punch, no product content.
  // Left: editorial_products image. Right: different image (projects section opener).
  {
    const dpsImg = (d.section_openers && d.section_openers.editorial_products)
      || (d.section_openers && d.section_openers.applications)
      || (d.projects && d.projects[1] && d.projects[1].hero);
    const dpsImgR = (d.section_openers && d.section_openers.editorial_products_r)
      || (d.section_openers && d.section_openers.projects)
      || (d.products && d.products[2] && d.products[2].hero);
    if (dpsImg) {
      const [sL, sR] = await pageDoublespread("In the Field", dpsImg, "Designed for the city. Built for the street.", undefined, dpsImgR);
      frames.push(sL, sR);
    }
  }

  // Section 2 — Applications
  const appsPage = frames.length + 1;
  frames.push(await pageSectionOpen("Two", "Applications.", d.section_openers && d.section_openers.applications));
  const nApps = (d.applications || []).length;
  let appIdx = 0;
  for (const app of (d.applications || [])) {
    appIdx++;
    frames.push(await pageApplication(app, appIdx, nApps));
  }

  // DPS-B — transition between Applications and Projects. Full-bleed visual breather.
  // Keys: dps_b_left / dps_b_right.
  {
    const dpsBL = d.section_openers && d.section_openers.dps_b_left;
    const dpsBR = d.section_openers && d.section_openers.dps_b_right;
    if (dpsBL) {
      const [bL, bR] = await pageDoublespread("Across Canada", dpsBL, "Five hundred municipalities. One standard.", undefined, dpsBR || dpsBL);
      frames.push(bL, bR);
    }
  }

  // Section 3 — Projects
  const projectsPage = frames.length + 1;
  frames.push(await pageSectionOpen("Three", "Projects.", d.section_openers && d.section_openers.projects));
  let projIdx = 0;
  const projs = d.projects || [];
  for (let pi = 0; pi < projs.length; pi++) {
    projIdx++;
    frames.push(await pageProjectHero(projs[pi]));
    frames.push(await pageProjectStory(projs[pi], projIdx));
    // Double-page spread halfway through projects — visual pause between project stories.
    // Left: editorial_projects image. Right: reference section opener (different category).
    if (pi === Math.floor(projs.length / 2) - 1) {
      const dpsImg2 = (d.section_openers && d.section_openers.editorial_projects)
        || (d.section_openers && d.section_openers.reference)
        || (projs[0] && projs[0].detail);
      const dpsImg2R = (d.section_openers && d.section_openers.editorial_projects_r)
        || (d.section_openers && d.section_openers.reference)
        || (projs[projs.length - 1] && projs[projs.length - 1].detail);
      if (dpsImg2) {
        const [sL2, sR2] = await pageDoublespread("Every Mark", dpsImg2, "Every mark tells a story.", undefined, dpsImg2R);
        frames.push(sL2, sR2);
      }
    }
  }

  // Section 4 — Network
  const networkPage = frames.length + 1;
  frames.push(await pageNetworkOpen(d));
  const installs = d.installers || [];
  for (let ii = 0; ii < installs.length; ii++) {
    frames.push(await pageInstaller(installs[ii], ii + 1, installs.length));
  }

  // DPS-C — between Network and Reference. Visual breathing room before back matter.
  // Keys: dps_c_left / dps_c_right.
  {
    const dpsCL = d.section_openers && d.section_openers.dps_c_left;
    const dpsCR = d.section_openers && d.section_openers.dps_c_right;
    if (dpsCL) {
      const [cL, cR] = await pageDoublespread("Built to Last", dpsCL, "The surface underfoot. The city above.", undefined, dpsCR || dpsCL);
      frames.push(cL, cR);
    }
  }

  // Section 5 — Reference
  const referencePage = frames.length + 1;
  frames.push(await pageSectionOpen("Five", "Reference.", d.section_openers && d.section_openers.reference));
  frames.push(await pageTechnical());
  frames.push(await pageCities(d));
  const lunchPage = frames.length + 1;
  frames.push(await pageLunchLearn(d.brand && d.brand.mascot));
  const contactPage = frames.length + 1;
  frames.push(await pageContact(d));
  // Field Notes: a ruled notepad page — faces the Contact page in the open spread.
  // Specifier reads your contact info on the left, picks up a pen on the right. Very hot.
  frames.push(await pageFieldNotes());

  // Final editorial double-page spread — dramatic closing statement before the back matter.
  // DPS3 — Spirit Trail closing spread. editorial_closing key = Spirit Trail B&W swirl crosswalk (Vancouver).
  // Cinematic full-stop before back matter. Falls back through reference if key is absent.
  {
    const closingImg = (d.section_openers && d.section_openers.editorial_closing)
      || (d.section_openers && d.section_openers.reference);
    if (closingImg) {
      const [sL3, sR3] = await pageDoublespread("The Mark", closingImg, "Specified. Installed. Built to outlast.", "navy");
      frames.push(sL3, sR3);
    }
  }

  // Pad to next multiple of 4 — saddle-stitch / perfect-bind requirement.
  // No upper-bound cap. Content count + 3 closing must be divisible by 4.
  while ((frames.length + 3) % 4 !== 0) {
    frames.push(await pageBlank(frames.length + 1));
  }

  // Closing pair + back cover
  // pageService ("Specified. Installed. Backed.") removed — DPS3 right already delivers this moment.
  frames.push(await pageClosing());
  frames.push(await pageQuietMark(d));
  frames.push(await pageBack(d));

  // TOC — v50 parity. Labels match section opener titles exactly; Lunch
  // & Learn added (CTA destination with QR). Editorial front matter
  // (Manifesto, Why HUB) is not listed; readers encounter it naturally.
  const tocEntries = [
    ["Products",       productsPage],
    ["Applications",   appsPage],
    ["Projects",       projectsPage],
    ["Network",        networkPage],
    ["Reference",      referencePage],
    ["Lunch & Learn",  lunchPage],
    ["Contact",        contactPage],
  ];
  frames[2] = await pageTOC(tocEntries, frames.length);

  // Prefix every frame name with its print page number so the Figma sidebar
  // and the TOC can be cross-referenced at a glance (p01, p02 … p100).
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (f) f.name = "p" + String(i + 1).padStart(2, "0") + " — " + f.name;
  }

  // TOC note: productsPage, appsPage, etc. are computed dynamically at the moment
  // each section is pushed into frames[], so TOC page numbers are always correct
  // regardless of front-matter changes. No hardcoded numbers anywhere.

  // Add folios to content pages (skip cover, section openers, DPS, blanks, quarter-ads).
  const _noFolioNames = new Set(["Cover", "Back Cover", "Half Title"]);
  const _noFolioPrefix = ["Rest ", "Section ", "Spread ", "QuarterAd", "By the Numbers"];
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (!f) continue;
    const raw = f.name.replace(/^p\d+ — /, "");
    if (_noFolioNames.has(raw)) continue;
    if (_noFolioPrefix.some(p => raw.startsWith(p))) continue;
    await addFolio(f, i + 1);
  }

  // Layout all frames in a grid and append to current page
  const COL = 10, GAP = 40;
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (!f) continue;
    f.x = (i % COL) * (450 + GAP);
    f.y = Math.floor(i / COL) * (450 + GAP);
    figma.currentPage.appendChild(f);
  }

  figma.viewport.scrollAndZoomIntoView([frames[0]]);
  figma.notify(
    "✓ " + frames.length + " pages built  ·  " +
    "Products p" + productsPage +
    "  ·  Apps p" + appsPage +
    "  ·  Projects p" + projectsPage +
    "  ·  Network p" + networkPage +
    "  ·  Ref p" + referencePage
  );
}

figma.ui.onmessage = async (msg) => {
  if (msg.type === "build") {
    try {
      await buildCatalogue(EMBEDDED_DATA);
      figma.closePlugin("Done!");
    } catch (e) {
      const m = (e && e.message) ? e.message : String(e);
      figma.notify("Build error: " + m, {error: true});
      console.error(e);
      figma.closePlugin();
    }
  } else {
    figma.closePlugin();
  }
};

figma.showUI(__html__, {width: 320, height: 200});
"""


def _generate_qr(dest_path: Path) -> bool:
    """Generate a hubss.com QR code PNG at dest_path. Returns True on success."""
    try:
        import qrcode  # pip install qrcode[pil]
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=12,
            border=3,
        )
        qr.add_data("https://hubss.com")
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        img.save(dest_path)
        print(f"  QR → {dest_path.name}")
        return True
    except ImportError:
        print("  QR skipped (pip install qrcode[pil] to enable)")
        return False


def main():
    if not DATA.exists():
        print(f"ERROR: {DATA} not found. Run: python -B -m src.export_json first.")
        return

    # Generate QR code as side-effect — embed_images.py will embed it from catalog_data.json path
    qr_path = ROOT / "public" / "images" / "assets" / "qr" / "hubss-qr.png"
    _generate_qr(qr_path)

    data = json.loads(DATA.read_text(encoding="utf-8"))
    data_json = json.dumps(data, ensure_ascii=False, separators=(",", ":"))

    # Inject the catalog data into the JS template
    code = JS.replace("CATALOG_DATA_JSON", data_json, 1)

    PLUGIN.write_bytes(code.encode("utf-8"))
    size_kb = PLUGIN.stat().st_size / 1024
    print(f"Wrote {PLUGIN.name}  ({size_kb:.0f} KB)")
    print(f"Frames: ~100 pages, all text live, photos = [PHOTO] placeholders")
    print(f"In Figma: remove old plugin, re-import manifest, click Build.")


if __name__ == "__main__":
    main()
