"""
generate_plugin.py — Write a clean, minimal code.js from catalog_data.json.

The embedded-image version of code.js reaches ~74 MB, which exceeds Figma's
plugin sandbox and prevents loading. This script generates a fresh ~100-200 KB
plugin that builds all 100 Figma frames with:
  - Correct frame names, background colours, navy bands, orange accents
  - All product/project text (name, tagline, body, callout, uses...)
  - Neutral light-grey [PHOTO] placeholder rectangles for every photo slot
  - Correct page order matching the PDF exactly

Usage:
    python -B -m src.export_json          # regenerate catalog_data.json
    python -B -m src.generate_plugin      # write fresh code.js
    python -B -m src.embed_images --lite  # MANDATORY: embed images at
                                          # review quality (~22 MB).
                                          # NEVER ship --print (~67 MB)
                                          # to Vernon — it crashes his
                                          # 30 GB Figma machine.
    Then in Figma: remove plugin, re-import manifest, click Build.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT   = Path(__file__).resolve().parent.parent
DATA   = ROOT / "output" / "catalog_data.json"
PLUGIN = ROOT / "figma-plugin" / "code.js"

# ---------------------------------------------------------------------------
# The Figma plugin JavaScript — embedded as a Python string.
# CATALOG_DATA_JSON is replaced with the actual JSON before writing.
# ---------------------------------------------------------------------------
JS = r"""
"use strict";
// HUBSS Catalogue Builder — generated by src/generate_plugin.py
// IMAGE_BANK is injected by src/embed_images.py after this file is written.
// Without embed_images, photo slots degrade gracefully to [PHOTO] placeholders.
// PLUGIN_VERSION = v52.2 (overnight QA pass)
//   v52.2 (Phase 5): layer naming extended to Hub Numbers + Statement;
//        per-page safeBuild() wrapper so a single failure surfaces as a
//        red "FAILED — <reason>" frame instead of killing the whole
//        catalogue; design system expanded to 22 text styles + 6 paint
//        styles, each mapped 1:1 to print typography roles.
//   v52: L&L parity with v48 print (QR + raised moose + tight copy);
//        extended layer-naming pass on Cover, Product Hero, Product Spec,
//        Application, Project Hero, Project Story, Installer, Contact,
//        Back Cover, DPS-L; design system idempotent (v51 carryover).
//   v52.1 (overnight parity sweep): closed deep-divergence gaps surfaced
//        by Phase 2 audit — Cover navy wash 50%, Half Title orange dot at
//        (222,393), Manifesto h1 size 36 weight=800, Why Stats 32pt title
//        + 34pt orange num, Why Proof 19pt headline + 6.5pt eyebrow,
//        TOC "What's Inside" + 32pt display + dot-led rows, Product Hero
//        photo bleed-extended (-12,-12,474,310) + Medium tagline,
//        Product Spec BAND_H=82, 2-col [28,230] spec grid, drop callout,
//        body 9.5/subhead 10.5, Project Hero/Story/Application photos
//        bleed-extended, Installer name 28pt body 9.5, Back Cover URL 11pt.

const IMAGE_BANK = {};
const EMBEDDED_DATA = CATALOG_DATA_JSON;

// --- colour tokens ---
const O  = {r:0.976, g:0.451, b:0.086};  // HUBSS orange
const N  = {r:0.047, g:0.063, b:0.125};  // HUBSS navy rich
const W  = {r:1,     g:1,     b:1    };  // white
const D  = {r:0.12,  g:0.12,  b:0.12 };  // near-black body
const M  = {r:0.45,  g:0.45,  b:0.45 };  // mid grey
const F  = {r:0.65,  g:0.65,  b:0.65 };  // faint
const PH = {r:0.93,  g:0.93,  b:0.93 };  // v51: neutral light-grey photo placeholder (cream retired — Vernon: 'no cream background colors')

// --- low-level helpers ---
function fr(name, bg) {
  const f = figma.createFrame();
  f.name = name;
  f.resize(450, 450);
  f.clipsContent = true;
  f.fills = [{type:"SOLID", color: bg || W}];
  return f;
}

function rct(p, x, y, w, h, col, name) {
  const r = figma.createRectangle();
  r.resize(Math.max(1, Math.round(w)), Math.max(1, Math.round(h)));
  r.x = Math.round(x);
  r.y = Math.round(y);
  r.fills = [{type:"SOLID", color: col}];
  if (name) r.name = name;
  p.appendChild(r);
  return r;
}

function base64ToBytes(b64) {
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}

// ph() — photo rect: FILL mode crops to frame (correct for photos).
// Tries filename-only key first, full path as fallback.
function ph(p, x, y, w, h, label, imagePath) {
  const r = rct(p, x, y, w, h, PH, "[PHOTO] " + (label || ""));
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");   // parent/filename — unique key matching embed_images.py
    const fname = parts[parts.length - 1];    // filename-only fallback
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FILL", imageHash: img.hash}];
        r.name = label || "Photo";
      } catch(e) { /* keep placeholder */ }
    }
  }
  return r;
}

// phFit() — like ph() but FIT mode: shows entire image, may letterbox.
// Use when the subject (crosswalk decal, marking) must not be cropped at any edge.
function phFit(p, x, y, w, h, label, imagePath) {
  const r = rct(p, x, y, w, h, PH, "[PHOTO] " + (label || ""));
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");
    const fname = parts[parts.length - 1];
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FIT", imageHash: img.hash}];
        r.name = label || "Photo";
      } catch(e) {}
    }
  }
  return r;
}

// logo() — like ph() but uses FIT mode so the full wordmark is never cropped.
// Transparent fill when no image is present (looks clean over any background).
function logo(p, x, y, w, h, label, imagePath) {
  const r = figma.createRectangle();
  r.resize(Math.max(1, Math.round(w)), Math.max(1, Math.round(h)));
  r.x = Math.round(x);
  r.y = Math.round(y);
  r.fills = [];
  r.name = "[LOGO] " + (label || "");
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");
    const fname = parts[parts.length - 1];
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FIT", imageHash: img.hash}];
        r.name = label || "Logo";
      } catch(e) {}
    }
  }
  p.appendChild(r);
  return r;
}

function rul(p, x, y, w) {
  return rct(p, x, y, w, 2, O, "OrangeRule");
}

// tx() — all text creation goes through here.
// lh: explicit line height in px; if omitted, auto-computed for print-quality rhythm.
//   Body (sz < 11):  lh = sz × 1.55  (generous open leading, readable at small sizes)
//   Display (sz ≥ 11): lh = sz × 1.18  (tight but not cramped for headlines)
async function tx(p, text, x, y, sz, col, bold, maxW, align, lh) {
  if (!text || text === "") return null;
  const t = figma.createText();
  // v48 — Vernon: 'thin font on web' complaint. Inter Regular reads
  // visibly lighter than the print PDF's Helvetica Regular. Bumping
  // the non-bold default to Medium gives the on-screen Figma render
  // visual weight parity with what Doug sees in the printed catalogue.
  t.fontName = {family: "Inter", style: bold ? "Bold" : "Medium"};
  t.characters = String(text);
  t.fontSize = Math.round(sz);
  t.fills = [{type:"SOLID", color: col}];
  // Always set explicit line height — eliminates Figma's auto-leading inconsistencies
  // Display sizes (sz >= 11): tight 1.08× for print-quality heading rhythm
  const lineH = lh || (sz < 11 ? Math.round(sz * 1.55) : Math.round(sz * 1.08));
  t.lineHeight = {value: lineH, unit: "PIXELS"};
  if (maxW) {
    t.textAutoResize = "HEIGHT";
    t.resize(Math.max(10, Math.round(maxW)), 400);
  }
  if (align === "center") t.textAlignHorizontal = "CENTER";
  if (align === "right")  t.textAlignHorizontal = "RIGHT";
  t.x = Math.round(x);
  t.y = Math.round(y);
  p.appendChild(t);
  return t;
}

function navyBand(p, h) {
  rct(p, 0, 0, 450, Math.round(h), N, "NavyBand");
}

// --- page builders ---

async function pageCover(d) {
  const f = fr("Cover", N);
  // v52 parity with print page_cover: full-bleed photo + 50% navy wash
  // full-frame (Vernon v46: 'navy wash KEPT on cover, removed everywhere
  // else'). Restrained color logo top-LEFT + bottom masthead.
  ph(f, 0, 0, 450, 450, "Cover / Photo / Hero", d.cover_photo);
  // 50% navy wash — quietens busy photo for type legibility
  const wash = rct(f, 0, 0, 450, 450, N, "Cover / Navy Wash (50%)");
  wash.opacity = 0.50;
  // White-text logo top-LEFT (Vernon's call)
  logo(f, 28, 28, 110, 22, "Cover / Logo / HUBSS White", d.brand && d.brand.logo_white);
  // Bottom masthead — print uses mixed case "Decorative Pavement Solutions"
  const t1 = await tx(f, "Catalogue 2026.", 28, 370, 30, W, true, 394);
  if (t1) t1.name = "Cover / Display / Masthead";
  const t2 = await tx(f, "DECORATIVE PAVEMENT SOLUTIONS", 28, 410, 8, W, false, 394, null, 11);
  if (t2) { t2.letterSpacing = {value: 16, unit: "PERCENT"}; t2.name = "Cover / Eyebrow / Tagline"; }
  return f;
}

async function pageHalfTitle(d) {
  const f = fr("Half Title");
  // v52 parity with print page_half_title: logo centred at fy=200, two
  // tracked-caps lines (Catalogue 2026 + Established 1994), single orange
  // dot near bottom at (225, 395) as quiet brand pickup.
  logo(f, 135, 200, 180, 40, "Half Title / Logo / HUBSS Colour", d.brand && d.brand.logo_color);
  const cap1 = await tx(f, "CATALOGUE 2026", 25, 265, 7.5, M, false, 400, "center", 11);
  if (cap1) { cap1.letterSpacing = {value: 16, unit: "PERCENT"}; cap1.name = "Half Title / Caps / Catalogue"; }
  const cap2 = await tx(f, "ESTABLISHED 1994", 25, 283, 6.5, F, false, 400, "center", 10);
  if (cap2) { cap2.letterSpacing = {value: 16, unit: "PERCENT"}; cap2.name = "Half Title / Caps / Established"; }
  // Orange brand dot at fy=395 — print uses ellipse, not horizontal rule
  const dot = figma.createEllipse();
  dot.resize(5, 5);
  dot.x = 222; dot.y = 393;
  dot.fills = [{type:"SOLID", color: O}];
  dot.name = "Half Title / Orange Dot";
  f.appendChild(dot);
  return f;
}

async function pageManifesto(d) {
  const f = fr("03 — Manifesto");
  const m = d.manifesto || {};
  // v52 parity with print page_manifesto: eyebrow at fy=70 size=7.5,
  // h1 lines at fy=120 size=36 weight=800 (leading 42), body at size=10
  // leading=16, brand-rule + signature near bottom.
  const eb = await tx(f, (m.eyebrow||"WHO WE ARE").toUpperCase(), 40, 70, 7.5, O, true, 380, null, 11);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Manifesto / Eyebrow"; }
  let y = 120;
  const lines = m.h1_lines || ["The street", "is the canvas.", "We supply the paint."];
  for (let i = 0; i < lines.length; i++) {
    const col = (i === (m.h1_orange_line || 0)) ? O : D;
    const t = await tx(f, lines[i], 40, y, 36, col, true, 380, null, 42);
    if (t) t.name = "Manifesto / H1 / Line " + (i + 1);
    y += 42;
  }
  const body = await tx(f, m.body || "", 40, y + 20, 10, D, false, 350, null, 16);
  if (body) body.name = "Manifesto / Body";
  rct(f, 40, 393, 56, 2, O, "Manifesto / Brand Rule");
  const sig = await tx(f, (m.signature || "").toUpperCase(), 40, 410, 6.5, F, false, 350, null, 9);
  if (sig) { sig.letterSpacing = {value: 16, unit: "PERCENT"}; sig.name = "Manifesto / Signature"; }
  return f;
}

async function pageWhyStats(d) {
  const f = fr("04 — Why HUB Stats");
  const w = d.why_hub || {};
  // v52 parity with print page_why_stats: eyebrow at fy=50 size=7.5,
  // title lines at fy=88 size=32 weight=800, stat cards 2×2 with cell_w=195
  // cell_h=90 starting fy=240, orange num size=34, white label size=7,
  // grey sub size=7.5.
  const eb = await tx(f, (w.eyebrow||"WHY HUB").toUpperCase(), 40, 50, 7.5, O, true, 380, null, 11);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Why Stats / Eyebrow"; }
  let y = 88;
  for (let i = 0; i < (w.title_lines || []).length; i++) {
    const t = await tx(f, (w.title_lines)[i], 40, y, 32, D, true, 380, null, 38);
    if (t) t.name = "Why Stats / Title / Line " + (i + 1);
    y += 38;
  }
  if (w.subtitle) {
    const sub = await tx(f, w.subtitle, 40, y + 4, 11, M, false, 400, null, 15);
    if (sub) sub.name = "Why Stats / Subtitle";
  }
  const stats = w.stats || [];
  const cw = 195, ch = 90, gy = 240;
  for (let i = 0; i < Math.min(stats.length, 4); i++) {
    const col = i % 2, row = Math.floor(i / 2);
    const gx = 30 + col * (cw + 8), gyy = gy + row * (ch + 4);
    rct(f, gx, gyy, cw, ch, N, "Why Stats / Card " + (i + 1));
    const num = await tx(f, String(stats[i][0]||""), gx+8, gyy+10, 34, O, true, cw-16, null, 38);
    if (num) num.name = "Why Stats / Card " + (i + 1) + " / Number";
    const lbl = await tx(f, String(stats[i][1]||"").toUpperCase(), gx+8, gyy+52, 7, W, true, cw-16, null, 10);
    if (lbl) { lbl.letterSpacing = {value: 16, unit: "PERCENT"}; lbl.name = "Why Stats / Card " + (i + 1) + " / Label"; }
    const sub = await tx(f, String(stats[i][2]||""), gx+8, gyy+64, 7.5, M, false, cw-16, null, 10);
    if (sub) sub.name = "Why Stats / Card " + (i + 1) + " / Subline";
  }
  const rule = rct(f, 40, 430, 56, 2, O, "Why Stats / Brand Rule");
  return f;
}

async function pageWhyProof(d) {
  const f = fr("05 — Why HUB Proof");
  const w = d.why_hub || {};
  // v52 parity with print page_why_proof: "Four Reasons" mixed-case caps
  // at fy=50 size=6.5, two-line headline at size=19 weight=800, proof rows
  // starting fy=160 with num/claim/detail, brand rule at fy=430.
  const eb = await tx(f, "FOUR REASONS", 40, 50, 6.5, O, true, 380, null, 10);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Why Proof / Eyebrow"; }
  const h1a = await tx(f, "If it goes on the street,", 40, 74, 19, D, true, 380, null, 24);
  if (h1a) h1a.name = "Why Proof / Headline / Line 1";
  const h1b = await tx(f, "it stays on the street.", 40, 100, 19, O, true, 380, null, 24);
  if (h1b) h1b.name = "Why Proof / Headline / Line 2";
  let y = 160;
  let pi = 0;
  for (const [num, claim, detail] of (w.proof || [])) {
    pi++;
    const numT = await tx(f, String(num), 40, y, 6.0, O, true, 30, null, 9);
    if (numT) { numT.letterSpacing = {value: 16, unit: "PERCENT"}; numT.name = "Why Proof / Row " + pi + " / Num"; }
    const claimT = await tx(f, claim, 80, y, 11, D, true, 340, null, 14);
    if (claimT) claimT.name = "Why Proof / Row " + pi + " / Claim";
    const detT = await tx(f, detail, 80, y+16, 8, M, false, 340, null, 11);
    if (detT) detT.name = "Why Proof / Row " + pi + " / Detail";
    rct(f, 40, y+50, 380, 1, F, "Why Proof / Row " + pi + " / Divider");
    y += 60;
  }
  rct(f, 40, 430, 56, 2, O, "Why Proof / Brand Rule");
  return f;
}

async function pageTOC(sections, totalPages) {
  const f = fr("Contents");
  // v52 parity with print page_toc: "What's Inside" mixed-case caps at
  // fy=60 size=7.5, "Catalogue 2026." display at fy=88 size=32 weight=800,
  // section items starting fy=160 with orange-dot + label + page#,
  // 26px row stride. NOT the smaller "Contents." treatment.
  const eb = await tx(f, "WHAT'S INSIDE", 40, 60, 7.5, O, true, 380, null, 11);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "TOC / Eyebrow"; }
  const disp = await tx(f, "Catalogue 2026.", 40, 88, 32, D, true, 380, null, 38);
  if (disp) disp.name = "TOC / Display";
  let y = 160;
  for (let i = 0; i < sections.length; i++) {
    const [label, num] = sections[i];
    const dot = figma.createEllipse();
    dot.resize(3, 3);
    dot.x = 42; dot.y = y + 6;
    dot.fills = [{type:"SOLID", color: O}];
    dot.name = "TOC / Row " + (i + 1) + " / Dot";
    f.appendChild(dot);
    const lbl = await tx(f, label, 52, y, 10, D, true, 300, null, 14);
    if (lbl) lbl.name = "TOC / Row " + (i + 1) + " / Label";
    const pg = await tx(f, String(num), 28, y, 10, D, true, 392, "right", 14);
    if (pg) pg.name = "TOC / Row " + (i + 1) + " / Page #";
    rct(f, 40, y + 18, 380, 1, F, "TOC / Row " + (i + 1) + " / Rule");
    y += 26;
  }
  // Footer — dynamic page count, right-aligned
  const pg = await tx(f, String(totalPages || 100) + " pages", 40, y + 16, 6, F, false, 380, "right", 9);
  if (pg) pg.name = "TOC / Footer / Page Count";
  return f;
}

async function pageSectionOpen(num, title, imagePath) {
  const f = fr(`p__ / Section ${num} — ${title}`, N);
  // v50 parity (print page_section_open at final_catalog.py:513) —
  // Vernon: 'Section One could stand out more.' Orange dot pre-element,
  // rule UNDER the eyebrow, 64pt display, tracking -2.0.
  ph(f, 0, 0, 450, 450, "Section Opener / Photo / " + title, imagePath);
  // Orange dot — visual brand anchor
  const dot = figma.createEllipse();
  dot.resize(7, 7); dot.x = 22; dot.y = 320;
  dot.fills = [{type:"SOLID", color: O}];
  dot.name = "Section Opener / Dot";
  f.appendChild(dot);
  await tx(f, ("SECTION " + num).toUpperCase(), 34, 318, 8.5, W, false, 394, null, 13);
  rul(f, 28, 338, 44);   // rule UNDER eyebrow, not under the entire band
  f.children[f.children.length-1].name = "Section Opener / Brand Rule";
  await tx(f, title, 28, 358, 64, W, true, 394);
  // Name the last text node so layer panel reads cleanly
  const lastTx = f.children[f.children.length-1];
  if (lastTx && lastTx.type === "TEXT") lastTx.name = "Section Opener / Display Title";
  return f;
}

async function pageProductHero(prod) {
  const f = fr("Hero — " + prod.name, W);
  // v52 parity with print page_product_hero: photo extends through bleed
  // (x=-12, y=-12, w=474, h=310 — print: 'fx=-12, fy=-12, fw=474, fh=310'),
  // eyebrow dot at (28, 325 r=1.3), product name caps at (34, 322 size=7.5),
  // tagline at (28, 350 size=22 dark, no italic).
  ph(f, -12, -12, 474, 310, "Product Hero / Photo / " + prod.name, prod.hero);
  // Orange dot — circular accent (print uses orange_dot, not a square rect)
  const dot = figma.createEllipse();
  dot.resize(3, 3);
  dot.x = 28; dot.y = 324;
  dot.fills = [{type:"SOLID", color: O}];
  dot.name = "Product Hero / Orange Dot";
  f.appendChild(dot);
  const eb = await tx(f, (prod.name||"").toUpperCase(), 34, 322, 7.5, O, true, 394, null, 11);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Product Hero / Eyebrow / " + prod.name; }
  // Display tagline — Medium weight (Vernon v48: NO Inter Bold, NO italic, NO serif)
  const tag = figma.createText();
  tag.fontName = {family: "Inter", style: "Medium"};
  tag.characters = prod.tagline || "";
  tag.fontSize = 22;
  tag.fills = [{type:"SOLID", color: D}];
  tag.lineHeight = {value: 26, unit: "PIXELS"};
  tag.letterSpacing = {value: -1.4, unit: "PERCENT"};
  tag.textAutoResize = "HEIGHT";
  tag.resize(394, 400);
  tag.x = 28; tag.y = 350;
  tag.name = "Product Hero / Tagline";
  f.appendChild(tag);
  return f;
}

async function pageProductSpec(prod) {
  const f = fr("Spec — " + prod.name);
  // v52 parity with print page_product_spec (v29 refinement):
  //   - Slim navy band BAND_H=82 (was 118), not 116
  //   - Category eyebrow drives hierarchy from top (fy=18, size=5.5)
  //   - Product name fy=32, size=22 weight=800 (NOT 24)
  //   - Orange signature dash fy=64 (6px below name baseline)
  //   - Title fy=108 (dynamic display size — we hardcode 22), subhead fy~140 size=10.5
  //   - Body fy~168 size=9.5
  //   - Callout row REMOVED — v29 dropped it, key facts live in body + grid
  //   - Spec grid: 2-col [28, 230], 4 entries max, stride 34 starting fy=328
  //   - Uses joined caps centered, fy=414 size=6.5
  const BAND_H = 82;
  rct(f, 0, 0, 450, BAND_H, N, "Product Spec / Header / Navy Band");
  const tEb = await tx(f, ((prod.category || "HUB Surface Systems")).toUpperCase(), 28, 18, 5.5, O, true, 394, null, 8);
  if (tEb) { tEb.letterSpacing = {value: 16, unit: "PERCENT"}; tEb.name = "Product Spec / Header / Category Eyebrow"; }
  const tName = await tx(f, prod.name || "", 28, 32, 22, W, true, 394, null, 26);
  if (tName) tName.name = "Product Spec / Header / Product Name";
  rct(f, 28, 64, 32, 2, O, "Product Spec / Header / Orange Signature Dash");

  // Body zone
  const title = prod.title || prod.name;
  const tT = await tx(f, title, 28, 108, 22, D, true, 394, null, 26);
  if (tT) tT.name = "Product Spec / Body / Title";
  const tI = await tx(f, prod.italic || "", 28, 144, 10.5, M, false, 394, null, 15);
  if (tI) tI.name = "Product Spec / Body / Subhead";
  const tB = await tx(f, prod.body || "", 28, 176, 9.5, D, false, 394, null, 14);
  if (tB) tB.name = "Product Spec / Body / Description";

  // Spec grid — 2-col, 4 entries max (matches print)
  if (prod.spec_pairs && prod.spec_pairs.length) {
    rct(f, 28, 312, 394, 1, F, "Product Spec / Spec Grid / Rule");
    const colX = [28, 230];
    for (let i = 0; i < Math.min(prod.spec_pairs.length, 4); i++) {
      const [lbl, val] = prod.spec_pairs[i];
      const col = i % 2, row = Math.floor(i / 2);
      const xx = colX[col], yy = 328 + row * 34;
      const tL = await tx(f, (lbl||"").toUpperCase(), xx, yy, 6.0, F, true, 190, null, 9);
      if (tL) { tL.letterSpacing = {value: 16, unit: "PERCENT"}; tL.name = "Product Spec / Spec Grid / Row " + (i + 1) + " / Label"; }
      const tV = await tx(f, val||"", xx, yy+11, 8.5, D, true, 185, null, 11);
      if (tV) tV.name = "Product Spec / Spec Grid / Row " + (i + 1) + " / Value";
    }
  }

  // Uses footer — joined caps centered
  if (prod.uses && prod.uses.length) {
    rct(f, 28, 405, 394, 1, F, "Product Spec / Footer / Uses Rule");
    const tU = await tx(f, prod.uses.join("   ·   ").toUpperCase(), 25, 414, 6.5, M, true, 400, "center", 10);
    if (tU) { tU.letterSpacing = {value: 16, unit: "PERCENT"}; tU.name = "Product Spec / Footer / Uses"; }
  }
  return f;
}

async function pageApplication(app, idx, total) {
  const f = fr(`App ${String(idx).padStart(2,"0")} — ${app.name}`);
  // v52 parity with print page_application: photo bleed-extended
  // (x=-12, y=-12, w=474, h=296), orange-dot ellipse + caps eyebrow,
  // display tagline size=18 weight=800 tracking=-0.4, body size=8.5 mid.
  ph(f, -12, -12, 474, 296, "Application / Photo / " + app.name, app.image);
  const dot = figma.createEllipse();
  dot.resize(3, 3); dot.x = 28; dot.y = 324;
  dot.fills = [{type:"SOLID", color: O}];
  dot.name = "Application / Orange Dot";
  f.appendChild(dot);
  const eb = await tx(f, (app.name||"").toUpperCase(), 34, 322, 7.5, O, true, 394, null, 11);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Application / Eyebrow / " + app.name; }
  const tag = await tx(f, app.tagline || "", 28, 350, 18, D, true, 394, null, 22);
  if (tag) tag.name = "Application / Tagline";
  const body = await tx(f, app.body || "", 28, 388, 8.5, M, false, 394, null, 12);
  if (body) body.name = "Application / Body";
  const url = await tx(f, "HUBSS.COM", 28, 435, 5.5, O, true, 394, "right", 9);
  if (url) { url.letterSpacing = {value: 16, unit: "PERCENT"}; url.name = "Application / Footer / URL"; }
  return f;
}

async function pageProjectHero(proj) {
  const f = fr("Hero — " + proj.name, W);
  // v52 parity with print page_project_hero: photo bleed-extended
  // (x=-12, y=-12, w=474, h=310), orange-dot ellipse + caps eyebrow,
  // display title size=20 dark + tracking=-0.3, location/product caps fy=414.
  ph(f, -12, -12, 474, 310, "Project Hero / Photo / " + proj.name, proj.hero);
  const dot = figma.createEllipse();
  dot.resize(3, 3); dot.x = 28; dot.y = 324;
  dot.fills = [{type:"SOLID", color: O}];
  dot.name = "Project Hero / Orange Dot";
  f.appendChild(dot);
  const eb = await tx(f, (proj.name||"").toUpperCase(), 34, 322, 7.5, O, true, 394, null, 11);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Project Hero / Eyebrow / " + proj.name; }
  const title = await tx(f, proj.title || "", 28, 350, 20, D, true, 394, null, 24);
  if (title) title.name = "Project Hero / Title";
  const loc = await tx(f, (proj.location||"").toUpperCase(), 28, 414, 6, M, true, 190, null, 9);
  if (loc) { loc.letterSpacing = {value: 16, unit: "PERCENT"}; loc.name = "Project Hero / Meta / Location"; }
  const prod = await tx(f, (proj.product||"").toUpperCase(), 232, 414, 6, O, true, 190, "right", 9);
  if (prod) { prod.letterSpacing = {value: 16, unit: "PERCENT"}; prod.name = "Project Hero / Meta / Product"; }
  return f;
}

async function pageProjectStory(proj, idx) {
  const f = fr(`Story ${String(idx).padStart(2,"0")} — ${proj.name}`);
  // v52 parity with print page_project_story: photo bleed-extended
  // (x=-12, y=-12, w=474, h=296), product caps eyebrow + dot, project
  // name display size=17, location+product caps fy=376 size=5.5,
  // story body size=8 mid.
  ph(f, -12, -12, 474, 296, "Project Story / Photo / " + proj.name, proj.detail || proj.hero);
  const eyebrowLabel = proj.product ? proj.product.toUpperCase() : ("PROJECT " + String(idx).padStart(2,"0"));
  const dot = figma.createEllipse();
  dot.resize(3, 3); dot.x = 28; dot.y = 324;
  dot.fills = [{type:"SOLID", color: O}];
  dot.name = "Project Story / Orange Dot";
  f.appendChild(dot);
  const eb = await tx(f, eyebrowLabel, 34, 322, 7.0, O, true, 394, null, 11);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Project Story / Eyebrow"; }
  const name = await tx(f, proj.name || "", 28, 348, 17, D, true, 394, null, 20);
  if (name) name.name = "Project Story / Title";
  const meta = await tx(f, ((proj.location||"") + "    " + (proj.product||"")).toUpperCase(), 28, 376, 5.5, F, true, 394, null, 8);
  if (meta) { meta.letterSpacing = {value: 16, unit: "PERCENT"}; meta.name = "Project Story / Meta"; }
  const story = await tx(f, proj.story || "", 28, 394, 8.0, M, false, 394, null, 11);
  if (story) story.name = "Project Story / Body";
  return f;
}

async function pageInstaller(inst, idx, total) {
  const f = fr("Installer — " + inst.name);
  // Navy header band — credential zone. Keeps photo uncluttered.
  navyBand(f, 152);
  const bandNode = f.children[f.children.length - 1];
  if (bandNode) bandNode.name = "Installer / Header / Navy Band";
  const t1 = await tx(f, "HUB CERTIFIED INSTALLER", 28, 28, 5.5, O, false, 260, null, 8);
  if (t1) t1.name = "Installer / Header / Credential";
  const t2 = await tx(f, String(idx).padStart(2,"0") + " / " + String(total).padStart(2,"0"), 28, 28, 5.5, {r:0.38,g:0.38,b:0.38}, false, 394, "right", 8);
  if (t2) t2.name = "Installer / Header / Counter";
  const tName = await tx(f, inst.name, 28, 52, 28, W, true, 394, null, 32);
  if (tName) tName.name = "Installer / Header / Name";
  const tRegion = await tx(f, (inst.region || "").toUpperCase(), 28, 102, 5.5, {r:0.45,g:0.45,b:0.45}, false, 394, null, 8);
  if (tRegion) tRegion.name = "Installer / Header / Region";
  const rule = rul(f, 28, 128, 32); if (rule) rule.name = "Installer / Header / Brand Rule";
  // Contained editorial photo
  ph(f, 0, 152, 450, 192, "Installer / Photo / " + inst.name, inst.image);
  // White content zone below photo
  const body = await tx(f, inst.body || "", 28, 360, 9.5, D, false, 394, null, 14);
  if (body) body.name = "Installer / Body";
  // Footer
  const ftrRule = rct(f, 28, 400, 394, 1, F, "Installer / Footer / Rule");
  const phone = await tx(f, inst.phone || "", 28, 410, 10, D, true, 190);
  if (phone) phone.name = "Installer / Footer / Phone";
  const url = await tx(f, inst.url || "", 238, 411, 9, O, false, 182);
  if (url) url.name = "Installer / Footer / URL";
  return f;
}

// pageNetworkOpen — v47 — matches v46 print section openers. Full-bleed
// photo + white display type on photo. No scrim, no navy bottom.
async function pageNetworkOpen(d) {
  const f = fr("Section Four — Network", N);
  ph(f, 0, 0, 450, 450, "Network section opener", d.section_openers && d.section_openers.network);
  rul(f, 28, 313, 28);
  await tx(f, "SECTION FOUR", 28, 322, 7.5, W, false, 394, null, 11);
  await tx(f, "Network.", 28, 350, 44, W, true, 394);
  return f;
}

// pageDoublespread — two facing pages that read as one editorial spread.
// Left page: headline anchored bottom-left (big idea, reading direction cue).
// Right page: matching image, CTA URL bottom-right (where to go next).
// The left→right pairing creates intentional narrative: statement → action.
async function pageDoublespread(label, imagePath, caption, rightStyle, rightImagePath) {
  // v47 — matches v46 print: no scrim on left, no footer band on right.
  // Type sits directly on the photo (eyebrow + caption white on photo).
  const fL = fr("Spread L — " + (label||""), N);
  ph(fL, 0, 0, 450, 450, "Spread L / Photo / " + label, imagePath);
  // FINAL PASS: book-wide overlay scrim (navy bottom band) + caption promoted
  // to the 21 display tier — mirrors the ReportLab print build (overlay_scrim).
  // NOTE: unverified in-plugin (Vern's run is the verification); the shipping
  // artifacts are the ReportLab print PDF + flipbook, which ARE verified.
  rct(fL, 0, 300, 450, 150, N, "Spread L / Overlay Scrim");
  fL.children[fL.children.length-1].opacity = 0.62;
  const lRule = rul(fL, 28, 316, 24); if (lRule) lRule.name = "Spread L / Brand Rule";
  const lEb = await tx(fL, (label||"").toUpperCase(), 28, 326, 7.5, O, false, 394, null, 11);
  if (lEb) lEb.name = "Spread L / Eyebrow";
  if (caption) {
    const lCap = await tx(fL, caption, 28, 344, 21, W, true, 394, null, 23);
    if (lCap) lCap.name = "Spread L / Caption";
  }

  // Right page — photo CTA by default; navy brand statement when rightStyle === "navy"
  const fR = fr("Spread R — " + (label||""), N);
  if (rightStyle === "navy") {
    // Closing editorial — navy, giant type, lands as a final statement.
    // INTENTIONAL navy: this is a typographic brand-statement spread,
    // not a photo overlay. Per Vernon's rule, navy is OK on type-only pages.
    rul(fR, 28, 80, 32);
    await tx(fR, "THIRTY YEARS IN THE MAKING.", 28, 96, 6, O, false, 394, null, 9);
    await tx(fR, "Built to", 28, 116, 52, W, true, 394);
    await tx(fR, "outlast.", 28, 180, 52, O, true, 394);
    rct(fR, 28, 248, 394, 1, {r:1,g:1,b:1}, "Divider");
    fR.children[fR.children.length-1].opacity = 0.15;
    await tx(fR, "30+ years   ·   1,000+ projects   ·   500+ municipalities", 28, 262, 7.5, M, false, 394, "center", 11);
    rct(fR, 28, 288, 394, 1, {r:1,g:1,b:1}, "Divider");
    fR.children[fR.children.length-1].opacity = 0.08;
    await tx(fR, "The surface beneath every city we've built.", 28, 308, 12, W, false, 360);
    await tx(fR, "Spec the surface. Watch it work. Walk over it for twenty years.", 28, 332, 8, M, false, 360);
    rct(fR, 28, 404, 394, 1, O, "OrangeRule");
    await tx(fR, "hubss.com", 28, 414, 7.5, O, true, 394, "right", 11);
  } else {
    // Photo right — full bleed, no footer band, URL on photo right-aligned
    ph(fR, 0, 0, 450, 450, label + " — right", rightImagePath || imagePath);
    await tx(fR, "hubss.com", 28, 426, 7.5, O, true, 394, "right", 11);
  }
  return [fL, fR];
}

// pageImageSpread — v47 full-bleed photo, no caption band. Type on photo.
async function pageImageSpread(label, imagePath, headline) {
  const f = fr("Spread — " + (label||""), N);
  ph(f, 0, 0, 450, 450, label, imagePath);
  rul(f, 30, 410, 30);
  if (headline) {
    await tx(f, headline.toUpperCase(), 68, 413, 6, W, false, 352);
  }
  return f;
}

async function pageTechnical() {
  const f = fr("Reference — Technical");
  await tx(f, "TECHNICAL REFERENCE", 30, 40, 7, O, false, 370);
  await tx(f, "At a Glance.", 30, 68, 24, D, true, 370);
  const prods = [
    ["TrafficPatternsXD", "Thermoplastic", "High-durability preformed marking"],
    ["TrafficPatterns",   "Thermoplastic", "Standard preformed marking"],
    ["StreetBond",        "MMA Coating",   "Decorative coloured pavement"],
    ["StreetPrint",       "Stamped Asphalt","Brick and stone patterns"],
    ["DecoMark",          "Epoxy",         "Coloured crosswalk systems"],
    ["MMAX",              "MMA Resin",     "Coloured lane treatment"],
    ["DuraTherm",         "Inlaid",        "Snowplow-safe flush inlay"],
    ["DuraShield",        "Penetrating",   "Asphalt rejuvenator"],
    ["PreMark",           "Pre-cut",       "Bike infrastructure markings"],
    ["AirMark",           "Airfield",      "FAA-compliant markings"],
  ];
  let y = 128;
  for (const [name, key, desc] of prods) {
    await tx(f, name, 30, y, 9, D, true, 148);
    await tx(f, key.toUpperCase(), 185, y, 6, O, false, 110);
    await tx(f, desc, 272, y, 8, M, false, 158);
    rct(f, 30, y+15, 390, 1, F, "rule");
    y += 22;
  }
  return f;
}

async function pageCities(d) {
  const f = fr("Reference — Cities");
  // "500+" as hero stat — visual anchor, gives the city list credibility and scale
  await tx(f, "500+", 30, 28, 60, O, true, 390);
  await tx(f, "Canadian municipalities", 30, 98, 9, D, false, 280, null, 13);
  await tx(f, "that specify HUB systems by name.", 30, 113, 9, M, false, 280, null, 13);
  await tx(f, "FROM HALIFAX TO VANCOUVER", 30, 133, 5.5, F, false, 390, null, 8);
  rct(f, 30, 150, 390, 1, F, "rule");
  await tx(f, "A partial list", 30, 158, 7, M, false, 390, "right", 10);
  // City list — 2 columns, 8px type, generous spacing
  const cities = d.cities || [];
  let y = 172;
  for (let i = 0; i < cities.length; i += 2) {
    if (y > 418) break;
    await tx(f, cities[i]||"", 30, y, 8, D, false, 185);
    if (cities[i+1]) await tx(f, cities[i+1], 235, y, 8, D, false, 175);
    y += 13;
  }
  return f;
}

async function pageLunchLearn(d) {
  // v52 — Parity with v48 print L&L (final_catalog.py page_lunch_learn).
  // 3-zone layout: LEFT eyebrow/display/body/3-dot list, RIGHT TOP moose
  // (raised), RIGHT BOTTOM 1" QR on white plate + 'Scan to book' caption,
  // FOOTER full-width orange rule + URL + 2 contacts.
  const f = fr("CTA — Lunch and Learn", W);
  const LEFT_X = 28, LEFT_W = 215;

  // Moose — right column upper, raised so QR has clean room below it
  const mascot = d && d.brand && d.brand.mascot;
  const moose = logo(f, 257, 30, 170, 220, "L&L / Moose / Mascot", mascot);

  // Eyebrow caps — orange, left column
  const eb = await tx(f, "LUNCH & LEARN", LEFT_X, 46, 6, O, true, LEFT_W, null, 10);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "L&L / Eyebrow"; }

  // Display — two lines, second orange. Matches print: "Lunch is on us." / "Your spec is free."
  const d1 = await tx(f, "Lunch is on us.", LEFT_X, 68, 26, D, true, LEFT_W, null, 30);
  if (d1) d1.name = "L&L / Display / Line 1";
  const d2 = await tx(f, "Your spec is free.", LEFT_X, 100, 26, O, true, LEFT_W, null, 30);
  if (d2) d2.name = "L&L / Display / Line 2";

  // Body — single tight sentence
  const body = await tx(f,
    "Forty-five minutes of technical depth, real-world projects, " +
    "and CE-credit education — over lunch in your office.",
    LEFT_X, 158, 10, D, false, LEFT_W, null, 15);
  if (body) body.name = "L&L / Body";

  // 3 dot-led essentials
  const items = [
    "Tailored to your project",
    "CE credits — AIBC, RAIC, PEO",
    "In person across Canada, or virtual",
  ];
  let dy = 232;
  for (let i = 0; i < items.length; i++) {
    const dot = figma.createEllipse();
    dot.resize(3, 3);
    dot.x = LEFT_X + 1; dot.y = dy + 6;
    dot.fills = [{type:"SOLID", color: O}];
    dot.name = "L&L / Essentials / Dot " + (i + 1);
    f.appendChild(dot);
    const t = await tx(f, items[i], LEFT_X + 12, dy, 10, D, false, LEFT_W - 12, null, 14);
    if (t) t.name = "L&L / Essentials / Item " + (i + 1);
    dy += 20;
  }

  // QR zone — right column lower. 70px square (~1" at 5" trim) on white
  // plate (6px pad each side). Real QR PNG injected via d.brand.lunch_learn_qr
  // (encoded https://hubss.com/lunch-learn). Falls back to neutral placeholder.
  const QR_SIZE = 70, QR_PAD = 6, QR_FX = 287, QR_FY = 252;
  const plate = rct(f, QR_FX - QR_PAD, QR_FY - QR_PAD,
                       QR_SIZE + 2 * QR_PAD, QR_SIZE + 2 * QR_PAD,
                       W, "L&L / QR / Plate");
  const qrPath = d && d.brand && d.brand.lunch_learn_qr;
  if (qrPath) {
    const qr = phFit(f, QR_FX, QR_FY, QR_SIZE, QR_SIZE, "L&L / QR / Code (scan to book)", qrPath);
  } else {
    rct(f, QR_FX, QR_FY, QR_SIZE, QR_SIZE, D, "L&L / QR / Code placeholder (replace in Figma)");
  }
  const cap = await tx(f, "SCAN TO BOOK", QR_FX - QR_PAD, QR_FY - 14, 5.5, M, false, QR_SIZE + 2 * QR_PAD, null, 9);
  if (cap) { cap.letterSpacing = {value: 16, unit: "PERCENT"}; cap.name = "L&L / QR / Caption"; }

  // Footer — full-width orange rule, URL, 2 contacts
  const ftrRule = rct(f, LEFT_X, 350, 394, 1.5, O, "L&L / Footer / Brand Rule");
  const url = await tx(f, "hubss.com/lunch-learn", LEFT_X, 364, 18, O, true, 394, null, 22);
  if (url) url.name = "L&L / Footer / URL";
  const west = await tx(f, "Cleve Stordy   604.309.8212", LEFT_X, 406, 9, D, true, 200, null, 13);
  if (west) west.name = "L&L / Footer / Contact West";
  const east = await tx(f, "Doug Bain   416.540.9287", LEFT_X + 200, 406, 9, D, true, 194, null, 13);
  if (east) east.name = "L&L / Footer / Contact East";

  return f;
}

async function pageContact(d) {
  const f = fr("Contact");
  // Navy header — visual weight without breaking the clean layout
  rct(f, 0, 0, 450, 82, N, "Contact / Header / Navy Band");
  const t1 = await tx(f, "TWO OFFICES. ONE NETWORK.", 30, 14, 5.5, O, false, 390, null, 8);
  if (t1) t1.name = "Contact / Header / Eyebrow";
  const r1 = rul(f, 30, 30, 24); if (r1) r1.name = "Contact / Header / Brand Rule";
  const t2 = await tx(f, "Speak with HUB.", 30, 44, 22, W, true, 390);
  if (t2) t2.name = "Contact / Header / Display";
  // Content zone
  const intro = await tx(f, "Every project starts with a conversation.", 30, 96, 10, M, false, 390, null, 15);
  if (intro) intro.name = "Contact / Intro";
  rct(f, 30, 128, 390, 1, F, "Contact / Divider Rule 1");
  // West contact block
  const w1 = await tx(f, "WESTERN CANADA", 30, 144, 5.5, O, false, 188, null, 8);
  if (w1) w1.name = "Contact / West / Label";
  const w2 = await tx(f, "Cleve Stordy", 30, 158, 20, D, true, 188);
  if (w2) w2.name = "Contact / West / Name";
  const w3 = await tx(f, "cleve.stordy@hubss.com", 30, 194, 8.5, D, false, 188);
  if (w3) w3.name = "Contact / West / Email";
  const w4 = await tx(f, "604.309.8212", 30, 212, 8.5, M, false, 188);
  if (w4) w4.name = "Contact / West / Phone";
  const w5 = await tx(f, "Ladysmith, British Columbia", 30, 230, 7, M, false, 188);
  if (w5) w5.name = "Contact / West / City";
  // East contact block
  const e1 = await tx(f, "EASTERN CANADA", 242, 144, 5.5, O, false, 178, null, 8);
  if (e1) e1.name = "Contact / East / Label";
  const e2 = await tx(f, "Doug Bain", 242, 158, 20, D, true, 178);
  if (e2) e2.name = "Contact / East / Name";
  const e3 = await tx(f, "doug.bain@hubss.com", 242, 194, 8.5, D, false, 178);
  if (e3) e3.name = "Contact / East / Email";
  const e4 = await tx(f, "416.540.9287", 242, 212, 8.5, M, false, 178);
  if (e4) e4.name = "Contact / East / Phone";
  const e5 = await tx(f, "Milton, Ontario", 242, 230, 7, M, false, 178);
  if (e5) e5.name = "Contact / East / City";
  rct(f, 30, 258, 390, 1, F, "Contact / Divider Rule 2");
  const u1 = await tx(f, "hubss.com", 30, 272, 16, O, true, 390);
  if (u1) u1.name = "Contact / URL";
  const u2 = await tx(f, "Spec sheets · project gallery · installer network · lunch + learn booking", 30, 304, 8, M, false, 390, null, 12);
  if (u2) u2.name = "Contact / URL Subline";
  rct(f, 30, 338, 390, 1, F, "Contact / Footer / Rule");
  const cp = await tx(f, "© 2026 HUB Surface Systems   ·   Established 1994   ·   Coast to Coast", 30, 350, 5.5, F, false, 390, "center", 8);
  if (cp) cp.name = "Contact / Footer / Copyright";
  return f;
}

async function pageClosing() {
  // Confident sign-off. More breathing room, stronger hierarchy.
  const f = fr("Closing — The Street");
  // Eyebrow
  await tx(f, "THE STREET IS", 28, 52, 6.5, O, false, 394, null, 9);
  // Two-line display headline with more white space
  await tx(f, "The public realm.", 28, 76, 38, D, true, 394);
  await tx(f, "Ours to build right.", 28, 128, 38, O, true, 394);
  // Orange accent rule — visual pause before the statement
  rct(f, 28, 185, 48, 2, O, "OrangeRule");
  // Statement — tighter body copy with more breathing room above
  await tx(f, "Every surface we build is walked over, driven on, played at, and lived around. That is the standard we hold ourselves to. Specify it right. Watch it work. Walk over it for twenty years.", 28, 208, 9.5, D, false, 340);
  // Three-word sign-off as horizontal trio
  rct(f, 28, 356, 394, 1, F, "rule");
  await tx(f, "SPECIFIED.", 28, 370, 9, D, true, 120);
  await tx(f, "INSTALLED.", 162, 370, 9, D, true, 120);
  await tx(f, "BACKED.", 296, 370, 9, D, true, 100);
  rul(f, 28, 393, 32);
  await tx(f, "HUB SURFACE SYSTEMS", 28, 404, 5.5, F, false, 394, "center", 8);
  return f;
}

async function pageService() {
  const f = fr("Closing — Service Promise");
  await tx(f, "HOW WE WORK", 28, 50, 6.5, O, false, 394);
  await tx(f, "Specified.", 28, 76, 24, D, true, 394);
  await tx(f, "Installed.", 28, 110, 24, D, true, 394);
  await tx(f, "Backed.", 28, 144, 24, D, true, 394);
  await tx(f, "Every HUB project is spec-supported, installer-trained, and backed by our performance guarantee.", 28, 205, 8.5, D, false, 394);
  return f;
}

async function pageQuietMark(d) {
  const f = fr("Closing — HUB Mark");
  // Optical centre — logo sits in the upper third, generous air around it
  // 148×32px frame: same proportions as cover/back-cover for visual system cohesion
  logo(f, 151, 162, 148, 32, "HUBSS logo colour", d.brand && d.brand.logo_color);
  // Rule then type — spaced on a 16px baseline grid from logo bottom (y=194)
  rct(f, 213, 208, 24, 1, O, "OrangeRule");
  await tx(f, "HUB SURFACE SYSTEMS", 28, 220, 7, D, true, 394, "center", 11);
  await tx(f, "ESTABLISHED 1994   ·   COAST TO COAST", 28, 235, 5.5, F, false, 394, "center", 8);
  rct(f, 98, 260, 254, 1, F, "Divider");
  await tx(f, "Thank you.", 28, 280, 13, M, false, 394, "center", 18);
  return f;
}

async function pageBack(d) {
  const f = fr("Back Cover", N);
  ph(f, 0, 0, 450, 450, "Back Cover / Photo / Asphalt", d.brand && d.brand.asphalt_photo);
  // Single smooth navy wash — lets photo texture breathe while legibility is guaranteed
  rct(f, 0, 0, 450, 450, N, "Back Cover / Navy Wash");
  f.children[f.children.length-1].opacity = 0.72;
  logo(f, 151, 178, 148, 32, "Back Cover / Logo / HUBSS White Centred", d.brand && d.brand.logo_white);
  rct(f, 213, 222, 24, 1, O, "Back Cover / Brand Rule");
  const tag = await tx(f, "Canada's Leading Decorative Pavement Solutions", 28, 234, 8.5, W, false, 394, "center", 12);
  if (tag) tag.name = "Back Cover / Tagline";
  const url = await tx(f, "hubss.com", 28, 254, 11, W, true, 394, "center", 14);
  if (url) url.name = "Back Cover / URL";
  rct(f, 98, 280, 254, 1, {r:1,g:1,b:1}, "Back Cover / Divider");
  f.children[f.children.length-1].opacity = 0.20;
  const ph1 = await tx(f, "West / Prairies   604.309.8212", 28, 292, 6.5, W, false, 394, "center", 10);
  if (ph1) ph1.name = "Back Cover / Contact / West";
  const ph2 = await tx(f, "Central / Maritimes   416.540.9287", 28, 306, 6.5, W, false, 394, "center", 10);
  if (ph2) ph2.name = "Back Cover / Contact / East";
  const cp = await tx(f, "© 2026 HUB Surface Systems", 28, 330, 5.5, M, false, 394, "center", 8);
  if (cp) cp.name = "Back Cover / Copyright";
  return f;
}

async function pageBlank(idx) {
  // Intentional rest page — minimal, never truly empty.
  // Centred orange dash signals editorial breathing room, not an oversight.
  const f = fr("Rest " + idx);
  rct(f, 213, 224, 24, 2, O, "OrangeRule");
  return f;
}

// pageFieldNotes — a ruled notepad page for specifiers.
// Simple, intentional — the specifier gets a physical place to record their project details.
// Sits after the Contact page so it directly faces the contact information.
// addFolio — page number at bottom of content pages.
// y=415: bottom=423, gap=27px (0.3" from trim edge — within 0.25" safe margin).
// Skipped on: Cover, Back Cover, Half Title, Rest/blank, Section openers, Spread/DPS.
async function addFolio(frame, num) {
  await tx(frame, String(num), 28, 415, 5.5, M, false, 394, "center", 8);
}

async function pageFieldNotes() {
  const f = fr("Field Notes");
  // Header: small-caps label + orange rule — same visual grammar as the rest of the catalogue
  await tx(f, "FIELD NOTES", 28, 36, 6, O, false, 394, null, 9);
  rul(f, 28, 54, 20);
  await tx(f, "Your project. Your notes.", 28, 64, 7.5, M, false, 300, null, 11);
  // 14 ruled lines evenly distributed across the body — 96px to 398px
  const lineY0 = 96, lineY1 = 398, lineCount = 14;
  const lineGap = Math.round((lineY1 - lineY0) / (lineCount - 1));
  for (let i = 0; i < lineCount; i++) {
    rct(f, 28, lineY0 + i * lineGap, 394, 1, F, "NoteLine");
  }
  // Footer: moved up — bottom=~414, gap=36px (≥0.25" safe margin)
  rct(f, 28, 402, 394, 1, F, "rule");
  await tx(f, "HUB SURFACE SYSTEMS   ·   hubss.com   ·   604.309.8212   ·   416.540.9287", 28, 410, 5.5, F, false, 394, "center", 8);
  return f;
}

// pageHubNumbers — navy full-bleed stats spread.
// Giant orange numbers on navy — maximum typographic confidence.
async function pageHubNumbers() {
  const f = fr("By the Numbers", N);
  const eb = await tx(f, "BY THE NUMBERS", 28, 38, 6, O, true, 394, null, 9);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Hub Numbers / Eyebrow"; }
  const rule = rul(f, 28, 56, 24); if (rule) rule.name = "Hub Numbers / Brand Rule";
  const rows = [
    ["30+",    "years building Canadian streets"],
    ["1,000+", "projects completed coast to coast"],
    ["500+",   "municipalities that specify HUB by name"],
  ];
  let sy = 80;
  let ri = 0;
  for (const [num, label] of rows) {
    ri++;
    const n = await tx(f, num, 28, sy, 56, O, true, 394, null, 66);
    if (n) n.name = "Hub Numbers / Stat " + ri + " / Number";
    const l = await tx(f, label, 28, sy + 72, 8.5, W, false, 360, null, 12);
    if (l) l.name = "Hub Numbers / Stat " + ri + " / Label";
    const d = rct(f, 28, sy + 96, 394, 1, {r:1,g:1,b:1}, "Hub Numbers / Stat " + ri + " / Divider");
    if (d) d.opacity = 0.12;
    sy += 116;
  }
  return f;
}

// pageStatement — editorial quote page on white.
// A breath before the product sections begin. Clean typographic confidence.
async function pageStatement() {
  const f = fr("Editorial — Statement");
  const eb = await tx(f, "THE SURFACE UNDERFOOT", 28, 60, 6, O, true, 394, null, 9);
  if (eb) { eb.letterSpacing = {value: 16, unit: "PERCENT"}; eb.name = "Statement / Eyebrow"; }
  const h1 = await tx(f, "Every surface", 28, 86, 30, D, true, 394, null, 36);
  if (h1) h1.name = "Statement / H1 / Line 1";
  const h2 = await tx(f, "tells the city's", 28, 124, 30, D, true, 394, null, 36);
  if (h2) h2.name = "Statement / H1 / Line 2";
  const h3 = await tx(f, "story first.", 28, 162, 30, O, true, 394, null, 36);
  if (h3) h3.name = "Statement / H1 / Line 3";
  rct(f, 28, 214, 32, 2, O, "Statement / Brand Rule");
  const body = await tx(f, "From a community crosswalk in Sechelt to a transit corridor in Toronto, the mark on the street carries meaning beyond its function. Specify it right. Choose it to last twenty years.", 28, 230, 9.5, D, false, 330, null, 14);
  if (body) body.name = "Statement / Body";
  rct(f, 28, 398, 394, 1, F, "Statement / Footer / Rule");
  const url = await tx(f, "hubss.com", 28, 410, 7, O, true, 394, "right", 11);
  if (url) url.name = "Statement / Footer / URL";
  return f;
}

// ---------------------------------------------------------------------
// v51 — VISUAL DESIGN SYSTEM
// Idempotent — checks if a style/component already exists by name before
// creating. Vernon's re-imports won't duplicate. Run once at the top
// of buildCatalogue so the styles + components exist before frames are
// built and can be referenced from the layers panel.
// ---------------------------------------------------------------------
function _hasPaintStyleByName(name) {
  const styles = figma.getLocalPaintStyles();
  for (let i = 0; i < styles.length; i++) if (styles[i].name === name) return styles[i];
  return null;
}
function _hasTextStyleByName(name) {
  const styles = figma.getLocalTextStyles();
  for (let i = 0; i < styles.length; i++) if (styles[i].name === name) return styles[i];
  return null;
}
function _hasComponentByName(name) {
  for (const page of figma.root.children) {
    for (const node of page.children) {
      if (node.type === "COMPONENT" && node.name === name) return node;
    }
  }
  return null;
}
function _ensurePaintStyle(name, color) {
  let s = _hasPaintStyleByName(name);
  if (s) return s;
  s = figma.createPaintStyle();
  s.name = name;
  s.paints = [{type:"SOLID", color: color}];
  return s;
}
function _ensureTextStyle(name, family, style, fontSize, lineHeight, tracking) {
  // UPSERT (type-pass): existing styles are updated in place so re-running
  // the plugin migrates Vern's file to the current TYPE-SPEC ramp instead
  // of silently keeping stale values.
  let s = _hasTextStyleByName(name);
  if (!s) {
    s = figma.createTextStyle();
    s.name = name;
  }
  s.fontName = {family: family, style: style};
  s.fontSize = fontSize;
  if (lineHeight) s.lineHeight = {value: lineHeight, unit: "PIXELS"};
  if (typeof tracking === "number") s.letterSpacing = {value: tracking, unit: "PERCENT"};
  return s;
}
async function createDesignSystem() {
  // Paint styles — brand palette (6 styles, covers every print color use)
  _ensurePaintStyle("HUBSS / Orange",       O);
  _ensurePaintStyle("HUBSS / Navy",         N);
  _ensurePaintStyle("HUBSS / Ink",          D);
  _ensurePaintStyle("HUBSS / Paper",        W);
  _ensurePaintStyle("HUBSS / Mid Grey",     M);
  _ensurePaintStyle("HUBSS / Faint Grey",   F);

  // Text styles — v52.1 DDB grade: each style maps 1:1 to a specific
  // print typography role in final_catalog.py so Vernon can pick a
  // text style in Figma and get pixel-accurate parity with the printed
  // catalogue. Sizes/leading/tracking taken verbatim from the print
  // builder. Inter Medium is the minimum body weight (Vernon's v48 mandate
  // — Regular reads too thin on press). Inter Bold for display + eyebrow.

  // Display — TYPE-SPEC ramp (figma units; ratio ~1.2; leading x1.08)
  _ensureTextStyle("Display / Section Opener",   "Inter", "Bold",   52, 56,  -2.0);  // section + Network titles
  _ensureTextStyle("Display / Manifesto",        "Inter", "Bold",   37, 40,  -1.9);  // manifesto h1 + stat numbers
  _ensureTextStyle("Display / Catalogue (TOC)",  "Inter", "Bold",   31, 33.5, -1.9); // TOC/cover/statement/why heads
  _ensureTextStyle("Display / Stat Number",      "Inter", "Bold",   37, 40,  -1.9);  // why_stats numbers (= L tier)
  _ensureTextStyle("Display / Cover Masthead",   "Inter", "Bold",   31, 33.5, -1.9); // cover masthead (= M tier)

  // Titles — 26 / 21 / 17.5 / 14.5 (leading x1.08-1.10)
  _ensureTextStyle("Title / Spread & Card Head", "Inter", "Bold",   26, 28,  -1.9);  // spread heads + app/project cards
  _ensureTextStyle("Title / Product Name",       "Inter", "Bold",   21, 23,  -1.8);  // spec-page wordmark
  _ensureTextStyle("Title / Product Tagline",    "Inter", "Medium", 21, 23,  -1.4);  // product-hero tagline (shrinks to fit)
  _ensureTextStyle("Title / Project Hero",       "Inter", "Bold",   21, 23,  -1.8);  // names / proof headline tier
  _ensureTextStyle("Title / Application",        "Inter", "Bold",   17.5, 19.3, -2.0); // app tagline / story names
  _ensureTextStyle("Title / Process Step",       "Inter", "Bold",   14.5, 16, -2.0);  // process-strip steps
  _ensureTextStyle("Title / Spread Caption",     "Inter", "Bold",   21,   23, -1.9);  // DPS/spread photo captions (final pass: 14.5->21)

  // Body + subhead + spec + caption (leading x1.40 / 1.25 / 1.30 / 1.30)
  _ensureTextStyle("Body / Print",               "Inter", "Medium", 10, 14,   0.0);  // ALL running body
  _ensureTextStyle("Subhead / Standfirst",       "Inter", "Medium", 12.5, 15.6, 0.0); // subhead-over-body
  _ensureTextStyle("Spec / Values & Compact",    "Inter", "Medium", 8.6, 11.2, 0.0);  // spec values / compact prose
  _ensureTextStyle("Caption / Names & Fine",     "Inter", "Medium", 7.8, 10.1, 0.0);  // chip names / fine lines (7.5pt floor)

  // Caps ladder — tracked caps; % = the print build's 2.4pt charSpace
  // expressed against each tier's pt size (NOT a flat 16%)
  _ensureTextStyle("Caps / Display (SECTION)",   "Inter", "Bold",  8.5, 11,  29.0);
  _ensureTextStyle("Eyebrow / Standard",         "Inter", "Bold",  7.5, 11,  33.0);  // every page eyebrow
  _ensureTextStyle("Caps / Label",               "Inter", "Bold",  6.5, 9,   38.0);  // spec labels / meta / tags
  _ensureTextStyle("Eyebrow / Small",            "Inter", "Bold",  5.5,  9,  45.0);  // RATIFIED micro footer caps

  // TOC + folio
  _ensureTextStyle("TOC / Item",                 "Inter", "Bold",   10, 14,   0.0);
  _ensureTextStyle("TOC / Page Number",          "Inter", "Bold",   10, 14,   0.0);
  _ensureTextStyle("Folio / Page Number",        "Inter", "Medium", 5.5,  8,   0.0);  // retired in print (no folios)

  // Components — reusable design-system elements parked on a hidden page
  // so they're discoverable in the Assets panel without cluttering canvas.
  let dsPage = figma.root.children.find(p => p.name === "Design System");
  if (!dsPage) {
    dsPage = figma.createPage();
    dsPage.name = "Design System";
  }
  if (!_hasComponentByName("Orange Dot")) {
    const c = figma.createComponent();
    c.name = "Orange Dot";
    c.resize(8, 8);
    const ell = figma.createEllipse();
    ell.resize(8, 8);
    ell.fills = [{type:"SOLID", color: O}];
    ell.name = "Dot";
    c.appendChild(ell);
    dsPage.appendChild(c);
  }
  if (!_hasComponentByName("Brand Rule / Orange Thin")) {
    const c = figma.createComponent();
    c.name = "Brand Rule / Orange Thin";
    c.resize(44, 2);
    const r = figma.createRectangle();
    r.resize(44, 2);
    r.fills = [{type:"SOLID", color: O}];
    r.name = "Rule";
    c.appendChild(r);
    dsPage.appendChild(c);
  }
  if (!_hasComponentByName("Page Number Footer")) {
    const c = figma.createComponent();
    c.name = "Page Number Footer";
    c.resize(40, 14);
    const tn = figma.createText();
    tn.fontName = {family:"Inter", style:"Medium"};
    tn.characters = "00";
    tn.fontSize = 8;
    tn.fills = [{type:"SOLID", color: M}];
    tn.x = 0; tn.y = 0;
    tn.name = "Page Number";
    c.appendChild(tn);
    dsPage.appendChild(c);
  }
}

// --- main build ---
//
// safeBuild — wrap any page builder so one failure doesn't kill the whole
// build. Vernon needs partial-success: if page 42 errors, pages 1-41 and
// 43-116 should still render and the layers panel should show a "FAILED
// — <reason>" red placeholder frame so the failure is visible.
async function safeBuild(label, builderFn) {
  try {
    const f = await builderFn();
    return f;
  } catch (e) {
    const msg = (e && e.message) ? e.message : String(e);
    console.warn("Page failed: " + label + " — " + msg);
    figma.notify("Page failed: " + label, {error: true, timeout: 1200});
    const f = fr("FAILED — " + label, {r:1,g:0.92,b:0.92});
    try {
      await tx(f, "BUILD ERROR", 28, 200, 12, {r:0.7,g:0.05,b:0.05}, true, 394, "center", 16);
      await tx(f, label, 28, 224, 9, D, true, 394, "center", 13);
      await tx(f, msg.substring(0, 200), 28, 250, 7.5, D, false, 394, "center", 11);
    } catch (_) {}
    return f;
  }
}

async function buildCatalogue(d, section) {
  // section: "all" (default) or one of products|applications|projects|
  // network|reference — the sectioned-import fallback so the book can be
  // brought in section by section if a full pass is too heavy on a machine.
  section = section || "all";
  const ALL = section === "all";
  const want = (s) => ALL || section === s;

  // Yield to the main thread between batches so the UI paints immediately and
  // a large book never stalls Figma. setTimeout exists in the plugin sandbox;
  // guard anyway so a missing timer degrades to a no-op rather than throwing.
  const tick = (typeof setTimeout === "function")
    ? () => new Promise((r) => setTimeout(r, 0))
    : () => Promise.resolve();
  let _built = 0;
  async function progress(label) {
    _built++;
    if (_built % 12 === 0) { figma.ui.postMessage({type:"progress", built:_built, label}); await tick(); }
  }

  // v51 — load all weights used by the design system + frames
  await figma.loadFontAsync({family:"Inter", style:"Regular"});
  await figma.loadFontAsync({family:"Inter", style:"Medium"});
  await figma.loadFontAsync({family:"Inter", style:"SemiBold"});
  await figma.loadFontAsync({family:"Inter", style:"Bold"});
  // Bootstrap the design system once per Figma session (idempotent).
  try { await createDesignSystem(); } catch (e) { console.warn("Design system init failed:", e); }

  const frames = [];

  // Front matter — full builds only (sectioned imports skip it).
  if (ALL) {
  // Front matter — TOC on p3 so readers can navigate from the first spread
  frames.push(await pageCover(d));        // 0 = p1
  frames.push(await pageHalfTitle(d));    // 1 = p2
  frames.push(null);                      // 2 = p3  TOC — filled after numbering
  frames.push(await pageManifesto(d));    // 3 = p4  Brand promise (not in TOC — editorial)
  frames.push(await pageWhyStats(d));     // 4 = p5  Why HUB stats
  frames.push(await pageWhyProof(d));     // 5 = p6  Why HUB proof
  frames.push(await pageHubNumbers());    // 6 = p7  Bold stats moment — navy
  frames.push(await pageStatement());     // 7 = p8  Editorial statement — white

  // DPS-A — opening editorial. Full-bleed before Products section.
  // Vernon swaps images in Figma for final. Keys: dps_a_left / dps_a_right.
  {
    const dpsAL = d.section_openers && d.section_openers.dps_a_left;
    const dpsAR = d.section_openers && d.section_openers.dps_a_right;
    if (dpsAL) {
      const [aL, aR] = await pageDoublespread("The Work", dpsAL, "From every intersection, a statement.", undefined, dpsAR || dpsAL);
      frames.push(aL, aR);
    }
  }

  } // end front matter

  // Section 1 — Products
  const productsPage = frames.length + 1;
  if (want("products")) {
  frames.push(await safeBuild("Section Open — Products", () => pageSectionOpen("One", "Products.", d.section_openers && d.section_openers.products)));
  for (const prod of (d.products || [])) {
    frames.push(await safeBuild("Product Hero — " + (prod && prod.name || "?"), () => pageProductHero(prod)));
    frames.push(await safeBuild("Product Spec — " + (prod && prod.name || "?"), () => pageProductSpec(prod)));
    await progress("Products");
  }
  } // end products
  // Double-page spread at end of products — pure editorial punch, no product content.
  // Left: editorial_products image. Right: different image (projects section opener).
  {
    const dpsImg = (d.section_openers && d.section_openers.editorial_products)
      || (d.section_openers && d.section_openers.applications)
      || (d.projects && d.projects[1] && d.projects[1].hero);
    const dpsImgR = (d.section_openers && d.section_openers.editorial_products_r)
      || (d.section_openers && d.section_openers.projects)
      || (d.products && d.products[2] && d.products[2].hero);
    if (dpsImg) {
      const [sL, sR] = await pageDoublespread("In the Field", dpsImg, "Designed for the city. Built for the street.", undefined, dpsImgR);
      frames.push(sL, sR);
    }
  }

  // Section 2 — Applications
  const appsPage = frames.length + 1;
  if (want("applications")) {
  frames.push(await safeBuild("Section Open — Applications", () => pageSectionOpen("Two", "Applications.", d.section_openers && d.section_openers.applications)));
  const nApps = (d.applications || []).length;
  let appIdx = 0;
  for (const app of (d.applications || [])) {
    appIdx++;
    const _idx = appIdx;
    frames.push(await safeBuild("Application — " + (app && app.name || "?"), () => pageApplication(app, _idx, nApps)));
    await progress("Applications");
  }
  } // end applications

  // DPS-B — transition between Applications and Projects. Full-bleed visual breather.
  // Keys: dps_b_left / dps_b_right.
  {
    const dpsBL = d.section_openers && d.section_openers.dps_b_left;
    const dpsBR = d.section_openers && d.section_openers.dps_b_right;
    if (dpsBL) {
      const [bL, bR] = await pageDoublespread("Across Canada", dpsBL, "Five hundred municipalities. One standard.", undefined, dpsBR || dpsBL);
      frames.push(bL, bR);
    }
  }

  // Section 3 — Projects
  const projectsPage = frames.length + 1;
  const projs = d.projects || [];
  if (want("projects")) {
  frames.push(await safeBuild("Section Open — Projects", () => pageSectionOpen("Three", "Projects.", d.section_openers && d.section_openers.projects)));
  let projIdx = 0;
  for (let pi = 0; pi < projs.length; pi++) {
    projIdx++;
    const _idx = projIdx;
    const _proj = projs[pi];
    frames.push(await safeBuild("Project Hero — " + (_proj && _proj.name || "?"), () => pageProjectHero(_proj)));
    frames.push(await safeBuild("Project Story — " + (_proj && _proj.name || "?"), () => pageProjectStory(_proj, _idx)));
    await progress("Projects");
    // Double-page spread halfway through projects — visual pause between project stories.
    // Left: editorial_projects image. Right: reference section opener (different category).
    if (pi === Math.floor(projs.length / 2) - 1) {
      const dpsImg2 = (d.section_openers && d.section_openers.editorial_projects)
        || (d.section_openers && d.section_openers.reference)
        || (projs[0] && projs[0].detail);
      const dpsImg2R = (d.section_openers && d.section_openers.editorial_projects_r)
        || (d.section_openers && d.section_openers.reference)
        || (projs[projs.length - 1] && projs[projs.length - 1].detail);
      if (dpsImg2) {
        const [sL2, sR2] = await pageDoublespread("Every Mark", dpsImg2, "Every mark tells a story.", undefined, dpsImg2R);
        frames.push(sL2, sR2);
      }
    }
  }

  } // end projects

  // Section 4 — Network
  const networkPage = frames.length + 1;
  if (want("network")) {
  frames.push(await safeBuild("Network Section Opener", () => pageNetworkOpen(d)));
  const installs = d.installers || [];
  for (let ii = 0; ii < installs.length; ii++) {
    const _inst = installs[ii];
    const _i = ii + 1;
    const _total = installs.length;
    frames.push(await safeBuild("Installer — " + (_inst && _inst.name || "?"), () => pageInstaller(_inst, _i, _total)));
  }

  // DPS-C — between Network and Reference. Visual breathing room before back matter.
  // Keys: dps_c_left / dps_c_right.
  {
    const dpsCL = d.section_openers && d.section_openers.dps_c_left;
    const dpsCR = d.section_openers && d.section_openers.dps_c_right;
    if (dpsCL) {
      const [cL, cR] = await pageDoublespread("Built to Last", dpsCL, "The surface underfoot. The city above.", undefined, dpsCR || dpsCL);
      frames.push(cL, cR);
    }
  }

  } // end network

  // Section 5 — Reference
  const referencePage = frames.length + 1;
  if (want("reference")) {
  frames.push(await pageSectionOpen("Five", "Reference.", d.section_openers && d.section_openers.reference));
  frames.push(await pageTechnical());
  frames.push(await pageCities(d));
  const lunchPage = frames.length + 1;
  frames.push(await pageLunchLearn(d));
  const contactPage = frames.length + 1;
  frames.push(await pageContact(d));
  // Field Notes: a ruled notepad page — faces the Contact page in the open spread.
  // Specifier reads your contact info on the left, picks up a pen on the right. Very hot.
  frames.push(await pageFieldNotes());

  // Final editorial double-page spread — dramatic closing statement before the back matter.
  // DPS3 — Spirit Trail closing spread. editorial_closing key = Spirit Trail B&W swirl crosswalk (Vancouver).
  // Cinematic full-stop before back matter. Falls back through reference if key is absent.
  {
    const closingImg = (d.section_openers && d.section_openers.editorial_closing)
      || (d.section_openers && d.section_openers.reference);
    if (closingImg) {
      const [sL3, sR3] = await pageDoublespread("The Mark", closingImg, "Specified. Installed. Built to outlast.", "navy");
      frames.push(sL3, sR3);
    }
  }

  } // end reference

  // Closing matter — full builds only.
  if (ALL) {
  // Pad to next multiple of 4 — saddle-stitch / perfect-bind requirement.
  while ((frames.length + 3) % 4 !== 0) {
    frames.push(await pageBlank(frames.length + 1));
  }
  // Closing pair + back cover
  frames.push(await pageClosing());
  frames.push(await pageQuietMark(d));
  frames.push(await pageBack(d));
  } // end closing

  // TOC — v50 parity. Labels match section opener titles exactly; Lunch
  // & Learn added (CTA destination with QR). Editorial front matter
  // (Manifesto, Why HUB) is not listed; readers encounter it naturally.
  const tocEntries = [
    ["Products",       productsPage],
    ["Applications",   appsPage],
    ["Projects",       projectsPage],
    ["Network",        networkPage],
    ["Reference",      referencePage],
    ["Lunch & Learn",  lunchPage],
    ["Contact",        contactPage],
  ];
  if (ALL && frames.length > 2) frames[2] = await pageTOC(tocEntries, frames.length);

  // Prefix every frame name with its print page number so the Figma sidebar
  // and the TOC can be cross-referenced at a glance (p01, p02 … p100).
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (f) f.name = "p" + String(i + 1).padStart(2, "0") + " — " + f.name;
  }

  // TOC note: productsPage, appsPage, etc. are computed dynamically at the moment
  // each section is pushed into frames[], so TOC page numbers are always correct
  // regardless of front-matter changes. No hardcoded numbers anywhere.

  // Add folios to content pages (skip cover, section openers, DPS, blanks, quarter-ads).
  const _noFolioNames = new Set(["Cover", "Back Cover", "Half Title"]);
  const _noFolioPrefix = ["Rest ", "Section ", "Spread ", "QuarterAd", "By the Numbers"];
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (!f) continue;
    const raw = f.name.replace(/^p\d+ — /, "");
    if (_noFolioNames.has(raw)) continue;
    if (_noFolioPrefix.some(p => raw.startsWith(p))) continue;
    await addFolio(f, i + 1);
  }

  // Layout all frames in a grid and append to current page — yield every
  // 10 so the canvas paints progressively instead of in one blocking burst.
  const COL = 10, GAP = 40;
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (!f) continue;
    f.x = (i % COL) * (450 + GAP);
    f.y = Math.floor(i / COL) * (450 + GAP);
    figma.currentPage.appendChild(f);
    if (i % 10 === 9) { figma.ui.postMessage({type:"progress", built:i+1, label:"Placing"}); await tick(); }
  }
  figma.ui.postMessage({type:"done", count: frames.filter(Boolean).length});

  figma.viewport.scrollAndZoomIntoView([frames[0]]);
  figma.notify(
    "✓ " + frames.length + " pages built  ·  " +
    "Products p" + productsPage +
    "  ·  Apps p" + appsPage +
    "  ·  Projects p" + projectsPage +
    "  ·  Network p" + networkPage +
    "  ·  Ref p" + referencePage
  );
}

figma.ui.onmessage = async (msg) => {
  if (msg.type === "build") {
    try {
      await buildCatalogue(EMBEDDED_DATA, msg.section || "all");
      // Leave the plugin open so the UI can show the done state; the user
      // closes it. (Auto-close raced the final progress paint.)
      figma.ui.postMessage({type:"done"});
    } catch (e) {
      const m = (e && e.message) ? e.message : String(e);
      figma.notify("Build error: " + m, {error: true});
      console.error(e);
      figma.closePlugin();
    }
  } else {
    figma.closePlugin();
  }
};

figma.showUI(__html__, {width: 340, height: 420});
"""


def _generate_qr(dest_path: Path) -> bool:
    """Generate a hubss.com QR code PNG at dest_path. Returns True on success."""
    try:
        import qrcode  # pip install qrcode[pil]
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=12,
            border=3,
        )
        qr.add_data("https://hubss.com")
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        img.save(dest_path)
        print(f"  QR -> {dest_path.name}")
        return True
    except ImportError:
        print("  QR skipped (pip install qrcode[pil] to enable)")
        return False
    except Exception as e:
        # Don't let QR side-effect kill the main plugin write
        print(f"  QR error (non-fatal): {e}")
        return False


def main():
    if not DATA.exists():
        print(f"ERROR: {DATA} not found. Run: python -B -m src.export_json first.")
        return

    # Generate QR code as side-effect — embed_images.py will embed it from catalog_data.json path
    qr_path = ROOT / "public" / "images" / "assets" / "qr" / "hubss-qr.png"
    _generate_qr(qr_path)

    data = json.loads(DATA.read_text(encoding="utf-8"))
    data_json = json.dumps(data, ensure_ascii=False, separators=(",", ":"))

    # Inject the catalog data into the JS template
    code = JS.replace("CATALOG_DATA_JSON", data_json, 1)

    PLUGIN.write_bytes(code.encode("utf-8"))
    size_kb = PLUGIN.stat().st_size / 1024
    print(f"Wrote {PLUGIN.name}  ({size_kb:.0f} KB)")

    # Split data artifact (directive): catalogue-layout.json next to the
    # plugin AND under public/catalogue/figma/ so it deploys (a fetchable,
    # version-controlled record of the exact layout the plugin renders).
    layout_path = PLUGIN.parent / "catalogue-layout.json"
    layout_path.write_text(data_json, encoding="utf-8")
    hosted = ROOT.parent / "public" / "catalogue" / "figma"
    hosted.mkdir(parents=True, exist_ok=True)
    (hosted / "catalogue-layout.json").write_text(data_json, encoding="utf-8")
    print(f"Wrote catalogue-layout.json  ({len(data_json)/1024:.0f} KB)  -> plugin + public/catalogue/figma/")
    print(f"NOTE: do NOT run embed_images (that base64 bank is what dark-screened Figma).")
    print(f"In Figma: remove old plugin, re-import manifest, Build (All or by section).")


if __name__ == "__main__":
    main()
