"""
generate_plugin.py — Write a clean, minimal code.js from catalog_data.json.

The embedded-image version of code.js reaches ~74 MB, which exceeds Figma's
plugin sandbox and prevents loading. This script generates a fresh ~100-200 KB
plugin that builds all 100 Figma frames with:
  - Correct frame names, background colours, navy bands, orange accents
  - All product/project text (name, tagline, body, callout, uses...)
  - Cream [PHOTO] placeholder rectangles for every photo slot
  - Correct page order matching the PDF exactly

Usage:
    python -B -m src.export_json          # regenerate catalog_data.json
    python -B -m src.generate_plugin      # write fresh code.js
    Then in Figma: remove plugin, re-import manifest, click Build.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT   = Path(__file__).resolve().parent.parent
DATA   = ROOT / "output" / "catalog_data.json"
PLUGIN = ROOT / "figma-plugin" / "code.js"

# ---------------------------------------------------------------------------
# The Figma plugin JavaScript — embedded as a Python string.
# CATALOG_DATA_JSON is replaced with the actual JSON before writing.
# ---------------------------------------------------------------------------
JS = r"""
"use strict";
// HUBSS Catalogue Builder — generated by src/generate_plugin.py
// IMAGE_BANK is injected by src/embed_images.py after this file is written.
// Without embed_images, photo slots degrade gracefully to [PHOTO] placeholders.

const IMAGE_BANK = {};
const EMBEDDED_DATA = CATALOG_DATA_JSON;

// --- colour tokens ---
const O  = {r:0.976, g:0.451, b:0.086};  // HUBSS orange
const N  = {r:0.047, g:0.063, b:0.125};  // HUBSS navy rich
const W  = {r:1,     g:1,     b:1    };  // white
const D  = {r:0.12,  g:0.12,  b:0.12 };  // near-black body
const M  = {r:0.45,  g:0.45,  b:0.45 };  // mid grey
const F  = {r:0.65,  g:0.65,  b:0.65 };  // faint
const PH = {r:0.85,  g:0.83,  b:0.78 };  // cream photo placeholder

// --- low-level helpers ---
function fr(name, bg) {
  const f = figma.createFrame();
  f.name = name;
  f.resize(450, 450);
  f.clipsContent = true;
  f.fills = [{type:"SOLID", color: bg || W}];
  return f;
}

function rct(p, x, y, w, h, col, name) {
  const r = figma.createRectangle();
  r.resize(Math.max(1, Math.round(w)), Math.max(1, Math.round(h)));
  r.x = Math.round(x);
  r.y = Math.round(y);
  r.fills = [{type:"SOLID", color: col}];
  if (name) r.name = name;
  p.appendChild(r);
  return r;
}

function base64ToBytes(b64) {
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}

// ph() — photo rect: FILL mode crops to frame (correct for photos).
// Tries filename-only key first, full path as fallback.
function ph(p, x, y, w, h, label, imagePath) {
  const r = rct(p, x, y, w, h, PH, "[PHOTO] " + (label || ""));
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");   // parent/filename — unique key matching embed_images.py
    const fname = parts[parts.length - 1];    // filename-only fallback
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FILL", imageHash: img.hash}];
        r.name = label || "Photo";
      } catch(e) { /* keep placeholder */ }
    }
  }
  return r;
}

// phFit() — like ph() but FIT mode: shows entire image, may letterbox.
// Use when the subject (crosswalk decal, marking) must not be cropped at any edge.
function phFit(p, x, y, w, h, label, imagePath) {
  const r = rct(p, x, y, w, h, PH, "[PHOTO] " + (label || ""));
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");
    const fname = parts[parts.length - 1];
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FIT", imageHash: img.hash}];
        r.name = label || "Photo";
      } catch(e) {}
    }
  }
  return r;
}

// logo() — like ph() but uses FIT mode so the full wordmark is never cropped.
// Transparent fill when no image is present (looks clean over any background).
function logo(p, x, y, w, h, label, imagePath) {
  const r = figma.createRectangle();
  r.resize(Math.max(1, Math.round(w)), Math.max(1, Math.round(h)));
  r.x = Math.round(x);
  r.y = Math.round(y);
  r.fills = [];
  r.name = "[LOGO] " + (label || "");
  if (imagePath) {
    const parts = imagePath.split(/[\\/]/);
    const key2 = parts.slice(-2).join("/");
    const fname = parts[parts.length - 1];
    const b64 = IMAGE_BANK[key2] || IMAGE_BANK[fname] || IMAGE_BANK[imagePath];
    if (b64) {
      try {
        const img = figma.createImage(base64ToBytes(b64));
        r.fills = [{type:"IMAGE", scaleMode:"FIT", imageHash: img.hash}];
        r.name = label || "Logo";
      } catch(e) {}
    }
  }
  p.appendChild(r);
  return r;
}

function rul(p, x, y, w) {
  return rct(p, x, y, w, 2, O, "OrangeRule");
}

// tx() — all text creation goes through here.
// lh: explicit line height in px; if omitted, auto-computed for print-quality rhythm.
//   Body (sz < 11):  lh = sz × 1.55  (generous open leading, readable at small sizes)
//   Display (sz ≥ 11): lh = sz × 1.18  (tight but not cramped for headlines)
async function tx(p, text, x, y, sz, col, bold, maxW, align, lh) {
  if (!text || text === "") return null;
  const t = figma.createText();
  t.fontName = {family: "Inter", style: bold ? "Bold" : "Regular"};
  t.characters = String(text);
  t.fontSize = Math.round(sz);
  t.fills = [{type:"SOLID", color: col}];
  // Always set explicit line height — eliminates Figma's auto-leading inconsistencies
  // Display sizes (sz >= 11): tight 1.08× for print-quality heading rhythm
  const lineH = lh || (sz < 11 ? Math.round(sz * 1.55) : Math.round(sz * 1.08));
  t.lineHeight = {value: lineH, unit: "PIXELS"};
  if (maxW) {
    t.textAutoResize = "HEIGHT";
    t.resize(Math.max(10, Math.round(maxW)), 400);
  }
  if (align === "center") t.textAlignHorizontal = "CENTER";
  if (align === "right")  t.textAlignHorizontal = "RIGHT";
  t.x = Math.round(x);
  t.y = Math.round(y);
  p.appendChild(t);
  return t;
}

function navyBand(p, h) {
  rct(p, 0, 0, 450, Math.round(h), N, "NavyBand");
}

// --- page builders ---

async function pageCover(d) {
  const f = fr("Cover", N);
  // Full-bleed photo — entire canvas
  ph(f, 0, 0, 450, 450, "Cover photo", d.cover_photo);
  // Navy wash — no hard lines anywhere
  rct(f, 0, 0, 450, 450, N, "NavyWash");
  f.children[f.children.length-1].opacity = 0.60;
  // Bottom masthead: logo left + year right — one unified horizontal element.
  // Both sit on the same baseline. Logo bottom = 422px → exactly 28px bottom margin.
  // No rule. No tagline. No floating elements. Just the brand mark and the year.
  logo(f, 28, 392, 160, 30, "HUBSS logo white", d.brand && d.brand.logo_white);
  // Align text baseline with logo vertical centre (logo h=30 → centre=392+15=407; text lh=10 → centre=y+5; y=402)
  await tx(f, "CATALOGUE 2026", 28, 402, 6.5, W, false, 394, "right", 10);
  return f;
}

async function pageHalfTitle(d) {
  const f = fr("Half Title");
  // Logo: refined to 180px — 40% of frame width, controlled and dignified.
  // Centred: x = (450 - 180) / 2 = 135. Optical centre sits above geometric midpoint.
  logo(f, 135, 172, 180, 40, "HUBSS logo colour", d.brand && d.brand.logo_color);
  // Rule: 24px centred tick (225 − 12 = 213), 12px below logo
  rct(f, 213, 222, 24, 1, O, "OrangeRule");
  await tx(f, "Catalogue 2026", 25, 236, 8, M, false, 400, "center", 12);
  await tx(f, "Established 1994", 25, 252, 6, F, false, 400, "center", 9);
  return f;
}

async function pageManifesto(d) {
  const f = fr("03 — Manifesto");
  const m = d.manifesto || {};
  // Label — 8px top margin, standard 28px left
  await tx(f, (m.eyebrow||"WHO WE ARE").toUpperCase(), 28, 40, 6, O, false, 394);
  // H1 display — 26px, tight 1.15× leading baked in by tx()
  let y = 76;
  const lines = m.h1_lines || ["The street", "is the canvas.", "We supply the paint."];
  for (let i = 0; i < lines.length; i++) {
    const col = (i === (m.h1_orange_line || 0)) ? O : D;
    await tx(f, lines[i], 28, y, 26, col, true, 394);
    y += 31;  // 26px font + 5px gap = tight stacked display
  }
  // Body copy — 16px gap from headline block
  await tx(f, m.body || "", 28, y + 16, 8, D, false, 362);
  rct(f, 28, 398, 394, 1, F, "rule");
  await tx(f, (m.signature || "").toUpperCase(), 28, 408, 5.5, F, false, 394);
  return f;
}

async function pageWhyStats(d) {
  const f = fr("04 — Why HUB Stats");
  const w = d.why_hub || {};
  await tx(f, (w.eyebrow||"WHY HUB").toUpperCase(), 28, 38, 6, O, false, 394);
  let y = 66;
  for (const line of (w.title_lines || [])) {
    await tx(f, line, 28, y, 22, D, true, 394);
    y += 27;  // 22px font, tight leading
  }
  // Stat cards — 2×2 grid, navy bg, orange number
  const stats = w.stats || [];
  const cw = 197, ch = 88, gy = 222;
  for (let i = 0; i < Math.min(stats.length, 4); i++) {
    const col = i % 2, row = Math.floor(i / 2);
    const gx = 28 + col * (cw + 6), gyy = gy + row * (ch + 6);
    rct(f, gx, gyy, cw, ch, N, "StatCard");
    // Number — 28px bold orange, inset 10px
    await tx(f, String(stats[i][0]||""), gx+10, gyy+10, 28, O, true, cw-20);
    // Stat label — 6px caps white
    await tx(f, String(stats[i][1]||"").toUpperCase(), gx+10, gyy+50, 6, W, false, cw-20, null, 9);
    // Sub-label — 6.5px mid grey
    await tx(f, String(stats[i][2]||""), gx+10, gyy+62, 6.5, M, false, cw-20, null, 10);
  }
  rul(f, 28, 430, 32);
  return f;
}

async function pageWhyProof(d) {
  const f = fr("05 — Why HUB Proof");
  const w = d.why_hub || {};
  await tx(f, "FOUR REASONS", 28, 38, 6, O, false, 394);
  await tx(f, "If it goes on the street,", 28, 64, 20, D, true, 394);
  await tx(f, "it stays on the street.", 28, 90, 20, O, true, 394);
  let y = 150;
  for (const [num, claim, detail] of (w.proof || [])) {
    await tx(f, String(num), 28, y, 6.5, O, false, 28, null, 10);
    await tx(f, claim, 58, y, 10, D, true, 350);
    await tx(f, detail, 58, y+14, 7.5, M, false, 350);
    rct(f, 28, y+46, 394, 1, F, "rule");
    y += 58;
  }
  rul(f, 28, 430, 32);
  return f;
}

async function pageTOC(sections, totalPages) {
  const f = fr("Contents");
  await tx(f, "CATALOGUE 2026", 28, 38, 6, O, false, 394, null, 9);
  await tx(f, "Contents.", 28, 52, 22, D, true, 394);
  rct(f, 28, 94, 394, 1, F, "rule");
  let y = 112;
  for (let i = 0; i < sections.length; i++) {
    const [label, num] = sections[i];
    const idx = String(i + 1).padStart(2, "0");
    // Row height = 40px, text lh = 13px → vertical centre offset = (40-13)/2 ≈ 13px from top rule
    // top rule at y-18, so centred text at y-18+13 = y-5; we use y-4 (nearest px)
    await tx(f, idx, 28, y - 4, 8, O, true, 28, null, 13);
    await tx(f, label, 62, y - 4, 9.5, D, false, 300, null, 13);
    await tx(f, String(num), 28, y - 4, 9, M, false, 394, "right", 13);
    rct(f, 28, y + 22, 394, 1, F, "rule");
    y += 40;
  }
  // Footer — dynamic page count, right-aligned
  await tx(f, String(totalPages || 100) + " pages", 28, y + 16, 6, F, false, 394, "right", 9);
  return f;
}

async function pageSectionOpen(num, title, imagePath) {
  // Cinematic section opener — photo breathes at top, type anchors at bottom.
  // Scrim builds from invisible to dense only in the text zone. Clean and confident.
  const f = fr(`Section ${num} — ${title}`, N);
  ph(f, 0, 0, 450, 450, "Section opener: " + title, imagePath);
  // Single smooth scrim — avoids banding. Photo is the hero.
  rct(f, 0, 260, 450, 190, N, "Scrim");
  f.children[f.children.length-1].opacity = 0.75;
  // Eyebrow + rule — precise alignment. 24px tick rule reads as a confident mark.
  await tx(f, ("SECTION " + num).toUpperCase(), 28, 324, 5.5, W, false, 394, null, 8);
  rul(f, 28, 318, 24);
  // Title — 40px for real cinematic presence. More drama than before.
  await tx(f, title, 28, 346, 40, W, true, 394);
  return f;
}

async function pageProductHero(prod) {
  const f = fr("Hero — " + prod.name, N);
  // Photo fills top 63% — hard print edge into navy band
  ph(f, 0, 0, 450, 284, prod.name + " — hero photo", prod.hero);
  rct(f, 0, 284, 450, 166, N, "NavyBand");
  // Band internal layout: 24px top breathing room before first text
  // Rule sits immediately above the eyebrow label — directly adjacent, not floating
  await tx(f, (prod.name||"").toUpperCase(), 28, 320, 6.5, O, false, 394, null, 9);
  rul(f, 28, 314, 24);   // rule 6px above the label — clear typographic relationship
  // Tagline: 14px below label bottom (label 6.5px + lh≈10, bottom≈330; gap to 344)
  await tx(f, prod.tagline || "", 28, 344, 21, W, true, 394);
  return f;
}

async function pageProductSpec(prod) {
  const f = fr("Spec — " + prod.name);
  // Band height 116px — enough room to push all header text into the 28px safe zone
  navyBand(f, 116);
  // Header text starts at y=28: the same safe-zone margin used everywhere else.
  // At 450px = 5", y=16 puts live text ~1mm from the trim edge — not print-safe.
  // y=28 = ~3mm from edge, safely inside the live area on any print spec.
  await tx(f, "BY HUB SURFACE SYSTEMS", 28, 28, 5.5, O, false, 394, null, 8);
  // Product name: 8px below eyebrow bottom (eyebrow bottom = 28+8 = 36, name at 44)
  await tx(f, prod.name || "", 28, 44, 24, W, true, 394);
  // Rule: 6px below name bottom (name bottom ≈ 44+28 = 72, rule at 78)
  rul(f, 28, 78, 24);
  // Category: 4px below rule
  await tx(f, (prod.category || "Decorative Pavement").toUpperCase(), 28, 84, 5.5, W, false, 394, null, 8);

  // Body zone — 28px breathing room below band (band ends at 116, content at 144)
  const title = prod.title || prod.name;
  await tx(f, title, 28, 144, 21, D, true, 394);
  await tx(f, prod.italic || "", 28, 184, 8.5, M, false, 394);
  const callout = ((prod.callout||"") + "  ·  " + (prod.callout_unit||"")).toUpperCase();
  rul(f, 28, 210, 24);
  await tx(f, callout, 28, 216, 6, O, false, 394, null, 9);
  await tx(f, prod.body || "", 28, 230, 8, D, false, 394);

  // Spec grid — anchored from bottom, leaving intentional white space above
  if (prod.spec_pairs && prod.spec_pairs.length) {
    rct(f, 28, 308, 394, 1, F, "rule");
    const colX = [28, 162, 296];
    for (let i = 0; i < Math.min(prod.spec_pairs.length, 6); i++) {
      const [lbl, val] = prod.spec_pairs[i];
      const col = i % 3, row = Math.floor(i / 3);
      const xx = colX[col], yy = 320 + row * 30;
      await tx(f, (lbl||"").toUpperCase(), xx, yy, 5.5, F, false, 124, null, 8);
      await tx(f, val||"", xx, yy+10, 8, D, true, 124, null, 12);
    }
  }
  // Uses — footer: rule then centred uses line, pinned near page bottom
  if (prod.uses && prod.uses.length) {
    rct(f, 28, 392, 394, 1, F, "rule");
    await tx(f, prod.uses.join("   ·   ").toUpperCase(), 28, 402, 6, M, false, 394, "center", 9);
  }
  // CTA: spec sheet URL — y=402 keeps bottom=412, well clear of folio at y=415
  await tx(f, "hubss.com/products", 28, 402, 6.5, O, false, 394, "right", 10);
  return f;
}

async function pageApplication(app, idx, total) {
  const f = fr(`App ${String(idx).padStart(2,"0")} — ${app.name}`);
  ph(f, 0, 0, 450, 288, app.name + " — application photo", app.image);
  await tx(f, `APPLICATION   ${String(idx).padStart(2,"0")} / ${String(total)}`, 30, 306, 5.5, O, false, 370);
  await tx(f, app.name, 30, 321, 19, D, true, 390);
  await tx(f, app.tagline || "", 30, 354, 8.5, M, false, 370);
  await tx(f, app.body || "", 30, 376, 7.5, D, false, 370);
  // Footer: moved up from y=418 — clear of safe margin, no folio collision (App pages skip folios)
  rct(f, 30, 406, 390, 1, F, "rule");
  await tx(f, "hubss.com", 30, 414, 6.5, O, false, 390, "right", 10);
  return f;
}

async function pageProjectHero(proj) {
  const f = fr("Hero — " + proj.name, N);
  ph(f, 0, 0, 450, 284, proj.name + " — hero photo", proj.hero);
  rct(f, 0, 284, 450, 166, N, "NavyBand");
  // Same rule-above-label discipline as product hero
  await tx(f, (proj.name||"").toUpperCase(), 28, 320, 6.5, O, false, 394, null, 9);
  rul(f, 28, 314, 24);
  await tx(f, proj.title || "", 28, 344, 20, W, true, 394);
  // Location/product footer — white rule divider, then two-column detail line
  rct(f, 28, 406, 394, 1, {r:1,g:1,b:1}, "Divider");
  f.children[f.children.length-1].opacity = 0.18;
  await tx(f, (proj.location||"").toUpperCase(), 28, 418, 6, W, false, 190, null, 9);
  await tx(f, (proj.product||"").toUpperCase(), 232, 418, 6, O, false, 190, null, 9);
  return f;
}

async function pageProjectStory(proj, idx) {
  const f = fr(`Story ${String(idx).padStart(2,"0")} — ${proj.name}`);
  // FILL mode: full-bleed, edge-to-edge. Subject centered by default.
  ph(f, 0, 0, 450, 248, proj.name + " — detail photo", proj.detail || proj.hero);
  // Eyebrow = product (e.g. "MMAX", "TRAFFICPATTERNS XD") — tells reader WHAT product achieved this
  const eyebrowLabel = proj.product ? proj.product.toUpperCase() : "";
  if (eyebrowLabel) {
    await tx(f, eyebrowLabel, 30, 262, 5.5, O, false, 370, null, 8);
  }
  // H2: project name. Tagline stays on the hero page — no repetition.
  await tx(f, proj.name || "", 30, 276, 16, D, true, 370);
  // Location only — product is already the eyebrow, don't duplicate it here
  await tx(f, (proj.location||"").toUpperCase(), 30, 306, 5.5, M, false, 370, null, 8);
  rct(f, 30, 318, 390, 1, {r:0.88,g:0.88,b:0.88}, "StoryRule");
  await tx(f, proj.story || "", 30, 328, 7.5, D, false, 390);
  return f;
}

async function pageInstaller(inst, idx, total) {
  const f = fr("Installer — " + inst.name);
  // Navy header band — credential zone. Keeps photo uncluttered.
  navyBand(f, 152);
  // Credential badge top-left, counter top-right — both sit in the navy zone
  await tx(f, "HUB CERTIFIED INSTALLER", 28, 28, 5.5, O, false, 260, null, 8);
  await tx(f, String(idx).padStart(2,"0") + " / " + String(total).padStart(2,"0"), 28, 28, 5.5, {r:0.38,g:0.38,b:0.38}, false, 394, "right", 8);
  // Name: 30px — large, white, in the navy zone
  await tx(f, inst.name, 28, 52, 30, W, true, 394);
  // Region: small caps, muted charcoal on navy
  await tx(f, (inst.region || "").toUpperCase(), 28, 102, 5.5, {r:0.45,g:0.45,b:0.45}, false, 394, null, 8);
  rul(f, 28, 128, 32);
  // Contained editorial photo — full width, runs from bottom of header to content zone
  ph(f, 0, 152, 450, 192, inst.name + " — photo", inst.image);
  // White content zone below photo
  await tx(f, inst.body || "", 28, 360, 8, D, false, 394);
  // Footer: moved up to y=400/410 — bottom=420, gap=30px (≥0.25" safe margin)
  rct(f, 28, 400, 394, 1, F, "rule");
  await tx(f, inst.phone || "", 28, 410, 10, D, true, 190);
  await tx(f, inst.url || "", 238, 411, 9, O, false, 182);
  return f;
}

// pageNetworkOpen — Network section opener. Photo top, solid navy bottom.
// The title is pushed lower for more drama — photo breathes, type anchors.
async function pageNetworkOpen(d) {
  const f = fr("Section Four — Network", N);
  ph(f, 0, 0, 450, 244, "Network section opener", d.section_openers && d.section_openers.network);
  rct(f, 0, 244, 450, 206, N, "NavyBand");
  // Section label — restrained, 6px
  await tx(f, "SECTION FOUR", 28, 264, 5.5, O, false, 394, null, 8);
  rul(f, 28, 280, 24);
  // Title — 40px for real presence. More air between lines.
  await tx(f, "Certified", 28, 296, 40, W, true, 394);
  await tx(f, "Installers.", 28, 348, 40, O, true, 394);
  return f;
}

// pageDoublespread — two facing pages that read as one editorial spread.
// Left page: headline anchored bottom-left (big idea, reading direction cue).
// Right page: matching image, CTA URL bottom-right (where to go next).
// The left→right pairing creates intentional narrative: statement → action.
async function pageDoublespread(label, imagePath, caption, rightStyle, rightImagePath) {
  // Left page — headline lives here. Reader's eye enters bottom-left.
  const fL = fr("Spread L — " + (label||""), N);
  ph(fL, 0, 0, 450, 450, label + " — left", imagePath);
  // Deep scrim across bottom third — legibility without killing the photo
  rct(fL, 0, 340, 450, 110, N, "ScrimBottom");
  fL.children[fL.children.length-1].opacity = 0.72;
  // Orange rule: thin horizontal anchor above text block
  rul(fL, 28, 352, 20);
  // Eyebrow: small-caps label identifies which spread this is
  await tx(fL, (label||"").toUpperCase(), 28, 361, 6, O, false, 394, null, 9);
  // Headline: the bold editorial statement — white, confident, left-aligned
  if (caption) {
    await tx(fL, caption, 28, 382, 10.5, W, true, 390, null, 15);
  }

  // Right page — photo CTA by default; navy brand statement when rightStyle === "navy"
  const fR = fr("Spread R — " + (label||""), N);
  if (rightStyle === "navy") {
    // Closing editorial — navy, giant type, lands as a final statement.
    rul(fR, 28, 80, 32);
    await tx(fR, "THIRTY YEARS IN THE MAKING.", 28, 96, 6, O, false, 394, null, 9);
    await tx(fR, "Built to", 28, 116, 52, W, true, 394);
    await tx(fR, "outlast.", 28, 180, 52, O, true, 394);
    rct(fR, 28, 248, 394, 1, {r:1,g:1,b:1}, "Divider");
    fR.children[fR.children.length-1].opacity = 0.15;
    await tx(fR, "30+ years   ·   1,000+ projects   ·   500+ municipalities", 28, 262, 7.5, M, false, 394, "center", 11);
    rct(fR, 28, 288, 394, 1, {r:1,g:1,b:1}, "Divider");
    fR.children[fR.children.length-1].opacity = 0.08;
    await tx(fR, "The surface beneath every city we've built.", 28, 308, 12, W, false, 360);
    await tx(fR, "Spec the surface. Watch it work. Walk over it for twenty years.", 28, 332, 8, M, false, 360);
    rct(fR, 28, 404, 394, 1, O, "OrangeRule");
    await tx(fR, "hubss.com", 28, 414, 7.5, O, true, 394, "right", 11);
  } else {
    // Photo right — use rightImagePath if supplied, else mirror left
    ph(fR, 0, 0, 450, 450, label + " — right", rightImagePath || imagePath);
    rct(fR, 0, 418, 450, 32, N, "FooterBand");
    fR.children[fR.children.length-1].opacity = 0.72;
    // URL: orange, right-aligned — unmistakable action anchor
    await tx(fR, "hubss.com", 28, 426, 7.5, O, true, 394, "right", 11);
  }
  return [fL, fR];
}

// pageImageSpread — full-bleed editorial photo page. No product info.
// Used as visual punctuation between catalogue sections.
async function pageImageSpread(label, imagePath, headline) {
  const f = fr("Spread — " + (label||""), N);
  ph(f, 0, 0, 450, 450, label, imagePath);
  // Minimal footer — dark band, orange rule, caption in small caps
  rct(f, 0, 404, 450, 46, N, "CaptionBand");
  rul(f, 30, 410, 30);
  if (headline) {
    await tx(f, headline.toUpperCase(), 68, 413, 6, W, false, 352);
  }
  return f;
}

async function pageTechnical() {
  const f = fr("Reference — Technical");
  await tx(f, "TECHNICAL REFERENCE", 30, 40, 7, O, false, 370);
  await tx(f, "At a Glance.", 30, 68, 24, D, true, 370);
  const prods = [
    ["TrafficPatternsXD", "Thermoplastic", "High-durability preformed marking"],
    ["TrafficPatterns",   "Thermoplastic", "Standard preformed marking"],
    ["StreetBond",        "MMA Coating",   "Decorative coloured pavement"],
    ["StreetPrint",       "Stamped Asphalt","Brick and stone patterns"],
    ["DecoMark",          "Epoxy",         "Coloured crosswalk systems"],
    ["MMAX",              "MMA Resin",     "Coloured lane treatment"],
    ["DuraTherm",         "Inlaid",        "Snowplow-safe flush inlay"],
    ["DuraShield",        "Penetrating",   "Asphalt rejuvenator"],
    ["PreMark",           "Pre-cut",       "Bike infrastructure markings"],
    ["AirMark",           "Airfield",      "FAA-compliant markings"],
  ];
  let y = 128;
  for (const [name, key, desc] of prods) {
    await tx(f, name, 30, y, 9, D, true, 148);
    await tx(f, key.toUpperCase(), 185, y, 6, O, false, 110);
    await tx(f, desc, 272, y, 8, M, false, 158);
    rct(f, 30, y+15, 390, 1, F, "rule");
    y += 22;
  }
  return f;
}

async function pageCities(d) {
  const f = fr("Reference — Cities");
  // "500+" as hero stat — visual anchor, gives the city list credibility and scale
  await tx(f, "500+", 30, 28, 60, O, true, 390);
  await tx(f, "Canadian municipalities", 30, 98, 9, D, false, 280, null, 13);
  await tx(f, "that specify HUB systems by name.", 30, 113, 9, M, false, 280, null, 13);
  await tx(f, "FROM HALIFAX TO VANCOUVER", 30, 133, 5.5, F, false, 390, null, 8);
  rct(f, 30, 150, 390, 1, F, "rule");
  await tx(f, "A partial list", 30, 158, 7, M, false, 390, "right", 10);
  // City list — 2 columns, 8px type, generous spacing
  const cities = d.cities || [];
  let y = 172;
  for (let i = 0; i < cities.length; i += 2) {
    if (y > 418) break;
    await tx(f, cities[i]||"", 30, y, 8, D, false, 185);
    if (cities[i+1]) await tx(f, cities[i+1], 235, y, 8, D, false, 175);
    y += 13;
  }
  return f;
}

async function pageLunchLearn(mascotPath) {
  // PREMIUM L&L — editorial split: left type / right Moose. Warm and confident.
  // Moose fills the full right half — he's the visual hook, not a corner decoration.
  const f = fr("CTA — Lunch and Learn");

  // Moose — right half, generous and prominent. FIT/logo mode: transparent, never cropped.
  logo(f, 238, 12, 198, 270, "Moose — HUB mascot", mascotPath);

  // Left column — generous leading, breathing room between each element
  await tx(f, "FOR ENGINEERS", 28, 24, 5, O, false, 200, null, 8);
  await tx(f, "PLANNERS + SPECIFIERS", 28, 33, 5, O, false, 200, null, 8);
  rul(f, 28, 48, 20);
  await tx(f, "Lunch", 28, 60, 30, D, true, 200);
  await tx(f, "Is On Us.", 28, 96, 30, O, true, 200);

  // Benefit list — restrained, generous spacing
  const items = [
    "45 min, tailored to your project",
    "Live Q&A with technical team",
    "Spec sheets + sample materials",
    "AIBC / RAIC / PEO CE credits",
    "Lunch included — $25 virtual voucher",
    "No cost · No obligation",
  ];
  let dy = 146;
  for (const item of items) {
    await tx(f, "— " + item, 28, dy, 7, D, false, 200);
    dy += 14;
  }
  rct(f, 28, dy + 8, 200, 1, F, "Separator");
  await tx(f, "Not a sales pitch. An education.", 28, dy + 18, 7.5, M, false, 200, null, 11);

  // Full-width bottom zone: generous gap between Moose zone and URL block
  rct(f, 28, 296, 394, 1, F, "rule");
  await tx(f, "hubss.com/lunch-learn", 28, 306, 14, O, true, 394);
  await tx(f, "Toronto · York Region · Vancouver · UBC · TransLink · 500+ municipalities", 28, 330, 6.5, M, false, 394, "center", 10);

  rct(f, 28, 350, 394, 1, F, "rule");
  await tx(f, "BOOK DIRECTLY WITH YOUR REGIONAL CONTACT", 28, 358, 5, F, false, 394, null, 8);
  await tx(f, "Cleve Stordy   604.309.8212", 28, 370, 9, D, false, 188, null, 13);
  await tx(f, "Doug Bain   416.540.9287", 238, 370, 9, D, false, 178, null, 13);
  rct(f, 28, 396, 394, 1, F, "rule");
  await tx(f, "HUB SURFACE SYSTEMS   ·   hubss.com", 28, 404, 5.5, F, false, 394, "center", 8);
  return f;
}

async function pageContact(d) {
  // Contact page — editorial premium. Navy band anchors, generous whitespace below.
  // Names scaled DOWN to 14px — they are contacts, not headlines. White space does the work.
  const f = fr("Contact");
  // Navy band — identity zone
  rct(f, 0, 0, 450, 88, N, "NavyBand");
  await tx(f, "TWO OFFICES. ONE NETWORK.", 30, 16, 5, O, false, 390, null, 8);
  rul(f, 30, 32, 20);
  await tx(f, "Speak with HUB.", 30, 46, 20, W, true, 390);

  // Tagline — generous air above
  await tx(f, "Every project starts with a conversation.", 30, 106, 9, M, false, 390, null, 14);
  rct(f, 30, 130, 390, 1, F, "rule");

  // West — names at 14px, contacts refined not oversized
  await tx(f, "WESTERN CANADA", 30, 146, 5, O, false, 188, null, 8);
  await tx(f, "Cleve Stordy", 30, 160, 14, D, true, 188);
  await tx(f, "cleve.stordy@hubss.com", 30, 184, 8, D, false, 188);
  await tx(f, "604.309.8212", 30, 200, 8, M, false, 188);
  await tx(f, "Ladysmith, British Columbia", 30, 216, 7, M, false, 188);

  // East
  await tx(f, "EASTERN CANADA", 242, 146, 5, O, false, 178, null, 8);
  await tx(f, "Doug Bain", 242, 160, 14, D, true, 178);
  await tx(f, "doug.bain@hubss.com", 242, 184, 8, D, false, 178);
  await tx(f, "416.540.9287", 242, 200, 8, M, false, 178);
  await tx(f, "Milton, Ontario", 242, 216, 7, M, false, 178);

  rct(f, 30, 244, 390, 1, F, "rule");

  // URL — one bold destination, generous space
  await tx(f, "hubss.com", 30, 258, 20, O, true, 390);
  await tx(f, "Spec sheets · Project gallery · Installer network · Lunch + Learn", 30, 294, 7.5, M, false, 390, null, 11);

  rct(f, 30, 322, 390, 1, F, "rule");
  await tx(f, "© 2026 HUB Surface Systems   ·   Established 1994   ·   Coast to Coast", 30, 332, 5, F, false, 390, "center", 8);
  return f;
}

async function pageClosing() {
  // Final word. Generous white space — the page earns the silence.
  // Upper half breathes. Lower half anchors. Statement in between.
  const f = fr("Closing — The Street");

  // Eyebrow — small, precisely tracked, not competing with headline
  await tx(f, "THE STREET IS", 28, 60, 5.5, O, false, 394, null, 8);
  rul(f, 28, 76, 20);

  // Display headline — maximum negative space above it
  await tx(f, "The public realm.", 28, 94, 40, D, true, 360);
  await tx(f, "Ours to build right.", 28, 150, 40, O, true, 360);

  // 48px orange rule accent — editorial not decorative
  rct(f, 28, 210, 48, 2, O, "Accent");

  // Statement — relaxed leading, breathing room on all sides
  await tx(f, "Every surface we build is walked over, driven on, played at, and lived around. That is the standard we hold ourselves to. Specify it right. Watch it work. Walk over it for twenty years.", 28, 228, 9.5, D, false, 330, null, 15);

  // Sign-off — three words as a trio, slightly more spacing between them
  rct(f, 28, 360, 394, 1, F, "rule");
  await tx(f, "SPECIFIED.", 28, 374, 8.5, D, true, 118);
  await tx(f, "INSTALLED.", 166, 374, 8.5, D, true, 118);
  await tx(f, "BACKED.", 304, 374, 8.5, D, true, 100);
  rul(f, 28, 396, 28);
  await tx(f, "HUB SURFACE SYSTEMS", 28, 404, 5, F, false, 394, "center", 8);
  return f;
}

async function pageService() {
  const f = fr("Closing — Service Promise");
  await tx(f, "HOW WE WORK", 28, 50, 6.5, O, false, 394);
  await tx(f, "Specified.", 28, 76, 24, D, true, 394);
  await tx(f, "Installed.", 28, 110, 24, D, true, 394);
  await tx(f, "Backed.", 28, 144, 24, D, true, 394);
  await tx(f, "Every HUB project is spec-supported, installer-trained, and backed by our performance guarantee.", 28, 205, 8.5, D, false, 394);
  return f;
}

async function pageQuietMark(d) {
  const f = fr("Closing — HUB Mark");
  // Optical centre — logo sits in the upper third, generous air around it
  // 148×32px frame: same proportions as cover/back-cover for visual system cohesion
  logo(f, 151, 162, 148, 32, "HUBSS logo colour", d.brand && d.brand.logo_color);
  // Rule then type — spaced on a 16px baseline grid from logo bottom (y=194)
  rct(f, 213, 208, 24, 1, O, "OrangeRule");
  await tx(f, "HUB SURFACE SYSTEMS", 28, 220, 7, D, true, 394, "center", 11);
  await tx(f, "ESTABLISHED 1994   ·   COAST TO COAST", 28, 235, 5.5, F, false, 394, "center", 8);
  rct(f, 98, 260, 254, 1, F, "Divider");
  await tx(f, "Thank you.", 28, 280, 13, M, false, 394, "center", 18);
  return f;
}

async function pageBack(d) {
  const f = fr("Back Cover", N);
  ph(f, 0, 0, 450, 450, "Back cover — asphalt photo", d.brand && d.brand.asphalt_photo);
  // Single smooth navy wash — lets photo texture breathe while legibility is guaranteed
  rct(f, 0, 0, 450, 450, N, "NavyWash");
  f.children[f.children.length-1].opacity = 0.72;
  // Logo: FIT mode, 32px tall — centred, restrained
  // 148px wide gives correct aspect for ~5:1 horizontal wordmark
  logo(f, 151, 178, 148, 32, "HUBSS logo white — centred", d.brand && d.brand.logo_white);
  // Rule separates logo from tagline
  rct(f, 213, 222, 24, 1, O, "OrangeRule");
  await tx(f, "Canada's Leading Decorative Pavement Solutions", 28, 234, 7.5, W, false, 394, "center", 11);
  await tx(f, "hubss.com", 28, 254, 9, W, true, 394, "center", 13);
  // Light divider
  rct(f, 98, 280, 254, 1, {r:1,g:1,b:1}, "Divider");
  f.children[f.children.length-1].opacity = 0.20;
  await tx(f, "West / Prairies   604.309.8212", 28, 292, 6.5, W, false, 394, "center", 10);
  await tx(f, "Central / Maritimes   416.540.9287", 28, 306, 6.5, W, false, 394, "center", 10);
  await tx(f, "© 2026 HUB Surface Systems", 28, 330, 5.5, M, false, 394, "center", 8);
  return f;
}

async function pageBlank(idx) {
  // Intentional rest page — minimal, never truly empty.
  // Centred orange dash signals editorial breathing room, not an oversight.
  const f = fr("Rest " + idx);
  rct(f, 213, 224, 24, 2, O, "OrangeRule");
  return f;
}

// pageFieldNotes — a ruled notepad page for specifiers.
// Simple, intentional — the specifier gets a physical place to record their project details.
// Sits after the Contact page so it directly faces the contact information.
// addFolio — page number at bottom of content pages.
// y=415: bottom=423, gap=27px (0.3" from trim edge — within 0.25" safe margin).
// Skipped on: Cover, Back Cover, Half Title, Rest/blank, Section openers, Spread/DPS.
async function addFolio(frame, num) {
  await tx(frame, String(num), 28, 415, 5.5, M, false, 394, "center", 8);
}

async function pageFieldNotes() {
  const f = fr("Field Notes");
  // Header: small-caps label + orange rule — same visual grammar as the rest of the catalogue
  await tx(f, "FIELD NOTES", 28, 36, 6, O, false, 394, null, 9);
  rul(f, 28, 54, 20);
  await tx(f, "Your project. Your notes.", 28, 64, 7.5, M, false, 300, null, 11);
  // 14 ruled lines evenly distributed across the body — 96px to 398px
  const lineY0 = 96, lineY1 = 398, lineCount = 14;
  const lineGap = Math.round((lineY1 - lineY0) / (lineCount - 1));
  for (let i = 0; i < lineCount; i++) {
    rct(f, 28, lineY0 + i * lineGap, 394, 1, F, "NoteLine");
  }
  // Footer: moved up — bottom=~414, gap=36px (≥0.25" safe margin)
  rct(f, 28, 402, 394, 1, F, "rule");
  await tx(f, "HUB SURFACE SYSTEMS   ·   hubss.com   ·   604.309.8212   ·   416.540.9287", 28, 410, 5.5, F, false, 394, "center", 8);
  return f;
}

// pageHubNumbers — navy full-bleed stats spread.
// Giant orange numbers on navy — maximum typographic confidence.
async function pageHubNumbers() {
  const f = fr("By the Numbers", N);
  await tx(f, "BY THE NUMBERS", 28, 38, 6, O, false, 394, null, 9);
  rul(f, 28, 56, 24);
  // Three stacked stats — descending scale (56 → 44 → 44)
  const rows = [
    ["30+",    "years building Canadian streets"],
    ["1,000+", "projects completed coast to coast"],
    ["500+",   "municipalities that specify HUB by name"],
  ];
  let sy = 80;
  for (const [num, label] of rows) {
    await tx(f, num, 28, sy, 56, O, true, 394);          // lh = 56*1.18 = 66
    await tx(f, label, 28, sy + 72, 8.5, W, false, 360); // caption below number
    rct(f, 28, sy + 96, 394, 1, {r:1,g:1,b:1}, "Divider");
    f.children[f.children.length-1].opacity = 0.12;
    sy += 116;
  }
  return f;
}

// pageStatement — editorial quote page on white.
// A breath before the product sections begin. Clean typographic confidence.
async function pageStatement() {
  const f = fr("Editorial — Statement");
  await tx(f, "THE SURFACE UNDERFOOT", 28, 60, 6, O, false, 394, null, 9);
  await tx(f, "Every surface", 28, 86, 30, D, true, 394);
  await tx(f, "tells the city's", 28, 124, 30, D, true, 394);
  await tx(f, "story first.", 28, 162, 30, O, true, 394);
  rct(f, 28, 214, 32, 2, O, "OrangeRule");
  await tx(f, "From a community crosswalk in Sechelt to a transit corridor in Toronto, the mark on the street carries meaning beyond its function. Specify it right. Choose it to last twenty years.", 28, 230, 9.5, D, false, 330);
  rct(f, 28, 398, 394, 1, F, "rule");
  await tx(f, "hubss.com", 28, 410, 7, O, true, 394, "right", 11);
  return f;
}

// --- main build ---
async function buildCatalogue(d) {
  await figma.loadFontAsync({family:"Inter", style:"Regular"});
  await figma.loadFontAsync({family:"Inter", style:"Bold"});

  const frames = [];

  // Front matter — TOC on p3 so readers can navigate from the first spread
  frames.push(await pageCover(d));        // 0 = p1
  frames.push(await pageHalfTitle(d));    // 1 = p2
  frames.push(null);                      // 2 = p3  TOC — filled after numbering
  frames.push(await pageManifesto(d));    // 3 = p4  Brand promise (not in TOC — editorial)
  frames.push(await pageWhyStats(d));     // 4 = p5  Why HUB stats
  frames.push(await pageWhyProof(d));     // 5 = p6  Why HUB proof
  frames.push(await pageHubNumbers());    // 6 = p7  Bold stats moment — navy
  frames.push(await pageStatement());     // 7 = p8  Editorial statement — white

  // DPS-A — opening editorial. Full-bleed before Products section.
  // Vernon swaps images in Figma for final. Keys: dps_a_left / dps_a_right.
  {
    const dpsAL = d.section_openers && d.section_openers.dps_a_left;
    const dpsAR = d.section_openers && d.section_openers.dps_a_right;
    if (dpsAL) {
      const [aL, aR] = await pageDoublespread("The Work", dpsAL, "From every intersection, a statement.", undefined, dpsAR || dpsAL);
      frames.push(aL, aR);
    }
  }

  // Section 1 — Products
  const productsPage = frames.length + 1;
  frames.push(await pageSectionOpen("One", "Products.", d.section_openers && d.section_openers.products));
  for (const prod of (d.products || [])) {
    frames.push(await pageProductHero(prod));
    frames.push(await pageProductSpec(prod));
  }
  // Double-page spread at end of products — pure editorial punch, no product content.
  // Left: editorial_products image. Right: different image (projects section opener).
  {
    const dpsImg = (d.section_openers && d.section_openers.editorial_products)
      || (d.section_openers && d.section_openers.applications)
      || (d.projects && d.projects[1] && d.projects[1].hero);
    const dpsImgR = (d.section_openers && d.section_openers.editorial_products_r)
      || (d.section_openers && d.section_openers.projects)
      || (d.products && d.products[2] && d.products[2].hero);
    if (dpsImg) {
      const [sL, sR] = await pageDoublespread("In the Field", dpsImg, "Designed for the city. Built for the street.", undefined, dpsImgR);
      frames.push(sL, sR);
    }
  }

  // Section 2 — Applications
  const appsPage = frames.length + 1;
  frames.push(await pageSectionOpen("Two", "Applications.", d.section_openers && d.section_openers.applications));
  const nApps = (d.applications || []).length;
  let appIdx = 0;
  for (const app of (d.applications || [])) {
    appIdx++;
    frames.push(await pageApplication(app, appIdx, nApps));
  }

  // DPS-B — transition between Applications and Projects. Full-bleed visual breather.
  // Keys: dps_b_left / dps_b_right.
  {
    const dpsBL = d.section_openers && d.section_openers.dps_b_left;
    const dpsBR = d.section_openers && d.section_openers.dps_b_right;
    if (dpsBL) {
      const [bL, bR] = await pageDoublespread("Across Canada", dpsBL, "Five hundred municipalities. One standard.", undefined, dpsBR || dpsBL);
      frames.push(bL, bR);
    }
  }

  // Section 3 — Projects
  const projectsPage = frames.length + 1;
  frames.push(await pageSectionOpen("Three", "Projects.", d.section_openers && d.section_openers.projects));
  let projIdx = 0;
  const projs = d.projects || [];
  for (let pi = 0; pi < projs.length; pi++) {
    projIdx++;
    frames.push(await pageProjectHero(projs[pi]));
    frames.push(await pageProjectStory(projs[pi], projIdx));
    // Double-page spread halfway through projects — visual pause between project stories.
    // Left: editorial_projects image. Right: reference section opener (different category).
    if (pi === Math.floor(projs.length / 2) - 1) {
      const dpsImg2 = (d.section_openers && d.section_openers.editorial_projects)
        || (d.section_openers && d.section_openers.reference)
        || (projs[0] && projs[0].detail);
      const dpsImg2R = (d.section_openers && d.section_openers.editorial_projects_r)
        || (d.section_openers && d.section_openers.reference)
        || (projs[projs.length - 1] && projs[projs.length - 1].detail);
      if (dpsImg2) {
        const [sL2, sR2] = await pageDoublespread("Every Mark", dpsImg2, "Every mark tells a story.", undefined, dpsImg2R);
        frames.push(sL2, sR2);
      }
    }
  }

  // Section 4 — Network
  const networkPage = frames.length + 1;
  frames.push(await pageNetworkOpen(d));
  const installs = d.installers || [];
  for (let ii = 0; ii < installs.length; ii++) {
    frames.push(await pageInstaller(installs[ii], ii + 1, installs.length));
  }

  // DPS-C — between Network and Reference. Visual breathing room before back matter.
  // Keys: dps_c_left / dps_c_right.
  {
    const dpsCL = d.section_openers && d.section_openers.dps_c_left;
    const dpsCR = d.section_openers && d.section_openers.dps_c_right;
    if (dpsCL) {
      const [cL, cR] = await pageDoublespread("Built to Last", dpsCL, "The surface underfoot. The city above.", undefined, dpsCR || dpsCL);
      frames.push(cL, cR);
    }
  }

  // Section 5 — Reference
  const referencePage = frames.length + 1;
  frames.push(await pageSectionOpen("Five", "Reference.", d.section_openers && d.section_openers.reference));
  frames.push(await pageTechnical());
  frames.push(await pageCities(d));
  const lunchPage = frames.length + 1;
  frames.push(await pageLunchLearn(d.brand && d.brand.mascot));
  const contactPage = frames.length + 1;
  frames.push(await pageContact(d));
  // Field Notes: a ruled notepad page — faces the Contact page in the open spread.
  // Specifier reads your contact info on the left, picks up a pen on the right. Very hot.
  frames.push(await pageFieldNotes());

  // Final editorial double-page spread — dramatic closing statement before the back matter.
  // DPS3 — Spirit Trail closing spread. editorial_closing key = Spirit Trail B&W swirl crosswalk (Vancouver).
  // Cinematic full-stop before back matter. Falls back through reference if key is absent.
  {
    const closingImg = (d.section_openers && d.section_openers.editorial_closing)
      || (d.section_openers && d.section_openers.reference);
    if (closingImg) {
      const [sL3, sR3] = await pageDoublespread("The Mark", closingImg, "Specified. Installed. Built to outlast.", "navy");
      frames.push(sL3, sR3);
    }
  }

  // Pad to next multiple of 4 — saddle-stitch / perfect-bind requirement.
  // No upper-bound cap. Content count + 3 closing must be divisible by 4.
  while ((frames.length + 3) % 4 !== 0) {
    frames.push(await pageBlank(frames.length + 1));
  }

  // Closing pair + back cover
  // pageService ("Specified. Installed. Backed.") removed — DPS3 right already delivers this moment.
  frames.push(await pageClosing());
  frames.push(await pageQuietMark(d));
  frames.push(await pageBack(d));

  // TOC — six navigable sections only. Editorial front matter (Manifesto, Why HUB)
  // comes after p3 and is not listed; readers encounter it naturally front-to-back.
  const tocEntries = [
    ["Products",            productsPage],
    ["Applications",        appsPage],
    ["Projects",            projectsPage],
    ["Certified Installers",networkPage],
    ["Technical Reference", referencePage],
    ["Contact",             contactPage],
  ];
  frames[2] = await pageTOC(tocEntries, frames.length);

  // Prefix every frame name with its print page number so the Figma sidebar
  // and the TOC can be cross-referenced at a glance (p01, p02 … p100).
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (f) f.name = "p" + String(i + 1).padStart(2, "0") + " — " + f.name;
  }

  // TOC note: productsPage, appsPage, etc. are computed dynamically at the moment
  // each section is pushed into frames[], so TOC page numbers are always correct
  // regardless of front-matter changes. No hardcoded numbers anywhere.

  // Add folios to content pages. Skip pages with their own footer treatment to avoid collisions.
  // App pages: have footer URL rule at y=406 — folio would clash.
  // Story pages: always adjacent to numbered hero pages; folio redundant + story body can overflow to folio zone.
  // Field Notes: has explicit footer attribution line at y=410.
  const _noFolioNames = new Set(["Cover", "Back Cover", "Half Title", "Field Notes"]);
  const _noFolioPrefix = ["Rest ", "Section ", "Spread ", "QuarterAd", "By the Numbers", "App ", "Story "];
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (!f) continue;
    const raw = f.name.replace(/^p\d+ — /, "");
    if (_noFolioNames.has(raw)) continue;
    if (_noFolioPrefix.some(p => raw.startsWith(p))) continue;
    await addFolio(f, i + 1);
  }

  // Layout all frames in a grid and append to current page
  const COL = 10, GAP = 40;
  for (let i = 0; i < frames.length; i++) {
    const f = frames[i];
    if (!f) continue;
    f.x = (i % COL) * (450 + GAP);
    f.y = Math.floor(i / COL) * (450 + GAP);
    figma.currentPage.appendChild(f);
  }

  figma.viewport.scrollAndZoomIntoView([frames[0]]);
  figma.notify(
    "✓ " + frames.length + " pages built  ·  " +
    "Products p" + productsPage +
    "  ·  Apps p" + appsPage +
    "  ·  Projects p" + projectsPage +
    "  ·  Network p" + networkPage +
    "  ·  Ref p" + referencePage
  );
}

figma.ui.onmessage = async (msg) => {
  if (msg.type === "build") {
    try {
      await buildCatalogue(EMBEDDED_DATA);
      figma.closePlugin("Done!");
    } catch (e) {
      const m = (e && e.message) ? e.message : String(e);
      figma.notify("Build error: " + m, {error: true});
      console.error(e);
      figma.closePlugin();
    }
  } else {
    figma.closePlugin();
  }
};

figma.showUI(__html__, {width: 320, height: 200});
"""


def _generate_qr(dest_path: Path) -> bool:
    """Generate a hubss.com QR code PNG at dest_path. Returns True on success."""
    try:
        import qrcode  # pip install qrcode[pil]
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=12,
            border=3,
        )
        qr.add_data("https://hubss.com")
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        dest_path.parent.mkdir(parents=True, exist_ok=True)
        img.save(dest_path)
        print(f"  QR → {dest_path.name}")
        return True
    except ImportError:
        print("  QR skipped (pip install qrcode[pil] to enable)")
        return False


def main():
    if not DATA.exists():
        print(f"ERROR: {DATA} not found. Run: python -B -m src.export_json first.")
        return

    # Generate QR code as side-effect — embed_images.py will embed it from catalog_data.json path
    qr_path = ROOT / "public" / "images" / "assets" / "qr" / "hubss-qr.png"
    _generate_qr(qr_path)

    data = json.loads(DATA.read_text(encoding="utf-8"))
    data_json = json.dumps(data, ensure_ascii=False, separators=(",", ":"))

    # Inject the catalog data into the JS template
    code = JS.replace("CATALOG_DATA_JSON", data_json, 1)

    PLUGIN.write_bytes(code.encode("utf-8"))
    size_kb = PLUGIN.stat().st_size / 1024
    print(f"Wrote {PLUGIN.name}  ({size_kb:.0f} KB)")
    print(f"Frames: ~100 pages, all text live, photos = [PHOTO] placeholders")
    print(f"In Figma: remove old plugin, re-import manifest, click Build.")


if __name__ == "__main__":
    main()
