// Catalogue 2026 flipbook (featured on Resources).
// Server component auto-discovers the newest v{NN}/ page manifest, so the
// viewer always serves whatever the catalog build last produced. Vernon
// re-renders via scripts/render-catalogue-pages.py — that script also
// auto-detects the latest vNN PDF, so the pair stays self-syncing.
import { promises as fs } from "node:fs";
import path from "node:path";
import { notFound } from "next/navigation";
import Flipbook from "./Flipbook";
import { showCatalogue } from "@/lib/feature-flags";

// Evaluate the feature flag at request time, not build time, so flipping the
// flag in Vercel env vars doesn't require a rebuild. The page itself is
// light (manifest read + Flipbook), so dynamic rendering costs nothing.
// Note: the primary gate is middleware.ts (returns HTTP 307 → /resources);
// this page-level notFound() is defense-in-depth in case middleware misses.
export const dynamic = "force-dynamic";

async function getPageManifest(): Promise<{ pages: string[]; version: string | null; alt: string[] }> {
  // Read a single committed manifest (a static path) instead of fs.readdir'ing
  // the catalogue directory. fs.readdir made Next's file tracing bundle the
  // entire multi-version webp tree into this serverless function, which blew
  // past Vercel's 250MB function limit. Reading one known file keeps the
  // function tiny; the webp themselves are still served as static CDN assets.
  // manifest.json = { version, pages[], alt[] } — regenerated by
  // catalogue-finishing/build_flipbook.py.
  try {
    const raw = await fs.readFile(
      path.join(process.cwd(), "public", "catalogue", "manifest.json"),
      "utf8",
    );
    const m = JSON.parse(raw) as { version?: string; pages?: unknown; alt?: unknown };
    const pages = Array.isArray(m.pages) ? m.pages.map((s) => String(s)) : [];
    const alt = Array.isArray(m.alt) ? m.alt.map((s) => String(s)) : [];
    if (pages.length > 0) return { pages, version: m.version ?? null, alt };
  } catch {
    /* no manifest present */
  }
  return { pages: [], version: null, alt: [] };
}

// Check that the web-sized download PDF actually exists before exposing the
// Download button — produced by scripts/build-catalogue-download-pdf.py.
async function downloadPdfHref(): Promise<string | undefined> {
  const rel = "/catalogue/HUBSS-Catalogue-2026.pdf";
  const abs = path.join(process.cwd(), "public", rel);
  try {
    await fs.access(abs);
    return rel;
  } catch {
    return undefined;
  }
}

export default async function CataloguePage() {
  // Defense-in-depth: middleware should have already redirected when the
  // flag is off. If it somehow didn't, render the 404 body so visitors
  // never see the catalogue.
  if (!showCatalogue()) notFound();

  const { pages, alt } = await getPageManifest();
  const downloadHref = await downloadPdfHref();

  if (pages.length === 0) {
    return (
      <main className="grid min-h-dvh place-items-center px-6 text-center text-white/80">
        <div>
          <p className="text-sm uppercase tracking-[0.25em] text-orange-400">Catalogue</p>
          <p className="mt-3 text-lg">No catalogue pages have been rendered yet.</p>
          <p className="mt-2 text-sm text-white/50">
            Run <code className="rounded bg-white/10 px-2 py-0.5 font-mono text-xs">python scripts/render-catalogue-pages.py</code>
          </p>
        </div>
      </main>
    );
  }

  return <Flipbook pages={pages} alt={alt} downloadHref={downloadHref} />;
}
